### ISSUE TITLE
Gradle: Test dependencies and output are placed to "Runtime" scope

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-debug#1008]
- Open a gradle project
[TestGradle.zip](https://github.com/microsoft/vscode-java-debug/files/6530426/TestGradle.zip)
- Add a `Hello.java` with main method to `src/test/java`.
- In launch.json for `Hello.java`, set the `classPaths` to `[ "$Runtime" ]` and try to debug the application. I observe the calculated classpaths still contain all dependencies and output from test scope.

By following the definition of "$Runtime" constant, it should only resolve the classpath within "runtime" scope only.

**Comment by jdneo** [comment]
Seems related to https://github.com/eclipse/buildship/issues/953, will take a look

**Comment by jdneo** [comment]
This issue should have been resolved with the latest [Language Support for Java(TM) by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.java)@1.1.0.
