### ISSUE TITLE
Cannot launch multiple Java programs

### ISSUE THREAD

**Issue by curlyblueeagle** [microsoft/vscode-java-debug#1009]
Still seeing issue described in https://github.com/microsoft/vscode-java-debug/issues/209 . Cannot launch multiple Java programs since the debugger tries to do so in the same terminal.

##### Environment
- Operating System: macOS Mojave
- JDK version: 11.0.11
- Visual Studio Code version: 1.56.2
- Java extension version: 0.15.0
- Java Debugger extension version: 0.34.0

##### Steps To Reproduce
1. Launch a long running class
2. [Immediately launch another class

##### Current Result
Class 1 runs in terminal. The second class is launched in the same terminal and therefore doesn't run.

##### Expected Result
Both classes to be launched in their own dedicated terminal.

**Comment by testforstephen** [comment]
i didn't have the issue at macOS Catalina 10.15.7.

**Comment by curlyblueeagle** [comment]
> i didn't have the issue at macOS Catalina 10.15.7.

Woah this is a macOS issue?

**Comment by testforstephen** [comment]
Not sure. The terminal behavior is controlled by the upstream [VS Code](https://github.com/microsoft/vscode/issues), need a ticket there to have a look.

**Comment by curlyblueeagle** [comment]
I did file a ticket there https://github.com/microsoft/vscode/issues/124711 . They asked me to file here saying it's an extension issue.

**Comment by curlyblueeagle** [comment]
Also, I just tried this with node.js programs and had no issue. I was able to launch 2 different node.js files in separate terminals. So I am thinking this must be the java ext issue.

**Comment by testforstephen** [comment]
This can reproduce with "Run" feature. Debugging multiple programs in terminal works fine.

I added a comment to the upstream issue. https://github.com/microsoft/vscode/issues/124711#issuecomment-851313349

**Comment by curlyblueeagle** [comment]
@testforstephen yes, you are correct this works in debug mode but not run mode. I will follow up in the upstream ticket. Thanks for your comments and feel free to close this issue.

**Comment by testforstephen** [comment]
Since it's an issue in upstream, we will use upstream issue to track it.
