### ISSUE TITLE
The debugger jump to the wrong source code for Step.java

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#101]
![image](https://user-images.githubusercontent.com/14052197/31700409-c234265e-b3fb-11e7-8c5c-e6a78ce584e4.png)

My main class is called `Step.java`, but when the breakpoint was hit, the debugger jumps to the wrong step.class.
![image](https://user-images.githubusercontent.com/14052197/31700431-f29aefee-b3fb-11e7-938d-15b2489fc285.png)

**Comment by testforstephen** [comment]
When search the fully qualified name `Step`, the search engine also matches the result `com.sun.org.apache.xalan.internal.xsltc.compiler.Step`. That's not accurate. Should filter the wrong match from results.

**Comment by akaroml** [comment]
This is related to "Just my code" feature which tries to navigate to users' own code when looking for source. Let's think of a systematical way to handle this problem.

**Comment by testforstephen** [comment]
duplicated with #121
