### ISSUE TITLE
Help: How to set this '-Dfile.encoding=UTF-8' in extension settings ??

### ISSUE THREAD

**Issue by thefatwhale** [microsoft/vscode-java-debug#1010]
[provide a description of the issue]
How to set `-Dfile.encoding=UTF-8` in settings
[![2ksrC9.png](https://z3.ax1x.com/2021/05/29/2ksrC9.png)](https://imgtu.com/i/2ksrC9)

##### Environment
- Operating System: Windows 7 x64
- JDK version: 1.8.0_271
- Visual Studio Code version: 1.56.2
- Java extension version: 0.64.1
- Java Debugger extension version: 0.34.0

**Comment by imba-tjd** [comment]
https://github.com/microsoft/vscode-java-debug#launch

> encoding - The file.encoding setting for the JVM. If not specified, 'UTF-8' will be used.
