### ISSUE TITLE
Error in running java code with external jar while the path includes chinese 

### ISSUE THREAD

**Issue by F-19-F** [microsoft/vscode-java-debug#1012]
[provide a description of the issue]

##### Environment
- Operating System:Windows 10 19042.985
- JDK version: 15.0.2
- Visual Studio Code version: 1.56.2
- Java extension version: v0.16.0
- Java Debugger extension version: v0.34.0

##### Steps To Reproduce
1. Just open a simple dir(the parent includes chinese) and create a java source file to active java extension;
2. import jar library
3. Run code that uses library classes
4. Errors happen 

##### Current Result
terminal just says Exception in thread "main" java.lang.NoClassDefFoundError
##### Expected Result
running code as expected
##### Additional Informations
I just cpoy the args and input it into Java Process Console manualy,it works well.
```package f19.learn;
import java.io.IOException;

import org.jsoup.Connection;
import org.jsoup.Jsoup;
class entry{
    public static void main(String[] args) throws IOException {
        Connection con = Jsoup.connect("http://www.baidu.com").followRedirects(true);
        Connection.Response res = con.execute();
        String text = res.body();
        System.out.println(text+"\n");
    }
}
```

by clicking run
![image](https://user-images.githubusercontent.com/58457605/120326255-1fcd1780-c31b-11eb-8e10-661b0b8551fd.png)
manually input works well

![image](https://user-images.githubusercontent.com/58457605/120326686-91a56100-c31b-11eb-920c-45e4cb56d427.png)

**Comment by F-19-F** [comment]
It works well by clicking the run button while the path doesn't include chinese

**Comment by testforstephen** [comment]
Could you pls try the latest debugger 0.37.0 to see if it still exists?


If it still exists, then you could reference the troubleshooting guide for encoding issues on Windows about the possible fix.
https://github.com/microsoft/vscode-java-debug/blob/main/Troubleshooting_encoding.md
