### ISSUE TITLE
Exception has occurred: java.lang.ClassNotFoundException "java.lang.ClassNotFoundException: javax.servlet.Servlet"

### ISSUE THREAD

**Issue by HelpMePls321** [microsoft/vscode-java-debug#1013]
![image](https://user-images.githubusercontent.com/85263276/120567632-3db08000-c3e0-11eb-89c3-7044bb932176.png)

**Comment by testforstephen** [comment]
In the left bottom corner of your screenshot, you enabled "Uncaught Exceptions" and "Caught Exceptions" breakpoints. This is expected behavior.
