### ISSUE TITLE
Cannot debug the codes in jdk

### ISSUE THREAD

**Issue by joyous-coder** [microsoft/vscode-java-debug#1015]
[provide a description of the issue]
Sometimes I need to look into the jdk to understand how it works, but vscode java debugger does not show variables changes in vscode. Are there any configurations I can change to solve this ?
##### Environment
- Operating System: win10 20H2
- JDK version: 15.0.2
- Visual Studio Code version: 1.56.2
- Java extension version: 0.79.2
- Java Debugger extension version: 0.34.0

##### Steps To Reproduce
![image](https://user-images.githubusercontent.com/42910684/120632087-2da9a680-c49b-11eb-83b7-83a9b1f78c89.png)

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by rama430** [comment]
HOW to solve this
