### ISSUE TITLE
Shortencommandline lacks functionality

### ISSUE THREAD

**Issue by 92daxia** [microsoft/vscode-java-debug#1019]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version: 1.8
- Visual Studio Code version: 1.52.1
- Java extension version: 0.14.0
- Java Debugger extension version: v0.31.0

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Expected Result
This configuration needs to be added in shortencomandline:
classpath file -java WrapperClass classpathFile [args]

**Comment by testforstephen** [comment]
Please describe your request with some user scenario.
