### ISSUE TITLE
unresolved module error in module-info.java

### ISSUE THREAD

**Issue by OkonSamuel** [microsoft/vscode-java-debug#1021]
[provide a description of the issue]

Trying to import external dependencies into a vscode java project having a `module-info.java` file and no build tool, causes unresolved errors in the `module-info.java` file. It seems module-info.class isnt being generated in the output folder.
![image](https://user-images.githubusercontent.com/39421418/122026465-3b630400-cd98-11eb-9ae9-a27863250c7b.png)
```json
 "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Launch Current File",
            "request": "launch",
            "mainClass": "${file}"
        },
        {
            "type": "java",
            "name": "Launch App1",
            "request": "launch",
            "mainClass": "mail/mypack.App",
            "vmArgs": "--module-path /home/okonsamuel/javafx-sdk-11.0.2/lib --add-modules javafx.controls "
        },
]
```
Adding module-path and reference libraries doesn't seem to help.
Everything works once I remove modules (i.e removing module-info.java) and use only packages in my project.

##### Environment
- Operating System: Linux x86_64
- JDK version: 11
- Visual Studio Code version: 1.56.2
- Java extension version:  0.16.0
- Java Debugger extension version: 0.34.0

**Comment by testforstephen** [comment]
You're accessing javafx through module, you can take a look at https://github.com/redhat-developer/vscode-java/issues/881. Looks like you need to use a build tool such as gradle to manage the javafx library as module. You can post more discussion to the duplicated issue https://github.com/redhat-developer/vscode-java/issues/881

**Comment by badis-zgh** [comment]
I have a problem and I hope you will help me, module-info.java does not exist in project Java I am using Visual Studio Code!

**Comment by testforstephen** [comment]
@badis-zgh Could you please open a new issue? It's better to provide a sample project to help reproduce the issue? thanks.
