### ISSUE TITLE
Unable to debug after adding library to pom.xml file

### ISSUE THREAD

**Issue by pughua** [microsoft/vscode-java-debug#1022]
**Describe the bug**
Unable to debug after adding library to pom.xml file.Program Error: Could not find or load main class.

**To Reproduce**
1. Create a new “maven-archetype-quickstart” project using "com.example",“demo”.
2. Add a breakpoint in "app.java" and run it by pressing F5.It's working and it's at the breakpoint.
3. Open "pom.xml" and add dependency package "org.reflections".And update the project.
4. Add a breakpoint in "app.java" and run it by pressing F5.Program Error: Could not find or load main class.
5. Open "pom.xml" and remove dependency package "org.reflections".And update the project.
6. Add a breakpoint in "app.java" and run it by pressing F5.It's working and it's at the breakpoint.

**Expected behavior**
Hopefully it will work when you add a dependency package

**Environments:**
 - OS: Windows 10
 - VS Code version: 1.57.0
 - Extension version: Maven for Java v0.31.0
 - Debugger for Java: v0.34.0

**Run the information**

`
1.Before adding a dependency package
PS D:\文档\Git\JavaProject\demo>  d:; cd 'd:\ĵ\Git\JavaProject\demo'; & 'c:\Users\lemonnc\.vscode\extensions\vscjava.vscode-java-debug-0.34.0\scripts\launcher.bat' 'D:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:53351' '-Dfile.encoding=UTF-8' '-cp' 'D:\ĵ\Git\JavaProject\demo\target\classes' 'com.example.App' 
Hello World!

2.After adding a dependency package
PS D:\文档\Git\JavaProject\demo>  d:; cd 'd:\ĵ\Git\JavaProject\demo'; & 'c:\Users\lemonnc\.vscode\extensions\vscjava.vscode-java-debug-0.34.0\scripts\launcher.bat' 'D:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:53377' '-Dfile.encoding=UTF-8' '@C:\Users\xxxx\AppData\Local\Temp\cp_elrq980gdoztxi0tmpyepn1ao.argfile' 'com.example.App' 
错误: 找不到或无法加载主类 com.example.App
原因: java.lang.ClassNotFoundException: com.example.App

3.After removing the dependent packages
PS D:\文档\Git\JavaProject\demo>  d:; cd 'd:\ĵ\Git\JavaProject\demo'; & 'c:\Users\lemonnc\.vscode\extensions\vscjava.vscode-java-debug-0.34.0\scripts\launcher.bat' 'D:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:63844' '-Dfile.encoding=UTF-8' '-cp' 'D:\ĵ\Git\JavaProject\demo\target\classes' 'com.example.App' 
Hello World!
`

**Additional context**
For some reason, the running directory changed after the dependency package was added.

as "C:\Users\XXXXX\AppData\Local\Temp\cp_elrq980gdoztxi0tmpyepn1ao.argfile"，This file or directory does not exist.

**Comment by Qike7** [comment]
I solve this bug when I change the directory of my code from Chinese path to English path

**Comment by testforstephen** [comment]
does this issue still exist with the latest Debugger version 0.37.0?
