### ISSUE TITLE
hotCodeReplace button disapper when debug.toolBarLocation=docked

### ISSUE THREAD

**Issue by AethLi** [microsoft/vscode-java-debug#1024]
##### Environment
- Operating System:Windows 10
- JDK version:openjdk version "11.0.11" 2021-04-20
- Visual Studio Code version:1.57.1
- Java extension version:0.16.0
- Java Debugger extension version:0.34.0

##### Steps To Reproduce
1. [step 1]
 set "debug.toolBarLocation": "docked" in settings.json
2. [step 2]
 run java code

##### Current Result
![image](https://user-images.githubusercontent.com/25505798/123046174-5be12d00-d42e-11eb-8ae9-a60b129b8196.png)

##### Expected Result
![image](https://user-images.githubusercontent.com/25505798/123046401-a4004f80-d42e-11eb-95d2-b2b14dafff35.png)
hotCodeReplace button should still on position

**Comment by testforstephen** [comment]
Duplicates with https://github.com/microsoft/vscode/issues/115945

**Comment by testforstephen** [comment]
This issue is fixed in VS Code 1.60.
