### ISSUE TITLE
Failed to attach to remote debuggee VM. 

### ISSUE THREAD

**Issue by zhangqiannh** [microsoft/vscode-java-debug#1026]
[provide a description of the issue]

##### Environment
Operating System: Windows_NT x64 10.0.19042
JDK version: openjdk-11
Visual Studio Code version:Version: 1.56.2 (user setup)
Java extension version: Language Support for Java by Red Hat(version: v0.79.2)
Java Debugger extension version: v0.34.0

##### Steps To Reproduce
![image](https://user-images.githubusercontent.com/55779832/124913830-2dfd0a80-e022-11eb-8ac9-41d2590c6553.png)
![image](https://user-images.githubusercontent.com/55779832/124913845-33f2eb80-e022-11eb-9397-f7ad6e2a531f.png)

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
When I debugged, the project failed to start
##### Expected Result
The project started successfully in debug mode
##### Additional Informations
![image](https://user-images.githubusercontent.com/55779832/124913973-5d137c00-e022-11eb-8eec-73d3e45541ea.png)
@see https://github.com/microsoft/vscode-maven/issues/643

**Comment by testforstephen** [comment]
Could you please share a sample to help reproduce the issue?

**Comment by zhangqiannh** [comment]
This bug is easy to reproduce,
1. Repeat debug to start a springboot project in workspace
2. Or open two or more spring boot projects in the same workspce, and then debug them several times.
Sometimes this bug can appear more than ten times a day. I restart vscode or restart my computer, and then debug is OK.
But the bug will still appear at some point. I'm really broken!!!!!!!!

**Comment by zhangqiannh** [comment]
This bug is easy to reproduce,
1. Repeat debug to start a springboot project in workspace
2. Or open two or more spring boot projects in the same workspce, and then debug them several times.
Sometimes this bug can appear more than ten times a day. I restart vscode or restart my computer, and then debug is OK.
But the bug will still appear at some point. I'm really broken!!!!!!!!

**Comment by zhangqiannh** [comment]
> Could you please share a sample to help reproduce the issue?

![image](https://user-images.githubusercontent.com/55779832/125734475-c5f065b4-dc7c-417c-ab7d-c352a01bb7bb.png)
![image](https://user-images.githubusercontent.com/55779832/125734552-c122d869-aff9-44c6-bb23-3475b317aa34.png)
![image](https://user-images.githubusercontent.com/55779832/125734838-7f33c1b8-d9ca-42be-83a2-878d0c3e5e15.png)
test code:
[springboot-demo.zip](https://github.com/microsoft/vscode-java-debug/files/6820629/springboot-demo.zip)

**Comment by zhangqiannh** [comment]
Can you let me know the progress or give me a reply.

**Comment by testforstephen** [comment]
The run/debug context menu on Maven explorer is contributed by springboot extension, let @Eskibear to take a look.

**Comment by Eskibear** [comment]
known issue tracked in https://github.com/microsoft/vscode-maven/issues/757#issuecomment-961670609

**Comment by Eskibear** [comment]
should be fixed with https://github.com/microsoft/vscode-maven/pull/777
