### ISSUE TITLE
mac debug for java 运行java 文件 卡在debug：importing projects 了

### ISSUE THREAD

**Issue by yunxiaoyang01** [microsoft/vscode-java-debug#1027]
[provide a description of the issue]

##### Environment
- Operating System: mac
- JDK version: jdk11
- Visual Studio Code version: 最新版
- Java extension version: 
- Java Debugger extension version: 最新版

##### Steps To Reproduce
1. 创建java项目
2. 运行hello-word.java 文件 
3. 在debug：importing projects  卡主了

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by yunxiaoyang01** [comment]
最新发现，是因为不能创建launch.json 文件所以卡住了。但是具体原因未知

**Comment by yunxiaoyang01** [comment]
希望大佬能帮忙解决一下

**Comment by testforstephen** [comment]
如果你看到进度条显示在“importing projects”，说明Java插件还在加载你的工程，和创建launch.json没关系。你能试下reload一下vscode吗？

**Comment by yunxiaoyang01** [comment]
> 如果你看到进度条显示在“importing projects”，说明Java插件还在加载你的工程，和创建launch.json没关系。你能试下reload一下vscode吗？

reload了也不好用。

**Comment by yunxiaoyang01** [comment]
> 如果你看到进度条显示在“importing projects”，说明Java插件还在加载你的工程，和创建launch.json没关系。你能试下reload一下vscode吗？

感觉像是mac哪里的配置有问题。我用windows安装了java插件就可以正常运行

**Comment by yunxiaoyang01** [comment]
![image](https://user-images.githubusercontent.com/39183504/125153421-20f92c00-e186-11eb-9b42-216230ba766e.png)
这里一直再转

**Comment by yunxiaoyang01** [comment]
刚开始以为是插件冲突导致的。把所有的插件都卸载了然后只安装了java for Pack 。感觉是整个包都没有生效

**Comment by testforstephen** [comment]
再试试"**F1 -> Java: Clean Java Language Server Workspace**"
