### ISSUE TITLE
locate wrong class file when there are two class with same name in different project.

### ISSUE THREAD

**Issue by 1615200373** [microsoft/vscode-java-debug#1028]
Hi team,
I have two projects,  one is projectone, the other one is projecttwo.
And they all have a class com.project.ClassOne.
When I debug this class, the debugger may locate the wrong classfile.
In eclipse, there are a feature named at source lookup, is there are a similar feature for this Java Debugger?
![image](https://user-images.githubusercontent.com/32661800/125306526-e1873700-e361-11eb-8917-396ca5486c50.png)

##### Environment
- Operating System: Macos
- JDK version: Jdk 11
- Visual Studio Code version:1.58.0
- Java extension version: v0.80.0
- Java Debugger extension version: v0.34.0

**Comment by testforstephen** [comment]
We do not have a mechanism to reorder the source lookups yet.

Here is how the debugger searches for source files. The debugger will first try to search for the source file from the classpath of the current project. If it doesn't find it, it will search in the workspace. For your case, if you run the main class from project1, then it should find the class file from project1.

If this is not the behavior you observed, can you help share a sample project for us to reproduce?
