### ISSUE TITLE
Provide command to continue/pause all/other threads

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-java-debug#103]
When debugging a multi-thread application (Java in our case), there can be multiple threads paused at the same time. Our Java debugger only stops/continues one thread at a time. So when you hit a breakpoint in a runnable which is executed by multiple threads, it is really painful for to continue them one by one:
image

It would be really nice if vscode provides the menu entry to continue all the suspended threads with just one click. And maybe more like Pause All. And when right-clicking one thread, there could be entries like Continue Other Threads or Pause Other Threads according to the thread's state.

Please check the disscussion in Microsoft/vscode#36394 for proposed solution.

**Comment by testforstephen** [comment]
This is doable, but current blocking thing is how to customize the context menu entry. We have created vscode issues Microsoft/vscode#36394 and https://github.com/Microsoft/vscode/issues/39091 to discuss this.

**Comment by andxu** [comment]
@testforstephen since vscode side has completed the context menu, can you take a review of this issue?

**Comment by testforstephen** [comment]
The vscode change is ready on latest May release 1.24.1, it unblocks us. Let's start to get this done.

**Comment by chuggafan** [comment]
Any update on this? I just ran into a situation that I want this for but this issue has had the "voting" label for over a year.

**Comment by akaroml** [comment]
@testforstephen, any update?

**Comment by testforstephen** [comment]
VS Code has unblocked us, now it's possible to do it in debugger extension.

**Comment by akaroml** [comment]
Great. Let's get this planned at the right time.
