### ISSUE TITLE
Error: Running the contributed command: 'java.execute.workspaceCommand' failed.

### ISSUE THREAD

**Issue by jellyfamhamz17** [microsoft/vscode-java-debug#1032]
Every time I try to run my code which I will attach under this this error comes up.
I am just trying to create a simple calculator I quadruple checked the code for any mistakes.

public class HamzahCalculator
{
    public static void main(String[] args)
    {
       int num1 = 0;
       int num2 = 0;
       char operator;
       double answer = 0.0; 

       Scanner scanObject = new Scanner(System.in);

       System.out.println("Please enter first number: ");
       num1 = scanObject.nextInt();
       System.out.println("Please enter second number: ");
       num2 = scanObject.nextInt();
       System.out.println("What operation? ");
       operator = scanObject.next().chatAt(0);

       
       switch (operator) {
           case '+': answer = num1 + num2;
                     break;
           case '-': answer = num1 - num2;
                     break;
           case '*': answer = num1 * num2;
                     break;
           case '/': answer = num1 / num2;
                     break;
            
           
    }

    System.out.println(num +" "+operator+" ""+num2+" - "+answer);
    }
}

-Operating System: Windows_NT x64 10.0.19042
- JDK version: 15.0.2
- Visual Studio Code version: 1.58.2

**Comment by testforstephen** [comment]
Could you try "**F1 -> Java: Clean Java Language Server Workspace**"?
