### ISSUE TITLE
Add a "launch previously launched application option if the current file isn't executable" option.

### ISSUE THREAD

**Issue by kareem-ghazi** [microsoft/vscode-java-debug#1036]
Add an option to launch the last application if the current one isn't executable instead of showing a dialog box. If there's a feature for this already, please do let me know.

**Comment by testforstephen** [comment]
Another user feedback on this:
Hitting "Run Java" should not prompt me to select the main class every time. There is only one main method in my project. It's very disruptive to my workflow.

**Comment by testforstephen** [comment]
feedback +1:
Have to select the only runnable class over and over again if I want to run the program
