### ISSUE TITLE
Icon buttons of the right side panel hide out of the window boundaries when using the "Run/Debug" buttons to debug Java

### ISSUE THREAD

**Issue by aderchox** [microsoft/vscode-java-debug#1040]
[provide a description of the issue]
My VSCode shows "run / debug" inline buttons before the main method. When used, it opens a terminal in the VSCode's panel and shows the result. However, if the panel is on the right side of the VSCode(e.g., in my case), it will not use ellipsis on extra panel tab-buttons and so there's not enough room for icon-buttons and they go out of the window's boundaries.
OK, It's hard to describe it in words, so let me show a picture(notice how I've stretched the panel too wide deliberately. Still the icon buttons have overflown outside of the window):

![image](https://user-images.githubusercontent.com/52244768/130046355-44b403bb-49b4-47cb-b947-33c10e51b9cc.png)

I'm not sure if this is related to VSCode itself or to this extension. But I've not posted it on VSCode's repository because this issue does not exist when I open the terminal using [my hotkey for] the command "workbench.action.terminal.toggleTerminal". So probably VSCode does it right and it's an issue with my Java debugger extension.

##### Environment
- Operating System: Windows 10
- JDK version: openjdk 15.0.2 2021-01-19
- Visual Studio Code version: 1.59.0 (user setup)
- Java extension version: 0.81.0
- Java Debugger extension version: 0.35.0

##### Steps To Reproduce
1. Right click on the VSCode panel and choose "Move panel right"
2. Stretch it as much wide as you want.
3. Close the panel.
4. Use the button "Run" from the inline buttons "Run / Debug" before the Java main method.
5. The terminal is triggered automatically, but the icon buttons on the panel hide out of the window's boundaries.

##### Current Result
icon buttons hide

##### Expected Result
put an ellipsis on panel tab-buttons such that there will be enough room for panel icon-buttons

**Comment by testforstephen** [comment]
The new VS Code UIs will put the terminal instance names on a side panel, this issue should not exist any more. I'm closing it, feel free to reopen it if you want more discussion on it.
![image](https://user-images.githubusercontent.com/14052197/144181748-1e20c75d-52e4-4104-a18a-1c3ae338be5e.png)
