### ISSUE TITLE
Improve no launch.json debug experience and support no folder debugging

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-java-debug#1043]
Hi VS Code PM here 👋 

Just creating an issue to see if we can somehow simplify the Java debug experience.
I was just in a user study with @stevencl where a user could not setup Java debugging. 

I just tried debugging a simple `Java hello world` and I was offered to install Java development kit - cool. However after downloading it I still could not debug in a no folder vscode my `hello world` program.
So it seems like Java would not let me debug in a no folder workspace.

On the VS Code side we have been working on some improvements to this flow. Would you be interested in discussing this and potentially adopting this changes?

Some interesting changes:
* Contribute a dynamic `resolveDebugConfiguartion` that will provide a launch configuration on the fly. [Example](https://github.com/microsoft/vscode-mock-debug/blob/main/src/activateMockDebug.ts#L161). 
* Contribute a button to the debug start view. And make sure the Editor run java button works for simple cases

fyi @weinand @testforstephen

**Comment by testforstephen** [comment]
@weinand Correct. Java debugger registered a dynamic `resolveDebugConfiguartion` to auto generate a launch configuration in memory to launch a single Java file.

**Comment by weinand** [comment]
@isidorn could you please double check that this flow is not working for you and investigate what the difference between your and my setup is.

**Comment by isidorn** [comment]
For some reason this was not working on Friday for me, and now just works same as for you @weinand
I am sorry for creating noise. The experience is indeed excellent 👏 

From the user study: the participant had problems setting up a maven project, which is a different issue.
