### ISSUE TITLE
Error when debuging **Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException**

### ISSUE THREAD

**Issue by Nikegamerjjjj** [microsoft/vscode-java-debug#1045]
[provide a description of the issue]

##### Environment
- Operating System: Windows 10 21H1 Version
- JDK version: 16.0.2
- Visual Studio Code version: 1.59
- Java extension version: (Debugger for Java): 0.35.0

##### Steps To Reproduce
How it happened:
I normally run my Java code on VS Code, normally it compiles without any problem. Today i run my code(i run it before i changed the code) and it compiles then it shows me a error window saying this: **Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException**.

Here are my code: https://github.com/Nikegamerjjjj/Java_Window/

Problem is that it should not show what i marked bold. Thats supposed not....But after i click close is runs program without problem. Only when it compiles it, that message appears, i tried to clean workspace(if that even works?) But...as i thought that didnt work out. Help, please.

Appreciate!

**Comment by testforstephen** [comment]
Could you please record some screenshot or video to show how it happens?

**Comment by timPetProjects** [comment]
Hi,
This is a persisting issue as the attached screen shot shows
[DebugeeLaunchIssues.odt](https://github.com/microsoft/vscode-java-debug/files/9683404/DebugeeLaunchIssues.odt)
