### ISSUE TITLE
ClassNotFoundException when debug, but run works well

### ISSUE THREAD

**Issue by syntomic** [microsoft/vscode-java-debug#1052]
[provide a description of the issue]

##### Environment
- Operating System: WSL2
- JDK version: 11.0.10
- Visual Studio Code version:1.60.0
- Language Support for Java(TM) by Red Hat:0.81.0
- Java Debugger extension version:0.35.0

##### Steps To Reproduce
1. CLick the debug button
![image](https://user-images.githubusercontent.com/48039076/133250455-95b2ce70-5626-48ab-957e-d3d9b3bb59fd.png)

2. Throws Exception
![image](https://user-images.githubusercontent.com/48039076/133250547-c378cc9e-dd03-46eb-94e0-b677ec4ba091.png)

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Additional Informations
try F1 ->Clean the java language server workspace, but not work

**Comment by testforstephen** [comment]
it's because you enabled exception breakpoint, please uncheck "Caught Exceptions" and "Uncaught Exceptions".

![image](https://user-images.githubusercontent.com/14052197/133254407-24f467ea-8eb1-4dd4-b5c6-b42064b0002b.png)

**Comment by syntomic** [comment]
> it's because you enabled exception breakpoint, please uncheck "Caught Exceptions" and "Uncaught Exceptions".
> 
> ![image](https://user-images.githubusercontent.com/14052197/133254407-24f467ea-8eb1-4dd4-b5c6-b42064b0002b.png)

It solved my problem, thanks~
