### ISSUE TITLE
Using VS Code same as Eclipse packages and classes

### ISSUE THREAD

**Issue by JJ1006** [microsoft/vscode-java-debug#1053]
[provide a description of the issue]
I am unable to use packages properly as it shows that a class is not able to get another even if it is public. While I am able to perform the same task in other IDE. I always prefer VS Code over any other IDE, but this problem is not getting solved. Please see to it...

##### Environment
- Operating System:  Windows
- JDK version: 15
- Visual Studio Code version: 1.60.1
- Java extension version: Red Hat Latest
![Screenshot (20)](https://user-images.githubusercontent.com/74872123/133595092-453a7efe-a74c-4b2c-8a74-7fb4d48b46e0.png)

- Java Debugger extension version: Red Hat Latest

##### Steps To Reproduce
1. [step 1] 
![Screenshot (21)](https://user-images.githubusercontent.com/74872123/133595097-0ed6211c-7f13-4eca-99c5-6ba1500c1cc3.png)
Make a package and add this code.
2. [step 2]
3. run it

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by testforstephen** [comment]
Duplicates with https://github.com/redhat-developer/vscode-java/issues/2113
