### ISSUE TITLE
Spring Boot project does reload when a non-java file is saved (e.g. application.properties)

### ISSUE THREAD

**Issue by alx1024** [microsoft/vscode-java-debug#1056]
In a Spring Boot project with DevTools dependency for hot reloading, the reload does not work when you save a non-java-file like application.properties, it did work in 0.81.0 of the extension

##### Environment
- Operating System: Win 10 x64
- JDK version: OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
- (also tested with OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode) with the same result)
- Visual Studio Code version: 1.60.2
- Java extension version: 0.82.0
- Java Debugger extension version: 0.36.0
- Extension Pack for Java version: 0.18.5

##### Steps To Reproduce
1. run attached project in an IDE
2. try changing the server port and saving application.properties

##### Current Result
Project does not reload after saving application.properties

##### Expected Result
Project should reload

[demo.zip](https://github.com/microsoft/vscode-java-debug/files/7231388/demo.zip)

**Comment by testforstephen** [comment]
It works for me with your sample project.

**Comment by alx1024** [comment]
thank you for looking into it, i just realized that the version infos were not saved properly when creating the issue, i updated them

**Comment by testforstephen** [comment]
Tried it in multiple machines, it can reload automatically once updating `server.port` property in application.properties.

please make sure autobuild is enabled. See the setting `java.autobuild.enabled`.

**Comment by alx1024** [comment]
autobuild is enabled, issue still persists. since you can't reproduce i will stay on 0.81.0 of the extension and hope i can update to 0.83.0 without the issue, thank you very much

**Comment by alx1024** [comment]
i was able to fix the problem by deleting %USERPROFILE%\.vscode which deletes all extensions and reinstalling VSCode
