### ISSUE TITLE
Does not refresh dependencies in Spring Boot Gradle project on save

### ISSUE THREAD

**Issue by alx1024** [microsoft/vscode-java-debug#1059]
In a Spring Boot project with DevTools dependency for hot reloading, the reload does not work when you save a non-java-file like application.properties, it did work in 0.81.0 of the extension

##### Environment
- Operating System: Win 10 x64
- JDK version: OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
- (also tested with OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode) with the same result)
- Visual Studio Code version: 1.60.2
- Java extension version: 0.82.0
- Java Debugger extension version: 0.36.0
- Extension Pack for Java version: 0.18.5

##### Steps To Reproduce
1. Run attached project in an IDE
2. Try uncommenting the "Gson" dependency in "build.gradle" and save the file
3. Look if activating line get's rid of compile error

##### Current Result
- Project does not update dependency
- No notification after save
- It works with the plugin version 0.81.0

##### Expected Result
- Project should update dependency which should be reflected in the auto-import
- Notification "A build file was modified. Do you want to synchronize the Java classpath/configuration" should appear
[demo.zip](https://github.com/microsoft/vscode-java-debug/files/7260344/demo.zip)

**Comment by testforstephen** [comment]
Could you try "**F1 -> Java: Clean Java Language Server Workspace**"? if it doesn't work, we need move this issue to https://github.com/redhat-developer/vscode-java/issues for further investigation.

**Comment by testforstephen** [comment]
This is a regression issue in 0.82.0, and will be fixed in next version of **Language Support for Java by Red Hat** extension.
