### ISSUE TITLE
Java language server fails to load

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode-java-debug#1060]
[provide a description of the issue]

After creating a java app using VS Code, I am unable to run it, the lang server fails to load.

I've tried some of the steps here, doesn't help: https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting

##### Environment
- Operating System: Linux openSUSE TW
- JDK version: openjdk version "16.0.1"
- Visual Studio Code version: 1.16-0-insider
- Java extension version: v0.18.5
- Java Debugger extension version: v0.36.0

$ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK-16.0.1+9 (build openj9-0.26.0, JRE 16 Linux amd64-64-Bit Compressed References 20210421_23 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - cea22090ecf based on jdk-16.0.1+9)

$ echo $JAVA_HOME
/home/yadav/.sdkman/candidates/java/current

##### Steps To Reproduce
1. Create a simple hello world java project (maven based)
2. Open App.java (your main java class)
3. Hit run in debugger.

##### Current Result

Java lang server fails to load?

##### Additional Informations

For error message in terminal

```
0ecd96e1 Refreshing Maven model [Done]
06fc3ab0 Resolve plugin dependency [Done]
23027ed9 Repository registry initialization [Done]
35af6525 Reporting encoding changes. [Done]
d16ae805 Building [Done]
edf4d9dc Building: 5% (Found 1 error) Compiling demo/src/main/java/com/example [46/1000]
```

**Comment by rajinder-yadav** [comment]
Here is a copy of the javacore file generated in my the project root folder:

[javacore.20211004.100552.18872.0004.txt](https://github.com/microsoft/vscode-java-debug/files/7281076/javacore.20211004.100552.18872.0004.txt)

**Comment by testforstephen** [comment]
could you share a sample to help debug the problem?

**Comment by rajinder-yadav** [comment]
What I am seeing is there:

![Screenshot_20211009_093724](https://user-images.githubusercontent.com/439226/136660088-b5c65a22-66cd-4d58-9d73-9c821ad65e98.png)

On the bottom status bar, the spinner keeps spinning
![Screenshot_20211009_093621](https://user-images.githubusercontent.com/439226/136660153-105c42e2-2963-451c-87c0-4ebeeadbea73.png)


Here is the log file: [.log](https://github.com/microsoft/vscode-java-debug/files/7315690/default.log)

**Comment by rajinder-yadav** [comment]
FYI: I am using Eclipse for the same project and it opens, builds and run fine.

**Comment by testforstephen** [comment]
The log shows that lombok extension breaks the Java extension. Could you try to uninstall lombok extension and reset the user setting "java.jdt.ls.vmargs"?
