### ISSUE TITLE
为什么我想要进行远程附加到Jvm进行调试的时候,vsocode总是让我选择一个MainClass?

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [microsoft/vscode-java-debug#1067]
我的远程debug配置如下,

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug (Attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": 45001,
            "timeout": 9999999999
        }
    ]
}
```

45001已经在jvm调试端口开启了.

但是我运行这个配置的时候弹出(会强制让我选择一个class, idea可以直接附加到目标jvm,我用的是java项目管理器创建的项目,不是maven也不是gradle)
![image](https://user-images.githubusercontent.com/57204004/139526249-2889b8d8-af33-4d7a-9643-b02242443bce.png)

有方法解决这个问题么?

**Comment by YU5Z8X2CvH1fv4ep** [comment]
选择了class也无法开始调试.他是新启动被选择的class的main方法.

**Comment by YU5Z8X2CvH1fv4ep** [comment]
我想要可以连接上远程jvm调试

**Comment by YU5Z8X2CvH1fv4ep** [comment]
我用了别的版本的就可以了我用的30

**Comment by mozhuanzuojing** [comment]
@YU5Z8X2CvH1fv4ep 

你需要添加项目属性，它会把你的项目作为获取源码的途径

"projectName": "fa",

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> @YU5Z8X2CvH1fv4ep
> 
> 你需要添加项目属性，它会把你的项目作为获取源码的途径
> 
> "projectName": "fa",

添加了也没用,他会自动到当前目录中找MianClass 而不是附加到远程jvm调试

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> > @YU5Z8X2CvH1fv4ep
> > 你需要添加项目属性，它会把你的项目作为获取源码的途径
> > "projectName": "fa",
> 
> 添加了也没用,他会自动到当前目录中找MianClass 而不是附加到远程jvm调试

idea就可以附加上去,但是vscode就不行,为啥非要让我启动啊,我明明配置的是attach

**Comment by mozhuanzuojing** [comment]
@YU5Z8X2CvH1fv4ep 分享一下你安装的所有插件，settings.json和你的项目。

你是本地启动一个服务，然后再远程调试这个项目？
可以直接调试启动本地项目

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> @YU5Z8X2CvH1fv4ep 分享一下你安装的所有插件，settings.json和你的项目。
> 
> 你是本地启动一个服务，然后再远程调试这个项目？ 可以直接调试启动本地项目

是的用命令行启动,然后vscode启动对应的远程调试配置连上去是这样.

**Comment by testforstephen** [comment]
You need go to **Debug** view, select your config "**Debug (Attach)**" first, then trigger debugging.

![image](https://user-images.githubusercontent.com/14052197/139617644-97991889-45a3-4245-8ea7-8e62399d7b28.png)

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> 您需要转到**调试**视图，首先选择您的配置“**调试（附加）** ”，然后触发调试。
> 
> ![图片](https://user-images.githubusercontent.com/14052197/139617644-97991889-45a3-4245-8ea7-8e62399d7b28.png)



> You need go to **Debug** view, select your config "**Debug (Attach)**" first, then trigger debugging.
> 
> ![image](https://user-images.githubusercontent.com/14052197/139617644-97991889-45a3-4245-8ea7-8e62399d7b28.png)

我是这样操作的 你可以附加到远程jvm?为什么我不可以?

**Comment by YU5Z8X2CvH1fv4ep** [comment]
他是直接让我启动一个类

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> You need go to **Debug** view, select your config "**Debug (Attach)**" first, then trigger debugging.
> 
> ![image](https://user-images.githubusercontent.com/14052197/139617644-97991889-45a3-4245-8ea7-8e62399d7b28.png)

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "attch",
            "request": "attach",
            "hostName": "localhost",
            "port": 15001
        }
    ]
}

这个配置 15001已经启动

**Comment by YU5Z8X2CvH1fv4ep** [comment]
![screenscast_20211101_221403](https://user-images.githubusercontent.com/57204004/139685804-76918b1b-75c4-4106-a8c6-e901833b30da.gif)

**Comment by testforstephen** [comment]
I cannot reproduce it in VS Code 1.61. What VS Code version are you using?

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> I cannot reproduce it in VS Code 1.61. What VS Code version are you using?

vscjava.vscode-java-test 问题出现在这个插件中，只要我装了它， 调试配置好像被覆盖了，就不能直接连上去，卸载就好了

**Comment by YU5Z8X2CvH1fv4ep** [comment]
问题已经搞定了，谢谢各位大哥

**Comment by YU5Z8X2CvH1fv4ep** [comment]
最好还是吧vscjava.vscode-java-test这个问题解决一下，因为这个是套装里面的，很多人都用。那么他们都会有这个问题

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> I cannot reproduce it in VS Code 1.61. What VS Code version are you using?

vscjava.vscode-java-dependency貌似和这个插件也有问题，我刚重启电脑后，还是出现无法直接附加到远程问题，然后关闭了vscjava.vscode-java-dependency插件又恢复了

**Comment by testforstephen** [comment]
你这个问题看起来像个人环境问题。vscjava.vscode-java-test 和 vscjava.vscode-java-dependency并不会注册Java调试配置项，讲道理不会影响Java debugger调试项。你的截图显示你在用code-server，你可以试下标准的vscode么？https://code.visualstudio.com/

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> 你这个问题看起来像个人环境问题。vscjava.vscode-java-test 和 vscjava.vscode-java-dependency并不会注册Java调试配置项，讲道理不会影响Java debugger调试项。你的截图显示你在用code-server，你可以试下标准的vscode么？https://code.visualstudio.com/


对，是我的个人的一个环境配置问题。没问题了可以正常使用了
