### ISSUE TITLE
vscode java server refreshing the workspace (cleaning and building) for each restart consuming much CPU and time

### ISSUE THREAD

**Issue by bitsInnovate00** [microsoft/vscode-java-debug#1068]
[vscode java server refreshing the workspace (cleaning and building) for each restart which is taking a lot of time]

##### Environment
- Operating System: Windows 10
- JDK version: JDK 11
- Visual Studio Code version: 1.61.2
- Java extension version: v0.18.6
- Java Debugger extension version: v0.36.0

##### Steps To Reproduce
I have a workspace with 5 maven projects which is already refreshed by the vscode java server. But if I simply restart the workspace, its again repeating the workspace refreshment with cleaning and building which is taking a lot of CPU and time. Why its redoing the same thing again and again

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
The workspace restart is consuming a lot of CPU and time for the vscode java server for doing the workspace refresh
##### Expected Result
The worspace should refresh and restart very quickly
##### Additional Informations
NA

**Comment by testforstephen** [comment]
this is an issue from Java language support extension, could you pls open an issue there https://github.com/redhat-developer/vscode-java/issues? It's better to provide some sample project to reproduce the problem.

**Comment by bitsInnovate00** [comment]
Raised  https://github.com/redhat-developer/vscode-java/issues/2222

**Comment by testforstephen** [comment]
let's use the upstream issue to track it.
