### ISSUE TITLE
Organize Imports on save does only work with manual settings.json-edit

### ISSUE THREAD

**Issue by alx1024** [microsoft/vscode-java-debug#1071]
[provide a description of the issue]

##### Environment
- Operating System: Win 10
- JDK version: 11
- Visual Studio Code version: 1.62.0
- Java extension version: 1.0.0
- Java Debugger extension version: 0.36.0

##### Steps To Reproduce
1. In any Java Program in any main-function type "File f = new File("/");"
2. Save File

##### Current Result
Even with checkbox checked in settings menu "Java > Save Actions: Organize Imports" (which results in     

"java.saveActions.organizeImports": true

in settings.json): imports are not automatically organized

##### Expected Result
Imports are automatically organized on file save with setting checked

##### Additional Informations
if you modify the settings.json manually to:

"editor.codeActionsOnSave": {
    "source.organizeImports": true
}

regardless if Java > Save Actions-option is checked, imports work, but you have to search for this solution on Stackoverflow

**Comment by testforstephen** [comment]
There is a limit on the usage of "**Java > Save Actions: Organize Imports**", it can only add import for the classes with unique package import option, but ignore those with multiple import candidates. Could you check if there are multiple File import options in your project?

And if you try to add a snippet `"ArrayList list;"` on your code, it should be able to auto add `import java.util.ArrayList;` on save.

Anyway, i would recommend using `"editor.codeActionsOnSave"`, and it handles ambiguous import better.

**Comment by alx1024** [comment]
- `"Java > Save Actions"` does not work for me at all, not with File nor ArrayList

- `"editor.codeActionsOnSavbe"` works perfectly and lets me select ambiguous imports, it would just be great if there was an option for it instead of having to manually modify the settings file

**Comment by testforstephen** [comment]
- `"Java > Save Actions"` works for me on the case with unique package import. Could you pls share a minimum sample project and snippet to help reproduce the issue?

https://user-images.githubusercontent.com/14052197/140923475-724c7aa6-15e6-4ed1-8ab7-2c0b6e40e595.mov

>- `"editor.codeActionsOnSavbe"` works perfectly and lets me select ambiguous imports, it would just be great if there was an option for it instead of having to manually modify the settings file.

Adding one more setting just to help configure another setting seems to go a bit too far. But I'm open to this, just need to know if this is what most users want.

**Comment by alx1024** [comment]
Can you post your settings.json content at the point of the screen recording? (doesn't matter if before or after checking the "Save Actions"-checkbox)

**Comment by alx1024** [comment]
`"Java > Save Actions"` does nothing for m

https://user-images.githubusercontent.com/30522582/140971441-a3e62115-057b-4c3f-9b18-edde880be57a.mp4

e

**Comment by alx1024** [comment]
I just tried to reproduce in Ubuntu:

1. `"Java > Save Actions"` works as you described for non-ambiguous packages, I don't know why my VSCode/Windows-Kombination does not work at all (have tried uninstall + deletion of `"%USERPROFILE%/.vscode"` and `"%APPDATA%/Code"`

2. The best solution regardless of operating system seems to be:  `"editor.codeActionsOnSave": { "source.organizeImports": true }` because it works better. My suggestions is to replace the current settings entry with the better working one as the checkbox-functionality

**Comment by testforstephen** [comment]
`"Java > Save Actions"` doesn't work for me in Windows as well. It works in macOS.

Since this feature is provided by https://github.com/redhat-developer/vscode-java/issues, I will move the issue there for further investigation.

**Comment by testforstephen** [comment]
Use https://github.com/redhat-developer/vscode-java/issues/2207 to track the issue.
