### ISSUE TITLE
Auto-completion does not take effect when debugging and evaluating expressions

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [microsoft/vscode-java-debug#1076]
- vscode 1.6.2
- java-debug 36
- red-hat java 1.0

Auto-completion does not take effect when debugging and evaluating expressions

![screenscast_20211115_205457](https://user-images.githubusercontent.com/57204004/141785716-19287fe0-e975-4dce-97c1-cf54281e97ab.gif)

**Comment by YU5Z8X2CvH1fv4ep** [comment]
按回车后，不会补全表达式

**Comment by YU5Z8X2CvH1fv4ep** [comment]
而是直接输出回车 执行表达式

**Comment by testforstephen** [comment]
默认按“**Tab**”才是插入completion选项。你可以通过设置`"debug.console.acceptSuggestionOnEnter": "on"`改回用**Enter**

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> 默认按“**Tab**”才是插入completion选项。你可以通过设置`"debug.console.acceptSuggestionOnEnter": "on"`改回用**Enter**

ok
