### ISSUE TITLE
Error: Could not find or load main class Caused by: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by tuanisme13** [microsoft/vscode-java-debug#1079]
running code runner fails, but other compiler works. What is the error? 
Hope everybody help please!
![Screenshot (50)](https://user-images.githubusercontent.com/94700747/142651311-d14e60fd-9eb4-4c9a-99bb-0d87bfd38071.png)
![Screenshot (51)](https://user-images.githubusercontent.com/94700747/142651314-e65efad8-ebfd-4913-83e7-bf9fb6f6cd62.png)
.

**Comment by testforstephen** [comment]
Sorry, Code Runner feature is not out of scope of this Java debugger extension. Could you please open you issue at https://github.com/formulahendry/vscode-code-runner?
