### ISSUE TITLE
Unable run or debug the spring boot application in VSCodium

### ISSUE THREAD

**Issue by vinith48** [microsoft/vscode-java-debug#1080]
Unable to start the debugger for spring boot application.
##### Environment
- Operating System: Windows 10
- JDK version: 1.11
- Visual Studio Code version: VSCodium v1.62.3
- Java extension version: v0.18.6
- Java Debugger extension version: v0.36.0

##### Steps To Reproduce
1. Install VSCodium and setup
2. Setup spring boot application with mvn build tool
3. Add java extension pack
4. Start Debugger

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### It was working previously but suddenly facing this issue. I tried restarting the VSCodium many times, but still the same result.
![img](https://user-images.githubusercontent.com/13465754/142658421-d648ac77-0346-465d-8f08-5214a1bd1b4a.PNG)

**Comment by stiftle** [comment]
I have the same issue. Downgrading "Debugger for Java" to version 0.35.0 and reloading the window helped for me.

**Comment by vinith48** [comment]
Thanks stiftle,

You saved my time. It really worked.
I think the latest version is having some issue.

**Comment by stiftle** [comment]
Very glad this helped! But I wouldn't close the issue because the bug itself still exists, downgrading the extension is just a workaround.

**Comment by testforstephen** [comment]
we didn't publish this Java debug extension to VSCodium, how did you install this extension?

**Comment by vinith48** [comment]
When installing java extension pack, it brings 6 more extension installed
behind it. Java debugger is one among them.

**Comment by testforstephen** [comment]
As far as I know, VSCodium is installing extensions from [open-vsx.org](https://open-vsx.org/), but that Java debug extension distribution is not maintained by us. Could you try the official VS Code from Microsoft to see if there is the same issue? thanks.

**Comment by vinith48** [comment]
Sure

**Comment by intact** [comment]
Looks like vscjava.vscode-java-debug-0.36.0.vsix from open-vsx miss server jar file.
