### ISSUE TITLE
No delegateCommandHandler for vscode.java.startDebugSession when starting Debugger in Gitpod

### ISSUE THREAD

**Issue by mattwelke** [microsoft/vscode-java-debug#1088]
Appears to be same issue as described in https://github.com/microsoft/vscode-java-debug/issues/728. I chose to open a new issue because that issue is closed.

##### Environment
- Operating System:
```
gitpod /workspace/spring-petclinic $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```
- JDK version:
```
gitpod /workspace/spring-petclinic $ which java
/home/gitpod/.sdkman/candidates/java/current/bin/java
gitpod /workspace/spring-petclinic $ java --version
Picked up JAVA_TOOL_OPTIONS: -Xmx2576m
openjdk 11.0.13 2021-10-19 LTS
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)
```
- Visual Studio Code version:
```
Version: 1.62.3
Commit: 25d9dd4c307716427469c02e8160b15cee4959f1
Date: 2021-11-19T15:21:17.186Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
```
- Java extension version:
```
Extension Pack for Java
v0.18.6
Language Support for Java(TM) by Red Hat
v1.0.0
```
- Java Debugger extension version:
```
Debugger for Java
v0.36.0
```

##### Steps To Reproduce
1. Fork GitHub repo https://github.com/spring-projects/spring-petclinic in your Gitpod account.
1. Load workspace for repo. Complete Gitpod prebuild (takes about 5 mins).
1. Load repo in Gitpod. Close already running web app (because we want to debug it instead of run it) by closing preview window and using `ctrl-c` on the "Java" process that is already running in the terminal area of VS Code.
1. Attempt to start debugger by clicking on the debugger in the top left after switching to the debug tab in VS Code.

Logs: https://gist.github.com/mattwelke/6b16e020da658d63e46cb686e37c9240

##### Current Result

**The first time I tried this**

"Compiling" message appears in bottom right:

![image](https://user-images.githubusercontent.com/7719209/143154258-7e8b84a4-e643-4b4b-ae78-c39bf477154d.png)

A moment later, error appears and debug session doesn't start:

![image](https://user-images.githubusercontent.com/7719209/143154230-18befcc5-c869-47fb-b806-52300e7cb8ea.png)

**The second time I tried this**

Debugger worked as expected. Web app running and able to set breakpoints and have them be hit when HTTP routes are hit in the running app. I used the Gitpod port forwarding to be able to hit the HTTP endpoints for the app in a different browser tab.

**All other times I tried this**

Same as "The first time I tried this".

##### Expected Result

Consistent experience same as "The second time I tried this".

##### Additional Informations

Chrome:
```
Chrome is up to date
Version 96.0.4664.45 (Official Build) (64-bit)
```
OS: Windows 10 Pro

**Comment by mattwelke** [comment]
Note that this may be tricky to reproduce. It did work one of the times I tried to do it. I don't understand why.

**Comment by testforstephen** [comment]
We didn't publish Java debugger extension to Gitpod, i don't know how did you install this extension in Gitpod.

Your issue looks duplicated with https://github.com/microsoft/vscode-java-debug/issues/1080

**Comment by mattwelke** [comment]
@testforstephen I didn't do anything to install the extension. I forked the Spring pet shop sample and opened it in the Gitpod site. I clicked "prebuild" and then when that step was finished, opened it in a Gitpod workspace. My goal was to just see how things worked out of the box, without me customizing anything.

**Comment by mattwelke** [comment]
I agree that this is a duplicate of https://github.com/microsoft/vscode-java-debug/issues/1080. Sorry, I did a search for "Gitpod" and only found the closed issue from 2019. I didn't see the one from 4 days ago. Closing this issue.

**Comment by akosyakov** [comment]
Gitpod is not allowed to use MS marketplace, so it is using OpenVSX instead. This extension is auto published there based on GitHub releases in this repo which was broken before: https://github.com/microsoft/vscode-java-debug/issues/1083

@testforstephen Would you be opened to take ownership in OpenVSX and publish there directly? Similarly how RedHat is publishing java lang support: redhat-developer/vscode-java@ff51dbf/Jenkinsfile#L73-L82 The docs for publishing the extension are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions. Technically this should be straightforward. You basically must get a token and call `ovsx publish` with it.

**Comment by testforstephen** [comment]
I'll invite our PM @nickzhums for comments.

**Comment by nickzhums** [comment]
> Gitpod is not allowed to use MS marketplace, so it is using OpenVSX instead. This extension is auto published there based on GitHub releases in this repo which was broken before: #1083
> 
> @testforstephen Would you be opened to take ownership in OpenVSX and publish there directly? Similarly how RedHat is publishing java lang support: [redhat-developer/vscode-java@ff51dbf](https://github.com/redhat-developer/vscode-java/commit/ff51dbf)/Jenkinsfile#L73-L82 The docs for publishing the extension are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions. Technically this should be straightforward. You basically must get a token and call `ovsx publish` with it.

Thanks @akosyakov . We'll need to look into this and get back to you, for the time being feel free to provide more info
