### ISSUE TITLE
application start failed for iTerm.app as external launch console

### ISSUE THREAD

**Issue by dominik42** [microsoft/vscode-java-debug#1089]
If using iTerm.app (iterm2) as default external terminal app in MacOS, starting of java applications failed.
It works if Terminal.app is used as default external terminal.

##### Environment
- Operating System: MacOS X Catalina 10.15.7
- JDK version: OpenJDK 17
- Visual Studio Code version: 1.62.3
- Java extension version: 0.18.6 and Language Support for Java(TM) by Red Hat 1.0.0
- Java Debugger extension version: 0.37.0

##### Steps To Reproduce
1. add in settings.json: `"terminal.external.osxExec": "iTerm.app"`
2. set in launch.json: `"console": "externalTerminal",`
2. start java application

##### Current Result
1. new window for iTerm is opened
2. iTerm/zsh prints `Last login: Wed Nov 24 13:33:47 on ttys006`
3. iTerm/zsh prints `You have mail.`
4. only the first 1024 chars of kind of command line is shown, but its obviously missing the last part
`
cd '/Users/Dominik/Documents/steel42/webapp'; env 'SECURITYSESSIONID=186a8' 'USER=Dominik' 'LOGNAME=Dominik' 'PATH=/Users/Dominik/bin:/Users/Dominik/.jenv/shims:/Users/Dominik/.nvm/versions/node/v10.16.3/bin:/Users/Dominik/Library/Mobile Documents/com~apple~CloudDocs/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/Dominik/.nvm:/Users/Dominik/.jenv/bin' 'SSH_AUTH_SOCK=/var/folders/hg/36tg3kxd22b2fglv7dv0r72m0000gn/T//ssh-JCJ7UdkuzWsM/agent.1132' 'SHELL=/bin/zsh' 'HOME=/Users/Dominik' '__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x3' 'LaunchInstanceID=8C7E90AF-DED3-41B7-93E0-34C175AE5AC3' 'TMPDIR=/var/folders/hg/36tg3kxd22b2fglv7dv0r72m0000gn/T/' 'XPC_SERVICE_NAME=com.microsoft.VSCode.51184' 'XPC_FLAGS=0x0' 'ORIGINAL_XDG_CURRENT_DESKTOP=undefined' 'SHLVL=0' 'PWD=/' 'OLDPWD=/' 'ZSH=/Users/Dominik/.oh-my-zsh' 'PAGER=less' 'LESS=-R' 'LSCOLORS=Gxfxcxdxbxegedabagacad' 'SSH_AGENT_PID=1134' 'JAVA_REMOTE_DEBUG=-agentlib:jdwp=transport=dt_socket,address=88%
`
5. command line prompt is shown: `➜  /Users/Dominik`
6. AGAIN the SAME first PART of the kind of command line used from VSCode to start the application is shown, only 1024chars.
7. few seconds later the TimeoutException message is shown.

Due to this 1024 chars issue, I also use `"shortenCommandLine": "argfile"` but without any success.

No outpout at the developer tools console.

Java language Server Log: 
```
!ENTRY org.eclipse.jdt.ls.core 1 0 2021-11-24 13:26:34.764
!MESSAGE >> workspace/executeCommand vscode.java.resolveJavaExecutable

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-11-24 13:26:34.768
!MESSAGE >> workspace/executeCommand vscode.java.checkProjectSettings

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-11-24 13:26:34.795
!MESSAGE >> workspace/executeCommand vscode.java.startDebugSession

!ENTRY java-debug 4 0 2021-11-24 13:26:56.576
!MESSAGE [error response][launch]: Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException
!STACK 0
com.microsoft.java.debug.core.DebugException: Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException
	at com.microsoft.java.debug.core.adapter.handler.LaunchWithDebuggingDelegate.lambda$launchInTerminal$0(LaunchWithDebuggingDelegate.java:130)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$sendRequest$2(AbstractProtocolServer.java:175)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
##### Expected Result
It works with Terminal.app as default external terminal app using this
settings.json: `"terminal.external.osxExec": "Terminal.app"` ; launch.json: `"console": "externalTerminal",`
It works also with default integratedTerminal or internalConsole
settings.json: `"console": "integratedTerminal",` or `"console": "internalConsole",`

##### Additional Informations
The iTerm.app uses zsh as SHELL and need ca. 3s to startup.

**Comment by testforstephen** [comment]
Usually terminals have a maximum length limit on the command line, and it looks like you've added a long list of envs that are dumped to the command line. Since this is a system issue, there is not much we can do for it. For such case, you're recommended to use `internalConsole` or other terminals to launch your app.

**Comment by dominik42** [comment]
1) I use zsh under Mac OSX 10.15.7 (Catalina). The 'wrapper' around that shell is either the Mac OS built in 'terminal' or the 3rd party application 'iTerm2'. Both are usually used under other Mac OS X versions too. 
The maximum length limit on that command line is 262144 chars determined with `echo "%$(getconf ARG_MAX)s"`.
2) My current setup used ENV with a total count of 3535 chars (BTW with VSCODE_* variables of 1226 chars 😀) so thats not that many ...

How VSCode determine, which ENVs are used for the startup command line ? I've tried to reduce the ENVs used by the Terminal.app to under 1024 chars. Then I started code from within this shell by using `code` with . But every subsequent launch of my application under development from within VSCode with settings `"terminal.external.osxExec": "Terminal.app",` uses the Terminal.app but with different ENVs, not those one I've set before ?

**Comment by testforstephen** [comment]
> 1. I use zsh under Mac OSX 10.15.7 (Catalina). The 'wrapper' around that shell is either the Mac OS built in 'terminal' or the 3rd party application 'iTerm2'. Both are usually used under other Mac OS X versions too.
The maximum length limit on that command line is 262144 chars determined with echo "%$(getconf ARG_MAX)s".
> 2. My current setup used ENV with a total count of 3535 chars (BTW with VSCODE_* variables of 1226 chars 😀) so thats not that many ...

The length limit is one aspect. Another thing is that the terminal must dump the env to the command line so that Java apps can inherit them. I remember some old MacBooks would take a long time to print a long command line to an external terminal so that the Java debugger timed out. If in your case, you believe the command line is not exceeding the limit, then you could extend the timeout range via user setting `java.debug.settings.jdwp.requestTimeout`. Anyway, `internalConsole ` is a good option for your case as well, because the debugger will use Java process API to launch your app. 

Your second question is about how VS Code inherit the ENVs, I suggest you to open an issue in the upstream VS Code repo https://github.com/microsoft/vscode/issues for that.
