### ISSUE TITLE
Java output and debug info wont appear in terminal.

### ISSUE THREAD

**Issue by Xx-Fox-Trot-xX** [microsoft/vscode-java-debug#1091]
The standard
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6...

is still remaining for the shell, but excluding that, no matter which codes I run, old or new, nothing pops up. I'm unsure of how to fix it because I'm not sure how it happened in the first place. Everything is the latest update, I reset modified settings, turned it off and on again, etc.

**Comment by testforstephen** [comment]
Could you pls provide reproducing steps? It's better to have some sample code for us to reproduce.

**Comment by Xx-Fox-Trot-xX** [comment]
Ah it was not a code specific issue. None of my codes would run. I
downloaded a previous version of the red hat Java language extension and
that fixed it. Thank you!

**Comment by testforstephen** [comment]
Looks like duplicates with https://github.com/redhat-developer/vscode-java/issues/2231

Do you run a standalone Java file in VS Code?

**Comment by testforstephen** [comment]
Duplicates with https://github.com/redhat-developer/vscode-java/issues/2231, there is a regression about single file support (no folder opened in VS Code).

The CI build https://download.jboss.org/jbosstools/jdt.ls/staging/java-1.2.0-470.vsix has fixed it, you can [install from vsix](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix).

Another workaround is to open a folder containing your Java files on VS Code.
