### ISSUE TITLE
Wont run code

### ISSUE THREAD

**Issue by yalsabah** [microsoft/vscode-java-debug#1095]
Issue Type: <b>Bug</b>

Everytime i click the run/debug code button, it does nothing

Extension version: 0.37.0
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by testforstephen** [comment]
Seems to duplicate with https://github.com/redhat-developer/vscode-java/issues/2231, there is a regression about single file support (no folder opened in VS Code).

The CI build https://download.jboss.org/jbosstools/jdt.ls/staging/java-1.2.0-470.vsix has fixed it, you can [install from vsix](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix).

Another workaround is to open a folder containing your Java files on VS Code.
