### ISSUE TITLE
How to develop this extension. Get "No delegateCommandHandler for vscode.java.startDebugSession" while debugging the extension

### ISSUE THREAD

**Issue by sandipchitale** [microsoft/vscode-java-debug#1105]
I am trying to implement some other commands available in [Eclipse JDT Debugger](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fviews%2Fvariables%2Fref-variables_view.htm&resultof%3D%2522%2576%2561%2572%2569%2561%2562%256c%2565%2573%2522%2520%2522%2576%2561%2572%2569%2561%2562%256c%2522%2520%2522%2576%2569%2565%2577%2522%2520). I have forked the repository. However when I try to debug the extension I always run into: 

```
No delegateCommandHandler for vscode.java.startDebugSession
```

![image](https://user-images.githubusercontent.com/3310939/147370194-f408b761-018f-4457-ba40-dd93132499f9.png)

![image](https://user-images.githubusercontent.com/3310939/147370202-01efdf91-738b-4727-a91e-0115180850ba.png)

Reloading VSCode does not help as has been indicated elsewhere.

BTW I also tried to build vsix package and install it. That runs into same issue.

Will restarting JLS help? Or may be disable enable extentions?

I think this has something to do with the order of activation of extensions. Is there a way to control the order of activation of extension?

**Is the correct way to develop this extension documented here.?**

The strong motivation for this for me is that I can truly switch over to VS Code for Java development.

- All Instances
- All References
- Open Actual Type
- Open Declared Type

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce

- Clone the repo
- npm install etc
- Debug the extension using F5

##### Current Result

See this exception in Extension Host log:

No delegateCommandHandler for vscode.java.startDebugSession

##### Expected Result

I should be able to debug the extension.

**Comment by sandipchitale** [comment]
In addition, I am trying to also implement Groovy support so that I can debug gradle build scripts. I am familiar with JDWP (JDI) and I know that JDI does support higher level JVM languages like Groovy, JSP.

**Comment by sandipchitale** [comment]
I think this has something to do with the order of activation of extensions.

**Comment by sandipchitale** [comment]
I see this in JLS.log:

Contains: Cannot extract bundle symbolicName or version c:\professional\vscode\extensions\vscode-java-debug\server\com.microsoft.java.debug.plugin-0.34.0.jar
java.nio.file.NoSuchFileException: c:\professional\vscode\extensions\vscode-java-debug\server\com.microsoft.java.debug.plugin-0.34.0.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)

And I do not see the server folder in my project. Maybe that is the issue.

**Comment by sandipchitale** [comment]
Ah... [CONTRIBUTING.md](https://github.com/microsoft/vscode-java-debug/blob/main/CONTRIBUTING.md) may have what I need. Will give that a try.

**Comment by sandipchitale** [comment]
I think following CONTRIBUTING.md helped. You can close the issue.

I suggest that add an explicit section on how to contribute and how to build and run the extension in the top level README.md.

**Comment by testforstephen** [comment]
it makes sense to mention CONTRIBUTING.md in README.
