### ISSUE TITLE
should not include test classes in classpaths when auto resolve maven project

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#111]
Original notes from @claycephas , 
https://github.com/Microsoft/vscode-java-debug/pull/108#issuecomment-339014200

Current implementation just invoked `JavaRuntime.computeDefaultRuntimeClassPath(javaProject)`, the result is not accurate. Need fix these two issues:
1. When debugging a maven-based project with VS Code, it is including test classes in the classpaths. 

2. For maven project with multiple modules, the auto-generated classpaths by the debugger didn't contain the depended modules' classpaths.

**Comment by claycephas** [comment]
Some potential places to look:

* https://github.com/Microsoft/java-debug/blob/master/com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveClasspathsHandler.java
* https://github.com/eclipse/eclipse.jdt.debug/blob/fce60cee0f2525cbeeb808581833fbaa9deaa449/org.eclipse.jdt.launching/launching/org/eclipse/jdt/launching/JavaRuntime.java

**Comment by testforstephen** [comment]
For maven project with multiple modules, the auto-generated classpaths by the debugger didn't contain the depended modules' classpaths. Also need fix it.

**Comment by claycephas** [comment]
Is there a way to make this conditional so that some launch configurations include the test classes and some don't? I'm thinking we would want to support debugging the implementation code (without tests) or debugging unit tests (which should include tests).

**Comment by testforstephen** [comment]
We'll add special support for JUnit. See task https://github.com/Microsoft/vscode-java-debug/issues/76

**Comment by gorkem** [comment]
I think @fbricon has adopted JDT.LS and m2e to exclude test classes.

**Comment by yaohaizh** [comment]
Close this as the LS filtered test classes.

**Comment by supersonicclay** [comment]
@yaohaizh I'm still seeing `/myproject/target/test-classes` listed in the classpaths with redhat.java@0.21.0 and vscjava.vscode-java-debug@0.7.0.

**Comment by yaohaizh** [comment]
Need further verify this issue.

**Comment by andxu** [comment]
The bug is still unfixed:

![image](https://user-images.githubusercontent.com/17075863/41574048-5f6cb8e8-73b2-11e8-99c6-a5d4f1c76e5d.png)

![image](https://user-images.githubusercontent.com/17075863/41574116-a2e33368-73b2-11e8-91f9-2d59ed904122.png)
