### ISSUE TITLE
How to set the *.argfile encoding type ?

### ISSUE THREAD

**Issue by aewnfin** [microsoft/vscode-java-debug#1112]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. .vscode/settings.ison as follows：
"[java]": {
    "files.encoding": "utf8"
  },
The command line is shown below：
java @*.argfile com.example.demo.MainApp
错误: 无法初始化主类 com.example.demo.MainApp
原因: java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContext
2. The encoding of the file *.argfile is utf-8 ,java couldn't identify it correctly
3. I want to set the encoding of the file to GBK ,what should I do ?
The following settings are not valid：
"[bat]": {
    "files.encoding": "gbk"
  },
"files.associations": {
    "*.argfile": "bat"
  }

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by aewnfin** [comment]
My maven repository contains Chinese path "D:\备份\LocalRepository\apache-maven"

**Comment by testforstephen** [comment]
*.argfile is auto generated by Java debugger, you cannot change its encoding through settings.json. From my experiment, it seems the encoding of *.argfile is not important. On Windows, I add Chinese string to the classpath, then run the app with *.argfile, it works well for me.

![image](https://user-images.githubusercontent.com/14052197/150526842-458c79d5-7c5f-4376-92c5-728df48733e5.png)

Based on my experience, if you want to use Chinese file path or input/output Chinese characters in Java, the best way is to change your current system locale to Chinese.

![image](https://user-images.githubusercontent.com/14052197/150527735-6ce7ca69-1390-4650-8885-287b25ab5a65.png)

**Comment by testforstephen** [comment]
Current workaround is to disable *.argfile. Go to .vscode/launch.json, change the launch setting to `"shortenCommandLine": "none"`.

If launch.json doesn't exist, use the following approach to generate one first.
![image](https://user-images.githubusercontent.com/14052197/150531012-3ccb88ce-dee8-4b33-9256-954b0cd206ab.png)
