### ISSUE TITLE
Breakpoints are skipped unless they are in the debugged class itself

### ISSUE THREAD

**Issue by EricBuist** [microsoft/vscode-java-debug#1116]
When debugging a Java program, only the breakpoints in the main class itself are stopped at. The main class is calling other classes and the debugger ignores any breakpoint I put in such classes. The debugged project is configured through Maven. There are multiple Maven modules in the project, but even when the debugged class I put breakpoints in is in the same module as my main or testing class, breakpoints are ignored.

##### Environment
- Operating System: Windows 10
- JDK version: OpenJDK 11
- Visual Studio Code version: 1.63.2
- Java extension version: 0.20.0
- Java Debugger extension version: 0.37.0

##### Steps To Reproduce
1. Open a folder with a Maven-based Java project containing multiple files.
2. Put a breakpoint in a class called by another class with a main method.
3. Start debugging the main method.
4. Observe that the breakpoint in other class is skipped.

##### Current Result

The breakpoints are skipped, as if no breakpoints were set. I checked many times and didn't toggle any option disabling all breakpoints. Debugger works because I can successfully set a breakpoint in the main class.

##### Expected Result

Breakpoints should be stopped at, whether in the main class being debugged or any method called by the debugged class.

**Comment by testforstephen** [comment]
I cannot reproduce it, could you pls provide a mini sample to reproduce this issue?

**Comment by EricBuist** [comment]
[simple1.zip](https://github.com/microsoft/vscode-java-debug/files/7942487/simple1.zip)
Hi, the attached project exhibits the issue. Put a breakpoint at the Simple.toString() method, start the test TestSimple.test1 in debug mode and observe that the breakpoint is skipped.
Possible that this happens only when the extension runs in remote mode. I got this problem when using the Remote WSL extension.

**Comment by testforstephen** [comment]
works for me. Could you try some more projects?

https://user-images.githubusercontent.com/14052197/151284173-8cdb0c47-bfa0-49fc-b359-ff8b09f42759.mov

**Comment by EricBuist** [comment]
Interesting. If I place a line breakpoint like you did, step tracing works. However, if I place a method breakpoint (one line above than what you did), then it is skipped.

**Comment by testforstephen** [comment]
Only line breakpoints are allowed, method breakpoints are not supported yet.
