### ISSUE TITLE
java.P5.java

### ISSUE THREAD

**Issue by Sarveshpc** [microsoft/vscode-java-debug#1120]
import java.util.*;

class p3{
    public static void main(string[] arg) {
        String s1,s2;
        Snner sc = new Snner(sytem.in);
        s1 = sc.nextline();
        s2 = sc.nextline();
        if(s1.length()!=scanner sc = new Snner(sytem.in);
        s1 = sc.nextline();
        s2 = sc.nextline();
        if(s1.length()!=s2.length())
        {
        system.out.printin("Not Anagram");
        return;
        char arr1[] = s1.tocharArray();
        char arr2[] = s2.tocharArray();
    
        Arrays.sort(arr1);
        Arrays.sort(arr2);
    
        s1 = new String(arr1);
        s2 = new String(arr2);
   
        if(s1.equals(s2)){
         
            system.out.printin("Anagram");
        {
            system.out.printin("Not Anagram");
}

**Comment by testforstephen** [comment]
Could you describe the issue you have with more details? thanks.
