### ISSUE TITLE
Run Test: Resolving launch configuration

### ISSUE THREAD

**Issue by dodalovic** [microsoft/vscode-java-debug#1126]
Maven project, latest VSCode. PopOS Linux 21.10

When in Java Projects view, and I find `src/test/java` dir, and do a right click on it, to invoke tests, this shows up, and never dissappears.

![image](https://user-images.githubusercontent.com/6358061/156438359-88e8d236-f076-4555-8469-e78550398875.png)

**Comment by testforstephen** [comment]
@dodalovic thanks for reaching out. Could you mind sharing a minimum sample project to help us reproduce it?

this is related with Java Test Runner, add @jdneo for further investigation.

**Comment by jdneo** [comment]
Could you also provide the version of `Test Runner for Java`? Is it a regression (works on previous version)?

**Comment by onixldlc** [comment]
after some experimenting i found some interesting stuff, so i re-download the template from [spring.io](https://start.spring.io/) and copy pasted all the code from the previous project, it works just fine, after looking on the JAVA PROJECT tabs i can see that on the old workspace the same class is not visible
![image](https://user-images.githubusercontent.com/81515667/178125202-e1c04970-f33d-475e-9ac5-339c92906cab.png)

java version:
```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)
```

i tried: 
  -  rebuild workspace: doesn't work
  -  clean workspace: doesn't work

the only method that work for me is to add it manually using the button and copy paste the old class to the new one
![image](https://user-images.githubusercontent.com/81515667/178125271-0f410b2f-9d5c-4f87-9983-5ccdd3a4a32d.png)
