### ISSUE TITLE
Put full name of thread in hover tooltip in Call Stack panel

### ISSUE THREAD

**Issue by sbj42** [microsoft/vscode-java-debug#1128]
The hover tooltip in the call stack for a thread is just "Thread".  Please change it so that it includes the full thread name.

When the RUN AND DEBUG sidebar is narrow, some thread names don't fit in the CALL STACK panel.  If the hover tooltip shows the full name then I wouldn't have to expand the sidebar to find the thread I want.

##### Environment
- Operating System: Windows
- JDK version: openjdk version "17.0.2" 2022-01-18
- Visual Studio Code version: 1.65.0
- Java extension version: redhat.java v1.4.0
- Java Debugger extension version: vscjava.vscode-java-debug v0.38.0

##### Steps To Reproduce
1. Attach the debugger to a JVM
2. Shrink the sidebar such that at least one thread name is truncated
3. Hover over that thread with the mouse

Here's an example screenshot:

![image](https://user-images.githubusercontent.com/99791/156828631-834818b0-5a4a-48d6-a7b5-7331459d76f1.png)

##### Current Result

Hover text reads: `Thread`

##### Expected Result

Hover text should read: `Thread [Full name of the thread here]`

**Comment by samochod23** [comment]
Open service brook ¥€¢£®™
TV 📺} ™>Umbrella ☔ Holding. S. Z. I.o.

pt., 4 mar 2022, 19:31 użytkownik James Clark ***@***.***>
napisał:

**Comment by testforstephen** [comment]
@sbj42 thanks for reaching out. This is a reasonable improvement.

However, the hover text is provided by VS Code itself, which uses the node kind (e.g. Thread) instead of the node name. Could you help open an issue at https://github.com/microsoft/vscode/issues for this? thanks.

**Comment by sbj42** [comment]
Okay, submitted as https://github.com/microsoft/vscode/issues/144540

**Comment by testforstephen** [comment]
Closing it since vscode 1.66 release has fixed this issue.
