### ISSUE TITLE
Disable preview features for jar export

### ISSUE THREAD

**Issue by 0x0x0x0x** [microsoft/vscode-java-debug#1130]
I have created a java project with no build tools enabled in vs code and now I want to export this project to jar in Java 17. However it is being forced into export with preview features enabled. Is there a configuration to disable these features or could you add one?

##### Environment
- Operating System: Linux & Windows
- JDK version: 17.0.1
- Visual Studio Code version: 1.64.2
- Project Manager for Java version: v0.19.0

**Comment by testforstephen** [comment]
You can create a file `.settings/org.eclipse.jdt.core.prefs` in your root folder for that.
```
org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures=disabled
```

![image](https://user-images.githubusercontent.com/14052197/157798083-a5c0b175-65e5-433a-bc29-86f07b19e8e6.png)

**Comment by 0x0x0x0x** [comment]
Thank you, it resolved the issue.
