### ISSUE TITLE
Java Web project compiles all the time when save

### ISSUE THREAD

**Issue by Matheeus00** [microsoft/vscode-java-debug#1131]
Sometimes when I save a Java file on VSCODE, the project decompiles and compiles again, the intellisense don't work as well. 

##### Environment
- Operating System: Windows 10 64bits
- JDK version: 13
- Visual Studio Code version: 1.65
- Java extension version: 1.4.0
- Java Debugger extension version: 0.38.0

##### Steps To Reproduce
1. Open a Java Web project with Gradle;
2. Every time a file has saved by pressing CTRL + S, the whole project compiles again, it takes a lot of time, preventing to make changes in the code.

OBS: Unfortunately I cannot show how this issue happen.

**Comment by luciano-zimermann** [comment]
This is happening for me as well, its a big projet where it is hapenning

**Comment by mozhuanzuojing** [comment]
请看wiki中的gradle性能问题，关闭vfs

**Comment by luciano-zimermann** [comment]
This started happening to me after the VSCode update on Friday. I opened an issue there, but I was told it was to open the issue in the Java extension, and so this issue was already open.

**Comment by luciano-zimermann** [comment]
> 请看wiki中的gradle性能问题，关闭vfs

What is the vfs?

**Comment by mozhuanzuojing** [comment]
please read https://github.com/redhat-developer/vscode-java/wiki/Gradle-Support#performance-degrades-with-gradle-project

**Comment by luciano-zimermann** [comment]
I downgraded the extension version to work

**Comment by augustsaintfreytag** [comment]
If we have to _downgrade_ to “fix” the issue, it has not been fixed, has it? This bug makes hot reloading entirely unusable, it spawns so many `java` processed to recompile, it starts to lock up the system.

![Image](https://github.com/user-attachments/assets/6957c0fd-e6c6-4c71-a26c-2d218c8dd048)
