### ISSUE TITLE
Visual Studio Code Java debugger stuck in internal JDK code

### ISSUE THREAD

**Issue by EricBuist** [microsoft/vscode-java-debug#1147]
When I try to debug a Java program with multiple classes, step tracing into code calling a method within another class doesn't work correctly as it gets stuck in code from ClassLoader (e.g., Launcher$AppClassLoader.loadClass, ClassLoader.loadClass, ClassLoader.checkPackageAccess, etc.) and never goes out. No matter how many times I step into or step out, it never goes out. The only workaround is to go into the called method, add a break point and resume execution.

##### Environment
- Operating System: Windows 10
- JDK version: 1.8.0_312
- Visual Studio Code version: 1.65.2
- Java extension version: 0.22.1
- Java Debugger extension version: 0.40.0

##### Steps To Reproduce
1. Create a Java project with a main method calling another method accepting a File argument, e.g., public static void test1(File file) {...} public static void main(String[] args) { test1(new File("f"));}
2. Add a breakpoint on the line calling test1.
3. Start debugger and step into test1.
4. Observe that the code remains stuck in JDK internals and requires a lot of step into and/or step out to get back to user code.
Things get worse and worse with projects having multiple classes in different packages.

##### Current Result

When stepping into a method calling into a method from another class, the debugger gets trapped in JDK internal code like the ClassLoader and requires a large number of steps to get into the debugged code. There is no obvious way to skip JDK internals during debugging, no "step filtering" options like there is in Eclipse.

##### Expected Result

The debugger should not step into code whose source is missing, stepping out should return to the caller rather than remaining trap in JDK internals, or there should be an option to filter steps corresponding to JDK internals.

**Comment by testforstephen** [comment]
This is by design.

You can use the following user setting to ignore the specified classes during stepping.
```json
    "java.debug.settings.stepping.skipClasses": [
        "java.lang.ClassLoader",
        "$JDK"
    ]
```

**Comment by EricBuist** [comment]
And where do I put these settings? And why is copy/pasting from web pages favored over well-designed GUI that would allow to set these things? In Eclipse, there is a check box, something like step filter, and that solves it. With this practice, some people will be more and more tempted to go quick and copy/paste all sorts of non-sense from various sources, and that will cause problems.

**Comment by jbhateja** [comment]
> This is by design.
> 
> You can use the following user setting to ignore the specified classes during stepping.
> 
> ```json
>     "java.debug.settings.stepping.skipClasses": [
>         "java.lang.ClassLoader",
>         "$JDK"
>     ]
> ```

Hi @testforstephen, Are there platform-specific settings that can modify this behavior?
