### ISSUE TITLE
Problems with using Unicode characters in paths

### ISSUE THREAD

**Issue by AgainPsychoX** [microsoft/vscode-java-debug#1149]
See https://github.com/redhat-developer/vscode-java/issues/2392 and https://github.com/redhat-developer/vscode-java/issues/2392#issuecomment-1090066575

**Comment by testforstephen** [comment]
See https://github.com/microsoft/java-debug/pull/458, we have made some improvement on this case. Could you have a try on the latest debugger to see if this issue still exists?
