### ISSUE TITLE
Support multi-root workspace

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-debug#115]
VS Code will be releasing the long-anticipated multi-root workspace support. Accordingly, we need to also make sure the debugger can work correctly in such workspaces.

**Comment by yaohaizh** [comment]
Blocking by the PR: https://github.com/eclipse/eclipse.jdt.ls/pull/412

**Comment by yaohaizh** [comment]
# Test on Linux/Ubuntu environment

1. Project petclinic
2. Project with single file
2. Ubuntu 16.04 LTS 
4. VSCode 1.18.0 (The latest version with Mutli-root)
3. Go through features: Breakpoint/callstack/view variable/external sources/main class/threads/java 9/single files)

Result:
1. This version works including Java as expected.
2. The single file debugging works as expected.

**Comment by yaohaizh** [comment]
https://github.com/Microsoft/java-debug/pull/114
https://github.com/Microsoft/vscode-java-debug/pull/174
