### ISSUE TITLE
Debugger allows setting of break points and appears to launch but the control applet disappears and the debugger does not show any of the detail of the code being 

### ISSUE THREAD

**Issue by tracyntimothy** [microsoft/vscode-java-debug#1151]
Issue Type: <b>Bug</b>

Running latest version of VS CODE on a Win10 64bit platform, latest version of debugger extension.

Extension version: 0.40.0
VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.90GB free)|
|Process Argv|--crash-reporter-id 4ace4767-4d89-4f70-9e76-80290230684b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

![Capture](https://user-images.githubusercontent.com/60150019/163012868-a79b3494-82f9-41ff-b0f9-ce7ae498e15f.JPG)

**Comment by tracyntimothy** [comment]
I've gone through multiple rounds of sequentially uninstalling , reloading , reinstalling, loading extensions

**Comment by testforstephen** [comment]
@tracyntimothy Thanks for reaching out. Do you mean the breakpoints are skipped during debugging? And would you mind sharing the full snippet for us to investigate the issue?
