### ISSUE TITLE
variables not show as `(...)` by default

### ISSUE THREAD

**Issue by AYiXi** [microsoft/vscode-java-debug#1154]
### How to set 0-10 like 11, 12 show by default rather than click `(...)` 

<img width="435" alt="image" src="https://user-images.githubusercontent.com/28703786/163556453-80712165-b065-4feb-80d0-f4cc60b9f36a.png">

**Comment by testforstephen** [comment]
VS Code has added a setting `debug.autoExpandLazyVariables` to control whether to auto expand lazy variable. That will be released in next VS Code version. Currently you can try it with VS Code Insider first.

**Comment by AYiXi** [comment]
oh...thanks

**Comment by AYiXi** [comment]
> VS Code has added a setting `debug.autoExpandLazyVariables` to control whether to auto expand lazy variable. That will be released in next VS Code version. Currently you can try it with VS Code Insider first.

oh... thanks

**Comment by testforstephen** [comment]
The latest VS Code 1.67.0 has provided a setting `debug.autoExpandLazyVariables` to allow you to expand the variable full value by default. So closing this issue.
