### ISSUE TITLE
debug orther jars 

### ISSUE THREAD

**Issue by swtseaman** [microsoft/vscode-java-debug#1155]
[provide a description of the issue]

##### Environment
版本: 1.66.2
提交: dfd34e8260c270da74b5c2d86d61aee4b6d56977
日期: 2022-04-11T07:47:29.396Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.3.0
JDK:11

##### Steps To Reproduce
The project is developed by Maven referencing other jar packages; When debugging, you need to follow other jars to see the situation;
But it's a class file that says 
// Failed to get sources. Instead, stub sources have been generated by the disassembler.
// Implementation of methods is unavailable.

Try right clicking on the code and selecting additional source code through After finding the corresponding jar file under m2 / repository /, there is still no change

How should I use it

**Comment by testforstephen** [comment]
Could you try "**F1 -> Java: Clean Java Language Server Workspace**"?
