### ISSUE TITLE
Support JEP 425: Virtual Threads (JDK 19)

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-debug#1159]
This issue is used to track the work to support "Virtual Threads" in JDK 19.

https://openjdk.java.net/jeps/425
https://jdk.java.net/loom/

**Comment by AlanBateman** [comment]
JEP 425 integrated into JDK 19 in early May for build 22.
Links to the JDK 19 schedule, downloads, and docs can be found here:
https://jdk.java.net/19/
