### ISSUE TITLE
Conditional breakpoints

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-debug#118]
Support conditional breakpoints with complex expressions. This is a feature that can be released after expression evaluation is in place.

#114 is for tracking expression evaluation.

**Comment by clankill3r** [comment]
Are simple expressions supposed to work? I tried `true == false` on a breakpoint but it still triggered.

**Comment by andxu** [comment]
Expression evaluation is supported in 0.5.0, Conditional breakpoints is not supported now, I will work on this on later releases.

**Comment by andxu** [comment]
Done in 0.7.0
