### ISSUE TITLE
Support Step Into Target

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-debug#1192]
VS Code 1.69 brings the new capability "step into target", we can adopt it in the case of multiple method invocations in the same line.

https://code.visualstudio.com/updates/v1_69#_improved-step-into-target-ui

https://microsoft.github.io/debug-adapter-protocol/specification#Requests_StepInTargets

**Comment by soccerdude288** [comment]
I would like to upvote this feature request.

**Comment by testforstephen** [comment]
This has been implemented with https://github.com/microsoft/java-debug/pull/434.

https://user-images.githubusercontent.com/14052197/197928155-e2293882-fb59-4582-b971-2a50e5b4bbe0.mp4

Currently it has been in pre-release version of debugger extension. And also will be in the stable version 0.46.0 this week.
