### ISSUE TITLE
Support BreakpointLocationsRequest 

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-debug#1193]
See [Show visual hints for inline breakpoints #31612](https://github.com/microsoft/vscode/issues/31612) and [Find the possible Breakpoints for a source line](https://github.com/microsoft/debug-adapter-protocol/issues/72#)

**Comment by testforstephen** [comment]
See the latest UX on Java Debugger. When you add a line breakpoint, if that line contains inline breakpoints, then Java debugger will visualize those inline positions with grey circles.

![image](https://user-images.githubusercontent.com/14052197/190965636-d2794c99-115e-4d72-8269-b7f6e9d38efe.png)

**Comment by indjosh12** [comment]
pls support me i need fix about problem PDF
![Screenshot 2024-09-10 155705](https://github.com/user-attachments/assets/12d21cfe-d930-480b-849c-209790d39f9e)

**Comment by indjosh12** [comment]
![image](https://github.com/user-attachments/assets/d00df7d1-4762-4c5d-8223-145a4f8557fa)
i dont understand PDF
