### ISSUE TITLE
Unable to build project when file encoding is in Big5 

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode-java-debug#1199]
##### Environment
- Operating System: `Microsoft Windows [ver 10.0.20348.825]`
- JDK version: `1.8`
- Visual Studio Code version: `1.69.2`
- Java extension version: `v1.9.0`
- Java Debugger extension version: `v0.43.0`

##### Steps To Reproduce
1. Follow the [Troubleshooting Guide for Encoding Issues](https://github.com/microsoft/vscode-java-debug/blob/main/Troubleshooting_encoding.md)'s `3.1) Fix Suggestion : Change system locale to the target language.` to configure Windows.

2. Clone my [sample repo](https://github.com/doggy8088/java-encoding-issue-big5)

    ```sh
    git clone https://github.com/doggy8088/java-encoding-issue-big5.git
    ```

3. Open folder from Visual Studio Code

4. The encoding of the `src\App.java` file is `Big5`.

5. Build project.

    ![image](https://user-images.githubusercontent.com/88981/182914225-1e8e3f3f-2c2c-40ea-b00e-cb01d9faa15b.png)

    ![image](https://user-images.githubusercontent.com/88981/182914506-3d745ed1-f231-4cdb-a07e-a90e9ccd7196.png)

    ![image](https://user-images.githubusercontent.com/88981/182916340-33cf96df-426a-4285-8b90-85f9bd3b71a1.png)

6. Run the class. You will get `String literal is not properly closed by a double-quote` error.

    ![image](https://user-images.githubusercontent.com/88981/182914648-a71ed887-c74b-4094-a39a-a85acf08bef7.png)

7. If I run `javac` with `-encoding big5` by myself. It works.

    ![image](https://user-images.githubusercontent.com/88981/182915073-61b926f1-3264-4b33-81cd-824076183fcf.png)

    ```sh
    javac -sourcepath src -classpath lib -d bin -encoding big5 .\src\*.java
    cd bin
    java App
    ```

##### Current Result

```log
[Error - 8:13:16 PM] Aug 3, 2022, 8:13:16 PM Error occured while building workspace. Details: 
 message: String literal is not properly closed by a double-quote; code: 1610612995; resource: C:/Projects/test1/src/App.java; line: 3
```

##### Expected Result

I already configured system locale and I expected to build project successfully.

##### Additional Informations

I also recorded a video clip. Please watch it. I always can't build project.

YouTube: <https://youtu.be/tfb5SGoE3OI>

In the IntelliJ IDEA, there is a **Project Encoding** setting. After I change to `Big5`, the project can build successfully.

![image](https://user-images.githubusercontent.com/88981/182605362-ac77e625-9786-43b4-84f8-ff5666cd6470.png)

I actually have a big project. I can't change file encoding for every `.java` files. Is it possible to build project successfully?

**Comment by testforstephen** [comment]
@doggy8088 Could you try to change the VS Code setting `files.encoding` to Big5 as well?

**Comment by doggy8088** [comment]
@testforstephen I already did that. It still not working.

**Comment by doggy8088** [comment]
Is there any way I can put `-encoding big5` to the `javac` command when VSCode compiling `.java` files behind the scenes.

**Comment by testforstephen** [comment]
VS Code Java compiler uses the encoding in setting `files.encoding` to compile your Java files by default. You could try to clean cache via "**F1** -> **Java: Clean Java Language Server Workspace**".

**Comment by doggy8088** [comment]
The "**F1** -> **Java: Clean Java Language Server Workspace**" solved all my issues. Thanks!
