### ISSUE TITLE
Cannot invoke

### ISSUE THREAD

**Issue by TBug001** [microsoft/vscode-java-debug#1212]
Type: <b>Bug</b>

I'm not much of a GitHub user, so let me briefly describe my problem.

I don't know since when I use VScode to open Java files, I will be prompted to use JDK17, but at this time, I can still use DEBUG. After a period of time, when I use it again, the DEBUG will not be able to use, and the following error will be displayed. I guess it is the problem of the plug-in "Debugger for Java", but I can't solve it after lowering the version.

Cannot invoke "org.eclipse.jdt.internal.compiler.util.JrtFileSystem.walkModuleImage(org.eclipse.jdt.internal.compiler.util.JRTUtil$JrtFileVisitor, int)" because the return value of "org.eclipse.jdt.internal.compiler.util.JRTUtil.getJrtSystem(java.io.File, String)" is null
![err1](https://user-images.githubusercontent.com/89027753/190426816-dd627455-628f-442c-bb5a-9907de189e4a.png)
![err2](https://user-images.githubusercontent.com/89027753/190426996-b3fb21ed-b4fe-4d5f-9ea0-afb52d2cae48.png)
![err3](https://user-images.githubusercontent.com/89027753/190427034-52cecf08-5aad-4faf-8b29-4f6f52cdaa03.png)
![err4](https://user-images.githubusercontent.com/89027753/190427059-84cc7c53-ca77-4aff-826e-94c77aec75a3.png)

Extension version: 0.44.0
VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.54GB free)|
|Process Argv|--crash-reporter-id d984063b-117c-401c-9522-5dc0346638b3|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by amwestrich** [comment]
Having the same issue but on Linux with openjdk 17.

**Comment by amwestrich** [comment]
The version from two months ago, `v1.8.2022062904` doesn't have the issue.

**Comment by bib1963** [comment]
I see this as well. It needs nothing special, just create a new java project and the error will appear. The only source file is the default App.java which is automatically created.

**Comment by jadavis42** [comment]
@amwestrich  is correct.  I downgraded Language Support for Java(TM) by Red Hat to older version v1.8.2022062904 and the problem goes away.  I'm using VS Code on Windows 10 with jdk 17

**Comment by TBug001** [comment]
@testforstephen   
[log.log](https://github.com/microsoft/vscode-java-debug/files/9576041/log.log)
[client.log](https://github.com/microsoft/vscode-java-debug/files/9576054/client.log)

**Comment by TBug001** [comment]
Here is my configuration file. Can you help me see what's wrong? Now there is a problem with VScode. I need to use IDEA to write an algorithm problem, which is very troublesome

`{
  "code-runner.runInTerminal": true,
  "code-runner.ignoreSelection": true,
  "editor.suggestSelection": "first",
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
  "files.exclude": {
    "**/.classpath": true,
    "**/.project": true,
    "**/.settings": true,
    "**/.factorypath": true
  },
  "java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m",
  "open-in-browser.default": "{\"Open-in-browser: Default\":\"Chrome\"}",
  "c-cpp-compile-run.run-in-external-terminal": true,
  "eslint.runtime": "",
  "files.autoGuessEncoding": true,
  "editor.unicodeHighlight.allowedCharacters": {
    "：": true,
    "！": true,
    "α": true
  },
  //"C_Cpp.updateChannel": "Insiders",
  "window.zoomLevel": 1,
  "editor.unicodeHighlight.allowedLocales": {
    "zh-hans": true
  },
  "update.enableWindowsBackgroundUpdates": false,
  "update.mode": "manual",
  "[java]": {
    "editor.defaultFormatter": "redhat.java"
  },
  "java.jdt.ls.java.home":"d:\\JAVA",
  "workbench.editorAssociations": {
    "*.class": "default"
  },
  "files.associations": {
    "*.class": "bat",
    "*.java": "java"
  },
  "workbench.colorTheme": "Visual Studio Dark",
  "maven.terminal.useJavaHome": true,
  "java.configuration.runtimes": [
  
  {
    "name":"JavaSE-13",
    "path":"d:\\JAVA",
    "sources":"D:\\JAVA\\lib\\src.zip",
    "default":true
  }
  ],
}`

**Comment by testforstephen** [comment]
```
!ENTRY org.eclipse.jdt.ls.core 4 0 2022-09-08 11:16:16.741
!MESSAGE Initialization failed 
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.util.JrtFileSystem.walkModuleImage(org.eclipse.jdt.internal.compiler.util.JRTUtil$JrtFileVisitor, int)" because the return value of "org.eclipse.jdt.internal.compiler.util.JRTUtil.getJrtSystem(java.io.File, String)" is null
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.walkModuleImage(JRTUtil.java:242)
	at org.eclipse.jdt.internal.core.JavaProject.loadModulesInJimage(JavaProject.java:983)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:782)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1103)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1048)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1025)
	at org.eclipse.jdt.internal.core.JavaProject.buildStructure(JavaProject.java:538)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:266)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:597)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:328)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:314)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:269)
	at org.eclipse.jdt.internal.core.JavaProject.getPackageFragmentRoots(JavaProject.java:2384)
	at org.eclipse.jdt.internal.core.JavaProject.getPackageFragments(JavaProject.java:2408)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.cleanupResources(ProjectsManager.java:278)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:107)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:244)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
The NPE above is the reason for the failure, it occurred when Java extension tried to parse your JDK info such as jrt-fs.jar, release. This issue seems related with the JDK installation. 

Could you provide more information about the JDK installation you use?
- What JDK distribution do you use? How do you install it?
- If you're using Linux or macOS, check if your JDK related settings (e.g. `java.home`, `java.jdt.ls.java.home`, `java.configuration.runtimes`) point to any JDK location with symlink.

// @TBug001 @amwestrich @bib1963 @weberhofer @jadavis42

**Comment by TBug001** [comment]
@testforstephen   Windows10 JDK13
![Snipaste_2022-09-16_13-31-13](https://user-images.githubusercontent.com/89027753/190563702-0d8f5828-3ce3-44b2-8bb0-0ef65a40bda6.png)

**Comment by testforstephen** [comment]
Usually, this folder should include a `release` file, which contains the JDK vendor info.
![image](https://user-images.githubusercontent.com/14052197/190564413-4854b302-4945-422f-a33d-0924da9d3332.png)

@TBug001 Could you check if `release` file is missing in your JDK installation?

**Comment by testforstephen** [comment]
I think I eventually reproduced the issue. If I manually delete the `release` file from my JDK installation, then Java extension will throw the NPE error above. Adding it back, then it works again. Java extension does not handle the missing `release` file well.

As far as I know, most of JDK vendors will include a `release` file. So I'm wondering what JDK distribution do you use? How do you install it? By Intellij IDEA, http download, package manager?

**Comment by TBug001** [comment]
> 

The problem was solved according to your method. I re-downloaded a 13.0.2 JDK and copied its release file. Now it works properly. I don't know why the release file is missing, but I think I installed it three years ago via HTTP download

**Comment by TBug001** [comment]
The reason for the problem is the lack of release file. Thank you very much for  testforstephen's kind answer!

**Comment by maresmar** [comment]
Here are steps how to get `release` file for yourself :smile:
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/405#issuecomment-1249082357

**Comment by testforstephen** [comment]
We want to know if it is rare for JDK builds to not contain "release" files. So can you tell us the affected JDK distribution and version? Where can we get it from?

// @amwestrich @bib1963 @weberhofer @jadavis42 @maresmar

**Comment by testforstephen** [comment]
@TBug001 You can set the setting `java.debug.settings.onBuildFailureProceed` to always proceed.

**Comment by maresmar** [comment]
> So can you tell us the affected JDK distribution and version? Where can we get it from?

I use Java 11 from OpenSUSE Tumbleweed in WSL 2.0
```
$ cat /etc/os-release
NAME="openSUSE Tumbleweed"
# VERSION="20220917"
...
$ sudo zypper info java-11-openjdk-devel
Information for package java-11-openjdk-devel:
----------------------------------------------
Repository     : openSUSE-Tumbleweed-Oss
Name           : java-11-openjdk-devel
Version        : 11.0.16.0-2.1
Arch           : x86_64
Vendor         : openSUSE
...
```

**Comment by testforstephen** [comment]
@maresmar thanks for sharing your use case. Good to know that JDK in OpenSUSE doesn't contain `release` by default.

**Comment by amwestrich** [comment]
I use Java 17 from OpenSUSE Tumbleweed (# VERSION="20220918)

.....
Name               : java-17-openjdk-devel
Version            : 17.0.4.0-2.1
Arch               : x86_64
Vendor             : openSUSE
....

Am 19.09.22 um 13:12 schrieb Jinbo Wang:

**Comment by weberhofer** [comment]
In the meantime Java 11 and Java 17 have been updated for openSUSE Tumbleweed and should work nicely:
```
> rpm -q java-17-openjdk-headless
java-17-openjdk-headless-17.0.4.0-2.1.x86_64

> rpm -ql java-17-openjdk-headless | grep release
/usr/lib64/jvm/java-17-openjdk-17/release

**Comment by H-Lo** [comment]
I can confirm that missing `release` file causes exception. But not only that: maven update cannot be done and Eclipse tries again and again in a loop and my pretty fast computer becomes unusable. It takes one minute to open Windows task manager and brutally kill Eclipse.
One relatively not important file missing shouldn't be the reason to destory the whole OS with indefinite loops for sure.
