### ISSUE TITLE
Error in DEBUG CONSOLE panel for testcase  9.realczase.lucene 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#122]
OS: Win10
VScode:  1.17.2 (32/64)
JDk: 1.8.0_151(x64)
Daily build 73

Repro steps:

1. Open the testcase 9. realcase.lucene
2. Open LuceneTest.java, and set breakpoint on line 43: writer.deleteAll();
3. Start debug and wait for breakpoint hit
![image](https://user-images.githubusercontent.com/22470312/32320300-3920316a-bff8-11e7-8b51-6ef995ed61ba.png)

**Comment by akaroml** [comment]
@andxu please investigate.
