### ISSUE TITLE
No variables shown  in VARIABLES when attach debug

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#123]
Attach debug a project and no variables shown in VARIABLES view

**Comment by bsaby** [comment]
Variables can now be displayed normally, so close this issue.
BUild: 74

**Comment by akaroml** [comment]
@andxu please investigate.

**Comment by andxu** [comment]
the test case misses -g parameter to javac, causing the .class file contains no DEBUG information including the variable table.
