### ISSUE TITLE
ERROR: transport error 202: getaddrinfo: failed to parse address

### ISSUE THREAD

**Issue by yyTang94** [microsoft/vscode-java-debug#1231]
ERROR: transport error 202: getaddrinfo: failed to parse address

##### Environment
- Operating System: macOS Monterey 12.5.1
- JDK version: openjdk 17.0.4.1
- Visual Studio Code version: 1.72.0 (Universal)
- Java extension version: Extension Pack for Java v0.25.3
- Java Debugger extension version: Debugger for Java v0.44.0

##### Steps To Reproduce
1. create a java file
2. start debug (F5)

[attach a sample project reproducing the error]
[attach [javadev.zip](https://github.com/microsoft/vscode-java-debug/files/9738192/javadev.zip)](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
After press F5 to start debug, vscode run the blow command in the internal terminal: 

``` bash
/usr/bin/env /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:51567 -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/touyouyou/Library/Application\ Support/Code/User/workspaceStorage/0ffec211a539bd992ff1a4db80d48904/redhat.java/jdt_ws/javadev_a6457af1/bin QuickStart
```

then, error is below: 

```
ERROR: transport error 202: getaddrinfo: failed to parse address
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:734]
```

##### Additional Informations

I think this error is related to `address=localhost:51567` in the command.

**Comment by testforstephen** [comment]
Can you check if the loopback `localhost` exists in your macOS? You can use the command `cat /etc/hosts` for that.

**Comment by yyTang94** [comment]
> Can you check if the loopback `localhost` exists in your macOS? You can use the command `cat /etc/hosts` for that.

The `localhost` does not exist in my hosts file. After add `127.0.0.1	localhost` in /etc/hosts, the address problem is fixed. Thank you very much!
