### ISSUE TITLE
Quarkus / MapStruct - Annotation Processing (build project or launchBeforeBuild)

### ISSUE THREAD

**Issue by kjq** [microsoft/vscode-java-debug#1232]
Just developing, _not_ running `quarkus:dev`, if I go to "build the project" or run any tests with `launchBeforeBuild=true`, I get errors that the MapStruct mappers are not correct as if the annotation processor did not run.  

Running Maven in the CLI works fine and if I have `launchBeforeBuild=false` or proceed after the errors I can run and debug the tests without a problem (this is not acceptable though because it basically says everything is broken until I clear the workspace).

If I just build the project using the Java Project extension, I will get the errors but then running `Maven -> Reload Project` afterwards brings it back to the correct state (and no errors are displayed). Unfortunately, I cannot do this with tests if `launchBeforeBuild=true`.

Some things  I have tried:
- Opening the single project only gives the same result
- Disabled m2e_apt "seemed" to get me closer but had other issues.
- Tried probably every post about annotation processing etc. regarding MapStruct and Lombok.

##### Environment
- Operating System: WSL2
- JDK version: JDK 17
- Visual Studio Code version: latest
- Java extension version: latest
- Java Debugger extension version: latest

##### Steps To Reproduce

Using the Java Project extension run **Build Project** or run a test case with `launchBeforeBuild=true`:

![Screenshot 2022-10-10 153537](https://user-images.githubusercontent.com/533810/194940090-81d6b0ee-9856-4c24-a7d3-10866bc5aef2.png)

> If I have `launchBeforeBuild=false`, build outside VSCode using Maven, the tests run fine and I can debug them.

Using the Java Project extension run **Maven Reload Project** right after brings it back to the correct state:

![Screenshot 2022-10-10 153624](https://user-images.githubusercontent.com/533810/194940234-fbf9a3ef-d21b-4892-abeb-a0c1a17d08a0.png)

##### Expected Result
Since I am running the same as I would be with Maven in the CLI and not using `quarkus:dev` it should generate and recognize the mappings being generated through the annotation processor. The build and the generated mappings work fine in the CLI using Maven.

**Comment by testforstephen** [comment]
@kjq Could you provide a sample project for us to try the issue? thanks.
