### ISSUE TITLE
Java.Class not found

### ISSUE THREAD

**Issue by naik0069** [microsoft/vscode-java-debug#1237]
![image](https://user-images.githubusercontent.com/108566555/195270453-8d6cd485-dedb-4a70-92a6-c834182c4f60.png)

Hi i could not able to run my Java code in VS Code. Please help!

Thanks in advance!!!

**Comment by testforstephen** [comment]
Looks like you're opening no build_tools Java folder in VS Code. And Java extension doesn't recognize your source directory well. Would you mind sharing the directory structure to us?

// cc: @jdneo
