### ISSUE TITLE
FAILURE: Build failed with an exception.  * What went wrong: Could not open settings generic class cache for settings file 'D:\project\tools\prouprint\android\settings.gradle' (D:\project\tools\gradle-7.5.1\caches\7.5.1\scripts\5o6jmz0o7vlzhu5xtvutuo3me). > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63  * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights.  * Get more help at https://help.gradle.org  BUILD FAILED in 772ms

### ISSUE THREAD

**Issue by abdulrhman-alfeel** [microsoft/vscode-java-debug#1242]
FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'D:\project\tools\prouprint\android\settings.gradle' (D:\project\tools\gradle-7.5.1\caches\7.5.1\scripts\5o6jmz0o7vlzhu5xtvutuo3me).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 772ms

**Comment by testforstephen** [comment]
The error is that you're using JDK 19 (major version 63) to run your gradle project, that's not supported. See the [compatibility matrix](https://docs.gradle.org/current/userguide/compatibility.html), gradle-7.5.1 only supports Java 18.

A quick suggestion is that you need to configure the VS Code settings `java.import.gradle.java.home` with a JDK compatible with your project.

**Comment by abdulrhman-alfeel** [comment]
I removed jdk19 and installed jdk 17 and it worked, thanks for the solution testforstephen

**Comment by rw2n** [comment]
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by siddhantpriyadarshi18581** [comment]
I installed JDK 18 but it is not yet working what to do now???

**Comment by panditakshay402** [comment]
@sidd

> I installed JDK 18 but it is not yet working what to do now???

Hey , try jdk 17.
if still not working check you gradle version and check this

Java version | First Gradle version to support it
-- | --
8 | 2.0
9 | 4.3
10 | 4.7
11 | 5.0
12 | 5.4
13 | 6.0
14 | 6.3
15 | 6.7
16 | 7.0
17 | 7.3
18 | 7.5
19 | 7.6
20 | 8.1 ⚠
 and
installed gradle according to this chart.

**Comment by prashanth586** [comment]
currently iam using jdk 17 and flutter version 2.0.1, but still iam facing the issue, can anyone provide solution for it.

**Comment by shebeeradly** [comment]
![image](https://github.com/microsoft/vscode-java-debug/assets/108452829/0d357fa4-eac9-42e8-83ea-5385daf1bf3d)

https://github.com/microsoft/vscode-java-debug/assets/108452829/0d357fa4-eac9-42e8-83ea-5385daf1bf3d try this link and will get an image in react native installation set up page , default version , then you goto 

https://reactnative.dev/docs/environment-setup

or 

![image](https://github.com/microsoft/vscode-java-debug/assets/108452829/a7f47bad-7e64-497f-8c7c-93ab418f1be7)

**Comment by Shahabmustafa** [comment]
go to android folder > gradle > gradle-wrapper.properties open this file and change distributionUrl

before : distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip

After : distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-all.zip
