### ISSUE TITLE
Remot extension

### ISSUE THREAD

**Issue by Blazingstar26** [microsoft/vscode-java-debug#1245]
when I went inside, it always show, "remote extension host terminated unexpectedly 3 times within the last 5 minutes."

Version: 1.72.3
Commit: f69482e92e41b84fb15688f3c0d0a1eca1d5bce3
User Agent: Mozilla/5.0 (X11; CrOS x86_64 15054.98.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Embedder: codespaces

Extension version: 0.45.0

**Comment by testforstephen** [comment]
Could you pls provide the steps how to reproduce it?
