### ISSUE TITLE
Classes are not automatically imported in the "Debug Console"

### ISSUE THREAD

**Issue by cazacugmihai** [microsoft/vscode-java-debug#1246]
When the code completion is used, classes are not automatically imported in the **Debug Console**:

> Set.of(1, 2)
> Cannot evaluate because of compilation error(s): Set cannot be resolved.

##### Environment
- Operating System: linux
- JDK version: 19.0.1
- Visual Studio Code version: 1.72.2
- Java extension version: 0.25.3
- Java Debugger extension version: 0.45.0

##### Steps To Reproduce
1. Create a breakpoint in a Java class;
![0](https://user-images.githubusercontent.com/89212/197364270-1eeb68d6-99db-49f3-bed0-a6e007f83b9f.png)

2. When the execution is suspended, open the **Debug Console** and try to create a [Set](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/util/Set.html) (e.g. `Set.of(1, 2)`), using the code completion feature. The aforementioned error is shown.
![1](https://user-images.githubusercontent.com/89212/197364271-dc779c64-b602-4099-9822-504a4d8038ab.png)

##### Current Result
> Set.of(1, 2)
> Cannot evaluate because of compilation error(s): Set cannot be resolved.

![2](https://user-images.githubusercontent.com/89212/197364272-f4c00004-f154-4f86-86e5-7857f6db2a22.png)

##### Expected Result
> ImmutableCollections$Set12@287 size=2
> 0: Integer@276
> 1: Integer@277

![3](https://user-images.githubusercontent.com/89212/197364275-aa620998-ca83-4e87-93cd-59313955c949.png)

##### Additional Informations
This functionality works out-of-the-box in IntelliJ IDEA. It would be nice to have it also in Visual Studio Code.

**Comment by testforstephen** [comment]
+1
it makes sense to auto import for classes in evaluation console.

**Comment by testforstephen** [comment]
+1 from April 2023 user feedback

**Comment by testforstephen** [comment]
+1 from March 2023 feedback

**Comment by testforstephen** [comment]
+ 1 from June 2023 feedback
