### ISSUE TITLE
Debug java apps running on the containers

### ISSUE THREAD

**Issue by viswatejan** [microsoft/vscode-java-debug#1248]
This is a feature request to provide the capability to debug the java apps running on the containers. Currently, container(docker) debug support is only limited to dotnet core and node js apps.

**Comment by testforstephen** [comment]
Can you elaborate your use case a little bit? How do you run your apps on container?

**Comment by viswatejan** [comment]
Never mind, I can able to debug a java app running on a docker container. I forgot to do port forwarding on the debugger port.
