### ISSUE TITLE
Building multi project java workspace with cross dependent modules(Java9)

### ISSUE THREAD

**Issue by RedIODev** [microsoft/vscode-java-debug#1249]
[provide a description of the issue]

##### Environment
- Operating System: Windows 10
- JDK version: 19
- Visual Studio Code version: 1.72.2
- Java extension version: 1.12.0
- Java Debugger extension version: 0.45.0

##### Steps To Reproduce
1. Open a folder in vscode
2. Create a file structure like this: ![FileStructure](https://user-images.githubusercontent.com/96652711/198694561-5517e362-a57c-496a-a70d-9e60fc678cf8.PNG)
3. Open the folder as a multi project workspace like this: ![workspace](https://user-images.githubusercontent.com/96652711/198694951-2f5bd30d-a66a-40b1-9535-c8263ff5abfa.PNG)
4. Make the module main depend on sub1 and sub2
5. (no errors from linter) run the main 

##### Current Result
Error: Cannot resolve the modulepaths/classpaths automatically, please specify the value in the launch.json

##### Expected Result
Runs the main modules Main with sub1 and sub2 
##### Additional Informations
I already tried to set the module and classpath variables in multiple ways: as relative paths from main project, as absolute paths with ${workspaceFolder}... , and with and without $auto as part of the lists. I couldn't find good information about these 2 options and how to set them correctly. 
I am mimicking a eclipse multi project solution with modules and cross requirements since I discovered A: that the VSCode extension is based on eclipse and B: neither of them support "normal" single projects with multiple modules. But the nice menu to add in workspace dependencies to the other projects from eclipse is missing in vscode,

**Comment by testforstephen** [comment]
You should use "**Open Workspace from File...**" menu to open it as a multi-root workspace. 

If you just open it as a folder, then VS Code Java extension will consider them as one project. There is a limitation that one project can only have at most one module-info.java.

If it's opened as a multi-root workspace, then each root will be initialized as a standalone project and be able to own a module-info.java.
