### ISSUE TITLE
SFDX: auth org Issue

### ISSUE THREAD

**Issue by naik0069** [microsoft/vscode-java-debug#1255]
Kindly please help me with the below error: 

tried to reinstallation and stopped at taskmgr and all applications were up to date.

thanks in advance!

17:36:54.255 sfdx force:auth:web:login --setalias raj --instanceurl https://login.salesforce.com --setdefaultusername
ERROR running auth:web:login:  spawn UNKNOWN

**Comment by testforstephen** [comment]
This looks like a behavior issue on your Java application itself. Is there anything anormal on Java Debugger side?
