### ISSUE TITLE
当工作目录的路径中存在中文时，如果lib文件夹中存在依赖文件，则无法运行该工作目录下的Java程序

### ISSUE THREAD

**Issue by Lixuhuilll** [microsoft/vscode-java-debug#1258]
[provide a description of the issue]

##### Environment
- Operating System: Windows 11   22H2
- JDK version: 17.0.5 2022-10-18 LTS
- Visual Studio Code version:  1.73.1 (user setup)
- Java extension version:  v1.12.0
- Java Debugger extension version: v0.46.0

##### Steps To Reproduce
1. 打开路径中存在中文的工作目录
2. 在 lib 文件夹中添加 .jar 依赖
3. 运行 java 程序

##### Current Result
`PS D:\OneDrive\Documents\Code\Java\Java练习与测试>  & 'D:\app\Java\jdk-17\bin\java.exe' '-XX:+ShowCodeDetailsInExceptionMessages' '@C:\Users\lxh\AppData\Local\Temp\cp_d6rp3v5gka2lpygmucjh8mnd5.argfile' 'fileStreamTest' 
错误: 找不到或无法加载主类 fileStreamTest
原因: java.lang.ClassNotFoundException: fileStreamTest`

##### Expected Result
`PS D:\OneDrive\Documents\Code\Java\Java练习与测试> & 'D:\app\Java\jdk-17\bin\java.exe' '-XX:+ShowCodeDetailsInExceptionMessages' '-cp' "D:\\OneDrive\\Documents\\Code\\Java\\Java练习与测试\\bin;d:\\OneDrive\\Documents\\Code\\Java\\Java练习与测试\\lib\\LScanner.jar" 'fileStreamTest'
中文输入
English`

##### Additional Informations
文件C:\Users\lxh\AppData\Local\Temp\cp_d6rp3v5gka2lpygmucjh8mnd5.argfile的内容为：
`-cp "D:\\OneDrive\\Documents\\Code\\Java\\Java练习与测试\\bin;d:\\OneDrive\\Documents\\Code\\Java\\Java练习与测试\\lib\\LScanner.jar"`

**Comment by testforstephen** [comment]
This duplicates with https://github.com/microsoft/vscode-java-debug/issues/1112

If you want to disable `*.argfile`, you can go to .vscode/launch.json, and change the launch setting to `"shortenCommandLine": "none"`.

If launch.json doesn't exist, use the following approach to generate one first.
![image](https://user-images.githubusercontent.com/14052197/150531012-3ccb88ce-dee8-4b33-9256-954b0cd206ab.png)
