### ISSUE TITLE
Failed to launch debuggee in terminal. Reason: terminal xxx does not exist

### ISSUE THREAD

**Issue by passion123** [microsoft/vscode-java-debug#1259]
[provide a description of the issue]

##### Environment
- Operating System:windows
- JDK version: java SE 17 / java SE12
- Visual Studio Code version: VS Code API: 1.55.2
- Java extension version: vscode-java-debug
- Java Debugger extension version:0.31.0  / 0.45.0

##### Steps To Reproduce
1. install the exclipse theia and 
2. create the java project without tools
[HERE](https://community.theia-ide.org/t/an-error-while-debug-a-java-project/2662/3) is the quesion in the community
![image](https://user-images.githubusercontent.com/9447543/201457206-f574174c-4b13-4a11-86c4-6bfcf9dd22f8.png)

![image](https://user-images.githubusercontent.com/9447543/201459410-715f15c4-485d-4d77-bce1-c5fc6cc47771.png)

**Comment by testforstephen** [comment]
Java Debugger is just an implementation of DAP (debug adapter protocol), the terminal creation behavior is totaly controlled by the client like VS Code and Theia. The exception log on Java debugger is just an echo of the error returned from client. This looks like an error on Theia itself.

Could you try if other extension can launch in terminal well?
