### ISSUE TITLE
Debbuger error

### ISSUE THREAD

**Issue by Neri-hV** [microsoft/vscode-java-debug#1270]
[provide a description of the issue]

##### Environment
VS Code version: Code 1.73.1 (https://github.com/microsoft/vscode/commit/6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
- Operating System:
- JDK version: 17
- Visual Studio Code version:
- Java extension version: red 1.12
- Java Debugger extension version: 0.47.0

##### Steps To Reproduce
1. [step 1] Run the script and does not update and when I cleared the cache  it finally does not run anymore.

3. [step 2] shows error message Build failed do you want to continue?

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by testforstephen** [comment]
Could you pls elaborate on the reproduce steps?

**Comment by Neri-hV** [comment]
I only run any script with java code.
Then, if I modify the script the debug extension doesn't recognize the
changes of the script, it continues running the old code.
Finally, If I clear the cache, then, the extension doesn't work.
This problem is recent, I think, because the last update of 2022/11/29.

**Comment by testforstephen** [comment]
Could you share a sample code to help us to reproduce it?
