### ISSUE TITLE
Failed to launch debuggee in terminal with TransportTimeoutException on Mac

### ISSUE THREAD

**Issue by xin911** [microsoft/vscode-java-debug#1278]
output:
Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException
Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException
com.microsoft.java.debug.core.DebugException: Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException
	at com.microsoft.java.debug.core.adapter.handler.LaunchWithDebuggingDelegate.lambda$launchInTerminal$0(LaunchWithDebuggingDelegate.java:147)

--- terminal output:
ERROR: transport error 202: connect failed: Operation timed out
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
-----

Why transports not initialized..?
How to initialize transports correctly?

##### Environment
- Operating System: Mac  10.15.7 
- JDK version:1.8
- Visual Studio Code version:1.74.2
- Java extension version:v0.40.2 0(Maven for Java)
- Java Debugger extension version:v0.47.0(Debugger for Java)

##### Steps To Reproduce
1. open Test.java, write helloworld, and click debug CodeLens

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
![image](https://user-images.githubusercontent.com/11419372/209899269-f3de0ee2-9aca-4c2c-937e-16f7c1b9999d.png)

##### Additional Informations
terminal error:
/usr/bin/env /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin/java -age
ntlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:53567 -cp /var/folders/ky/y9rt99sn6tb61yy6yr7thpjw0000gp/T/cp_cpk4v9ggyl99nrk9hupdd9ium.jar com.ziroom.finance.monitormanage
r.configuration.Test 
ERROR: transport error 202: connect failed: Operation timed out
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]

try:
1、add this line (, "java.debug.settings.console": "internalConsole")
alert: Failed to launch debuggee VM. Reason: VM did not connect within given time: 10000 ms
ERROR: transport error 202: connect failed: Operation timed out
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
output:
Failed to launch debuggee VM. Reason: VM did not connect within given time: 10000 ms
Failed to launch debuggee VM. Reason: VM did not connect within given time: 10000 ms
com.microsoft.java.debug.core.DebugException: Failed to launch debuggee VM. Reason: VM did not connect within given time: 10000 ms
	at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.launch(LaunchRequestHandler.java:320)
	at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.handleLaunchCommand(LaunchRequestHandler.java:187)
	at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.handle(LaunchRequestHandler.java:89)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.lambda$dispatchRequest$0(DebugAdapter.java:93)

JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
2、 try to add "shortenCommandLine": "jarmanifest" in launch.json
output:
Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException
Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException
com.microsoft.java.debug.core.DebugException: Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException
	at com.microsoft.java.debug.core.adapter.handler.LaunchWithDebuggingDelegate.lambda$launchInTerminal$0(LaunchWithDebuggingDelegate.java:147)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)

**Comment by xin911** [comment]
Last month, every thing is OK.
A few days ago, I installed k8s and docker on my mac.
Now，I cannot debug any java programe even "helloworld".
Add config "java.debug.settings.console": "internalConsole" in settings.json, and "shortenCommandLine": "jarmanifest" in launch.json.Still got error.
How to solve the TransportTimeoutException...?

**Comment by xin911** [comment]
switchhosts add 127.0.0.1 localhost

**Comment by xin911** [comment]
switchhosts add 127.0.0.1 localhost

**Comment by liuenci** [comment]
> 127.0.0.1 localhost

good，you had fix my question, thanks
