### ISSUE TITLE
FrameworkEvent ERROR

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#128]
OS: Mac
VSCode: 1.17.2 
JDK: 1.8.0_151
Daily build :74

Open a java project to debug and find a frameworkevent errors in Java language server log file.

**Error log**
![image](https://user-images.githubusercontent.com/22470312/32367781-550496c0-c0be-11e7-85e3-1cf2da372f12.png)

**Comment by akaroml** [comment]
@yaohaizh please investigate.

**Comment by yaohaizh** [comment]
Since the java & java debugger cannot start from the log, this is a normal error situation here.

**Comment by yaohaizh** [comment]
Add related issue: https://github.com/Microsoft/vscode-java-debug/issues/112
