### ISSUE TITLE
Cannot evaluate because of compilation error(s): x cannot be resolved or is not a field.

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-java-debug#1281]
OSX 10.15.7
Debugger for Java v0.47.0
VSCode Version: 1.74.2
JavaSE-17 / temurin-17.jdk

I notice more problems with evaluating expressions lately, to give an example:
<img width="430" alt="Screenshot 2023-01-09 at 15 50 31" src="https://user-images.githubusercontent.com/738650/211337297-ea141e25-3340-4b3f-afa7-1fa76d34405d.png">

`node.left.point` works fine, `node.left.point.x` does not, yet if I expand the first one, I can clearly see the `.x` part.

**Comment by testforstephen** [comment]
Could you pls share a snippet including the full context information?
