### ISSUE TITLE
Debugger doesn't attach with background preLaunchTask

### ISSUE THREAD

**Issue by srfrnk** [microsoft/vscode-java-debug#1283]
I have a Java project with the following debug config:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "java",
      "name": "API",
      "request": "attach",
      "hostName": "localhost",
      "port": "5005",
      "preLaunchTask": "Test"
    }
  ]
}
```
And task configs:
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "isBackground": true,
      "type": "shell",
      "label": "Test",
      "command": "while true; do print \"running\"; sleep 1; done",
      "problemMatcher": [
        {
          "pattern": [
            {
              "regexp": ".",
              "file": 1,
              "location": 2,
              "message": 3
            }
          ],
          "background": {
            "activeOnStart": true,
            "beginsPattern": "running",
            "endsPattern": "---"
          }
        }
      ]
    }
  ]
}

```

The "command" I'm trying to run is really "gradle test" but for simplicity to show how this fails to work I used a while loop.
When starting debugging (F5) the task runs forever (as expected) but debugging fails to start.
It keeps showing the progress indicator and never attempts to connect to the process.
When manually stopping the task debug will stop.

##### Environment
- Operating System: Mac
- JDK version: 11
- Visual Studio Code version: ```code --version
1.74.3
97dec172d3256f8ca4bfb2143f3f76b503ca0534
arm64```
- Java extension version: v1.13.0
- Java Debugger extension version: v0.47.0

##### Steps To Reproduce
1. Open any java project
2. Configure as described above

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Debugger not attaching

##### Expected Result
Debugger to attach

**Comment by testforstephen** [comment]
Could you reference the link https://github.com/microsoft/vscode-java-debug/issues/120#issuecomment-417269773 about the definition of problem matcher?

**Comment by srfrnk** [comment]
Could you explain what more info you need? "problemMatcher" is described above already? Anything else?

**Comment by testforstephen** [comment]
This issue said the debugger not attaching, but from the information you provide we cannot tell anything wrong with debugger. One suspicious reason is your current problem matcher never exits. You must follow the sample above to fix the problemMatcher by yourself first.
