### ISSUE TITLE
installing java pack

### ISSUE THREAD

**Issue by kunalkhaire95** [microsoft/vscode-java-debug#1288]
Type: <b>Performance Issue</b>

extension pack for java installation is too slow

Extension version: 0.47.0
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz (4 x 2128)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.80GB (0.61GB free)|
|Process Argv|--crash-reporter-id 3329a959-7935-48a9-acdc-975617225bc9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    95	  3020	code main
    0	    83	  3528	   window (undefined)
    4	    46	  4268	   utility-network-service
    2	    91	  6684	   issue-reporter
    0	   139	  8520	   shared-process
    0	    73	  2312	     ptyHost
    0	    72	  5100	     fileWatcher
    0	   102	  8856	   extensionHost
    0	   163	  9636	   window (Extension: Extension Pack for Java - Visual Studio Code)
    4	   104	  9680	   gpu-process
    0	    26	  9748	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
f6dab269:30613381

```

</details>

**Comment by testforstephen** [comment]
The extension installation is out of scope of debugger extension. This may depend on your network speed.
