### ISSUE TITLE
vscode-maven-java-debug

### ISSUE THREAD

**Issue by leoleon726** [microsoft/vscode-java-debug#1295]
I need to execute a debug in Visual studio code but it is not so intuitive. I have a web maven project which does not have a main classes. When I run this maven command is not bringing any issue.

##### Environment
- Operating System: Windows 10 
- JDK version: 1.8
- Visual Studio Code version: 1.75

##### Steps To Reproduce
The command that I run on the terminal of vscode:
`mvn -s [PATH of settings file] -T 10 tomcat7:run-war "-Dx.uri=/sites/A" -f "[PATH of pom file]" -DskipTests -P C,D`
I have tried using mvnDebug or add this (-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000) but none of them works on Visual Studio

**Comment by testforstephen** [comment]
You might take a look at https://github.com/microsoft/vscode-java-debug/issues/120#issuecomment-417269773. Basically you could wrap your own maven command into a preLaunchTask, and then attach debugger to the maven process.
