### ISSUE TITLE
Unable to Debug any Code

### ISSUE THREAD

**Issue by Blackjack92** [Microsoft/vscode-java-debug#130]
Hello everybody, 

when I enable the following packages: 

- Debugger for Java
- Java Extension Pack
- Language Support for Java

I cannot start any kind of debugging. Not even Python, Node.js, etc. Also I am not able to add any configuration (I can click the buttons but nothing happens). Furthermore I don't see any problem in the problem window. 
When I disable these packages I am able to debug and create configurations.

My system: Linux Mint
`Linux blackjack92-laptop 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

My Java version: 
`OpenJDK 9` and also `OpenJDK 8`

I am grateful for any help provided.

**Comment by akaroml** [comment]
@Blackjack92 thanks for reporting this issue. What kind of project are you working with? Currently, Maven/Gradle/Eclipse projects are supported. And it would be helpful to know the version of VS Code and all three extensions.

When you start debugging, VS Code asks the language type. And after you pick "Java", our code kicks in and try to generate a working configuration. It should not block you from debugging Python or Node.js code.

**Comment by Blackjack92** [comment]
Hello @akaroml thanks for response. 

I was working on no specific file it was just a `Main.java` class with a `static void main` to print hello world. Furthermore I used the newest version of all three extensions (I cannot name them - sorry). 

I could not even start debugging because the selection dialog for the language type did not appear.  

You can close this bug because I changed my system from linux mint to arch and it works there.
