### ISSUE TITLE
Dialog window to write the project name for the Java debugger

### ISSUE THREAD

**Issue by leosj29** [microsoft/vscode-java-debug#1309]
The window to specify a project name for java debugger opens and closes immediately, so it is not possible to specify a new project name (if required).
This occurs after the first time the project name is specified.

##### Environment
- Operating System: Linux
- JDK version: 8
- Visual Studio Code version: 1.76.0
- Java extension version: 0.25.8
- Java Debugger extension version: 0.49.0
- Apache Tomcat version: 8.5.23

##### Steps To Reproduce
1. Use the extension Community Server Connector.
2. Add an Apache Tomcat Server.
3. Right click and select "Debug Server".
4. The window appears to select a project name to be used by the java debugger.
5. Specify a project name.
6. Apache Tomcat Server deploys fine in debug mode.
7. Stop the Apache Tomcat Server.
8. When you try to repeat step 3, the window to write a project name opens and closes immediately.

![Screenshot from 2023-03-09 11-04-36](https://user-images.githubusercontent.com/2030440/224108661-72b3680c-ace9-48e9-be91-2ecebccc558b.png)

[Screencast from 09-03-2023 11:02:22.webm](https://user-images.githubusercontent.com/2030440/224108764-b89d25f6-78f0-4697-86d9-ffbcb27e6888.webm)

##### Current Result
The window to write a project name opens and closes immediately.

##### Expected Result
The window to write a project name should open (remembering the previous one) and wait for user action

**Comment by testforstephen** [comment]
This dialog is from Community Server Connector extension, could you pls open your issue there?
