### ISSUE TITLE
0.3.0 Endgame

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#131]
- Prepare RC
    - [x] 11/8 - Bump version to 0.3.0 - @testforstephen
    - [x] 11/8 - Add change log for 0.3.0 - @testforstephen
    - [x] 11/9 - Signed RC Bits ([#31](https://vscjavaci.cloudapp.net/job/vscode-java-debug.vsix-withSign/31/Azure), [#32](https://vscjavaci.cloudapp.net/job/vscode-java-debug.vsix-withSign/32/Azure/), [#34](https://vscjavaci.cloudapp.net/job/vscode-java-debug.vsix-withSign/34/Azure/)) - @testforstephen

- Test
    - [x] 11/9 - Test generic Java 8 and 9 support on the Mac - @testforstephen
    - [x] 11/9 - Test generic Java 8 and 9 support on the Linux/Ubuntu- @yaohaizh
    - [x] 11/9 - Test cwd/environment variables support on the Windows - @andxu 
    - [x] 11/9 - Test single file debugging support on the Windows (`cannot see compilation errors`)- @andxu 
    - [x] 11/9 - Test hex/showQualifiedNames/static user settings - @andxu 
    - [x] 11/9 - Test auto resolve main class and module paths for java 9 project - @andxu
    - [x] 11/9 - Test generic Java 8 and 9 support on the Windows - @ansyral 
    - [x] 11/9 - Test on the VSCode insider - @ansyral 
    - [x] 11/9 - Test debugging support for popular projects (e.g. spring boot/docker) - @akaroml 

> Generic java support:
> - Install/Update
> - Launch/Attach
> - Breakpoint
> - Step/Pause/Continue
> - Threads/Callstacks
> - Variables
> - External files/lib source debugging

- Release
    - [x] 11/10 - Add tag 0.3.0 for repositories vscode-java-debug and java-debug - @testforstephen
    - [x] 11/10 - Release to marketplace https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug - @testforstephen
    - [ ] 11/10 - Publish signed com.microsoft.java.debug.core-0.3.0.jar to maven central repository

**Comment by yaohaizh** [comment]
# Test on Linux/Ubuntu environment

1. Project petclinic
2. Project with single file
2. Ubuntu 16.04 LTS 
4. VSCode 1.18.0 (The latest version with Mutli-root)
3. Go through features: Breakpoint/callstack/view variable/external sources/main class/threads/java 9/single files)

Result:
1. This version works including Java as expected.
2. The single file debugging works as expected.

**Comment by testforstephen** [comment]
- ## Java 8 test on Mac

JDK: 1.8.0_121-b13

Java 8 Sample project: [5.breakpoint](https://github.com/vscjavaci/java-debug-ci/tree/master/testcase/5.breakpoint)


1. Update vsix from 0.2.0 to 0.3.0  `[Pass]`
2. Launch and auto resolve main class `[Pass]`
3. Breakpoint `[Pass]`
4. Threads/Callstacks `[Pass]`
5. Step `[Pass]`

Java 8 Sample project: [3.thread](https://github.com/vscjavaci/java-debug-ci/tree/master/testcase/3.thread)

6. Pause/Continue  `[Pass]`
7. stopOnEntry `[Pass]`
8. user settings for "java.debug.settings.showQualifiedNames" `[Pass]`

- ## Java 9 test on Mac
JDK: 9.0.1

Java 8 sample project: [5.breakpoint](https://github.com/vscjavaci/java-debug-ci/tree/master/testcase/5.breakpoint)

1. Compatibility test 
- Resolve main class `[Pass]`
- Launch `[Pass]`
- Breakpoint `[Pass]`
- Step/Continue `[Pass]`

Java 9 sample project: [19.java9-app](https://github.com/vscjavaci/java-debug-ci/tree/master/testcase/19.java9-app)

2. Resolve main class failed because the known issue (jdt search engine NPE) `[Fail]`
3. Configure the main class in launch.json manually and launch again `[Pass]`
4. Configuration snippet "{} Java: Launch Program" still generates `stopOnEntry: true`, submit a PR #144 to fix it.  Verify it at the new build [#32](https://vscjavaci.cloudapp.net/job/vscode-java-debug.vsix-withSign/32/Azure/)  `[Pass]`
5. Breakpoint/Step/Continue `[Pass]`

**Comment by akaroml** [comment]
Two blocking bugs found when validating using spring boot pet clinic app:
https://github.com/spring-projects/spring-petclinic

#145 - @ansyral 
#146 - @andxu 

These are blocking the 0.3.0 release. Please fix ASAP

**Comment by akaroml** [comment]
#147 was made to workaround #145 
#148 was made to workaround #146

**Comment by akaroml** [comment]
Validated the newest signed build with Spring Boot Pet Clinic sample project on Windows and Mac
- The project was launched with launch configuration generated correctly
- Breakpoints were hit correctly
- Enabled showHex option and integers were shown in hex format correctly
- Enabled showStaticVariables option and static variables were shown correctly
- Enabled showQualifiedNames options and class names were shown in fully qualified format correctly
- stopOnEntry was verified completely disabled in this build

redhat-developer/vscode-java#363 was found on my Mac but could not be reproduced on others' Mac. So I don't consider this a blocking issue for us.

**Comment by andxu** [comment]
- ## cwd/environment variables 

JDK: 1.8.0_121-b13

1. Update vsix from 0.2.0 to 0.3.0  `[Pass]`
2. Open project newly created by `mvn archetype:generate –DarchetypeArtifactId:maven-archetype-quickstart`
3. F5 and wait for the launch.json `[Pass]`
4. Add a cwd and env setting for a=b, change App.java to the following code:
`public class App 
{
    public static void main( String[] args )
    {
        System.out.println(new File("").getAbsolutePath());
        for (String key : System.getenv().keySet()) {
            if (key.equals("a"))
            System.out.println(key + " = " + System.getenv(key));
        }
    }
}`
