### ISSUE TITLE
Debugger for Java, skips breakpoints not in debugged class 

### ISSUE THREAD

**Issue by christianapopoola** [microsoft/vscode-java-debug#1319]
Debugger for Java skips the breakpoints not in the main class being debugged. 
When you try to step into one of the other classes referenced in the main class, it throws an error in the variables columns "Failed to get variables.  Reason: com.sun.jdi.internalexception: got error code in reply:35".
If you just try to run from breakpoint to breakpoint through the various classes, it ignores all other breakpoints and return to the one in the main debugged class

##### Environment
- Operating System: Windows 11
- JDK version: 11.0.18
- Visual Studio Code version: 1.76.2
- Java extension version: (Extension Pack for Java) 0.25.2023032708
- Java Debugger extension version: 0.48.0

![Screenshot 2023-03-29 102347](https://user-images.githubusercontent.com/122801860/228506137-7b07dd80-e637-4eb9-bf79-728994da3ad3.png)

**Comment by testforstephen** [comment]
@christianapopoola Could you share some sample code to help us to reproduce the issue consistently? thanks.
