### ISSUE TITLE
Trying to watch the value of a byte[] variable gives 'Cannot evaluate because of compilation error(s): Evaluations must contain either an expression or a block of well-formed statements'

### ISSUE THREAD

**Issue by nathan-gt** [microsoft/vscode-java-debug#1323]
When trying to watch a an array of byte, the debugger displays an error message instead of the values it has stored, despite the local variables list displaying the values correctly.

##### Environment
- Operating System: Windows 10
- JDK version: 17
- Visual Studio Code version: 1.76.2
- Java extension version: v0.25.10
- Java Debugger extension version: v0.49.1

##### Steps To Reproduce
1. Have a byte[] variable at runtime and put a breakpoint somewhere
2. try to add the variable to the watched variables
[attach a sample project reproducing the error]

We can see here that the Local variables list is able to read the values, but not the watch
![image](https://user-images.githubusercontent.com/45826581/231536262-ae198cec-f195-45f5-a221-0b2a80d33a26.png)

##### Current Result
'Cannot evaluate because of compilation error(s): Evaluations must contain either an expression or a block of well-formed statements.'
##### Expected Result
the list of values stored inside of the variable

**Comment by nathan-gt** [comment]
After some digging, it seems that it's right after a private function is called that i am unable to read the value of any variable, really strange behavior

**Comment by nathan-gt** [comment]
At first in a private function all is well
![image](https://user-images.githubusercontent.com/45826581/231540355-12fe688c-dc73-44bd-ae16-720b632d63f7.png)
Then inside the next private function calls, before a new "Node" object is created, the variables are still readable
![image](https://user-images.githubusercontent.com/45826581/231540485-4535b4f4-d9b5-4d31-b9d6-43fc5be20299.png)
And right after this new object is created, it throws an error in the watched variables
![image](https://user-images.githubusercontent.com/45826581/231540770-63d23a7f-19b5-4339-87b9-94c24229e8d9.png)

**Comment by testforstephen** [comment]
Cannot reproduce it with some similar snippets as you declared. Would you mind sharing some sample project for us to reproduce? thanks.

![image](https://user-images.githubusercontent.com/14052197/232361393-89a64319-7e2f-4852-97cb-b679ff075008.png)
