### ISSUE TITLE
Stuck on "Running tests..."

### ISSUE THREAD

**Issue by dsyer** [microsoft/vscode-java-debug#1324]
Since I upgraded VSCode to 1.77.3 I can't run tests any more. The test view shows up but clicking on any of the little run icons causes VSCode to say "Running tests..." in the status bar but nothing ever happens. I have tried release and pre-relese versions of this extension (and all Java Extension Pack).

Update: downgraded to 1.75.1 (and 1.16.0 of `redhat.java` since 1.17.0 is incompatible) and running tests works again.

**Comment by snjeza** [comment]
A related PR - https://github.com/eclipse/eclipse.jdt.ls/pull/2597
@dsyer Tests should work with the release version (VS Code 1.17.0, Java Extension Pack v0.25.10). Could you attach a project example?

**Comment by dsyer** [comment]
> Could you attach a project example?

Just download a project from start.spring.io (I was using Maven).

You are right that it works now though. I'm not sure what changed. Maybe I didn't actually have 1.17.0 before.

**Comment by dsyer** [comment]
Actually, I don't get 1.17.0 by default (1.16.0 instead). So that's probably what was broken? But how do I fix it? How do I make the extension pack install 1.17.0?

**Comment by snjeza** [comment]
Right-click `Language Support for Java(TM) by Red Hat`, select `Install Another version`

**Comment by dsyer** [comment]
You can't install 1.17.0 if VSCode is 1.75.1 (apparently). I tried that anyway, and that's what it looks like.

**Comment by testforstephen** [comment]
> You can't install 1.17.0 if VSCode is 1.75.1 (apparently). I tried that anyway, and that's what it looks like.

1.17.0 version requires a minimum VS Code 1.77.0, that's why you didn't see it in VS Code 1.75.1.

> Since I upgraded VSCode to 1.77.3 I can't run tests any more. The test view shows up but clicking on any of the little run icons causes VSCode to say "Running tests..." in the status bar but nothing ever happens. I have tried release and pre-relese versions of this extension (and all Java Extension Pack).

There is a regression in vscode-java@1.18 pre-release version. The fix will be available in the next pre-release version  of Java language support extension that will be released later today. Thank you for your patience and understanding.

**Comment by testforstephen** [comment]
The pre-release version `v1.18.2023041704` of `Language Support for Java(TM) by Red Hat` extension has fixed this bug, so I will close it.
