### ISSUE TITLE
When running debug, test dependencies are not included but test codes are. 

### ISSUE THREAD

**Issue by gnoo** [microsoft/vscode-java-debug#1326]
[provide a description of the issue]

##### Environment
- Operating System: Darwin x64 22.4.0
- JDK version: Java8
- Visual Studio Code version: Version: 1.77.3
- Java extension version: v1.17.0
- Java Debugger extension version: 0.49.1 

##### Steps To Reproduce
1. add spring boot to dependencies.(eg. gradle implementation config)
2. add `spring-boot-starter-test` to test dependencies(eg. gradle testImplementation config)
3. mark one of your service class in test codes(src/test dir) with `@Service` annotation, and initialize any class in test dependencies(eg. TestRestTemplate) in its constructor.
4. After running debug, `spring framework` scan `bean` configs to initialize its container and try to instantiate class we annotatated with `@Service` annotation in `Step 3`, throw `NoClassDefFoundError` because it cannot find class definition for TestRestTemplate.

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Class definition can't be found for test dependencies when debug.

##### Expected Result
Either excluding or including both test code and test dependencies.

**Comment by testforstephen** [comment]
Could you share some sample project for us to try directly? thanks.
