### ISSUE TITLE
History of called methods

### ISSUE THREAD

**Issue by jeanbrazcosta** [microsoft/vscode-java-debug#1327]
Type: <b>Feature Request</b>

If possible, I would like to implement the possibility of seeing the history of methods that were called when stopping at a breakpoint.

Example: Let's say I have the save method, and when stopping at the breakpoint in this method, it is possible to browse the history where it would show all the methods that were called before reaching that point.

This is possible in Intellij and helps a lot when we need to debug a code.

Extension version: 0.49.1
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

**Comment by testforstephen** [comment]
Interesting. Any screenshot or documentation to explain how it works?

**Comment by jeanbrazcosta** [comment]
Here's an explanation on an intellij blog, which even shows other very
interesting debug features.

https://blog.jetbrains.com/idea/2020/05/debugger-basics-in-intellij-idea/

Em sex., 28 de abr. de 2023 às 00:22, Jinbo Wang ***@***.***>
escreveu:

**Comment by testforstephen** [comment]
Are you talking about the call stack view? This has been already supported.
![image](https://user-images.githubusercontent.com/14052197/236118933-dea3b215-6c70-4ec0-a8d6-88e153e16e0b.png)

**Comment by jeanbrazcosta** [comment]
@testforstephen you're right, I ended up finding the feature.

Sorry.
