### ISSUE TITLE
Can't debug current file, always debug last Main class in workspace

### ISSUE THREAD

**Issue by amine-err** [microsoft/vscode-java-debug#1337]
So I'm learning Java for uni, and i have in one workspace different folders for each exercise with different Main.java files, when i use the java debugger to debug the current Main.java file it fails and always debug the last Main file in the workspace instead. 

##### Environment
- Operating System: Arch Linux
- JDK version: 20.0.1.u9
- Visual Studio Code version: 1.77
- Java extension version: 
- Java Debugger extension version: v0.50.0

##### Steps To Reproduce
1. Create new workspace
2. Create folder1, inside it create a Main.java file
3. Create folder2, inside it create a Main.java file
4. Debug folder1/Main.java using "Current file option", it fails and instead folder2/Main.java is debugged.

[Reproduce.zip](https://github.com/microsoft/vscode-java-debug/files/11361066/Reproduce.zip)

**Comment by testforstephen** [comment]
Your sample code has two Main.java files without any package declarations. This means they belong to the default package namespace in Java. However, Java does not allow you to have two classes with the same name in the same package namespace. Only one of them will work.

To fix this, you can either add package declarations (such as `package folder1;` and `package folder2;`) to your Main.java files to separate them, or rename one of the Main.java files to something else.

**Comment by amine-err** [comment]
While i understand why things are set the way you said, what i don't understand is that running using "Current file" option should act the same as running the file using `java Main.java` command which works with no errors.
The problem here is not that i can't run Main files, it's that the "current file" option isn't working and just falls back to creating a separate launch config for each Main file.
