### ISSUE TITLE
The Gradle project loading process always hang

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#134]
OS: Windows
VSCode: 1.17.2 32
JDK: 9.0.1_64
Daily build: 78
Testcase: 12.Gradle (with no laungh.json in .vscode folder)

![image](https://user-images.githubusercontent.com/22470312/32485289-deaafd5c-c3dd-11e7-9ca5-7f49b0aa5500.png)

**Comment by testforstephen** [comment]
This is LS bug, duplicated with https://github.com/redhat-developer/vscode-java/issues/359
