### ISSUE TITLE
Administration 

### ISSUE THREAD

**Issue by joneseri1234** [microsoft/vscode-java-debug#1340]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by testforstephen** [comment]
Invalid issue. Pls open a new issue with more details.
