### ISSUE TITLE
Debug seems not to work with Glassfish 5.0.1

### ISSUE THREAD

**Issue by JLLMNCHR** [microsoft/vscode-java-debug#1347]
**Debug** of a Java Web application seems not to work with **Glassfish 5.0.1**

**Environment:**

- Operating System: Windows 10 Pro
- JDK: openjdk version "1.8.0_192"
- GlassFish: v5.0.1
- Visual Studio Code: 1.78.2
- Extension Pack for Java: v0.25.11
- Debugger for Java: v0.51.0
- Community Server Connectors: v0.25.7
- Runtime Server Protocol UI: v0.24.7

**Steps To Reproduce:**

1. I add the war of my application to the server.
2. I start the server in Debug mode.
3. I specify the name of the project that I want to debug.
4. I set a breakpoint in a Java class on a line of code so I know the flow is going through it.
5. BUT, said breakpoint or any other that is set is not taken into account.
(See images below).

**Additional information:**

The same works correctly in a _Tomcat 9.0.41_

Here the '**Edit Server**' .json of the **GlassFish**:
```
{
  "args.override.boolean": "false",
  "args.program.override.string": "start-domain --verbose",
  "args.vm.override.string": "",
  "glassfish.domain": "domain1",
  "glassfish.host": "localhost",
  "glassfish.port": "8080",
  "id": "Glassfish 5.0.1",
  "id-set": "true",
  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.server.glassfish.5x",
  "server.home.dir": "c:\\Instalados\\glassfish5.0.1"
}
```

Here the '**Edit Server**' .json of the **Tomcat**:
```
{
  "args.override.boolean": "false",
  "args.program.override.string": "start",
  "args.vm.override.string": "-Djava.util.logging.config.file=/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dcatalina.base= -Dcatalina.home=c:\\Instalados\\apache-tomcat-9.0.41 -Djava.io.tmpdir=/temp",
  "id": "Tomcat 9.0.41",
  "id-set": "true",
  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.server.tomcat.90",
  "server.base.dir": "c:\\Instalados\\apache-tomcat-9.0.41",
  "server.deploy.dir": "${server.base.dir}/webapps/",
  "server.home.dir": "c:\\Instalados\\apache-tomcat-9.0.41",
  "server.http.host": "localhost",
  "server.http.port": "8080"
}
```

![image](https://github.com/microsoft/vscode-java-debug/assets/53475407/f4725312-e80d-43d5-a9cf-b6b3d80c1462)
![image](https://github.com/microsoft/vscode-java-debug/assets/53475407/3ec3cf6a-268b-467e-84be-4b6780aa28b5)
![image](https://github.com/microsoft/vscode-java-debug/assets/53475407/62b6521b-5e66-4e31-80e1-dfa5cb3ffed2)
![image](https://github.com/microsoft/vscode-java-debug/assets/53475407/abaf5737-9843-47fe-95e7-c126fcca3b5f)
![image](https://github.com/microsoft/vscode-java-debug/assets/53475407/da3539ca-4092-4461-8519-e2ac9d66bcba)

**Comment by JLLMNCHR** [comment]
This manual configuration doesn´t helps:

![image](https://github.com/microsoft/vscode-java-debug/assets/53475407/ee032eaa-d8da-4c9c-ae61-e2340e63bd05)

**Comment by testforstephen** [comment]
Glassfish debugging capability is provided by "Community Server Connectors", not by "Debugger for Java". Can you pls open an issue at "Community Server Connectors" extension repository?
