### ISSUE TITLE
Extend Java Debugger/Run configurations to allow run Maven/Gradle targets

### ISSUE THREAD

**Issue by MartinBalin** [microsoft/vscode-java-debug#1348]
Current VSCode Java debugger allows to run only Java process with arguments to be passed in like debug options, VM arguments, etc. e.g.:
`/usr/bin/env /Users/x/graal/graalvm-ee-java17-22.3.2/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:49853 @/var/folders/5c/50zk75k8.argfile com.example.Application`

Especially some frameworks like Micronaut or Spring Boot provide specialized plugins which allow execution and debugging of applications launched with special targets. These plugins are often developed along with framework, change often and it is not practical to reverse engineer what they do to run/debug applications just to run these using plain `java`.
For example  Micronaut https://micronaut-projects.github.io/micronaut-maven-plugin/latest/run-mojo.html which allows to execute a Micronaut application in development mode that allows instant rebuild and reload of app.

Will be great if Java Debug Server https://github.com/Microsoft/java-debug and VSCode Debugger for Java https://github.com/microsoft/vscode-java-debug allow to run also Maven or Gradle using Run/Debug configs.
E.g. java Run configuration can be extended by some new property like **`exec`** which accepts `./mvnw` or `./gradlew` as parameter as well as the target or some other options, when unspecified it will run Java as default as it is now. Other params should change accordingly. Such command then looks like this for Micronaut **mn:run** when using outside VSCode: 
`JAVA_HOME=/Users/x/graal/graalvm-ee-java17-22.3.2/Contents/Home /Users/x/dev/project2/mvnw -Dexec.vmArgs=-Dfile.encoding=UTF-8 "-Dexec.args=${exec.vmArgs} -classpath %classpath ${exec.mainClass} ${exec.appArgs}" -Dexec.mainClass=com.example.Application -Dexec.classpathScope=runtime -Dexec.appArgs= --no-transfer-progress mn:run`.

VSCode extensions supporting frameworks like Micronaut can be then able to programatically set Run/Debug configuration for various advanced use cases invoking Maven or Gradle and debug the app itself...

**Comment by testforstephen** [comment]
See https://github.com/microsoft/vscode-java-debug/issues/120#issuecomment-417269773, it's recommended to configure whatever command you want in tasks.json, and link it to launch.json via `preLaunchTask` property.
