### ISSUE TITLE
Missing release asset file

### ISSUE THREAD

**Issue by williamboman** [microsoft/vscode-java-debug#1373]
Hello! This software is being distributed to Neovim users via https://github.com/mason-org/mason-registry by pulling the release assets. The latest 0.53.0 release seems to be missing the asset file and I'm wondering if this was intentional. If it is intentional I'd much appreciate any guidance for how to package this outside of VSCode.

##### Current Result

No asset file available for release 0.53.0

##### Expected Result

An asset file to be present as with prior releases.

**Comment by nickzhums** [comment]
Hi @williamboman, since this question was already answered in another repo, I'm going to close this as duplicate. Feel free to ping us if you have questions, thanks!
