### ISSUE TITLE
0.53.0 release does not contain a vsix file

### ISSUE THREAD

**Issue by PeterJohnson** [microsoft/vscode-java-debug#1376]
The GitHub release for 0.53.0 does not include a vsix release artifact.  Previous releases including 0.52.0 do.

**Comment by milind-shakya-sp** [comment]
Can confirm. This seems to be causing issues for DAP installers like mason for neovim for example.

**Comment by PeterJohnson** [comment]
Turns out this is a duplicate of #1373 and (more usefully) https://github.com/microsoft/vscode-java-test/issues/1594.
