### ISSUE TITLE
I am getting error fix java.lang.classnotfoundexception in vscode

### ISSUE THREAD

**Issue by Afrojmd** [microsoft/vscode-java-debug#1377]
fix java.lang.classnotfoundexception in vscode.. I am getting this error again and again . I installed all the Java extension,jdk and also mentioned the jdk bin location in System environment. I cant even print "Hello world".. please help me anybody.@jadelike-wine
![IMG20230822124410](https://github.com/microsoft/vscode-java-debug/assets/99397443/ba452c99-a9e6-40db-bfd4-836ff5275809)

**Comment by testforstephen** [comment]
Looks like you're using "Code Runner" to run the code, is that right? Code runner extension is not contributed by java-debug extension.
