### ISSUE TITLE
can not add java class loading breakpoint 

### ISSUE THREAD

**Issue by JadeLuo** [microsoft/vscode-java-debug#1378]
[provide a description of the issue]

##### Environment
- Operating System: win10
- JDK version: jdk1.8
- Visual Studio Code version:1.18
- Java extension version:0.25.13
- Java Debugger extension version:0.53

##### Steps To Reproduce
1. switch to debug view
2. select a java file , then add breakpoint

[attach a sample project reproducing the error]

##### Current Result
can not add breakpoint 

##### Expected Result
can add  java class loading breakpoint  like eclipse

**Comment by testforstephen** [comment]
duplicates with https://github.com/microsoft/vscode-java-debug/issues/1110
