### ISSUE TITLE
Weird x: and s: showing up all over my code

### ISSUE THREAD

**Issue by vivekgohel2004** [microsoft/vscode-java-debug#1383]
class Tut1 {
    public static void main(String[] args) {
        System.out.print("s:Hello");
        System.out.println("x: World");
        System.out.print("s:Hello World");
    }
}

**Comment by testforstephen** [comment]
You can edit the user setting `"java.inlayHints.parameterNames.enabled": "none"` to disable the inlay hint feature.

**Comment by vivekgohel2004** [comment]
Thank you for your email, it worked very well for me .
