### ISSUE TITLE
Unable to Debug On Vscode 

### ISSUE THREAD

**Issue by MajorTomMan** [microsoft/vscode-java-debug#1385]
[provide a description of the issue]

##### Environment
- Operating System: Ubuntu 18.04
- JDK version: 17.0.7
- Visual Studio Code version: 1.81.1
- Java extension version: 0.25.13
- Java Debugger extension version: 0.54.0

##### Steps To Reproduce

When running a Java program, there is no way to Debug the program, as shown in the following figure

![Screenshot from 2023-08-31 10-24-52](https://github.com/microsoft/vscode-java-debug/assets/47267913/cd3e25d3-49d3-4dda-b9bf-ef4b6fc663d8)

and Here is Log

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-08-31 10:18:12.609
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-08-31 10:18:13.069
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-08-31 10:18:13.073
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-08-31 10:18:13.074
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-08-31 10:18:13.129
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-08-31 10:18:13.356
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-08-31 10:18:13.357
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-08-31 10:18:13.358
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-08-31 10:18:13.358
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-08-31 10:18:13.359
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-08-31 10:18:13.359
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-08-31 10:18:13.360
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-08-31 10:18:13.360
!MESSAGE Unable to load IDecompiler class for jarFileContentProvider

!ENTRY java-debug 4 0 2023-08-31 10:18:36.429
!MESSAGE Unrecognized request: { _request: breakpointLocations }

!ENTRY java-debug 4 0 2023-08-31 10:18:36.432
!MESSAGE Unrecognized request: { _request: breakpointLocations }

!ENTRY java-debug 4 0 2023-08-31 10:18:36.433
!MESSAGE Unrecognized request: { _request: breakpointLocations }

!ENTRY java-debug 4 0 2023-08-31 10:18:36.434
!MESSAGE Unrecognized request: { _request: breakpointLocations }

!ENTRY java-debug 4 0 2023-08-31 10:18:36.435
!MESSAGE Unrecognized request: { _request: breakpointLocations }

!ENTRY java-debug 4 0 2023-08-31 10:18:36.436
!MESSAGE Unrecognized request: { _request: breakpointLocations }

!ENTRY java-debug 4 0 2023-08-31 10:18:36.436
!MESSAGE Unrecognized request: { _request: breakpointLocations }

!ENTRY java-debug 4 0 2023-08-31 10:18:36.437
!MESSAGE Unrecognized request: { _request: breakpointLocations }

!ENTRY java-debug 4 0 2023-08-31 10:18:36.438
!MESSAGE Unrecognized request: { _request: breakpointLocations }

!ENTRY java-debug 4 0 2023-08-31 10:18:36.438
!MESSAGE Unrecognized request: { _request: breakpointLocations }

!ENTRY java-debug 4 0 2023-08-31 10:18:36.439
!MESSAGE Unrecognized request: { _request: breakpointLocations }

!ENTRY java-debug 4 0 2023-08-31 10:18:36.439
!MESSAGE Unrecognized request: { _request: breakpointLocations }

!ENTRY java-debug 4 0 2023-08-31 10:18:36.440
!MESSAGE Unrecognized request: { _request: breakpointLocations }

!ENTRY java-debug 4 0 2023-08-31 10:18:36.440
!MESSAGE Unrecognized request: { _request: breakpointLocations }

!ENTRY java-debug 4 0 2023-08-31 10:18:36.441
!MESSAGE Unrecognized request: { _request: breakpointLocations }

##### Current Result
Cant Debug
##### Expected Result
Can Debug

**Comment by testforstephen** [comment]
From the screenshot, the breakpoint is paused. Pls provide more details about the issue that's unable to debug.

**Comment by MajorTomMan** [comment]
> From the screenshot, the breakpoint is paused. Pls provide more details about the issue that's unable to debug.

When I click the continue button Debug program does not respond, there is no || icon, until I click the continue button many times, Debug program will run normally

**Comment by MajorTomMan** [comment]
> From the screenshot, the breakpoint is paused. Pls provide more details about the issue that's unable to debug.

This seems to happen only in certain folders, when I open Vscode to a higher folder, the Debug program works fine, but when I go back to that folder Debug still does this multiple clicks before it works fine

**Comment by testforstephen** [comment]
Given that you add lots of breakpoints in the code, when you click continue button, no || icon indicates that the execution has paused at another breakpoint further down in the code.

**Comment by MajorTomMan** [comment]
> Given that you add lots of breakpoints in the code, when you click continue button, no || icon indicates that the execution has paused at another breakpoint further down in the code.

But I've reduced the number of breakpoints to one, and I'm still getting this multiple clicks to get the line highlighting to work.

![Screenshot from 2023-08-31 11-11-54](https://github.com/microsoft/vscode-java-debug/assets/47267913/5cda4b4d-a578-4562-8ac8-cc5d58b3a79f)

**Comment by testforstephen** [comment]
You have set a breakpoint inside a while loop, of course it could hit the breakpoint multiple times.

I'm going to mark this as a user error. Pls provide a valid sample code for reproduce the issue if you feel it's a real bug.
