### ISSUE TITLE
C:\Users\MSI\Desktop> c: && cd c:\Users\MSI\Desktop && cmd /C ""C:\Program Files\Eclipse Adoptium\jdk-17.0.8.7-hotspot\bin\java.exe" -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:59908 -XX:+ShowCodeDetailsInExceptionMessages -cp C:\Users\MSI\AppData\Roaming\Code\User\workspaceStorage\50775f03e061fe718e06413bc79ba387\redhat.java\jdt_ws\jdt.ls-java-project\bin HelloWorld " Hello, World!

### ISSUE THREAD

**Issue by Nvm300603** [microsoft/vscode-java-debug#1391]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by testforstephen** [comment]
pls create the issue with details and reproducing steps.
