### ISSUE TITLE
VSIX no longer published in GitHub releases

### ISSUE THREAD

**Issue by puremourning** [microsoft/vscode-java-debug#1392]
More of a question... Releases since 0.52.0 no longer include the VSIX in the assets attached to the GitHub release. Is this intentional? 

Unfortunately, this makes it more difficult for third-party installers to download the assets, as the Vscode marketplace link is heavily rate limited and the CDN is obfuscated. 

Would it be possible to re-include the vsix, or at least a build of the jdt.ls plugin jar in the release assets? This would allow me to upgrade the version used by Vimspector.

**Comment by testforstephen** [comment]
Duplicates with https://github.com/microsoft/vscode-java-debug/issues/1376.

You can find com.microsoft.java.debug.plugin.jar from maven central.
https://central.sonatype.com/artifact/com.microsoft.java/com.microsoft.java.debug.plugin/0.49.0
