### ISSUE TITLE
java.lang.ClassNotFoundException error displayed in VS-Code

### ISSUE THREAD

**Issue by shwetasidhwani** [microsoft/vscode-java-debug#1398]
<img width="826" alt="error" src="https://github.com/microsoft/vscode-java-debug/assets/121174976/e00c48bb-15e0-4294-ba36-ded392aea3d7">
<img width="764" alt="Screenshot 2023-10-01 142634" src="https://github.com/microsoft/vscode-java-debug/assets/121174976/74d78a27-833d-4bbf-8b17-1ba5553292c7">
<img width="583" alt="Screenshot 2023-10-01 142741" src="https://github.com/microsoft/vscode-java-debug/assets/121174976/62699c33-b287-4832-9cb7-8e5c7ef0f522">

this is my code. I am getting java.lang.ClassNotFoundException error. How do i rectify this?

**Comment by testforstephen** [comment]
Could you provide a sample project to reproduce the issue?
