### ISSUE TITLE
Restart button is not working. Nothing changed.

### ISSUE THREAD

**Issue by eungook** [microsoft/vscode-java-debug#1399]
[provide a description of the issue]

##### Environment
- Operating System: **MacOS 14**
- JDK version: **openjdk 11.0.20.1**
- Visual Studio Code version: **1.83.0**
- Java extension version: **Language Support for Java(TM) by Red Hat, v1.24.2023100804, Pre-Release**
- Java Debugger extension version: **Debugger for Java, v0.54.2023092623, Pre-Release**

##### Steps To Reproduce
1. Run or Debug Application
2. Make a small change
3. Click the Restart Button

[attach a sample project reproducing the error]
[Spring Initializr, Spring Boot 2.7.16, Java 11, Spring Web](https://start.spring.io/#!type=gradle-project&language=java&platformVersion=2.7.16&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=buildReloadTest01&name=buildReloadTest01&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.buildReloadTest01&dependencies=web)

##### Current Result
- nothing changed

##### Expected Result
- confirm the changed emoji

##### Additional Informations
https://github.com/microsoft/vscode-java-debug/assets/11587634/0b014b40-740e-4d8a-b00c-708b5f76251e

thank you for reading me!

**Comment by testforstephen** [comment]
This looks like the build is out of sync. Do you have configured any setting to disable build?

**Comment by duc-cm** [comment]
Me too. I also faced this problem recently. May be due to VSCode or extensions update.

**Comment by mander76** [comment]
I'm having the same issue,
