### ISSUE TITLE
Debug Java Web Applications

### ISSUE THREAD

**Issue by AlexMAS** [Microsoft/vscode-java-debug#140]
Hello!

I suppose my question can be quite stupid because I have not enough experience with Java. But anyway. Is there possible to debug Java Web Applications? For example, I have an application which can be hosted on Apache Tomcat and I would like to debug it in VSCode using your extension, like I can debug it in Eclipse or IntelliJ IDEA using an appropriate debug configuration.

**Comment by andxu** [comment]
Currently, the launch mode cannot support launch web app in web container, but the attach mode should support debug servlet (jsp is not supported) , but we have not tested it yet, I will keep this issue open as the task from supporting web containers, please keep eyes on this issue for updates.

**Comment by fbricon** [comment]
@AlexMAS take a look at [this article](https://medium.com/@davidnussio/start-tomcat-with-jrebel-hot-reload-and-debug-support-from-maven-command-line-26278dd9a464). Even if you don't use JRebel, you'll see how to attach the debugger to a remote tomcat process.

**Comment by AlexMAS** [comment]
@fbricon thank you, it works fine!

I have a Gradle project, so I imported the [gretty](https://plugins.gradle.org/plugin/org.akhikhl.gretty) plugin as described comprehensively in [this article](https://guides.gradle.org/building-java-web-applications/) and configured an appropriate task to run the project:

```json
{
    "taskName": "Run Debug",
    "type": "shell",
    "command": "gradlew appRunDebug",
    "group": "build",
    "problemMatcher": []
}
```

You also have to configure [debug options](http://akhikhl.github.io/gretty-doc/Debugger-support.html) like next:

```gradle
allprojects {

    apply plugin: 'org.akhikhl.gretty'

    gretty {

        // Hosting
        servletContainer = 'tomcat8'
        host = 'localhost'
        httpPort = 8080

        // Debug
        debugPort = 5005
        debugSuspend = true
    }
}
```

And finally the launch configuration:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug (Attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": 5005
        }
    ]
}
```

**Comment by andxu** [comment]
Please take a look at this [plugin](https://marketplace.visualstudio.com/items?itemName=adashen.vscode-tomcat), we will prepare the tutorials for debug java web apps(jsp is not supported by now) .

**Comment by cvaliere** [comment]
hi @andxu i too have trouble figuring out how to do it
any news on the tutorial?

cheers
