### ISSUE TITLE
bin directory suddenly changed, much longer compile time and HCR refuses to detect anything.

### ISSUE THREAD

**Issue by DashieDev** [microsoft/vscode-java-debug#1400]
Recently while debugging a gradle project, I noticed HCR stopped recognizing any changes and decided to refresh the bin directory of my project by removing it, it doesn't re-create the directory as it used to do, so the run configuration on the launch.json generated by one of the gradle tasks referenced the wrong directory. I noticed it may have been changed to ```build/classes/java``` and ```build/resources``` as they have been newly created containing the files, and a system-wide search didn't find any other directory with the output class.  I had to manually search-and-replace all of the bin/ references in launch.json to the directory containing the class files that allow my code to run. But I am left with a much longer compile time as if the whole project got re-compiled every time even if I made only small changes like adding a println, a HCR which no longer recognizes any changes with the code so a restart is always required when I make even the simplest changes. The restart time and the compile time caused the development time to be significantly and unnecessarily longer than it used to be a few days ago. Another member of the project I am working at also facing the same problem and a fresh install and setup of a similar project in Windows Sandbox also resulted in the same situation. I am curious about what has changed that caused it. I am deeply sorry if I missed anything since I am not too familiar with Gradle. I am not sure where to ask about this as well because a few days ago it was okay and it has been working perfectly since I started using vsocde-gradle, but all too sudden and it happened. 

##### Environment
- Operating System: Windows 11 Pro 22H2 build 22621.2428
- JDK version: 17.0.4.1 2022-08-18 LTS
- Visual Studio Code version: 1.83.1 (user setup)
- Java extension version: v0.25.14
- Java Debugger extension version: v0.54.0

##### Steps To Reproduce
1. Download the test project below
2. Open the project with VSCode
3. You can notice a bin/ directory being created.
4. run ./gradlew genVSCodeRuns to generete the launch.json
5. run ./gradlew build to attempt to process and expand all of the identifiers in the resources.
6. Run a debugger session, you can see the program suffered from unprocessed resources since the bin/ folder is not being updated.
7. Manually copying the classes from the new path (```build/classes/java``` and ```build/resources```), into the bin folder
you will see the code runs fine but HCR does not work and the compile time stays as long as before.
8. Manually replacing all of the reference to the old path (```bin```) to the new path in launch.json produce the same
result as the preceeding.

##### The Test Project Reference
Forge Mod Development Kit Version 1.20.1. 
This is the test project that I used to test-run on the sandbox which reproduce the same problem.
You can get a copy of the MDK here.
https://files.minecraftforge.net/net/minecraftforge/forge/

**Comment by jdneo** [comment]
We are exploring a new way of Gradle project support which may cause this issue (HCR not working).

In short, the new approach will directly leverage gradle itself to generate compiled class files. Before, it's the java extension itself to compile the project and generate the output into `bin`.

As a temporary workaround, you can set the setting `java.gradle.buildServer.enabled` to `off` and click the `Reload` button when the bottom-right notification pops up.

**Comment by DashieDev** [comment]
I can't thank you enough for this information! The project now works like it usually does after I added that settings! You guys are truly amazing!
