### ISSUE TITLE
inline breakpoint will not work on some conditions

### ISSUE THREAD

**Issue by xinqingyaohao** [microsoft/vscode-java-debug#1414]
##### Environment
- JDK version: 1.8 , some inline breakpoints will not work

![图片](https://github.com/microsoft/vscode-java-debug/assets/77858516/d4d730c2-b598-47f6-b3d8-efa45cefddf7)

##### Environment
- JDK version: 17  , all inline breakpoints will not work

![图片](https://github.com/microsoft/vscode-java-debug/assets/77858516/8b0ddfe9-4aaa-4ae6-8932-6fce3cba8657)

**Comment by xinqingyaohao** [comment]
I Compared the source code of VSCode (debugger for java)  with Eclipse , the different as follow:

VSCode (debugger for java): inline breakpoint will not work

/*     */   public boolean visit(LambdaExpression node) {
/*  37 */     if (this.column > -1) {
/*  38 */       int startPosition = node.getStartPosition();
/*  39 */       int breakOffset = this.compilationUnit.getPosition(this.line, this.column);

/*     */       
/*  50 */       if (breakOffset == startPosition) {
/*  51 */         this.lambdaMethodBinding = node.resolveMethodBinding();
/*  52 */         this.found = true;
/*  53 */         this.lambdaExpression = node;
/*  54 */         return false;
/*     */       } 
/*     */     } 
/*  57 */     return super.visit(node);
/*     */   }
/*     */ 

/*     */   public boolean isFound() {
/*  64 */     return this.found;
/*     */   }
/*     */ 



Eclipse: (inline breakpoint will work)

/*      */   public boolean visit(LambdaExpression node) {
/* 1033 */     this.fMemberOffset = node.getStartPosition();
/* 1034 */     this.fNodeLength = node.getLength();
/* 1035 */     if (this.fInputOffset != -1 && this.fInputLength > 0 && this.fInputOffset >= this.fMemberOffset && this.fInputOffset + this.fInputLength <= this.fMemberOffset + this.fNodeLength) {
/* 1036 */       IMethodBinding methodBinding = node.resolveMethodBinding();
/* 1037 */       if (methodBinding != null) {
/* 1038 */         this.fLambdaVisited = true;
/* 1039 */         this.fLocationType = 4;
/* 1040 */         this.fLambdaMethodName = LambdaLocationLocatorHelper.toMethodName(methodBinding);
/* 1041 */         this.fLambdaMethodSignature = LambdaLocationLocatorHelper.toMethodSignature(methodBinding);
/* 1042 */         this.fLocationFound = true;
/* 1043 */         return false;
/*      */       } 
/* 1045 */     } else if (this.fLocationType != 4) {
/* 1046 */       this.fLocationType = 1;
/* 1047 */       this.fTypeName = computeTypeName((ASTNode)node);
/* 1048 */       int startLine = lineNumber(this.fMemberOffset);
/* 1049 */       if (this.fLineNumber <= startLine) {
/* 1050 */         if (this.fInputOffset != -1) {
/* 1051 */           this.fLineLocation = lineNumber(this.fInputOffset);
/*      */         } else {
/* 1053 */           this.fLineLocation = startLine;
/*      */         } 
/*      */       } else {
/*      */         
/* 1057 */         ASTNode body = node.getBody();
/* 1058 */         if (body instanceof Block) {
/* 1059 */           this.fLocationFound = false;
/* 1060 */           Block block1 = (Block)body;
/* 1061 */           if (visit(block1)) {
/* 1062 */             for (Object object : block1.statements()) {
/* 1063 */               if (object instanceof ASTNode) {
/* 1064 */                 ASTNode node1 = (ASTNode)object;
/* 1065 */                 node1.accept(this);
/*      */               }
/*      */             
/*      */             } 
/*      */           }
/* 1070 */         } else if (body instanceof LambdaExpression) {
/* 1071 */           body.accept(this);
/* 1072 */         } else if (body instanceof MethodInvocation) {
/* 1073 */           body.accept(this);
/*      */         } 
/*      */       } 
/* 1076 */       return false;
/*      */     } 
/* 1078 */     return visit((ASTNode)node, true);
/*      */   }

**Comment by xinqingyaohao** [comment]
if use JDK version: 17 , all inline breakpoints will not work for both VSCode (debugger for java) and Eclipse.

**Comment by testforstephen** [comment]
@xinqingyaohao Would you mind creating a pull request at https://github.com/microsoft/java-debug?
