### ISSUE TITLE
Java server started when clicking on 'config launch config'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-java-debug#142]
- Java extension pack installed
- have a non Java project open in VSCode
- open the debug viewlet and click on 'configure launch config'. 
- Surprisingly, this takes a few seconds. Check the status line and see that the Java language server is starting

-> As I'm in a non-Java project, the Java debug extension should detect that and not try to contribute a debug configuration and start the Java language server

**Comment by testforstephen** [comment]
Because VSCode stopped supporting `onDebug:type` activation event, java debugger can only configure the activation event `onDebug`. It seems Java debugger/Language server extension will be activated so long as the user clicks `F5` on any project.

**Comment by gregvanl** [comment]
Another scenario where this is problematic is if the user does not have a launch.json in their workspace. For example: create a new Express App and then press F5. In this case, the debugger calls each installed extension which activates on onDebugInitialConfiguration. The Java Debugger was changed recently to activate onDebugInitialConfigurations (from onDebug) but in the non-launch.json scenario, the Java Debugger extension is activated and there is long delay without any status to the user while the Java Language Server is started.

**Comment by andxu** [comment]
DUP as https://github.com/Microsoft/vscode-java-debug/issues/238, closing this one.
