### ISSUE TITLE
Java Project Unrecognized. Unable to Run/Debug.

### ISSUE THREAD

**Issue by jfetterolf** [microsoft/vscode-java-debug#1422]
##### Environment
- Operating System: WSL: Ubuntu-20.04 running on Windows 11
- JDK version: 21.0.1-zulu
- Visual Studio Code version: 1..85.1
- Java extension version: v0.25.15
- Java Debugger extension version: v0.55.0

##### Steps To Reproduce
1. Switch to release version of Language Support for Java(TM) by Red Hat (v1.25.1)
2. Open any Java project. VS Code will not recognize Java project and is unable to run/debug.

##### Current Result
VS Code will not load Java Project and is unable to run/debug.

##### Expected Result
VS Code loads Java Project and is able to run/debug.

##### Additional Information
Reverting to pre-release version produces expected result.

**Comment by testforstephen** [comment]
> Open any Java project. VS Code will not recognize Java project and is unable to run/debug.

Can you please clarify what you mean by ‘not recognize Java project’?

**Comment by jfetterolf** [comment]
Current release version is working as expected.
