### ISSUE TITLE
snake game code is not running in vs code 

### ISSUE THREAD

**Issue by Songoku3256** [microsoft/vscode-java-debug#1434]
[provide a description of the issue]
when i try to run the code of snake game in the vs code it is not able to run the code and show that the main class is not there ,and i also don't know how to creat a main class in the java to run the code can anyone help me out in this ??? 

##### Environment
- Operating System: window 11
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Additional Informations

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-java-debug/pull/1433
- [ ] https://github.com/microsoft/vscode-java-debug/issues/1432
```

**Comment by testforstephen** [comment]
Could you share a sample project and the specific steps for us to reproduce the issue? thanks.
