### ISSUE TITLE
Failed to resolve main method codeLens: _ [in BankManagementSystem_2d08eec7] is not on its project's build path

### ISSUE THREAD

**Issue by Dhyan-Chinnappa** [microsoft/vscode-java-debug#1440]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by testforstephen** [comment]
could you pls provide more details to help reproduce the issue?
