### ISSUE TITLE
ConfigError: .... not a valid java project.

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-java-debug#1442]
The `"projectName"` in launch.json is really picky of what it should be.
E.g. `"projectName": "26 - GLSL-Blobscanner_7de75d61",`, when changing this a project can not be run:

![Screenshot 2024-02-19 154637](https://github.com/microsoft/vscode-java-debug/assets/738650/787aeea1-8715-4d7c-945a-88ed6a897f58)

##### Environment
- Operating System: Windows
- JDK version: Adoptium jdk-17.0.6.10
- Visual Studio Code version: 1.85.2
- Java extension version: Do you mean"Language Support for Java(TM) by Red Hat? (v.1.28.1)
- Java Debugger extension version: v0.56

##### Steps To Reproduce

Open launch.json and change the project name.

###### -

I tried changing the folder name in `C:\Users\HSLab\AppData\Roaming\Code\User\workspaceStorage\e879949bb7afc25b73409d9ee869c095\redhat.java\ss_ws\26 - GLSL-Blobscanner_67167894` together with the value `.project` but this does not work. 

The thing is, I need to test on multiple machines and it would really benefit if I don't have to deal with this picky project name cause now I need to change it everytime I switch machine.

**Comment by testforstephen** [comment]
what happens if you leave the projectName is empty.

**Comment by clankill3r** [comment]
Good call,

```java
"projectName": "",
````

And having no projectName at all works!
