### ISSUE TITLE
Add support for running Java 21 "Unnamed classes and Instance main method"

### ISSUE THREAD

**Issue by fbricon** [microsoft/vscode-java-debug#1444]
vscode-java now provides support for Java 21 preview feature [Unnamed classes and Instance main method](https://openjdk.org/jeps/445), however, we're missing the Run/Debug codelens on the `main()` method

##### Environment
- Operating System: MacOS 14.3 (23D56)
- JDK version: 21.0.1 temurin
- Visual Studio Code version:  1.86.2
- Java extension version: 1.28.1
- Java Debugger extension version: 0.56.2024020601 pre-release

##### Steps To Reproduce
1. Set Java 21 as the default runtime
2. Create a hello.java file
3. Paste this code:
```java
String greeting = "Hello, World!";

void main() {
    System.out.println(greeting);
}
```

##### Current Result
No Run/Debug codelenses
<img width="446" alt="Screenshot 2024-02-21 at 10 49 05" src="https://github.com/microsoft/vscode-java-debug/assets/148698/9eb3581b-804e-430e-ac9f-ac915774b7ce">

##### Expected Result
Should be able to Run/Debug the class via codelenses either at the top of the file or over the `main()` method

**Comment by testforstephen** [comment]
When trying Java 21 Unnamed classes and Instance main method with the JDT language server, the instance main method works as expected. However, the unnamed classes fail to compile. See the issue https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3089.

@fbricon Do we finish the full support for the unnamed classes in jdt language server?

**Comment by testforstephen** [comment]
closed with https://github.com/microsoft/java-debug/pull/542
