### ISSUE TITLE
Feature Request: Add show/hide button for viewing/un-viewing the whole hashmap in one click for the debugger

### ISSUE THREAD

**Issue by IamManchanda** [microsoft/vscode-java-debug#1446]
**Note: Redirected to this repo from [here](https://github.com/microsoft/vscode/issues/205437#issuecomment-1952423652)**

----

**Feature Request** 

I would really love if we have the ability to debug HashMap without pressing eye icon again and again.

<img width="374" alt="Screenshot 2024-02-17 at 7 49 09 PM" src="https://github.com/microsoft/vscode/assets/4970624/14ba971f-5ef7-406b-b154-7c2004106495">

----

In Intelij Idea for example, I don't have this issue while debugging. 

<img width="358" alt="Screenshot 2024-02-17 at 7 51 16 PM" src="https://github.com/microsoft/vscode/assets/4970624/68f94894-45dd-4061-9475-a739ed945f58">

-----

Please fix by adding this feature 🙏

**Comment by testforstephen** [comment]
You can right click the VARIABLES view and click the context menu "Auto Expand Lazy Variables", which will expand the data automatically.

![image](https://github.com/microsoft/vscode-java-debug/assets/14052197/11c95ac9-7cae-496c-bb11-3698c9772df1)

**Comment by IamManchanda** [comment]
Thank you, that's helpful.
