### ISSUE TITLE
Adapter descriptor ERROR "No delegateCommandHandler for vscode.java.validateLaunchConfig"

### ISSUE THREAD

**Issue by InTEGr8or** [microsoft/vscode-java-debug#1448]
Type: <b>Bug</b>

Whenever I try to attach the debugger to a running app I get a popup saying "No delegateCommandHandler for vscode.java.startDebugSession"

"Couldn't find a debug adapter descriptor for debug type 'java. (extension might have failed to activate).'"

![image](https://github.com/microsoft/vscode-java-debug/assets/1802850/29b78181-8249-4e81-979e-996f4e01d499)

I've tried the last three versions. I restarted VSCode and the whole machine.

This started to happen a couple of days after I upgraded Java from 8 to 17, but the app is running and building and I don't see other Java-related problems anywhere else.

```json
        {
            "type": "java",
            "name": "Debug (attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": 8000,
            "sourcePaths": [
                "C:/clients/prs/roadmap-website/src/main/java"
            ],
            "cwd": "${workspaceFolder}"
        }
```

Extension version: 0.56.2024021907
VS Code version: Code - Insiders 1.87.0-insider (b8d6cdc09755c2fc8db77c179f10beb727846518, 2024-02-23T11:58:40.930Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (16.89GB free)|
|Process Argv|--crash-reporter-id 80cac15b-06cf-431f-b162-5b7ce5f0ca98|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:30784851
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:30968132
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
d6fi2104:30968146
pydisww1:30959800
cppperfcontrol:30963551
d34g3935:30961436
edj9j583:30969294
fegfb526:30952798
7j2b6412:30951517
e3gdj431:30946825
ccp2r3:30958153
pythonait:30968500

```

</details>

**Comment by InTEGr8or** [comment]
Ok, VSCode Bisect is a blunt tool. It doesn't allow you to reserve some extensions as important, so if a syntax highlighter conflicts with a debugger, it's just as likely to blame the debugger and disable it so you can keep using the easily replaceable syntax highlighter.

I like the idea of Bisect, but it's too blunt.

I wrote this simple PowerShell script to loop through my extensions, and I believe I have identified that something is conflicting with this debugger.

```ps1
Get-Content "$extensionsFile" | ForEach-Object {
    if($_ -match "^#") {
        Write-Host "UNinstalling $_"
        code-insiders --profile $profile --uninstall-extension $_.Replace("# ", "")
    } else {
        Write-Host "Installing $_"
        code-insiders --profile $profile --install-extension $_
    }
}
```

I will have more info shortly and I think I will be able to close this ticket soon.

**Comment by testforstephen** [comment]
The pre-release version 0.56.2024022605 should have fixed this issue.
