### ISSUE TITLE
100% CPU when debugging sprint boot pet clinic with "stopOnEntry" on

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-debug#145]
We noticed a huge performance downgrade when turning on the stopOnEntry option when debugging 
https://github.com/spring-projects/spring-petclinic

This is blocking the release. Please fix ASAP

**Comment by ansyral** [comment]
unfortunately, i couldn't repro it ..

**Comment by testforstephen** [comment]
Fixed in 0.4.0.
