### ISSUE TITLE
[Bug] - Can not debug lambda expression

### ISSUE THREAD

**Issue by mamilic** [microsoft/vscode-java-debug#1454]
[provide a description of the issue]
I have a stream, and I do couple of operations (filter, limit, foreach), when I try to set the breakpoint to lambda, it does not work. 

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. Make lambda function
3. Set breakpoint and debug

[Screencast from 2024-03-17 08-20-55.webm](https://github.com/microsoft/vscode-java-debug/assets/104531795/158705d4-7509-4233-b346-7ea9ad0bb969)

**Comment by testforstephen** [comment]
cannot reproduce. If you have some sample project to reproduce it consistently, feel free to share with us and reopen the issue.

https://github.com/microsoft/vscode-java-debug/assets/14052197/850ea306-8195-4bec-805b-9b663cccfbb0

**Comment by mamilic** [comment]
This was performed on Linux machine, could you please try just to be sure that this is only on my pc? Thanks!

**Comment by mamilic** [comment]
Hi @rgrunber, apologies for tagging you here, but you are only one who I know that uses linux, I was wondering could you please try to reproduce this with this example project - [demo.zip](https://github.com/user-attachments/files/17873286/demo.zip)? As of now I am not able to set inner debug breakpoint unless app is started, and also the inner breakpoint does not work, it does not stops the app when it reaches that.

https://github.com/user-attachments/assets/09fdae9b-9edc-45fe-852d-9f7ebc2a450b
