### ISSUE TITLE
Run Java works fine but Debug Java get ERROR: Could not find or load main class

### ISSUE THREAD

**Issue by d95776** [microsoft/vscode-java-debug#1457]
Type: <b>Bug</b>

when I run "Debug Java", I got the following error
/usr/bin/env /Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:52103 -Dkarate.debug.port=0 -XX:+ShowCodeDetailsInExceptionMessages -cp /Users/hchen/.vscode/extensions/karatelabs.karate-2.0.3/jar/karate-ide.jar com.discover.corebanking.bankdsldeferorforb.BankDSLDeferOrForbApplication 
Error: Could not find or load main class com.discover.corebanking.bankdsldeferorforb.BankDSLDeferOrForbApplication
Caused by: java.lang.ClassNotFoundException: com.discover.corebanking.bankdsldeferorforb.BankDSLDeferOrForbApplication

The class BankDSLDeferOrForbApplication is a spring main class with main() method.

Extension version: 0.56.2
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:57.520Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 4|
|Memory (System)|32.00GB (0.37GB free)|
|Process Argv|--enable-proposed-api genuitecllc.codetogether-onpremises --crash-reporter-id 7fdd26e4-519f-44e4-b459-5018e15c1bc0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
asynctok:30898717

```

</details>

**Comment by testforstephen** [comment]
Could you share a minimum sample project to help reproduce the problem?

**Comment by d95776** [comment]
We have several gradle projects have the errors. They run "Debug Java" fine before. But after Federal vscode release, they did not work. Also we have some other simple gradle projects which run Debug java fine. Sorry for not providing the sample project because they contain company code which can not be shared. I guess this issue is related to gradle settings. appreciated if you tell me how to trouble shot the issue.

**Comment by d95776** [comment]
In Classpath Configuration, I see all source codes are in the classpath but for the projects which run Debug Java works have bin as output and have all reference libraries while for the projects which does not work for Debug Java the output is bin/default (actually the classes output folder is bin) and there's no any reference libraries are defined there. However, Ouput and Referenced libraries are read-only, is it possible to redefine or change them?

**Comment by d95776** [comment]
another thing I found is that vscode generates "the generated code" twice: we use mapstruct to generate the mapped beans. vscode generates the same bean's implementation in two places - one is in bin/default folder and another is at generated-sources folder. please see the screen shot.
![Uploading Screenshot 2024-03-27 at 9.30.24 AM.png…]()

**Comment by d95776** [comment]
I guess the issue is related to vscode put the generated source code and binaries i.e. java classes the same parent folder called bin and then only points to the location of generated classes as the class path location, which in our case is bin/default. However, the classes' location should be bin. May I ask if vscode team provides a fix for this issue or a workaround. Looks like vscode having different kind of issues with generated codes with gradle project. Now, even "java.import.gradle.annotationProcessing.enabled": false does not work when we use java version 17 or higher. vscode does not recognize the source code location defined in sourceSet

**Comment by d95776** [comment]
if we do not set dependency of mapstruct in gradle, the vscode shows the Output as bin folder in "Configure Classpath" page (I believe that's the right output folder). But the bin folder itself is gone too. Looks like I can't find the bin folder any more. For the same reason, the vscode can't find main class since the bin does not exist in the current project. May I ask where's the bin folder defined by vscode for java on Macbook machine?

**Comment by d95776** [comment]
I found that the issue is related to  Ouput bin folder and Referenced libraries. if we use mapstruct, the bin folder only contains the generated codes without any other classes of the app such that there's no main class in bin folder. If we put all classes into bin folder manually, vscode also does not use the packages included in Referrenced libraries.

**Comment by testforstephen** [comment]
this is a project importing issue, which is not owned by Debugger for Java extension. It's RedHat Java extension responsible for importing the gradle projects.

For Gradle project importing, we introduced a Gradle Build Server to better support it. I recommend following the docs provided [here](https://devblogs.microsoft.com/java/new-build-server-for-gradle/) to try this new approach.

**Comment by d95776** [comment]
followed the steps in the linked article and got the same error.

**Comment by testforstephen** [comment]
tracked with issue https://github.com/microsoft/vscode-gradle/issues/1479
