### ISSUE TITLE
Unable to start debugging 

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-debug#146]
When debugging:
https://github.com/spring-projects/spring-petclinic

The debugger can be launched once. And later sessions will encounter this issue:
Error: Could not find or load main class org.springframework.samples.petclinic.PetClinicApplication

This is blocking the 0.3.0 release. please fix ASAP

**Comment by akaroml** [comment]
#148 was made to workaround this issue. Please further investigate the root cause and fix.

**Comment by andxu** [comment]
https://github.com/Microsoft/vscode-java-debug/pull/160

**Comment by yaohaizh** [comment]
Close this as the issue had been fixed.
