### ISSUE TITLE
[redhat.java] provider FAILED textDocument/hover has been cancelled

### ISSUE THREAD

**Issue by Mikaka27** [microsoft/vscode-java-debug#1463]
I'm using VSCode on windows, and then using remote ssh to connect to linux. Then I attach to running maven project (these are selenium tests).

##### Environment
- Operating System: Red Hat Enterprise Linux release 8.7 (Ootpa)
- JDK version: openjdk version "21" 2023-09-19
- Visual Studio Code version: 1.88.0
- Java extension version: 1.29.0
- Java Debugger extension version: 0.57.0

##### Steps To Reproduce
1. Start remote project
2. Attach java debugger to the process
3. Set a breakpoint that you know will be hit

I'll try to attach sample project, when I successfully create it, many things are blocked on these enterprise machines.
[java-logs.txt](https://github.com/microsoft/vscode-java-debug/files/14945748/java-logs.txt)

##### Current Result
Left debugging panel shows that it is stopped at exception, the bar which allows to step through program is displayed. However breakpoint is now howevered in editor:

This is the output of extension host process:
```
2024-04-11 13:30:18.908 [error] [redhat.java] provider FAILED
2024-04-11 13:30:18.908 [error] Error: The request (id: 29, method: 'textDocument/hover') has been cancelled
    at /repo/emiwaso/.vscode-server/extensions/redhat.java-1.29.0-linux-x64/dist/extension.js:2:1104651
    at ie (/repo/emiwaso/.vscode-server/extensions/redhat.java-1.29.0-linux-x64/dist/extension.js:2:1104945)
    at /repo/emiwaso/.vscode-server/extensions/redhat.java-1.29.0-linux-x64/dist/extension.js:2:1099729
    at Immediate.<anonymous> (/repo/emiwaso/.vscode-server/extensions/redhat.java-1.29.0-linux-x64/dist/extension.js:2:1099749)
    at processImmediate (node:internal/timers:476:21)
```

##### Expected Result
Breakpoint should be triggered in the editor.

##### Additional Informations
If I install previos version of those extensions, it works again.
So it works with those extension versions:
```
Debugger for Java: 0.56.2
Language Support for Java(TM) by Red Hat: 1.28.1
```

**Comment by testforstephen** [comment]
the output of extension host process is not related to the debugger extension.

Could you describe the exact issue you’re encountering with the debugger extension?

**Comment by Mikaka27** [comment]
The problem is that the editor view in vscode does not show where the program execution is stopped. And then when you do "step over" nothing happens in the editor.

**Comment by Mikaka27** [comment]
This seems to have fixed itself, with some recent update.
