### ISSUE TITLE
Debugger intermittently fails to launch java process

### ISSUE THREAD

**Issue by AustinHoover** [microsoft/vscode-java-debug#1464]
Consecutively starting debugging is failing to start the debugger. On first starting debugging it works correctly. If the process ends naturally and then I start debugging again it fails. This happens both if the process ends naturally as well as if I manually stop debugging via the VSCode control.

Notably, the terminal at the bottom of the window shows corrupted text where the call to start the java process clearly fails (I will include terminal logs at the bottom of the issue). I have found that closing the debug terminal every time causes this issue to not occur anymore. I'm speculating it's because the terminal is being re-opened every time. While this is a workaround, it's not ideal. 

Please let me know if there's any further info I can provide or tests I can run.

##### Environment
- Operating System: Windows 10
- JDK version: Temurin 17.0.10.7
- Visual Studio Code version: 1.88.0
- Java extension version: 1.29.0
- Java Debugger extension version: 0.57.0
- Git Bash: 5.2.26
- mintty: 3.7.0

##### Steps To Reproduce
1. Open a project
2. Start Debugger
3. Cancel current debugging process
4. Start debugger again
5. Observe that the debugger fails to start (easily within 3-5 attempts for me, if not more frequent)

This has happened for multiple projects I have opened. I created a completely new project consisting of just a pom.xml and a main class and it still occurred.

I attempted to turn on server tracing and the console did not display any messages. I did double check that both the java extension and debugger extension were enabled in the current workspace.

##### Current Result

After successive attempts to debug, the debugger fails to launch.

##### Expected Result

The debugger consistently launches.

##### Additional Informations
![terminalExample](https://github.com/microsoft/vscode-java-debug/assets/25714838/35a7a1b0-9465-4e07-9499-9f8e1fc79ab7)

**Comment by testforstephen** [comment]
Did you try the default cmd or powershell terminal to see if the same thing happens?

**Comment by AustinHoover** [comment]
Sure enough that fixed it. Thank you!

**Comment by fredx21** [comment]
I have the same issue but I prefer to use (git) bash as my default terminal (easier for working in multiple systems). It seems like a buffer issue or something like that. Can this use be re-open?

**Comment by testforstephen** [comment]
> I have the same issue but I prefer to use (git) bash as my default terminal (easier for working in multiple systems). It seems like a buffer issue or something like that. Can this use be re-open?

@fredx21 The terminal behavior on client side is not owned by Java Debugger. Java Debugger is only responsible for generating the command line and passing it to VS Code via DAP. If you want more support on it, you should open an issue at https://github.com/microsoft/vscode/issues.
