### ISSUE TITLE
Lombok functions are not retrieved in build phase

### ISSUE THREAD

**Issue by BenoitLoger** [microsoft/vscode-java-debug#1485]
[provide a description of the issue]

##### Environment
- Java extension version:1.29.0

##### Steps To Reproduce
1. [step 1] Update to version 1.29.0 
2. [step 2] Try to compile a project using lombok

##### Current Result
Build failed with errors. The method builder() is undefined for the type (ANY_CLASS_USING lombok builder())

##### Expected Result
Build succeed

##### Additional Information
The bug also appear in more recent versions of the plugin

**Comment by testforstephen** [comment]
duplicates with https://github.com/redhat-developer/vscode-java/issues/3561. Java language support by Red Hat extension 1.32.0 should have fixed this issue, pls update it to latest version for a try.
