### ISSUE TITLE
Support specifying explicit/separate JRE/JDK for a launch task

### ISSUE THREAD

**Issue by tginiotis-at-work** [microsoft/vscode-java-debug#1487]
Currently the JDK/JRE that VSCode uses to launch a `java` type task from `launch.json` seems to be picked via some internal VSCode logic. This prevents from using different JDK/JREs for compile-time and run-time.

It would be useful to allow to explicitly define a java home in the launch configuration to be used for run-time.

**Use-case:** I am working on code in an `aarch64` environment. The code can be compiled just fine with an `aarch64` JDK, but for runtime, I want to launch it with an `x86_64` emulated JDK, so it could load some dependent native `x86_64` libs in run-time and etc.

I am able to compile with one JDK and launch the code with the emulated other arch JDK with some configuration juggling, but as you can imagine - that is far from ideal. A key in a the launch configuration specifying the JDK/JRE would be ideal. Other IDEs, like Eclipse and IntelliJ, allow specifying a separate run-time JDK/JRE too.

Might be related: #884

**Comment by testforstephen** [comment]
In launch.json, we already support a settting `"javaExec"` to allow you specify a different java.exe to run the application.

**Comment by tginiotis-at-work** [comment]
Indeed, thanks! Could not find it documented anywhere.

**Comment by testforstephen** [comment]
Added to the README doc.
