### ISSUE TITLE
Debugger not working when jar packages contain unicode filenames

### ISSUE THREAD

**Issue by zminic** [microsoft/vscode-java-debug#1488]
Debugger stops on the breakpoint (as seen in callstack), but there is no change in the rest of the editor and I can't step through the code. 

##### Environment
- Operating System: Linux
- JDK version: 11
- Visual Studio Code version: 1.90.0
- Java extension version: 0.27.0
- Java Debugger extension version: 0.57.0

##### Steps To Reproduce
- Create SpringBoot maven project and add package "cucumber-java" version 7.8.1
- Try to debug any code

##### Current Result

When debugging is started in Call Stack window I can see that thread is paused for breakpoint, but there is no visual cue that we are in debug mode and can't proceed debugging.

Call stack window shows error message: "Malformed input or input contains unmappable characters."

##### Expected Result

I'm able to step through the code.

##### Additional Informations

When cucumber-java package is removed debugging starts working again.

![vscode debugging error](https://github.com/microsoft/vscode-java-debug/assets/5235407/43f0e197-3aef-4638-86e0-145725793f14)

**Comment by testforstephen** [comment]
If you use `Go to definition` feature, does it open the problem file in VS Code? The debugger is reusing the same class file resolving function as the Red Hat Java extension.

**Comment by zminic** [comment]
"Go to definition" stops working for the entire project at some point if this package is included. It works when I open vscode, but after some time (I think when compilation is done) it stops working and output for java language extension shows similar error as the one above.

**Comment by testforstephen** [comment]
this duplicates with https://github.com/redhat-developer/vscode-java/issues/3139
