### ISSUE TITLE
When attaching debugger to remote JVM, where do I see "System.out" output?

### ISSUE THREAD

**Issue by gsturov** [microsoft/vscode-java-debug#1491]
I am attaching VSCode Java debugger to a running JVM.  It runs on a different system but that is probably irrelevant.
The debugger works fine, it stops at the breakpoints, for example.
But I can't find where in VSCode I can see the output of the code under debugger, like System.out.println("test");
I am looking at every option in the "Output" VSCode tab but my output is not there.

**Comment by gsturov** [comment]
I use the following java code:
`public class HelloWorld {
    public static void main(String[] args) throws InterruptedException {
      for (int i = 0; i < 10000; i++) {
         Thread.sleep(1000);
         System.out.println("Hello, World");
      }
    }
 }`

Then I run it:

**Comment by testforstephen** [comment]
In attach mode, the output message is printed to the terminal where you launch your Java process. The debugger has no knowledge about them since the stdio output is not belonged to the standard Java debug protocol.
