### ISSUE TITLE
No delegateCommandHandler for vscode.java.resolveMainMethod

### ISSUE THREAD

**Issue by zrwsmd** [microsoft/vscode-java-debug#1492]
when i launch vscode-java-debug-main extension ,an error ,how to solve it
![image](https://github.com/microsoft/vscode-java-debug/assets/26995040/e331944e-946b-432a-88e7-4979aca537a5)

**Comment by zrwsmd** [comment]
![screenshot](https://github.com/microsoft/vscode-java-debug/assets/26995040/afabdddb-f7c2-4b07-8ac9-fd1f1a0b1e88)

**Comment by testforstephen** [comment]
any error logs?

- **F1 -> Java: Open All Log Files**
- **OUTPUT -> Language Support for Java**
