### ISSUE TITLE
ProjectName in debug profile doesn't match gradle projectName

### ISSUE THREAD

**Issue by Nightenom** [microsoft/vscode-java-debug#1497]
I have forced project name in settings.gradle `rootProject.name = "foobar"`
I also have plugin to generate launch.json configs from various enviromental variables which grabs project.getName() from gradle api -> `"projectName": "foobar",`

Because of multiple setups I have multiple folders with different names, then the "eclipse project name" ends up as addition of both: folder and project.getName() - eg: `foobar-foo` for forder `foo`

My question is: where is the code/logic defining what the projectName will be? (from eclipse pov, I need to replicate it)
can I access that from gradle eclipse api? (I doubt that)

##### Environment
- Operating System: Windows 11
- JDK version: 17/21
- Visual Studio Code version: 1.90.1
- Java extension version: v1.32.0
- Java Debugger extension version: v0.58.0

##### Steps To Reproduce
1. create gradle project with `rootProject.name` set in folder with different name
2. observe `projectName` in launch.json not being the same as the one configured in gradle

I tried to do `eclipse.project.name = rootProject.name` and it seems to launch but breaks some gradle tasks linked via autoBuild and similar

##### Current Result
`ConfigError: The project 'foobar' is not a valid java project.`

##### Expected Result
The projectName being stable and debug to launch

**Comment by testforstephen** [comment]
Add @jdneo to answer the question.

**Comment by jdneo** [comment]
One way to get the eclipse project name is check it in Java Projects explorer:

![image](https://github.com/microsoft/vscode-java-debug/assets/6193897/799a2b44-30c6-492a-a3e0-1c10b939548e)

You can trigger `Explorer: Focus on Java Projects View` to let it appear

**Comment by Nightenom** [comment]
Sorry, if I haven't formed my questions well, but I need to replicate the name creation programmatically because configs in my launch.json are generated programmatically. So I need to know which code/part is responsible for generating the name (ie. debug, redhat.java, any part of eclipse stack), I've spent half of day searching through GitHub but haven't found anything

**Comment by jdneo** [comment]
If the `Gradle for Java` is not installed in your vscode, then the project is imported by Buildship, where I believe below are the related codes:

https://github.com/eclipse/buildship/blob/06828cf4d0d6e822076f7da89435a4a9a1845239/org.eclipse.buildship.core/src/main/java/org/eclipse/buildship/core/internal/workspace/DefaultWorkspaceOperations.java#L113
https://github.com/eclipse/buildship/blob/06828cf4d0d6e822076f7da89435a4a9a1845239/org.eclipse.buildship.core/src/main/java/org/eclipse/buildship/core/internal/workspace/DefaultWorkspaceOperations.java#L145

**Comment by Nightenom** [comment]
I was there before, so I digged into eclipse-platform repo now, still haven't found how is the name created, probably gonna guess it and fix it on demand if it not entirely correct. Thanks
