### ISSUE TITLE
Debugger should have some response message to user's debug action when it's waiting for LS to be up.

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#15]
When the language server is not ready, user click 'F5' or 'debug button' to launch a debug session, the debugger just waits for language server to be up silently without any response message. It should add some progress status or notification message to let user know what happens now.

**Comment by yaohaizh** [comment]
Have dependency on VSCode-java. Need look into the vscode-jave for UI hint.

**Comment by andxu** [comment]
It is resolved by vscode-java side. @testforstephen please close it if it is resolved.

**Comment by testforstephen** [comment]
vscode-java has provided a progress bar during starting, so this issue is resolved.
