### ISSUE TITLE
Run Java code

### ISSUE THREAD

**Issue by VenyBuchty** [microsoft/vscode-java-debug#1502]
Type: <b>Bug</b>

Can not run Java code at all.

Extension version: 0.58.0
VS Code version: Code 1.92.1 (Universal) (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 3, 2|
|Memory (System)|32.00GB (3.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by testforstephen** [comment]
could you pls open an issue with the detailed steps to reproduce it? also it's better to provide a sample project for reproducing.
