### ISSUE TITLE
Launcher to support multiple envFiles

### ISSUE THREAD

**Issue by hildo** [microsoft/vscode-java-debug#1505]
Currently, when launching a Java application, a single envFile is supported.  It would be nice of environment variables could be defined from multiple environment files.

This is supported in other vscode extensions (this is one for example, https://github.com/Microsoft/vscode-go/issues/1746)

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. Try to define an Array of envFile locations when launching a Java application

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "May Application",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "mainClass": "org.csea.myapp.MyApplication",
            "projectName": "myapp",
            "envFile": [
            	"${workspaceFolder}/envs/.env1",
            	"${workspaceFolder}/envs/.env2"
    	    ]
        }

    ]
}

**Comment by testforstephen** [comment]
this has been supported by https://github.com/microsoft/vscode-java-debug/pull/1506

**Comment by hildo** [comment]
Thank you for that... what is the best way to get notified when a release of the plugin containing these changes will be available?

**Comment by testforstephen** [comment]
The pre-release v0.58.2024090204 is just released. The stable release usually happens at the end of the month.

**Comment by hildo** [comment]
Thank you sir!
