### ISSUE TITLE
Use the launch configuration name as the terminal name

### ISSUE THREAD

**Issue by MikeJCusack** [microsoft/vscode-java-debug#1508]
Recreating from https://github.com/microsoft/vscode/issues/80442. This behavior is still present. 

Description from linked ticket:
```
Currently when running or debugging a launch target, the default terminal names are generic and don't reflect the launch target.

This makes it hard to know which terminal relates to which launch, particularly when you have 3 or more launches running.

Example

a Java launch target named Debug (Launch) - webapp results in a terminal named 2: Java Debug Console . I suggest that the terminal name becomes Debug (Launch) - webapp or alternatively support an override field in the launch.json to configure per launch target.
```

It was stated that this behavior is controlled by the debugger. Please implement this functionality for the Java debugger.

**Comment by testforstephen** [comment]
Actually we have supported it a long time ago. What debugger version did you use?

![image](https://github.com/user-attachments/assets/fb0d8082-6f7b-42fe-8762-5db84389cc36)

![image](https://github.com/user-attachments/assets/7fecd1b2-66b8-408b-a961-decb8a546df1)

**Comment by MikeJCusack** [comment]
@testforstephen This does not work for microservices where they use the same entry class. It should be configurable in the launch configuration, which is what was asked in the original issue.
![image](https://github.com/user-attachments/assets/88b0909f-4140-4e66-8bf1-7ebca957fad2)

**Comment by MikeJCusack** [comment]
Which is also why this issue is titled the way it is. Sorry that wasn't more clear in the description.

**Comment by testforstephen** [comment]
Since you're using microservice, you can change the user setting to `"java.debug.settings.console": "internalConsole"`. That will use the DEBUG CONSOLE to print output instead of terminal, and also supports the launch configuration name as the console title.

![image](https://github.com/user-attachments/assets/fb0d8082-6f7b-42fe-8762-5db84389cc36)

The only difference between CONSOLE and TERMINAL is that the terminal accepts user input. Since you're service code, I guess user input is not needed.

**Comment by MikeJCusack** [comment]
@testforstephen Ok, that works, thank you. Is there a way to have the debug consoles sorted / run alphabetically? It seems to run them randomly and difficult to see which services are properly running.

**Comment by testforstephen** [comment]
this debug console order is controlled by the vscode client itself, not by the Java extension. It should sort the console titles by the time sequence of the creation of console.

**Comment by testforstephen** [comment]
> So is there no way to configure a start order so that the time sequence is what you want?

How did you launch the app? Isn't the start order controlled by your manual click on run/debug action?

**Comment by MikeJCusack** [comment]
I have a compound launch configuration.
