### ISSUE TITLE
Show package for object variables 

### ISSUE THREAD

**Issue by gorkem** [Microsoft/vscode-java-debug#151]
Debugger should also show the package names for variables. At the moment there is no way to distinguish between `my.package.MyClass` and `other.package.MyClass` because they both shown as `aClass: MyClass`

**Comment by andxu** [comment]
Please enable this flag in vscode user setting:

"java.debug.settings.showQualifiedNames": true

![image](https://user-images.githubusercontent.com/17075863/32928722-76e98018-cb8e-11e7-9264-17f62d181831.png)
