### ISSUE TITLE
i can't find  a solution

### ISSUE THREAD

**Issue by mmmm635** [microsoft/vscode-java-debug#1510]
so i have this problem i don't know the solution of it i have tried everything i even delete the whole thing and did it step by step but it didn't work 
every time i try to start a java code it tells me this even tho i installed all the extention and add a path in my pc for java :
Specifies the folder path to the JDK (17 or more recent) used to launch the Java Language Server.

On Windows, backslashes must be escaped, i.e.

"java.home":"C:\\Program Files\\Java\\jdk-17.0_3"

**Comment by testforstephen** [comment]
Could you please provide more details to clarify the specific issue you have?

**Comment by mmmm635** [comment]
![image](https://github.com/user-attachments/assets/f06c38a7-095c-49f7-83c0-20be693a0cc3)
This message shows up every time I try to write a java program

**Comment by testforstephen** [comment]
The yellow squiggly on "java.home" setting represents this setting is deprecated, and not recommended to use it. If your purpose is to configure a JDK to compile and run your code, please use the command `F1 -> Java: Configure Classpath`.
