### ISSUE TITLE
How do I properly set the property ProjectName for a JNI program?

### ISSUE THREAD

**Issue by X1nLi** [microsoft/vscode-java-debug#1513]
My project is using C++ to call JAVA code via JNI and there is no static main method in the code. When using the debugging watch function, the program reminds me that I need to specify the projectName in launch.json, but I don't know where this ProjectName comes from?

##### Environment
- Operating System: Ubuntu
- JDK version: openjdk version "17.0.12"

this is my launch.json:
```
            "type": "java",
            "name": "mydebug",
            "request": "attach",
            "hostName": "localhost",
            "port": 8002
```

**Comment by testforstephen** [comment]
You can use Java Projects view to find out what Java project your source file is located.

![Image](https://github.com/user-attachments/assets/430115f4-b75f-400b-8095-eccdc59b1ca3)
