### ISSUE TITLE
Run java not working on external console

### ISSUE THREAD

**Issue by montimatte** [microsoft/vscode-java-debug#1514]
[I've set to run the programs on external console because i don't like using vs code integrated terminal and everything was working fine until may (the last time that i used java), today i had to run a program i previously coded and when the cmd opens it tells me that 'C:\Program' is not recognized as an internal or external command]

##### Environment
- Operating System: Win 11 23H2
- JDK version:  22
- Visual Studio Code version: 1.93.1 (user)
- Java extension version: 0.29.0
- Java Debugger extension version: 0.58.0

**Comment by GitHababi** [comment]
I'm currently experiencing the same issue, I think this has to do with windows not liking spaces in filepaths. In the integrated terminal, the program currently sends the following command:
```
& 'C:\Program Files\Eclipse Adoptium\jdk-17.0.12.7-hotspot\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:60020' '-XX:+ShowCodeDetailsInExceptionMessages' '-cp' 'C:\ProjectFilePath\bin' 'App' 
```

**Comment by testforstephen** [comment]
Cannot reproduce it in Windows 11 machine. Is this issue related to your application type or your machine environment? Can you reproduce it in other Java programs?
