### ISSUE TITLE
java debug in devcontainer so slow

### ISSUE THREAD

**Issue by xiangpingjiang** [microsoft/vscode-java-debug#1515]
[provide a description of the issue]

##### Environment
- Operating System: Debian GNU/Linux 12 (bookworm)
- JDK version:  1.8.0_402
- Visual Studio Code version: 1.93.1
- Java extension version:v0.29.0
- Java Debugger extension version: v0.58.0

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
Sep 21, 2024 1:13:09 AM com.microsoft.java.debug.core.UsageDataSession recordInfo
INFO: launch debug info
Sep 21, 2024 1:15:02 AM com.microsoft.java.debug.core.UsageDataSession recordResponse
WARNING: abnormal response
Sep 21, 2024 1:15:02 AM com.microsoft.java.debug.core.UsageDataSession recordResponse
WARNING: abnormal response
Sep 21, 2024 1:15:02 AM com.microsoft.java.debug.core.UsageDataSession recordResponse
WARNING: abnormal response
Sep 21, 2024 1:15:37 AM com.microsoft.java.debug.core.UsageDataSession recordResponse
WARNING: abnormal response
Sep 21, 2024 1:16:20 AM com.microsoft.java.debug.core.UsageDataSession recordResponse
WARNING: abnormal response

**Comment by testforstephen** [comment]
pls share more details about your use case to help understand the issue. what steps do you use to start the debugger? what kind of application is it? what network environment does you use?

**Comment by leonardofel** [comment]
Appears to be related to invalid positioning of old breakpoints, I've solved this removing all breakpoints:

**Ctrl + Shift + P
Remove all breakpoints**
