### ISSUE TITLE
It's possible to debug javascript code running on nashorn?

### ISSUE THREAD

**Issue by beeblebrox3** [Microsoft/vscode-java-debug#152]
With netbeans it is possible using this instructions: https://blogs.oracle.com/sundararajan/remote-debugging-of-nashorn-scripts-with-netbeans-ide-using-debugger-statements

I'm trying to work with [this project](https://gitlab.com/thrustjs/thrust-seed).

Thanks!

**Comment by akaroml** [comment]
@beeblebrox3 thanks for asking. This is an interesting request. For debugger to correctly attach, we'll need the JVM to launch in debug mode and expose a debug port. This info needs to be passed to the debugger. In this case, the JavaScript runtime is responsible for doing so.

I'm opening an issue in redhat-developer/vscode-java#456
