### ISSUE TITLE
Debugging jumping directly into error in Class.class

### ISSUE THREAD

**Issue by tnguyen2601** [microsoft/vscode-java-debug#1520]
Upon launching debug either per launch.json or Spring Boot Dashboard, VSCode jumps to `Class.class` here.
![Image](https://github.com/user-attachments/assets/aa93691d-dd3e-4430-939d-43beadad9ed1)

 I don't event get to the Spring Boot Output in the Terminal which would normally happen. The terminal only shows the command that VSCode executes to launch Java. This "C:program Java jdk-21 jav.exe -gentlib.... .argfile ...." then it stops there and jumps to the error.
![Image](https://github.com/user-attachments/assets/0a3cdc5b-f9c4-4711-a311-805ce4a16c54)

Once continued I get `java.lang.IllegalArgumentException` in `getKeyStore` of  `Class.class` 
![Image](https://github.com/user-attachments/assets/148cb557-edc0-4099-8a98-2e0f6d548d3c)

And it would take me for ever to screenshot and mention every following Exception which happens afterwards.
Everything worked perfectly fine before that. It happened from one debug session to another. I tested with a freshly generated maven-quickstart project and debug there worked perfectly fine. 

What worked:

- Running and debugging in IntelliJ 
- My Coworker tried it in their VSCode and it worked for them

What I tried:
- Restart Laptop
- Reinstall VSCode
- Cleaned Cache
- Tried older Version of VSCode Debugger for Java

Infos:

- My` launch.json`
  - `{
      "name": "Launch App",
      "type": "java",
      "request": "launch",
      "envFile": "${workspaceFolder}/.env",
      "mainClass": "com.agb.app.MyApp",
      "projectName": "MyApp"
    },`
- Debugger Version: `v0.58.0`
- VSCode Version: `1.95.0` (user setup)

**Comment by testforstephen** [comment]
![Image](https://github.com/user-attachments/assets/14951fc0-3b31-4389-9c91-41bab5da5d3f)

This pause is from Exception Breakpoint. Please toggle off "**Caught/Uncaught Exceptions**" in the BREAKPOINTS view.
