### ISSUE TITLE
Breakpoint still show on UI after disabled

### ISSUE THREAD

**Issue by songkaiape** [Microsoft/vscode-java-debug#156]
Repro steps:
1. add a breakpoint on line 10
![image](https://user-images.githubusercontent.com/4318793/32821086-9fbee3d0-ca0c-11e7-8396-cfda4e533ec6.png)

2. click again to disable it, the breakpoint is not showed in BREAKPOINTS window but the UI still show the breakpoint
![image](https://user-images.githubusercontent.com/4318793/32821125-ce69f878-ca0c-11e7-9b9f-c71ef76c6d95.png)

3. This issue only repro in some lines. So you need to try to add several breakpoints to repro this

**Comment by andxu** [comment]
vscode bug

**Comment by andxu** [comment]
Close it since vscode has fixed it .
