### ISSUE TITLE
Add feature: copy fully qualified name

### ISSUE THREAD

**Issue by mojo2012** [Microsoft/vscode-java-debug#159]
I often need to copy a classes fully qualified name, eg. to put into a spring.xml file.

Best would be to have it directly in the context menu when right-clicking on a class name.

**Comment by akaroml** [comment]
This looks like a language server feature. @yaohaizh could you please open an issue in redhat-developer/vscode-java?

**Comment by yaohaizh** [comment]
@mojo2012 on which UI part to copy fully qualified name? On editor or debugging stack?

**Comment by mojo2012** [comment]
In the editor, in eclipse you have to right click on the classname.

**Comment by yaohaizh** [comment]
This feature request should be on the vscode-java side:
https://github.com/redhat-developer/vscode-java/issues/new

Close this instead.
