### ISSUE TITLE
Junit project: Cannot determine executable for debug  adapter '{0}' 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#167]
##### Environment
- win10 (x64/x86)
- JDK version: 1.8.151_64, 1.8.151_86, 9.0.1_64
- Visual Studio Code version: 1.18.1(32/64)
- Java extension version: 0.14.0
- Java Debugger extension version:  0.3.1

##### Steps To Reproduce
1.	Open vscode and open testcase 10. junit 
2.	Open MyTest.java, and set breakpoint on line 10 and 16
3.	Start debug 

[attach a sample project reproducing the error]
[10.junit.zip](https://github.com/Microsoft/vscode-java-debug/files/1481521/10.junit.zip)

##### Current Result
![image](https://user-images.githubusercontent.com/22470312/32937314-f1ddc422-cbb2-11e7-858d-02f73728bac3.png)

**Comment by claycephas** [comment]
I have the same after updating to VSCode 1.18.1. I downgraded to VSCode 1.18.0, but am still experiencing the issue. My environment:

macOS Sierra: 10.12.6
VSCode: 1.18.1 and 1.18.0 (did not see the issue when on 1.18.0 prior to upgrade)

VSCode extensions:
`redhat.java`: 0.14.0
`vscjava.vscode-java-debug`: 0.3.1

java -version
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by claycephas** [comment]
No idea why, but this fixed it for me.

* Exit VS Code
* `rm -rf ~/Library/Application\ Support/Code/User/workspaceStorage/`
* Re-open VS Code

This is working with VS Code 1.18.1.

**Comment by testforstephen** [comment]
Problem marker shows:
<pre>
[Marker [on: /10.junit, id: 3, type: org.eclipse.buildship.core.gradleprojectconfigurationmarker, attributes: [message: Missing Gradle project configuration folder: .settings, severity: 2], created: 11/20/17 10:50 AM]]
</pre>

**Comment by GrubbyHalo** [comment]
@testforstephen How do you enable the language server in debug mode ? I have the same error on  my linux box. When i open up my project using eclipse i don't get any errors

**Comment by testforstephen** [comment]
@GrubbyHalo There are two ways to launch language server in debug mode.

1. java language server extension will detect if the extension is in `development mode`, if so, it will start with debug port `localhost:1044` enabled.

so if i run java debugger in `extension development` mode, the language server will be in debug mode too.
![image](https://user-images.githubusercontent.com/14052197/33015669-94496502-ce26-11e7-932d-8afdc8d54b46.png)

You can download language server and java debug server source code from github, and attach to 1044 port to debug the extension code.

2. The second way is a little hack.
Find javaServerStarter.js under the directory `C:\Users\jinbwan\.vscode\extensions\redhat.java-0.14.0\out\src\javaServerStarter.js`, and modify `const DEBUG = (typeof v8debug === 'object') || startedInDebugMode();` to `const DEBUG = true;`. Restart VSCode.

**Comment by GrubbyHalo** [comment]
Well this is bizarre. I fired up the extension in development mode and got the same error i got above while trying to debug it. No other meaningful messages. I then closed the extension dev host and on a whim removed the eclipse generated folders in my workspace (I used eclipse for this project before trying vscode) and tried debugging the project again and it worked! no error messages. I thought that maybe the eclipse generated folders might be responsible in some way for the errors so to test the theory i put them back again, but still got no errors! So now i am not sure what fixed  it.

**Comment by testforstephen** [comment]
@GrubbyHalo Refer to https://github.com/Microsoft/vscode-java-debug/issues/170, @wokhan provides a workaround, that should work.

**Comment by wokhan** [comment]
@testforstephen In fact the workaround I reintroduced was already there in the previous version of the extension (0.3.0), and has been "removed" (i.e. uncommented) by @andxu for 0.3.1 when RedHat Java support extension was upgraded to 0.14, so I guess there was a good reason for this.

**Comment by yaohaizh** [comment]
Fixed on PR: https://github.com/Microsoft/vscode-java-debug/pull/176

**Comment by danvsantos** [comment]
On windows 10 I solved it like this:

- Remove Java Plugins from the folder ---> C:\Users\{Your user}\.vscode ;
- And install plugins again
