### ISSUE TITLE
Debug console not working properly

### ISSUE THREAD

**Issue by mojo2012** [Microsoft/vscode-java-debug#169]
When the debugger breaks at a breakpoint I expect to be able to execute commands in the debug console. Also autocomplete/intellisense should work correctly.

I I enter the name of a variable I get this error:
```
Failed to evaluate. Reason: Cannot find the variable: XXX.
```

If I try something like *System.out.println("Test")*
```
Failed to evaluate. Reason: Complex expression is not supported currently.
```
##### Environment
- Operating System: macOS 10.13.1 (17B48)
- JDK version: 1.8.0_112
- Visual Studio Code version: 1.18.1 (1.18.1)
- Java extension version: 0.14.0
- Java Debugger extension version: 0.3.1 - 2017-11-17

##### Steps To Reproduce
1. set a breakpoint and start the debugger
2. When it stops at the breakpoint, issue some commands on the debug console

##### Current Result
<img width="553" alt="screen shot 2017-11-17 at 18 00 59" src="https://user-images.githubusercontent.com/1330361/32959238-4b830b50-cbc1-11e7-89a8-096844dd00ad.png">

##### Expected Result
The commands should be run successfully

###### Logs:
[debugger.log](https://github.com/Microsoft/vscode-java-debug/files/1483116/debugger.log)

###### launch.json
```
 {
            "type": "java",
            "name": "Debug (Launch)-Bootstrap<spot-core>",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "mainClass": "at.spot.core.infrastructure.support.init.Bootstrap",
            "projectName": "spot-core",
            "args": ""
        },
```
###### user settings:
```
"java.jdt.ls.vmargs": "-XXaltjvm=dcevm -Xdebug -noverify -Xmx1G -XX:+UseSerialGC -server -XX:+UseStringDeduplication",
```

**Comment by claycephas** [comment]
Regarding complex expressions, I believe that is a dup of #114

**Comment by akaroml** [comment]
@mojo2012 thanks for reporting and @claycephas thanks for linking the issue.

The current implementation has limited support for expression evaluation. It can only show values by looking up the specified name in the current stack frame.

We are currently developing the complete expression evaluation feature tracked by #114. Please stay tuned.
