### ISSUE TITLE
VS Code can't debug and run java files on the new version what happened ?

### ISSUE THREAD

**Issue by YousefSaber** [Microsoft/vscode-java-debug#172]
does anyone knows how to debug java files in the new version 
![1](https://user-images.githubusercontent.com/33742499/32987062-d1c917a4-cce8-11e7-93cd-41ac3d79fe15.jpg)
![2](https://user-images.githubusercontent.com/33742499/32987063-d1ef05cc-cce8-11e7-99a2-4a9969c856c9.jpg)
![3](https://user-images.githubusercontent.com/33742499/32987064-d2156a82-cce8-11e7-8932-cee9b44825bb.jpg)
![4](https://user-images.githubusercontent.com/33742499/32987065-d23d11fe-cce8-11e7-9b7e-73c5da48305c.jpg)

**Comment by andxu** [comment]
Duplicated as  https://github.com/Microsoft/vscode-java-debug/issues/170
