### ISSUE TITLE
JavaDebuggerServerPlugin.start will be invoked twice

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#173]
`JavaDebuggerServerPlugin.start()` will be invoked twice:
1. The first time happens when Java language server is started.
2. The second time happens when user clicks F5 to trigger debugger.

so that the JdtLoggerHandler will be added to logger repeatedly. Every time when the code invokes logger.fine(), it will print the same logger message twice.

##### Environment
- Operating System: Windows 10
- JDK version: 1.8.0
- Visual Studio Code version: 1.18.1
- Java extension version: 0.14.0
- Java Debugger extension version: 0.3.1

**Comment by yaohaizh** [comment]
https://github.com/eclipse/eclipse.jdt.ls/issues/450

**Comment by yaohaizh** [comment]
Resolved on eclipse.jdt.ls.
