### ISSUE TITLE
setExceptionBreakpoints throw ObjectCollectedException exception

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#182]
at Mac, debug `23.console-app`, and found `setExceptionBreakpoints` request would throw the exception `ObjectCollectedException`.

**Comment by akaroml** [comment]
@testforstephen please help investigate.

**Comment by andxu** [comment]
Seems related with same jdt bugs: https://github.com/Microsoft/java-debug/issues/23
