### ISSUE TITLE
Single file: Cannot read property 'openConfigFile' of undefined on jdk9 env

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#184]
##### Steps To Reproduce
1. Open single file : Main.java
2. Press F5 choose java, then press F5

![image](https://user-images.githubusercontent.com/22470312/33418463-ecd3c804-d5e0-11e7-80cc-ce0ba346cc2b.png)

**Comment by yaohaizh** [comment]
@bsaby Could you retest this on VSCode insider version?

**Comment by bsaby** [comment]
Insider version: 1.19.0-insider
The error of cannot read property 'openConfigFile' of undefined does not appear.

![image](https://user-images.githubusercontent.com/22470312/33423296-5927e118-d5f3-11e7-8ab5-8634e191b237.png)

**Comment by ansyral** [comment]
@bsaby ' cannot read property 'openConfigFile' of undefined ' is a know bug of vscode and it is already fixed in vscode insider

**Comment by bsaby** [comment]
Yes, i have verified this issue in insider version and cannot repro it, see my last comment.
