### ISSUE TITLE
Console application: java.lang.ClassNotFoundException: /encoding=UTF-8

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#185]
On Windows (My version is Windows 10 Enterprise)
Go to launch.json, change the option console to integratedTerminal.
Press F5 again.
##### Current Result
![image](https://user-images.githubusercontent.com/22470312/33420333-217ad3ba-d5e9-11e7-9532-f6a7e3618315.png)

**Comment by testforstephen** [comment]
The error happens when the integrated terminal is powershell. The command line string format is a little different with cmd.exe.

The workaround is to change the integrated terminal to cmd.exe by changing the user settings `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"`.

**Comment by bsaby** [comment]
Follow this workaround, integratedTerminal works fine on my Windows.

**Comment by ZZYSonny** [comment]
Will the extension support PowerShell later?

**Comment by testforstephen** [comment]
YES, this is bug, we will fix it.

**Comment by testforstephen** [comment]
Open a bug on VSCode for this issue https://github.com/Microsoft/vscode/issues/39530

**Comment by bsaby** [comment]
Test passed using the latest VSCode( version: 1.21.1)
Since this issue has been fixed and the test passed, close it.
