### ISSUE TITLE
If only 1 main class detected, proceed and start it directly

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode-java-debug#187]
When launching a main method from a standalone java class, the debugger asks me to select the 1 main class available, it should be smarter and go ahead directly

##### Environment
- Operating System: macOS High Sierra
- JDK version: 1.8
- Visual Studio Code version: 1.19.0-insiders
- Java extension version: 0.15.0
- Java Debugger extension version: 0.4.0

##### Steps To Reproduce
1. Open a standalone java file with a main method
```java
public class Standalone {
	public static void main(String[] args) {
		System.out.println("Hello World!");
	}
}
```
2. Press F5 to launch a Java environment

##### Current Result
Only the current main class is listed, user needs to select it to proceed
<img width="981" alt="screen shot 2017-11-30 at 12 59 09 pm" src="https://user-images.githubusercontent.com/148698/33446945-a4903778-d5cf-11e7-8045-4ced47cf5aaf.png">

##### Expected Result
Class selection should not be necessary, since there's no choice. 
It's even more frustrating when you repeat running the class: you need to select Java, then the class name, every time.

**Comment by andxu** [comment]
0.7.0 doesn't include this enhancement.

**Comment by andxu** [comment]
https://github.com/Microsoft/vscode-java-debug/pull/262

**Comment by bsaby** [comment]
Test passed.

- Vscode: 1.21.1
- Java debug build: andy conditional breakpoint/36
- Language support for java:0.21.0
