### ISSUE TITLE
${workspaceroot} is not converted in integratedconsole correctly when "console":"integratedconsole"

### ISSUE THREAD

**Issue by ZZYSonny** [Microsoft/vscode-java-debug#188]
[provide a description of the issue]

##### Environment
- Operating System: Win10/Mac
- JDK version: 9.0.1
- Visual Studio Code version: 1.18.1
- Java extension version: 0.15.0
- Java Debugger extension version: 0.4.0

##### Steps To Reproduce
1. Run any project that is starting from the integrated console
2. we will see the command was cd ${workspaceroot} (issue with this command) & command related to java launch ( current nothing wrong with this one) 
3. Check the directory of the integrated terminal. This issue causes java.io.FileNotFoundException if the program reads data from outside ( For example I used to read data using in.in in the workspaceroot, however, in the new settings, it is looking for in.in in another place)
##### Current Result
In powershell, terminal doesn't recognize ${workspaceroot} and gives warning messages.
In cmd, terminal doesn't recongnize ${workspaceroot} and won't run the second command.
In Mac Terminal, it goes to /Users/CurrentUser
##### Expected Result
Resolve ${workspaceroot} correctly in terminal
##### Additional Informations
There is always & before second command whether there is command ahead or not

**Comment by ZZYSonny** [comment]
One way to prevent the issue is set cwd without ${workspaceroot} or leave cwd as default.

**Comment by testforstephen** [comment]
typos.
${workspace**r**oot} => ${workspace**R**oot}
