### ISSUE TITLE
Should support class/package name with special characters.

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#19]
Like the following java file:
package ab$c;
public class Hello$orld {

}

**Comment by testforstephen** [comment]
the breakpoint support for this kind of class works in current debugger code. it doesn't work well when search the source file of these special classes. That's because the search engine cannot handle the class name with $ very well. I'm looking a way to improve the search engine.

**Comment by testforstephen** [comment]
duplicated with #121
