### ISSUE TITLE
The intellisense given too many suggestion

### ISSUE THREAD

**Issue by zmqcherish** [Microsoft/vscode-java-debug#190]
[provide a description of the issue]

##### Environment
- Operating System: Windows 10 Build 1703
- JDK version: 1.8
- Visual Studio Code version: 1.81.1
- Java extension version: 0.2.0
- Java Debugger extension version: 0.4.0

##### Steps To Reproduce
1. In a java project,which is a spring boot project. There is a Exception class define named 'ServiceException'
2. In a .java file, below code is to use the  'ServiceException':
`throw new ServiceException(String.format("数据异常：%s", item.getTitle()));`
3. The debugger extension auto show the intellisense. But it given too many that I have difficult to find the exact one I need. Below image is the tip:
![_20171207091652](https://user-images.githubusercontent.com/6880848/33694066-04ed05a4-db31-11e7-8e6d-a742f0a26bcc.png)

##### Current Result
The intellisense given too many suggestion
##### Expected Result
The intellisense just need to show one or maybe four/five suggestion other than so many useless items .
##### Additional Informations
the exact one suggestion  I need is on the bottom of the suggestion list.(The image can not show all of it)

**Comment by yaohaizh** [comment]
There is already similar one on the vscode-java. Close this one.
