### ISSUE TITLE
Feature Request - Variable Hover Check and Printing Variables

### ISSUE THREAD

**Issue by trexdinosaur** [Microsoft/vscode-java-debug#192]
I want to be able to hover over a variable/statement while in debug mode on a breakpoint and see what it was at the time. Along with that, I want to be able to print out each variables value on the screen after each statement. IntelliJ's debugger natively handles these aspects currently.

**Comment by andxu** [comment]
Do you mean this, please wait for 0.5.0 for evaluation feature to be ready:
![image](https://user-images.githubusercontent.com/17075863/33824027-f8f16a78-de97-11e7-8221-2d63cdecf308.png)

**Comment by andxu** [comment]
https://github.com/Microsoft/java-debug/pull/131

**Comment by andxu** [comment]
Will publish 0.5.0 tomorrow.

**Comment by andxu** [comment]
Close it, the expression evaluation is supported since 0.5.0.
