### ISSUE TITLE
Add libraries to single file without a project

### ISSUE THREAD

**Issue by clankill3r** [Microsoft/vscode-java-debug#194]
How can I provide a jar files to a single file that is not a project (like maven / eclipse /graddle)?
I tried:
```
 "args": "-classpath /Users/doekewartena/.m2/repository/org/processing/core/3.3.5"
```
and:
```
"args": "-classpath /Users/doekewartena/.m2/repository/org/processing/core/3.3.5/core-3.3.5.jar"
```
But that does not work.
Also I would prefer a way that intelliSense works, so that was heading the wrong way anyway.

I also tried a .classpath file in the root (this would be a nice way to have it working):

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
    <classpathentry kind="lib" path="/Users/doekewartena/.m2/repository/org/processing/core/3.3.5/core-3.3.5.jar"/>
</classpath>
```
Hope this is possible or would be possible in the future.
I'm really looking for a way where I don't have to use maven or eclipse or whatever to set up a simple java project.

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

##### Environment
- Operating System: OSX 10.12.6
- JDK version:  1.8.0_144
- Visual Studio Code version: VSCode 1.8.1
- Java extension version: 0.2.0
- Java Debugger extension version: 0.4.0

**Comment by andxu** [comment]
For single file, the 3-party library is not supported now(the package name isn't supported also), we can vote for the feature like simple-project without .classpath and .project with predefined folder structure, 
│   project.json/project.yaml --human readable configuration for project name, jdk version, etc
│
├───lib  -- folder for 3-party library
│       a.jar
│
└───src
    ├───main
    │   └───java
    │       └───com
    │           └───ms
    │               └───samples
    │                       App.java
    │
    └───test
        └───java
            └───com
                └───ms
                    └───samples
                            AppTest.java

**Comment by simahao** [comment]
@clankill3r u can add config in launch.json like below:
"vmArgs": "-Djava.ext.dirs=/Users/doekewartena/.m2/repository/org/processing/core/3.3.5"

**Comment by andxu** [comment]
@simahao  will add this feature at java-dependency in future, see it at https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency

**Comment by Kirajav** [comment]
> @clankill3r u can add config in launch.json like below:
> "vmArgs": "-Djava.ext.dirs=/Users/doekewartena/.m2/repository/org/processing/core/3.3.5"
I did it in the launch.json archive as mentioned before, but it doesn't really work for me. I'd really want to know "how can I provide a jar files to a single file that is not a project"?... 
After a little research, i finally opted to make a _quick-start maven project_ and [add the respective dependency](https://stackoverflow.com/a/35725899/9077593) in the pom.xml file.

Well i just wanted to add a mysql-driver.jar archive to a single source code file (just for do some basic querys in jdbc using Visual Studio Code)

**Comment by Kirajav** [comment]
> @simahao will add this feature at java-dependency in future, see it at https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency

I also have this installed, but i don´t know how can i supposed to add the .jar library with this extension.
