### ISSUE TITLE
Can vs-code variables be used in launch with "mainClass"?

### ISSUE THREAD

**Issue by darewreck54** [Microsoft/vscode-java-debug#197]
Question posted on stackoverflow as well:

https://stackoverflow.com/questions/47877843/how-to-debug-java-in-visual-studio-code

##### Environment
- Operating System: MAC
- JDK version: 1.8
- Visual Studio Code version: 1.19.0
- Java extension version: 0.2.0
- Java Debugger extension version:0.4.0

##### Steps To Reproduce
1. open java file
2. update launch to use vs variable for for file name.  Ex.  "mainClass": "${fileBasename}".  

get error: Failed to resolve classpath: Main class '${fileBasename}' doesn't exist in the workspace.

Question is:
1) Is using vs code launch variables supported for mainClass?
2) If not, is there a way to use the extension without having to type in the file name you want to debug

Thanks,
Derek

**Comment by testforstephen** [comment]
For question 1, currently the debugger doesn't support the vscode-variables for mainClass.
For question 2, you can try to leave the mainClass field to empty, the debugger will try to resolve all main classes in current workspace and pop up a select combox for you to choose.

**Comment by darewreck54** [comment]
@testforstephen I think that works beause you have a projectname associated.  Right now, if you don't have that it won't work.  I tried to leave it blank but i get the error still:

Please specify the mainClass (e.g. [mymodule/]com.xyz.MainClass) in the launch.json.

**Comment by akaroml** [comment]
This to me is resolved. Close for now.
