### ISSUE TITLE
Could not find or load main class GradleTest

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#20]
OS: Windows 10
Build: https://vscjavaci.cloudapp.net/job/vscode-java-debug.vsix/16/Azure/
VSCode: 1.16.1 x86
JDK: 1.8.0.14  x64

Repro Steps:

1. Open vscode and open folder the extracted folder 12. gradle from testcase.zip
2. Open GradleTest.java, and set breakpoint on line 4
3. Wait for language server ready, and verify two files: .classpath and .project are created.
4. Start debug

![image](https://user-images.githubusercontent.com/22470312/30626935-eb9e7650-9dff-11e7-89b6-b403fc610dd6.png)
Log:
![image](https://user-images.githubusercontent.com/22470312/30626942-f0970bae-9dff-11e7-9787-40cf1e1f15b7.png)

**Comment by akaroml** [comment]
@andxu please update the progress.

**Comment by andxu** [comment]
Synced with Mona, this issue cannot be reproduced since new red-hat plugin has released.
