### ISSUE TITLE
Single file: can not watch the variable value

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#204]
[provide a description of the issue]

##### Environment
- Operating System: windows10
- JDK version: 1.8 / 9
- Visual Studio Code version: 1.19.0
##### Steps To Reproduce
1. Create a new folder helloworld, create a file named App.java in this folder and filling the following codes:
public class App 
{
    public static void main( String[] args )
    {        
        System.out.println( "Hello World!" );
    }
}
2. Set BP on println and press F5 to generate launch.json
3. Press F5 and add watch args
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
![image](https://user-images.githubusercontent.com/22470312/34186887-450ccab0-e569-11e7-8720-b2d5a3f25a14.png)

##### Current Result
![image](https://user-images.githubusercontent.com/22470312/34186878-3a4bcff4-e569-11e7-9eaf-4cd7b0a28111.png)

**Comment by andxu** [comment]
https://github.com/Microsoft/java-debug/pull/146/files
