### ISSUE TITLE
Debugger will not wait for first compilation job and reports Error: "Could not find or load main class com.ms.samples.App"

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#207]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by x-strong** [comment]
I met the same problem. : (
Please fix the bug as soon as possible. Thks!

**Comment by andxu** [comment]
add SummerSun for investigation.

**Comment by bsaby** [comment]
Test passed.

Vscode: 1.21.1
Java debug build: andy private build/39
Language support for java:0.21.0
