### ISSUE TITLE
Cannot launch multiple programs in integrated terminal

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-debug#209]
1. Make sure there are two launch configurations in `launch.json`
2. Make sure both launch configurations' console setting is "integratedTerminal"
3. Launch the first one, and you see "Java Debug Console" channel added to integrated terminal
4. Try launch the second one, timeout

Expected behavior:
1. Users should be able to launch multiple programs in integrated terminal
2. Each program should have its own terminal created
3. The title of the terminal should reflect the program name, e.g. "Debug - simpleApp"

**Comment by testforstephen** [comment]
vscode tries to launch the two programs at the same integrate terminal so it failed. Open a bug on vscode https://github.com/Microsoft/vscode/issues/40814

**Comment by testforstephen** [comment]
This issue is fixed in the latest vscode.
