### ISSUE TITLE
Illegal argument

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#21]
OS: Windows 10
Build: https://vscjavaci.cloudapp.net/job/vscode-java-debug.vsix/16/Azure/
VSCode: 1.16.1 x86
JDK: 1.8.0.14 x64

Repro steps:
1. Open vocode and open folder the extracted folder 8.nosource from testcase.zip
2. Open NoSourceTest.java, and set breakpoint on line 4: System.out.println(i+10);
3. Start debug and wait for breakpoint hit
4. Switch to the Foo.java -1  stack fame
5. Press F5
6. Click any code in the Foo.java window
![image](https://user-images.githubusercontent.com/22470312/30627301-d61f0a9a-9e01-11e7-8fb5-6df5ede98a34.png)

**Comment by yaohaizh** [comment]
@testforstephen Please verify this issue on VSCode 1.17.0

**Comment by testforstephen** [comment]
Based on the PR https://github.com/Microsoft/java-debug/pull/58, the debugger will reuse the java language server to render the third-party contents. So this issue doesn't exist any more.
