### ISSUE TITLE
[Windows]Unable to launch in external terminal

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-debug#210]
Try launch spring-petclinic using the external terminal, timeout.

Works on Mac.

**Comment by testforstephen** [comment]
Windows cmd.exe has the maximum cli length limit, that is 8092 characters. The cli launch parameters of  Spring-petclinic project exceeds this limit, so it'll fail on cmd.exe. If the terminal is set to powershell, it works.

I verified that when `terminal.integrated.shell.windows` is set to powershell, launching spring-petclinic in integrated terminal will work, but `terminal.external.windowsExec` is set to powershell, launching in external terminal still fails. This looks like a VSCode issue, will open a bug there.

**Comment by andxu** [comment]
https://github.com/Microsoft/vscode-java-debug/issues/110

**Comment by andxu** [comment]
Use https://github.com/Microsoft/vscode-java-debug/issues/110 to discuss file too long issue.
