### ISSUE TITLE
Error "Failed to step because the thread 'http-nio-8004-ClientPoller-1' is not suspended in the target VM." with Java 9.0.1

### ISSUE THREAD

**Issue by khe817** [Microsoft/vscode-java-debug#213]
##### Environment
- Operating System: windows 10
- JDK version: 9.0.1
- Visual Studio Code version: 1.19.1
- Java extension version: 0.16.0
- Java Debugger extension version: 0.5.0

##### Steps To Reproduce
1. Put a break point in a spring boot controller.
2. Run the application. The debugger (type = launch) stops at the break point.
3. Try to step into the break point. <~~ fails here. See attached screenshot for the error.

![capture](https://user-images.githubusercontent.com/7119865/34301069-e37fadee-e6f8-11e7-8865-afaa8278cd13.PNG)

##### Additional Information
Still works fine in the older version of Java Debugger extension (0.4.0)
Still works with jdk1.8.0_131. Only jdk-9.0.1 that has problems.

**Comment by testforstephen** [comment]
@khe817 From `CALL STACK` view you provided, the thread `http-nio-8004-ClientPoller-1` is actually on running so the step failure is expected. You should switch current focus to a suspended thread to run step operation.

**Comment by khe817** [comment]
@testforstephen That is a bad screenshot that I have provided. The issue should have been that the debugger didn't work and didn't through any error.

Anyway, I restarted the computer after the holiday and tried to test it again. Everything miraculous works fine now.

I am sorry for the troubles!
