### ISSUE TITLE
com.sun.jdi.connect.VMStartException for java 9 project on Mac

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-java-debug#215]
##### Environment
- Operating System:Mac Capitan 10.11.6
- JDK version:9.0.1
- Visual Studio Code version:1.19.1
- Java extension version:0.16.0
- Java Debugger extension version:daily build 132

##### Steps To Reproduce

1. Open project 19.java9-app in vscode.
2. Press F5 choose java and verify launch.json is auto generated.
3. Press F5 to start debug.

[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
!ENTRY java-debug 4 0 2017-12-28 17:19:49.268 
!MESSAGE Failed to launch debuggee VM. Reason: com.sun.jdi.connect.VMStartException: VM did not connect within given time: 10000 ms 
!ENTRY java-debug 1 0 2017-12-28 17:19:49.272 
!MESSAGE  
[[RESPONSE]] 
Content-Length: 376 
{"success":false,"message":"Failed to launch debuggee VM. Reason: com.sun.jdi.connect.VMStartException: VM did not connect within given time: 10000 ms","request_seq":2,"command":"launch","body":{"error":{"id":1002,"format":"Failed to launch debuggee VM. Reason: com.sun.jdi.connect.VMStartException: VM did not connect within given time: 10000 ms"}},"seq":2,"type":"response"} 
!ENTRY java-debug 1 0 2017-12-28 17:19:49.276 
!MESSAGE  
[request] 
{"command":"disconnect","arguments":{"restart":false},"type":"request","seq":3} 
!ENTRY java-debug 1 0 2017-12-28 17:19:49.278 
!MESSAGE  
[[RESPONSE]] 
Content-Length: 81 
{"success":true,"request_seq":3,"command":"disconnect","seq":3,"type":"response"} 
!ENTRY java-debug 1 0 2017-12-28 17:19:49.287 
!MESSAGE Debug connection closed 

 
##### Current Result
![image](https://user-images.githubusercontent.com/28860891/34406561-bbf7e042-ebf4-11e7-8959-7437683e412b.png)
![image](https://user-images.githubusercontent.com/28860891/34406617-0b7a9812-ebf5-11e7-91ca-6f65376d46c2.png)

**Comment by mikemod** [comment]
I'm also using the above mentioned environment and running at the same issue. Any help would be greatly appreciated.

**Comment by AwesomeAlexander** [comment]
I'm also getting that error in a similar environment (Mac).

**Comment by Muttsu** [comment]
Same problem here on Archlinux, using jdk8. Same error when switched to openjdk9.

**Comment by andxu** [comment]
I cannot reproduce, synced with Sally Liu, she cannot repro it now.
