### ISSUE TITLE
[Multi root]Sometimes debug configuration can't auto update in debug view

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#217]
##### Environment
- Operating System: windows/mac
- JDK version: jdk8
- Visual Studio Code version: 1.19.2
- Java extension version: build152
- Java Debugger extension version: 0.17.0

##### Steps To Reproduce
1. Open a workspace
2. Generate configuration for one project
##### Current Result
![image](https://user-images.githubusercontent.com/22470312/35036528-96e35be0-fbaf-11e7-839c-abaa92ccbcd2.png)

**Comment by andxu** [comment]
vscode issue, not related to java debug

**Comment by akaroml** [comment]
@andxu how would you like to resolve this issue? you can either create an issue and track at vscode repo or provide a solution here.

**Comment by andxu** [comment]
New vscode version has fixed this issuee
