### ISSUE TITLE
Can not successfully install this extension on off-line mode.

### ISSUE THREAD

**Issue by x-strong** [Microsoft/vscode-java-debug#219]
Can not successfully install this extension on off-line mode.

##### Environment
- Operating System: Windows 7 x64
- JDK version: 1.8.0_121
- Visual Studio Code version: 1.19.1 / 1.20.0-insider
- Language Support for Java(TM) by Red Hat(redhat.java-0.17.0.vsix)
- Debugger for Java (vscjava.vscode-java-debug-0.5.0.vsix)

##### Steps To Reproduce
1. Download the extension Language Support for Java(TM) by Red Hat(version: 0.17.0) and Debugger for Java(version: 0.50)
2. First, install the extension Language Support for Java(TM) by Red Hat(version: 0.17.0) and restart the VS Code, and then install the extension Debugger for Java(version: 0.50)
 in off-line mode, restart the VS Code and find that the extension Debugger for Java(version: 0.50) haven't installed.
.

**Comment by andxu** [comment]
The latest java language server at https://marketplace.visualstudio.com/items?itemName=redhat.java is 0.17.0, and the java debug version is 0.5.0, are you installing the right extension?

**Comment by x-strong** [comment]
1. Language Support for Java(TM) by Red Hat(redhat.java-0.17.0.vsix)
2. Debugger for Java (vscjava.vscode-java-debug-0.5.0.vsix) 

Am i right?
@andxu

**Comment by andxu** [comment]
@x-strong You are right~

**Comment by x-strong** [comment]
So, as the steps list above, can you reproduce the problem?
@andxu

**Comment by andxu** [comment]
No, I cannot reproduce  the problem, can you give us a gif about the installation steps?

**Comment by andxu** [comment]
@x-strong Are you now able to install our extension?

**Comment by andxu** [comment]
@x-strong Can you take a try to uninstall Language Support for Java(TM) by Red Hat and
Debugger for Java by manually delete the folder like(close all vscode instances before deletion):
`C:\Users\andxu\.vscode\extensions\redhat.java-0.27.0`
`C:\Users\andxu\.vscode\extensions\vscjava.vscode-java-debug-0.9.0`
and install two vsixs one by one?
