### ISSUE TITLE
Provide a way to set default vmArgs

### ISSUE THREAD

**Issue by dsyer** [microsoft/vscode-java-debug#220]
It's nice that I can set "vmArgs" in a launch configuration, but it's tedious to have to type it again and again for each project I start, and each launcher I create. Some way to set the defaults (and view it in case I want to change it) would be good.

**Comment by testforstephen** [comment]
@dsyer thanks for the suggestion, i prefer to add a configure item `java.debug.settings.vmArgs` in vscode user settings for that. Do you think it's OK?

**Comment by dsyer** [comment]
I don’t have an opinion on that. Just something that works.

**Comment by bill-mao** [comment]
I worked it out by new a Java project rather than running a single current file.
