### ISSUE TITLE
Failed to attach to remote debuggee VM. Reason: com.sun.jdi.connect.spi.ClosedConnectionException

### ISSUE THREAD

**Issue by JunQianZ** [Microsoft/vscode-java-debug#221]
try to attach an Java web project to running tomcat on localhost, and do debugging, it failed, with below errors:
Failed to attach to remote debuggee VM. Reason: com.sun.jdi.connect.spi.ClosedConnectionException

##### Environment
- Operating System: windows 10
- JDK version: jdk1.8.0_152
- Visual Studio Code version:1.18.1
- Java extension version:0.17.0 (January 16th, 2018)
- Java Debugger extension version: 0.5.0 - 2017-12-20

##### Steps To Reproduce
1. [step 1] add tomcat add-in to tfs, and config tomcat to run successfully. run on http://localhost:9090/
2. [step 2] try to attach a java web project to running tomcat and do debugging on visual studio code

[attach a sample project reproducing the error]
for the launch.json: 
  "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug (Attach to Tomcat server)",
            "request": "attach",
            "hostName": "127.0.0.1",
            "port": 9090
        },
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
![image](https://user-images.githubusercontent.com/7043827/35141239-50441f26-fd35-11e7-8f23-efcb7fc3a47d.png)

**Comment by testforstephen** [comment]
@JunQianZ  Port `9090` is the application port (for http), not the debug port.  One of our team members published a dedicated tomcat extension https://marketplace.visualstudio.com/items?itemName=adashen.vscode-tomcat, i would suggest you to use it for tomcat debugging.

**Comment by JunQianZ** [comment]
@testforstephen so what should be the debug port? 
and I did use the tomcat debugging. the tomcat is configured launched successfully from my visual studio code.

**Comment by testforstephen** [comment]
Please refer to this doc for enabling remote debugging on tomcat.
https://stackoverflow.com/questions/3835612/remote-debugging-tomcat-with-eclipse

**Comment by akaroml** [comment]
@JunQianZ thanks for reporting. This issue can be addressed by following the stackoverflow discussion. Close for now.

**Comment by Aman-kumar-1999** [comment]
I have changed the testing port then It works
