### ISSUE TITLE
After rerunning a test, previously opened report should refresh

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode-java-debug#222]
After rerunning a test, previously opened report should refresh.

##### Environment
- Operating System: macOS 10.13.2  
- JDK version: 1.8.0_161
- Visual Studio Code version: 1.20-0 insiders
- Java extension version: 0.18.0
- Java Debugger extension version: 0.5.0

##### Steps To Reproduce
1. Say you have a test class with one test method 
2. run the test
3. open the test report.
4. Add a new method or break the test  
5. run the test class a 2nd time while the report is still open

##### Current Result
The report page is not refreshed with the new results.

##### Expected Result
The report page is refreshed with the new results.

**Comment by akaroml** [comment]
@fbricon thanks for reporting.
This is tracked by Microsoft/vscode-java-test#132. Close this one.
