### ISSUE TITLE
VSCode Java isn't running the latest code

### ISSUE THREAD

**Issue by ZZYSonny** [Microsoft/vscode-java-debug#223]
When I changed something in the code and run it, VSCode is running the old version and give me the old response. When I run the code for the second time without changing it, it runs the new one.

##### Environment
- Operating System: Mac 10.13.3
- JDK version:9.0.4
- Visual Studio Code version:1.19.3
- Java extension version:0.17.0
- Java Debugger extension version:0.5.0

##### Steps To Reproduce
1. Open any code, run once (First output in the photo)
2. Quickly change part of code, run immediately, check the response (Second output in the photo)
3. Run the code without changing any thing, check the response (Third output in the photo)

##### Current Result
![2018-01-26 8 56 13](https://user-images.githubusercontent.com/28442838/35420142-cd47b9a6-0276-11e8-96a4-c429344311ae.png)
![2018-01-26 8 55 45](https://user-images.githubusercontent.com/28442838/35420145-d0585a1a-0276-11e8-9d2a-9789522eb15b.png)
##### Expected Result
Response at 2 should be same with 3
##### Additional Informations
If not running immediately, it will run the latest code. Probably need some delay before running?

**Comment by ZZYSonny** [comment]
Java Language Service plugin automatically do the compile so I think there is no need to have a task.json file to build. And I remember at early version of debug plugin, it waits for the compile.
![2018-03-05 11 28 47](https://user-images.githubusercontent.com/28442838/36983337-17277cae-20cd-11e8-87c0-8974e02f28c9.png)
![2018-03-05 11 29 03](https://user-images.githubusercontent.com/28442838/36983347-1903dffe-20cd-11e8-9a47-9fcb44c5d2f1.png)

**Comment by andxu** [comment]
I cannot reproduce it no matter how fast I change my code, would you please upgrade to the latest version :

Language support for Java:0.20.0
Java Debugger extension version:0.6.0

**Comment by andxu** [comment]
Based on your gif, it is because you don't save after edit, it should be a bug but is trivial and we will fix it later. I will create a new bug of this.

**Comment by bsaby** [comment]
Test passed.

Vscode: 1.21.1
Java debug build: andy private build/39
Language support for java:0.21.0

**Comment by pedrobbarbosa** [comment]
Looks like a similar problem to the issue below:
#302 https://github.com/microsoft/vscode-java-debug/issues/302
