### ISSUE TITLE
Support "Logical Structure" for debug variables

### ISSUE THREAD

**Issue by dgileadi** [Microsoft/vscode-java-debug#227]
Eclipse supports "Logical Structure" for debug variables, where things like Lists and Maps display as lists of values instead of the internal structure of, say, ArrayList or LinkedHashMap. Eclipse has preferences for these under Java > Debug > Logical Structures. There are several built in, and you can add your own.

It would be really nice for this project to support them too, ideally with preferences for creating your own.

**Comment by akaroml** [comment]
@dgileadi thanks for reporting. We'll see what we can do here.

@andxu please investigate.

**Comment by ivenxu** [comment]
Looking forward to have this!

**Comment by testforstephen** [comment]
The new release 0.18.0 has enabled 'Logical Structure' view for Map and Collection variables. Please have a try.
