### ISSUE TITLE
Suggestion: Prompt user for program arguments

### ISSUE THREAD

**Issue by ChrisTrenkamp** [Microsoft/vscode-java-debug#228]
As a user of the vscode-java-debug extension, I want to be optionally prompted for the parameters to pass in to the program.

I have a program that I very frequently run on different sets of data and requires passing in different arguments.  I could create a new launch configuration, but that takes too long to do and my workspace will get cluttered quickly.

It will be easier to create one launch configuration that simply prompts me for the parameters that I want to pass in.

The vscode-powershell extension already has something like this:
[https://github.com/PowerShell/vscode-powershell/blob/master/examples/.vscode/launch.json#L26](https://github.com/PowerShell/vscode-powershell/blob/master/examples/.vscode/launch.json#L26)

##### Environment
- Operating System: N/A
- JDK version: N/A
- Visual Studio Code version: 1.19.3
- Java extension version: 0.17.0
- Java Debugger extension version: 0.5.0

**Comment by testforstephen** [comment]
Code merged. Will be released in 0.7.0.
