### ISSUE TITLE
Sometimes could not read metadata for maven project

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#232]
##### Environment
- Operating System: Windows10/Linux
- JDK version: jdk8
- Visual Studio Code version: 1.19.3
- Java extension version: 0.6.0
- Java Debugger extension version: 0.18.1

##### Steps To Reproduce
1. Open maven project simple-app
2. Open generated simple-app folder using vscode
3. Wait and verify .project and .classpath files and target folder are generated.
4. Press F5 choose java and F5 again to start debug

[attach a sample project reproducing the error]
[simple-app.zip](https://github.com/Microsoft/vscode-java-debug/files/1688057/simple-app.zip)

[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
![image](https://user-images.githubusercontent.com/22470312/35716600-ec1f3554-0814-11e8-8333-7dc5d9b562ec.png)

**Comment by akaroml** [comment]
@andxu Please help investigate

**Comment by andxu** [comment]
It is related to java language server startup, cannot reproduce now and investigate in next sprint.

**Comment by andxu** [comment]
Contacted with the author, cannot reproduce now.
