### ISSUE TITLE
For unsupported HCR case, should show "Continue" and "Terminate" button

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#233]
When add new method during HCR, it pops up message saying that `Hot code replace failed - Add method not implemented.` and `Not show again`/`Close`.

The suggestion buttons should be `Continue`/`Terminate` instead of `Not show again`/`Close`.

**Comment by akaroml** [comment]
The current behavior is to hint the users that their newly added functions won't take effect. The debugger won't stop the user from debugger though. The debugger session is not stopped in any way so I don't see 'Continue' apply to the scenario.

I'm seeing the Restart useful for this one. So the hint message is:
Hot code replace failed - adding member functions is not supported. Would you like to restart the debug session?

And with the following options:
'Yes'
'No'
'Never'

**Comment by yaohaizh** [comment]
https://github.com/Microsoft/vscode-java-debug/pull/244
