### ISSUE TITLE
Failed to launch debuggee VM on non-English folder name

### ISSUE THREAD

**Issue by XIAZY** [Microsoft/vscode-java-debug#234]
Opened a brand new project from Eclipse. Seems failed to launch Java VM.

Error message:
> Failed to launch debuggee VM. Reason: java.io.IOException: Cannot run program "/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/bin/java" (in directory "/Users/xia/Documents/测试/"): error=2, No such file or directory

##### Environment
- Operating System: macOS 10.13.3
- JDK version: 1.8.0_144
- Visual Studio Code version: 1.19.3
- Java extension version: 0.18.1
- Java Debugger extension version: 0.6.0

##### Steps To Reproduce
1. Click debug(launch)
2. error

##### Additional Informations
I spent at least four hours on trying to solve my environment, then realized the problem is the folder name.
For what I've tested, debugging is working on this folder name:
- Test
But definitely not working on these:
- 测试
- Próf
- тест
- テスト

I hope this helps.

**Comment by akaroml** [comment]
@testforstephen This looks like something we need to fix.

**Comment by testforstephen** [comment]
Internally the debugger will invoke `Runtime.getRuntime().exec(cmds, envVars, cwd)` to launch the program. Looks like java Runtime.exec cannot handle non ascii characters argument very well. And try the non-english folder case in eclipse, it also failed there with the same error message.

**Comment by testforstephen** [comment]
Reproduced this issue on windows 10. On cmd terminal and java debugger extension, they both cannot launch a non-ascii folder correctly. This is a known java issue because of your system locale. The workaround for windows is changing system locale to your target language (Chinese, Japanese, etc.). 

Here is the steps about how to do it in windows. https://www.java.com/en/download/help/locale.xml

**Comment by testforstephen** [comment]
@XIAZY What's your mac locale? You can exec `locale` command in Terminal to get the locale info.

My mac locale is `en_US.UTF-8`, and i use the debug extension to debug a java project with Chinese characters in the directory, the launch succeeds.

**Comment by XIAZY** [comment]
@testforstephen 
here's my locale
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by bsaby** [comment]
Can't find or load main class in Windows on non-English folder name
![image](https://user-images.githubusercontent.com/22470312/39285162-841bbe98-4949-11e8-8d1a-35fb8d91ade1.png)
JDK8 environmet:
![image](https://user-images.githubusercontent.com/22470312/39285170-8d0e7d88-4949-11e8-9e38-d19ba56c9eda.png)
JDK10 environment:
![image](https://user-images.githubusercontent.com/22470312/39285176-9972836c-4949-11e8-8316-729ad4879cdb.png)

**Comment by testforstephen** [comment]
Cannot reproduce it on Mac. I saw the project is from eclipse, not sure whether there's some implicit eclipse settings making an impact. Could you try the same project in eclipse?

**Comment by andxu** [comment]
@XIAZY Could you please repro this issue and give us the feedback? Thanks.

**Comment by martinmeeser** [comment]
I think one of the ways a configuration is added automatically is broken:
`{
            "type": "java",
            "name": "Debug (Launch)-SkaScu<scu.ska>",
            "request": "launch",
            "mainClass": "com.mtm.ska.SkaScu",
            "projectName": "scu.ska",
            "args": "/home/martin/Projects/scu3/scu.ska/settings.json"
 }`

This one leads to 
![image](https://user-images.githubusercontent.com/7906509/55607934-a9095380-577d-11e9-9283-7f5019c03d16.png)

But this one is working
`{
            "type": "java",
            "name": "CodeLens (Launch) - SkaScu",
            "request": "launch",
            "mainClass": "scu.ska/com.mtm.ska.SkaScu",
            "projectName": "scu.ska"
        }`

So you need to add the package name ...
