### ISSUE TITLE
Support "Drop to frame"

### ISSUE THREAD

**Issue by mojo2012** [Microsoft/vscode-java-debug#235]
It's very hand to be able to "drop to frame" (eclipse terminology) while debugging. Basically it allows you to restart at the beginning of a method (or any method on the stack).
This is especially useful when using DCEVM or jrebel to inject code changes and rerun them.

##### Environment
- Operating System: macOS 10.12.6 (16G1212)
- JDK version: 1.8.0_144-b01
- Visual Studio Code version:  1.20.0 (1.20.0)
- Java extension version: 0.18.1
- Java Debugger extension version:0.6.0

##### Steps To Reproduce
1. set a breakpoint in the middle of a method and break there

##### Current Result
no way to restart method

##### Expected Result
key short cut or context menu option on stack to restart at top of method

**Comment by akaroml** [comment]
Technically, we are able to do so. This happens automatically if you are using Hot Code Replace. But as far as I know, we don't have the menu entry to trigger this function manually. If you right-click on a function of the call stack, the context menu entries are generated by VS Code and cannot be customized.

@yaohaizh please double confirm.

**Comment by mojo2012** [comment]
If it's not possible to customize the menu entries, why not add at least a "command" for this?

**Comment by yaohaizh** [comment]
VSCode provider a mechanism to restart the frame.  

Investigate the code in this sprint and targeting release on next Sprint.

**Comment by yaohaizh** [comment]
Merged.

**Comment by hwellmann** [comment]
Note for anyone landing here in search of the "Drop to frame" feature and wondering how to use it:

VS Code now has a 'Restart Frame' action in the stack frame context menu in the CALL STACK viewlet.
