### ISSUE TITLE
Auto-complete in debug console/watch view

### ISSUE THREAD

**Issue by mojo2012** [Microsoft/vscode-java-debug#237]
When being on a breakpoint, autocomplete in the debug console should work exactly like in the editor.
Also the "watch view" should support autocomplete.
When a called method throws an exception, this should be printed in the debug console as well.

##### Environment
- Operating System: macOS 10.12.6 (16G1212)
- JDK version: 1.8.0_144-b01
- Visual Studio Code version: 1.20.0 (1.20.0)
- Java extension version: 0.18.1
- Java Debugger extension version:0.6.0

##### Steps To Reproduce
1. break at a break  point
2. open debug console and start typing a variable name in the scope of the breakpoint and hit ctrl-space.

##### Current Result
empty auto complete box

##### Expected Result
same as in editor view

##### Additional Informations
![bildschirmfoto 2018-02-09 um 08 55 00](https://user-images.githubusercontent.com/1330361/36017214-0575ee28-0d77-11e8-840e-4c4435113608.png)

**Comment by akaroml** [comment]
@yaohaizh is auto-completion possible in the Watch panel and the Debug Console?

**Comment by Baadier-Sydow** [comment]
@andxu How do I vote on this feature?

**Comment by andxu** [comment]
Click on the emoji 

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
