### ISSUE TITLE
Java Debug - Cannot open file after renaming folder

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-java-debug#242]
_From @yhtsao on February 28, 2018 7:13_

- VSCode Version: 1.20.1
- OS Version: MacOS 10.12.6
- Language: Java
- Extensions: 
    Debugger for Java 0.6.0
    Java Extension Pack 0.3.0
    Java Test Runner 0.3.0
    Language Support for Java(TM) by Red Hat 0.19.0

I'm new to use VS code to develop Java. Everything goes fine when creating the simple java program, compiling and debugging. But when I rename the folder that contains java file and debug the java program, it comes an error that shows debugger cannot find java source file. The solution that I found by myself is closing folder and re-import folder again. I'm not sure if there is a bug or I miss some steps to update config in VS code?

Steps to Reproduce:

1. Here's my simple java program, and it works fine when first created
![image](https://user-images.githubusercontent.com/11153474/36774161-db006a26-1c97-11e8-83e9-23b1934e6d2b.png)

2. My task.json and launch.json for compile and debug
![image](https://user-images.githubusercontent.com/11153474/36774193-f7ae8978-1c97-11e8-89bf-b2f6f5ea0a69.png)

3. Then I rename the folder (SimpleJava -> Simple)
![image](https://user-images.githubusercontent.com/11153474/36774215-109a4a9e-1c98-11e8-9298-689c84a15da0.png)

4. Rebuild Hello.java and debug "Hello", it comes an error. 
    It seems that debugger wants to open the file with the previous folder name.
![image](https://user-images.githubusercontent.com/11153474/36774253-3799fb76-1c98-11e8-9f6d-145f86292829.png)

Does this issue occur when all extensions are disabled?: No

_Copied from original issue: Microsoft/vscode#44706_

**Comment by weinand** [comment]
_From @vscodebot[bot] on February 28, 2018 7:13_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [Java Extension... java.home problem (#41176)](https://www.github.com/Microsoft/vscode/issues/41176) 
- [Failed to save '<filename>.java': The content on disk is newer. Click on Compare to compare your version with the one on disk. (#41159)](https://www.github.com/Microsoft/vscode/issues/41159) 
- [Doesn't run Java Out Of BOX + Selenium Using Java setting up problem, How to do ? (#41857)](https://www.github.com/Microsoft/vscode/issues/41857)

**Comment by akaroml** [comment]
@andxu please investigate. It looks like a language server bug to me. If so, please create an issue in vscode-java repo.

**Comment by andxu** [comment]
@weinand It is a cache bug for single file debug, I will open a new bug track this issue in java language server, BTW, seems your are manually editing launch.json/tasks.json in your configuration and bypassing the project/single file support provided by java language support, it is not suggested because it is hard to write correct javac commands with debug symbol and dependencies, the suggested way is to delete tasks.json and launch.json and press F5 to choose `java` to debug, in this way the compilation is done by  java language server

**Comment by weinand** [comment]
@weinand please note, I'm not the original author of this bug. I just moved the issue from the VS Code repo to the Java repo.

**Comment by yhtsao** [comment]
@andxu Thanks for your reply. But I'm confused about the debug way that you mentioned. I try to delete the all setting files under ".vscode/" and all *.class files, press F5 to debug my "Hello" program. There will have a window jump out to tell me to select a debug environment. Then I choose "Java", the launch.json will auto-generate as follow:
![image](https://user-images.githubusercontent.com/11153474/36942661-509be29c-1fb3-11e8-91b3-7c8ea4dfcf0b.png)

I press F5 again to debug my program, but the debug console shows debugger cannot find main class:
![image](https://user-images.githubusercontent.com/11153474/36942706-7777a56c-1fb4-11e8-8477-481cfda5c633.png)

It seems the debugger only works on already compiled JAVA program (*.class) and the compile job is not included. So I'm confused the way you mentioned:

>  the suggested way is to delete tasks.json and launch.json and press F5 to choose java to debug, in this way the compilation is done by java language server

**Comment by andxu** [comment]
@yhtsao Thank you for your patient for using our plugin, this is another known bug(cannot reproduce everytime), https://github.com/Microsoft/vscode-java-debug/issues/207, for a temporary solution, try to edit the java file or delete  all C:\Users\{your user name}\AppData\Roaming\Code\User\workspaceStorage, wishing it will solve your problem

**Comment by andxu** [comment]
Close here because it is related to vscode-java not vscode-java-debug
