### ISSUE TITLE
Support multiple projects at one time.

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#246]
from @iamlothian, 
> If I have multiple vscode windows open with different java projects only one has java language support. If i close the one supported then the other gains support.
--

**Comment by andxu** [comment]
https://github.com/Microsoft/vscode-java-pack/issues/21

**Comment by andxu** [comment]
we should evaluate why java language  server cannot be started at the same time and how to solve it, multiple eclipse can be run at the same time

**Comment by gorkem** [comment]
jdt.ls does support multiple instances. I constantly use multiple workspaces with Java projects without any issues on Linux and Mac.

**Comment by andxu** [comment]
@iamlothian, when I try the java extensions, it seems they support multiple vscode instances at one time, can you verify the problem is still here again?

**Comment by andxu** [comment]
Can not get the feedback from issue creator for a long time, close it.
