### ISSUE TITLE
'javac' is not recognized as an internal or external command, operable program or batch file. 

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#247]
from @Zayik, 
> VS Code recognizes that OpenJDK is not downloaded and informs user to download it from
https://developers.redhat.com/products/openjdk/overview/

Upon doing so, the user is still unable to use javac to compile the code. They receive the error
"'javac' is not recognized as an internal or external command, operable program or batch file."

This is very frustrating to new users, and those who are rusty towards knowing about pathing and environment variables. At this point, the user is still stuck despite following VS Code prompt.

Once the JDK is downloaded, VS Code should probably either auto include the path in its built in terminal, or prompt the user to locate the JDK to add the path. At the very least, it could send a reminder that the pathing needs to be updated in order to use it and direct them to a useful link.

This would make setting up VS Code dramatically quicker for those who are just learning coding in general. It would also add convenience for those who are already more adept at coding by giving them one less thing to worry about.

**Comment by gorkem** [comment]
I think this needs to be reported to https://github.com/redhat-developer/vscode-java/.

**Comment by andxu** [comment]
Please refer to this wiki for env setup for java: https://github.com/redhat-developer/vscode-java/wiki
