### ISSUE TITLE
Second argument is replaced upon completing the first argument in a method call

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#248]
Moved from https://github.com/Microsoft/vscode/issues/41971

- VSCode Version: Latest Insiders
- OS Version: Mac OS

Steps to Reproduce:
1. Insert cursor before the first argument (that accesses some property) to the method.
2. Start typing new argument that also accesses property. 
3. On suggestion appearance, press Tab to enter suggestion value
It replaces the old first argument instance with the property from the new argument. 

![vscode](https://user-images.githubusercontent.com/2239563/35227216-bad6a62e-ff8d-11e7-9291-85fc71e8e9f9.gif)

Sample code:
```java
public class Test {
    public int testInt;

    public boolean method(int x, int y, int z) {
        return true;
    }
}

public class Main {
    public static void main(String[] args) {
        Test t = new Test();
        t.method(t.testInt, t.testInt);
    }
}
```

**Comment by andxu** [comment]
https://github.com/Microsoft/vscode-java-pack/issues/12

**Comment by yaohaizh** [comment]
@andxu, should move to https://github.com/redhat-developer/vscode-java

**Comment by andxu** [comment]
We need to investigate first whether it is a question before reporting on vscode-java

**Comment by yaohaizh** [comment]
@https://github.com/redhat-developer/vscode-java/issues/462 

Just close this one as it is tracked vscode java.
