### ISSUE TITLE
End game 0.7.0

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#250]
# Build
- [x] 3/15 - Bump version to 0.7.0 @andxu
- [x] 3/15 - Add change log for 0.7.0 - @andxu 
- [x] 3/15 - Signed RC Bits @testforstephen Bits available at https://vscjavaci.cloudapp.net/job/vscode-java-debug.vsix-withSign/45/

# Test
- [x] 3/15 - Run test plan vscjavaci/java-debug-ci#17 - @bsaby  
- [x] 3/15 - Test Conditional BP for Windows, Ubuntu @andxu
- [x] 3/15 - Test Single file support with Conditional BP @yaohaizh 
- [x] 3/15-  Test Conditional for MAC @testforstephen 
- [x] 3/15 - Test generic Java 8 and 9 support on the Mac - @testforstephen 
- [x] 3/15 - Test generic Java 8 and 9 support on the Linux/Ubuntu- @yaohaizh
- [x] 3/15 - Test generic Java 8 and 9 support on the Windows - @andxu 
- [x] 3/15 - Test on the VSCode insider - @andxu

# Release
- [x] 3/15- Add 0.7.0 tag for vscode-java-debug and java-debug - @andxu
- [x] 3/15 - Release to marketplace - @andxu

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by andxu** [comment]
Reproduce a known issue on Ubuntu: 
![image](https://user-images.githubusercontent.com/17075863/37446571-a0dc0e46-2858-11e8-8fdf-3067351c3737.png)

**Comment by andxu** [comment]
I have tested conditional breakpoints on windows and ubuntu 16 lts, vscode and insider, and common java 8 && 9 features on Windows.

**Comment by testforstephen** [comment]
# Java 9 on Mac

1. Open project 5.breakpoint in vscode.
2. F5 and the launch.json is generated successfully.
3. Click F5 to start debugging.
4. Add breakpoint at inner class, anonymous class, they all can be hit.
5. Try to set variable and evaluate, it works.
6. Add a Conditional breakpoint at a for loop, the breakpoint is only hit when expression is satisfied.

**Comment by yaohaizh** [comment]
# Test Single file support with Conditional BP 
- Open single file from the java-debug-ci project 
- Set breakpoint with condition with two sites: 
     - The first one is valid variable
     - The second one is invalid variable
- Hit F5 to start debug
- The breakpoint is hit in error condition
- The condidtional works as expected in valid expression

**Comment by yaohaizh** [comment]
Ubuntu

    OS: Ubuntu 16.04
    VSCode: 1.19.0

Java 8:

    Following the steps from here: vscjavaci/java-debug-ci#17
    The basic functions work as expected: Breakpoints/threads/callstack/variable
    Maven: Newly generated & spring-petclinic works correctly with debugging features.
    Gradle & Single file: Press F5 without issues.

Java 9:

    Following the steps from here: vscjavaci/java-debug-ci#17
    The basic functions work as expected: Breakpoints/threads/callstack/variable
    Maven: Newly generated works correctly with debugging features.(Spring not supported on Java 9 yet)
    Single file: Press F5 without issues.

**Comment by bsaby** [comment]
# Run test plan
1. Configuration

Win10 x64 | Win10 x86 | Win10 x64 | Mac | Mac | Ubuntu
-- | -- | -- | -- | -- | --
Vscode   1.21.1   JDK   1.8.0_161 | Vscode   1.21.1   JDK   1.8.0_161 | Vscode   1.21.1   jdk-9.0.4 | Vscode   1.21.1   JDK   1.8.0_151 | Vscode   1.21.1   jdk-9.0.4 | Vscode   1.21.1   JDK   1.8.0_131

2. Open Bugs: 
#254  #255 

3. Test result


Test case | Win10 x64 | Win10 x86 | Win10 x64 | Mac | Mac | Ubuntu
-- | -- | -- | -- | -- | -- | --
Configurations | Vscode   1.21.1   JDK   1.8.0_161 | Vscode   1.21.1   JDK   1.8.0_161 | Vscode   1.21.1   jdk-9.0.4 | Vscode   1.21.1   JDK   1.8.0_151 | Vscode   1.21.1   jdk-9.0.4 | Vscode   1.21.1   JDK   1.8.0_131
Clean   install | Pass | Pass | Pass | Pass | Pass | Pass
Uninstall | Pass | Pass | Pass | Pass | Pass | Pass
Update | Pass | Pass | Pass | Pass | Pass | Pass
Auto   generating launch.json | Pass | Pass | Pass | Pass | Pass | Pass
HelloWorld | Pass | Pass | Pass | Pass | Pass | Pass
CallStack | Pass | Pass | Pass | Pass | Pass | Pass
Multiple   Thread | Pass | Pass | Pass | Pass | Pass | Pass
Variables | Pass | Pass | Pass | Pass | Pass | Pass
Big   stack frame | Pass | Pass | Pass | Pass | Pass | Pass
Breakpoint   and inner class | Pass | Pass | Pass | Pass | Pass | Pass
No   debug information test | Pass | Pass | Pass | Pass | Pass | Pass
Attach   evaluation | #255 | #255 | #255 | #255 | #255| #255
Gradle   test | Pass | Pass | Pass | Pass | Pass | Pass
PetClinc | Pass | Pass | \ | Pass | \ | Pass
TODO   application | Pass | pass | pass | Pass | Pass | Pass
Single   file build | Pass | pass | Pass | Pass | Pass | Pass
Console   application | Pass | pass | pass | Pass | Pass | Pass
Java 9   modular application | \ | \ | Pass | \ | Pass | \
Multi-root | Pass | Pass | Pass | Pass | Pass | Pass
Step   filters | Pass | Pass | pass | Pass | Pass | Pass
Hot   Code Replace | Pass | pass | Pass | Pass | Pass | Pass
Conditional   Breakpoints[New] | #254 | pass | pass | #254 | Pass | #254

**Comment by akaroml** [comment]
Perfect. Thank you, everyone.
