### ISSUE TITLE
Conditional breakpoint: com.sun.jdi.InvalidStackFrameException occurred while retrieving value

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#254]
##### Environment
- Operating System: Windows
- JDK version: 8
- Visual Studio Code version: 1.21.1
- Java extension version: 0.7.0
- Java Debugger extension version:0.20.0

##### Steps To Reproduce
1. Open project simple-app in vscode
2. Set conditional breakpoint on line 13 with condition i ==1000, F5 and wait the breakpoint to be hit

[attach a sample project reproducing the error]
[simple-app.zip](https://github.com/Microsoft/vscode-java-debug/files/1814135/simple-app.zip)

[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
![image](https://user-images.githubusercontent.com/22470312/37446815-c0e7869c-2859-11e8-81cb-a2f6ad214fb6.png)

##### Current Result
![image](https://user-images.githubusercontent.com/22470312/37446783-9c20290e-2859-11e8-9dc3-16f599a4ef73.png)
##### Except Result
Hit the conditional breakpoint when i equals 1000

**Comment by andxu** [comment]
It's related to JdiStackFrame cached in JDIThread, I will fix it in later release.

**Comment by andxu** [comment]
Please test on bit https://github.com/Microsoft/vscode-java-debug/issues/254 for this bug

**Comment by bsaby** [comment]
Now I can't repro this issue using build: andy_conditional_breakpoint/33

**Comment by andxu** [comment]
https://github.com/Microsoft/java-debug/pull/163
