### ISSUE TITLE
Still need project name for one project when attach debug 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#255]
##### Environment
- Operating System: All platforms
- JDK version: 8
- Visual Studio Code version: 1.21.1
- Java extension version: 0.7.0
- Java Debugger extension version: 0.20.0

##### Steps To Reproduce
1. Open project 18.attachdebug in testcase
2. Attach debug

##### Current Result
![image](https://user-images.githubusercontent.com/22470312/37450234-1e52e08e-2868-11e8-94e8-974e2e970ea7.png)

**Comment by bsaby** [comment]
Find that only the first time watching variable the error occurs
![image](https://user-images.githubusercontent.com/22470312/37453315-48459c10-2872-11e8-8891-10664c693bed.png)

**Comment by andxu** [comment]
https://github.com/Microsoft/java-debug/pull/164

**Comment by bsaby** [comment]
Test passed.

- Vscode: 1.21.1
- Java debug build: andy conditional breakpoint/36
- Language support for java:0.21.0
