### ISSUE TITLE
debug/run a web application with the skeleton of WEB-INF & WebServlet

### ISSUE THREAD

**Issue by xiaodongliang** [microsoft/vscode-java-debug#256]
I have a JAVA web application that is server-client by WEB-INF & WebServlet. Dependencies are managed by Maven pom.xml.
https://github.com/xiaodongliang/learn.forge.viewmodels-Intellij-Maven
It has an index.html in WEB-INF, and WEB-INF/web.xml defines the web endpoints by WebServlet. The project works well in IntelliJ. I can run/debug localhost:XXXX/index.html.

The project can be compiled successfully in VScode. However I did not get how to debug/run it. my Tomcat server can start, and I tried with ‘Debug Attach’ to localhost. It is attached. However no contents from server if accessing http://localhost:8000

launch.json
 {
            "type": "java",
            "name": "Debug (Attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": 8000
  }

another extension is available for Tomcat debugging, but it requires to have a WAR file. I did not get how to make a WAR file in VSCode. In IntelliJ, after building, the WAR package is there.
https://marketplace.visualstudio.com/items?itemName=adashen.vscode-tomcat

Could you shed a light how to run/debug such project? Thank you!

##### Environment
- Operating System:  MacBook MacOs Sierra
- JDK version: 8
- Visual Studio Code version: 1.21.1
- Java extension version: 0.3.0
- Java Debugger extension version: 0.1.5

**Comment by andxu** [comment]
We will provide a tutorial for tomcat users about how to debug a web application.

**Comment by SummerSun** [comment]
@xiaodongliang  You could just google how to create a .war file and you will get https://www.javatpoint.com/war-file

We are  supporting to run/debug a web app folder on tomcat server in our [VS Code Tomcat Extension](https://marketplace.visualstudio.com/items?itemName=adashen.vscode-tomcat) in the version 0.10.0. Please stay tuned.

**Comment by andxu** [comment]
attach this issue https://github.com/Microsoft/vscode-java-debug/issues/462 and can work together with external build-launch-in-debug tasks.

**Comment by testforstephen** [comment]
Here is a sample about how to debug Java webapps using tomcat7-maven-plugin.
https://github.com/microsoft/vscode-java-debug/blob/master/Configuration.md#attach-to-embedded-maven-tomcat-server
