### ISSUE TITLE
Support function breakpoints

### ISSUE THREAD

**Issue by dgileadi** [microsoft/vscode-java-debug#258]
Support and document how to set a [function breakpoint](https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/debugging.md#function-breakpoints).

##### Environment
- Operating System: macOS 10.13.3 High Sierra
- JDK version: 8
- Visual Studio Code version: 1.21.1
- Java extension version: 0.21.0
- Java Debugger extension version: 0.7.0

##### Steps To Reproduce
1. Set a function breakpoint in vscode by clicking the `+` button in the Breakpoints view and entering a method name from a Java class.
2. If not already started, start a Java debug session for that code.
2. Execute code that exercises that function.

##### Current Result
Execution is not paused in the debugger.

##### Expected Result
Execution is paused at the point when the function is called and the debugger displays information about the execution context.

##### Additional Information
It may be that this functionality is supported and I am simply creating the function breakpoint incorrectly. If this is the case then the readme and/or wiki should document how to correctly create a function breakpoint for Java code.

**Comment by andxu** [comment]
Thank you for bring the idea of functional bp, we only support line and limited exception bp now, the function/class bp and variable bp(break one the field is read or written) are not supported yet, please vote this one if you need this feature.

**Comment by wsq-7** [comment]
Does the plug-in support function breakpoints now？

**Comment by testforstephen** [comment]
In 0.42.0 version, you could add a function breakpoint with the syntax `FullyQualifiedClassName#methodName` (e.g. `java.util.ArrayList#add`).

![image](https://user-images.githubusercontent.com/14052197/176359594-601f9f61-45b1-4d2d-9811-aaadd32260f8.png)
