### ISSUE TITLE
Hot Code Replacement not working 

### ISSUE THREAD

**Issue by gitorko** [Microsoft/vscode-java-debug#259]
Hot Code Replacement not working in latest version of vscode 1.21.1

##### Environment
- Operating System: Windows 10.
- JDK version: 1.8
- Visual Studio Code version: 1.21.1
- Java extension version:  0.3.0
- Java Debugger extension version: 0.7.0 - 2018-3-15

##### Steps To Reproduce
1. Simple program with new line added within body for function.
2. variables are not detected as HCR didnt work. Breakpoint does seem to go back to same line though.

![hcr-bug3](https://user-images.githubusercontent.com/616726/37757109-cf67d578-2dd1-11e8-86d1-b1f8ce736bf4.gif)

**Comment by gitorko** [comment]
Invalid example

**Comment by gitorko** [comment]
Provided valid example

**Comment by yaohaizh** [comment]
@gitorko Could you share your repro project here?

**Comment by gitorko** [comment]
[helloworld.zip](https://github.com/Microsoft/vscode-java-debug/files/1838034/helloworld.zip)

If i make the change to Greet.java before a debugger checkpoint in the file is hit, then the HCR works. After the file is hit then though the breakpoint seems to be hit again the values dont show in variables.

**Comment by yaohaizh** [comment]
@gitorko: Do you have enable HCR on user setting: 

```json
    "java.debug.settings.enableHotCodeReplace": true,
```

**Comment by gitorko** [comment]
No it was not present. After adding the property debugging is working fine. I guess that was the issue?

**Comment by yaohaizh** [comment]
Yes, by default HCR is disabled.  Close this issue as it is setting problem.
