### ISSUE TITLE
chinese character don't display appropriate

### ISSUE THREAD

**Issue by xpf7622** [microsoft/vscode-java-debug#260]
// **Hello world java file is utf-8**
**public class HelloWorld** {
public static void main(String[] args) {
System.out.println("Hello World! **汉字！**");
}
}

output as follows:

**Hello World! 姹夊瓧锛�**

but java file have the default code utf-8. and Debugger for java default also utf8, why the output is abnormal character!

**Operating system : simplified Chinese win10 ;  version. :  1709(16299 .334)** 

**launch.json:**
    "configurations": [
        {
            "type": "java",
            "name": "Java Debug",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopOnEntry": false,
            "mainClass": "HelloWorld",
            **"encoding": "UTF-8",**
            "args": ""            
        },
……

**Comment by akaroml** [comment]
@testforstephen please take a look.

**Comment by andxu** [comment]
@xpf7622 could you please upload your HelloWorld.class to this issue?

**Comment by xpf7622** [comment]
@andxu Debug doesn't produce HelloWorld.class file。

**Comment by xpf7622** [comment]
this is my java file. debug process doesn't produce HelloWorld.class file.  
[HelloWorld.zip](https://github.com/Microsoft/vscode-java-debug/files/1847101/HelloWorld.zip)

**Comment by HaiUIT** [comment]
I have the same problem with you, after I set my java file encode to UTF-8 with BOM it work and print the right text. But it is not a solution, because javac doesn't work with UTF-8 with BOM. If i run javac or use other build tool like gradle, maven to build my code, it will throw this error : 

` > javac -encoding UTF8 Test.java`
`Test.java:1: error: illegal character: '\ufeff'`
`?class Test {`
`^`

**Comment by testforstephen** [comment]
The underlying compiler (jdt complier) used by java debug extension looks like using the OS default encoding to parse the source file, when source file encoding is not same as the system encoding, the generated .class file will contain messy string literal. Need find a way to pass the correct source file encoding to the jdt compiler.

**Comment by testforstephen** [comment]
Tracking the issue at vscode-java side https://github.com/redhat-developer/vscode-java/issues/479

**Comment by testforstephen** [comment]
Could you try the latest Java extensions to see if the issue still exists? thanks.
