### ISSUE TITLE
Running the contributed 

### ISSUE THREAD

**Issue by simahao** [Microsoft/vscode-java-debug#264]
[provide a description of the issue]

##### Environment
- Operating System:WIN7
- JDK version:1.8
- Visual Studio Code version:1.21.1
- Java extension version:0.21.0
- Java Debugger extension version:0.7.0

##### Steps To Reproduce
maven project or simple java file(only have System.out.println("hello world")),click f5 for debug,it is works,click f5 after a while,error messagebox is showed in right corner。
this issue can repos many times in my env.
![image](https://user-images.githubusercontent.com/4537287/37965273-15ef6c12-31f7-11e8-84cf-78e19d3065c5.png)

**Comment by andxu** [comment]
Thanks for using java debug plugin, could you please provide us the console log of vscode:

![image](https://user-images.githubusercontent.com/17075863/38181111-a1e84b60-3663-11e8-8072-d2243d6c7eb5.png)

**Comment by simahao** [comment]
reinstalled extension,error is not showed again. ：）

**Comment by andxu** [comment]
@simahao , Can we close this issue because it seems solved.
