### ISSUE TITLE
Unexpected error message when no main class is selected

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#266]
##### Environment
- Operating System: Windows / Mac
- JDK version: 8 / 9
- Visual Studio Code version:1.21.1
- Java extension version:0.21.0
- Java Debugger extension version: andy private build/39

##### Steps To Reproduce
1. Open two single files in the current window
2. Press F5
3. Select java environment
4. Don't select any main class and click on other areas to make the main class list disappear

##### Current Result
There are two error message and the error "Cannot read property 'log' of undefined" is unexpected
![image](https://user-images.githubusercontent.com/22470312/38017371-6f4d3048-32a4-11e8-844c-eca6de91bc85.png)

**Comment by andxu** [comment]
https://github.com/Microsoft/vscode-java-debug/pull/267/files
