### ISSUE TITLE
Restart frame on the bottom entry call stack fails, but Call Stack View status is still updated

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#270]
If i select the bottom call stack and execute `restart frame` operation, it will throw an error `Current stack frame doesn't support restart`. Apparently this means the operation failed, the issue is that VSCode Call Stack View status is still updated to `PAUSED ON RESTARTFRAME`. This looks like the call stack has been updated, but actually the current `Restart` operation didn't change the call stack. So it's better not to update the CALL STACK status.

**Comment by yaohaizh** [comment]
Non blocking, need update UI status for stop event.

**Comment by yaohaizh** [comment]
https://github.com/Microsoft/java-debug/pull/167
