### ISSUE TITLE
Resume all pausing threads

### ISSUE THREAD

**Issue by erihanse** [Microsoft/vscode-java-debug#271]
Is there some way to resume all waiting threads?
Sometimes when I set a breakpoint, I only want one of the threads to pause, to inspect some behaviour.

![image](https://user-images.githubusercontent.com/9251274/38283632-53e93686-37b7-11e8-82ae-f47eee8b5a36.png)

Same as https://github.com/redhat-developer/vscode-java/issues/488#event-1555413245

**Comment by testforstephen** [comment]
Duplicated with another issue https://github.com/Microsoft/vscode-java-debug/issues/103.
