### ISSUE TITLE
Support logpoint with the debug protocol changes

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode-java-debug#272]
https://code.visualstudio.com/updates/v1_22#_debug-adapter-protocol

VSCode java debug protocol has the logPoint support and some other changes: 
Logpoint support

> 
> The newly introduced Logpoints are surfaced in the Debug Adapter Protocol as a new attribute logMessage on the SourceBreakpoint and as a new capability supportsLogPoints. A debug adapter that supports Logpoints returns true for the supportsLogPoints capability and does not 'break' (stop) for a non-empty logMessage attribute but logs the message instead. Expressions within curly braces ('{...}') are evaluated and the result replaces the '{...}' in the log message.
> 
> New clientName attribute for initialize request
> 
> The frontend can use a new optional attribute clientName on the initialize request to pass the human readable name of the frontend to the debug adapter.
> 
> New terminateThreads request
> 
> A new terminateThreads request can be used by front ends to terminate one or more threads. A corresponding supportsTerminateThreadsRequest capability signifies that the debug adapter supports the request.
> 
> New setExpressionrequest
> 
> The new setExpression request can be used to assign a value to an assignable expression (aka "l-value"). A corresponding supportsSetExpression capability signifies that the debug adapter supports the request.
> 
> New preserveFocusHinton stopped event
> 
> A true-ish preserveFocusHint on the stopped event suggests to the front end that the stopped event should not change the focus.

**Comment by yaohaizh** [comment]
@andxu the logpoint should call evaluation when hit. Please help investigate to leverage the evluation provider.

**Comment by testforstephen** [comment]
See the PR https://github.com/Microsoft/java-debug/pull/184. This feature has been implemented at the release 0.10.0.
