### ISSUE TITLE
Debugger kicks off a (full?) compilation every time even when there is no code change

### ISSUE THREAD

**Issue by manastalukdar** [Microsoft/vscode-java-debug#274]
Workspace is being compiled (full?) every time on debugging even when there is no code change.

It appears after one of the recent updates, every time I hit debug a full compilation is initiated, which takes time and slows down my development workflow. Previously the debugger would start very quickly, possibly because it did an incremental compilation, perhaps only if any code changes were detected. Any way I can revert back to the old behavior?

##### Environment
- Operating System: Windows 10
- JDK version: 9
- Visual Studio Code version: 1.23.0-insider
- Java extension version: Language support: 0.22
- Java Debugger extension version: Debugger for Java: 0.8

More vscode information:
Version 1.23.0-insider
Commit fe9d9532ea6264152c144bd2ba3a6db2cd1732e3
Date 2018-04-12T05:17:00.120Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

##### Steps To Reproduce
1. Open a gradle project.
1. Hit F5 - workspace compiles, then debugger kicks in.
1. Hit F5 again - same as above.

Issue reproducible with project [here](https://github.com/manastalukdar/learning-computer-science).

##### Current Result

Project does a (full?) compilation every single time on starting debugging, even when there is no code change.

##### Expected Result

Debugging starts almost immediately, as it did before.

**Comment by rerosum** [comment]
Hi andxu,

I am experiencing the same issue.  I have a preLaunchTask that invokes gradle to do a build, so compiling the code before starting the debug session is not needed.  Is there any way to disable this compilation step?

If not, how would I go about rolling back to version 0.7.0?

Thank you

**Comment by manastalukdar** [comment]
Just updated language support extension to 0.23, and the pre-debug compilation is now a lot faster.

**Comment by rerosum** [comment]
Yes, much better, thank you.

**Comment by andxu** [comment]
Thanks for the feedback, close the issue.
