### ISSUE TITLE
Launch by sensing active source code

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-debug#275]
This is a request from the community.

When the current workspace contains multiple main classes, the debugger helps generate launch configuration for each main class. Then users can switch configurations to launch different classes.

An alternative is to remove the value of mainClass entry from launch configuration. This will make the debug list all the main classes and let users pick from the list. This is handy already.

Users want an even easier way of switch between main classes. E.g. launch the main class which has input cursor in the active window.

**Comment by andxu** [comment]
which need vscode interfaces for ui selection: https://github.com/Microsoft/vscode/issues/48650

**Comment by andxu** [comment]
Move to later release 0.10.0

**Comment by andxu** [comment]
There are multiple choices:

Use codelen to run
Use F5, and the active file will on the top of the list.
