### ISSUE TITLE
Stop on caught/uncaught exceptions

### ISSUE THREAD

**Issue by erihanse** [Microsoft/vscode-java-debug#277]
Issue Type: <b>Bug</b>

##### Steps To Reproduce
1. [step 1] Tick the uncaught and caught exceptions
2. [step 2] Produce an error

##### Current Result
Debugger doesn't halt where the exception occurs
##### Expected Result
Halt on exception. 
##### Additional Informations
I'm not sure if this is supported or not, I couldn't find any information on it. 

Extension version: 0.8.0
VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|15.86GB (1.71GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by andxu** [comment]
Seems a regression, I will figure out the root cause.

**Comment by erihanse** [comment]
![uten navn](https://user-images.githubusercontent.com/9251274/39327922-d4e7ef18-4999-11e8-8f59-6c42e10b41bf.png)

Great job! Just a slightly unexpected behaviour:
As you can see from the file here, I appear in a core library file. Step filters are default, not sure if those are concerned with caught/uncaught exceptions.

**Comment by andxu** [comment]
It is another on-road feature, I create new issue to track: https://github.com/Microsoft/vscode-java-debug/issues/295
