### ISSUE TITLE
Debug adapter doesn't detach when finished execution

### ISSUE THREAD

**Issue by erihanse** [Microsoft/vscode-java-debug#278]
Expected behaviour is that I won't need to stop execution when the program has finished. Reproducable with following boilerplate:

```
public class Foo {
    public static void main(String[] args) {

    }
}
```

![image](https://user-images.githubusercontent.com/9251274/39069618-9c2bafba-44e0-11e8-8e00-51c89f53fa68.png)

The way it is now, I need to press shift+F5 when execution is finished.

**Comment by andxu** [comment]
@erihanse I cannot repro your issue, see my gif, if you can still repro this bug, please attach the log by Help->Toggle Developer Tools


![test1](https://user-images.githubusercontent.com/17075863/39223910-0fcf19d6-4877-11e8-9327-91d814941044.gif)


![image](https://user-images.githubusercontent.com/17075863/39223928-2b692a06-4877-11e8-8d94-4bf489b65501.png)

**Comment by erihanse** [comment]
![debug-close](https://user-images.githubusercontent.com/9251274/39225794-b46bd836-484e-11e8-9271-dfd998b40cd8.gif)
Appreciate your time. 
When I created a new project in eclipse, and opened the folder in vs code I didn't manage to reproduce the issue. 

[-1524628741357.log](https://github.com/Microsoft/vscode-java-debug/files/1945435/-1524628741357.log)

**Comment by andxu** [comment]
Close this issue, please re-open it when this issue is happenning again.
