### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by simahao** [Microsoft/vscode-java-debug#280]
##### Environment
Operating System:WIN7
JDK version:1.8
Visual Studio Code version:1.22.2
Java extension version:0.23.0
Java Debugger extension version:0.8.0

##### Steps To Reproduce
1. simple hello world project,after click f5, annoying error message is showd.[build failed....]
![image](https://user-images.githubusercontent.com/4537287/39078989-f7fa74e8-4544-11e8-8557-fc75cca87dc3.png)

toggle developer tools

![image](https://user-images.githubusercontent.com/4537287/39078979-e116a760-4544-11e8-9368-ff3dcd676343.png)

notificationsAlerts.ts:39 Build failed, do you want to continue?
e.onDidNotificationChange @ notificationsAlerts.ts:39
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
e.notify @ notifications.ts:127
e.notify @ notificationService.ts:65
(anonymous) @ mainThreadMessageService.ts:86
e._showMessage @ mainThreadMessageService.ts:47
e.$showMessage @ mainThreadMessageService.ts:41
e._doInvokeHandler @ rpcProtocol.ts:174
e._invokeHandler @ rpcProtocol.ts:159
e._receiveRequest @ rpcProtocol.ts:108
e._receiveOneMessage @ rpcProtocol.ts:90
(anonymous) @ rpcProtocol.ts:33
(anonymous) @ rpcProtocol.ts:213
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560

**Comment by SummerSun** [comment]
Hi,

Thank you for reporting the issue. 

Have you tried the build from command line? If the build is fine from command line, maybe you could reference this issue https://github.com/redhat-developer/vscode-java/issues/495 and try to clean the workspace to give it another try.

**Comment by andxu** [comment]
@simahao Could you please upload your project folder as a zip file? Have you ever renamed the java file?

**Comment by psrivastava** [comment]
andxu -> I am seeing the name. This certianly has to do with renames.  My  'MyFirstProgram.java" was working all well till the time I not rename it to "FirstApp.java"
