### ISSUE TITLE
Warning: using incubator modules: jdk.incubator.httpclient

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#282]
##### Environment
- Operating System: Win10
- JDK version: JDK-10.0.1
- Visual Studio Code version: 1.22.2
- Java extension version: 0.23.0
- Java Debugger extension version: 0.8.0 (build246)

##### Steps To Reproduce
1. Open a java project in our test case
##### Current Result
![image](https://user-images.githubusercontent.com/22470312/39118864-faa6433c-471c-11e8-8da7-b6e3a46fb979.png)

**Comment by andxu** [comment]
according to article: http://www.cnblogs.com/IcanFixIt/p/7229611.html, the test case should change to the right package name of httpclient, the package jdk.incubator.httpclient should be deprecated and a new package in jdk 10 will be used, I will update the test case later
