### ISSUE TITLE
AM Unrecognized request: { _request: completions }

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-java-debug#284]
Environment

- Operating System: Windows10 x 64
- JDK version: JDK-10.0.1
- Visual Studio Code version:1.22.2
- Java extension version: 0.23.0
- Java Debugger extension version: 0.8.0(build 246)

Steps To Reproduce

1. Open test project 2.callstack
2. Open Bar.java,set BP on line 3
3. Press F5 to generate launch.json file
4. Press F5 ,click the testFoo line in the call stack view and change j to 32
5. Switch to stackframe Bar.testBar(int)(Bar.java:3) and switch back to Foo.testFoo(int)(Foo.java:6) ,input j+1 in debug console

Error in language support for java:
![image](https://user-images.githubusercontent.com/28860891/39119163-c391c316-471d-11e8-888d-03ce4eae5f9d.png)

[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
![image](https://user-images.githubusercontent.com/28860891/39119287-0b625958-471e-11e8-96fc-3ed0f24e4d79.png)

**Comment by yaohaizh** [comment]
https://github.com/Microsoft/java-debug/pull/175

**Comment by yaohaizh** [comment]
Fixed.
