### ISSUE TITLE
An error occurred while building workspace for java9 project

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#285]
##### Environment
- Operating System: Win10
- JDK version: JDK-10.0.1
- Visual Studio Code version: 1.22.2
- Java extension version: 0.23.0
- Java Debugger extension version: 0.8.0 (build246)

##### Steps To Reproduce
1. Open our testcase 19.java9-app in vscode

##### Current Result
![image](https://user-images.githubusercontent.com/22470312/39119228-ee59a514-471d-11e8-964b-40fda4a71ff6.png)

**Comment by andxu** [comment]
@SummerSun to take a look.

**Comment by bsaby** [comment]
Test passed.
#### Environment
1.  Win10
2. JDK-10.0.1
3. Visual Studio Code version: 1.22.2
4. Java extension version: 0.23.0
5. Java Debugger extension version: 0.8.0 (build251)
