### ISSUE TITLE
[Feature] Exception filter for handled/unhandled exception

### ISSUE THREAD

**Issue by andxu** [microsoft/vscode-java-debug#295]

**Comment by testforstephen** [comment]
We need have a look at the user experience for supporting this. There are already some discussions about this in VS Code.  See https://github.com/Microsoft/vscode/issues/11552

**Comment by andxu** [comment]
https://github.com/Microsoft/vscode/issues/58162

**Comment by andxu** [comment]
Will impl like this(available in 0.14.0)
https://cloud.githubusercontent.com/assets/1898161/24697055/0e1622fc-19ec-11e7-8919-d1bc1181b517.gif

**Comment by worksofliam** [comment]
What's the status of this? Was it merged?

**Comment by testforstephen** [comment]
Not fully supported yet.

so far we have exposed a setting `java.debug.settings.exceptionBreakpoint.skipClasses` to skip the specified classes when breaking on exception. Maybe we should add a new setting `java.debug.settings.exceptionBreakpoint.allowClasses` as well to specify what exception breakpoints you can enable.

**Comment by abique** [comment]
Exactly you need to specify the set of exception on which you want to break.
This is how both eclipse and intellij are working.
This is very basic stuff, I'm quite surprised it isn't there yet.

**Comment by testforstephen** [comment]
This has been supported in 0.50.0 version.

Here is how to enable exception breakpoint on the specified exception type:
1. Configure the exception types in the setting `java.debug.settings.exceptionBreakpoint.exceptionTypes`.
```json
    "java.debug.settings.exceptionBreakpoint.exceptionTypes": [
       "java.lang.NullPointerException" // fully qualified class name
    ]
```
2. Go to Breakpoint view, toggle the CaughtException or UncaughtException.
![image](https://user-images.githubusercontent.com/14052197/233827441-0c604ac1-2d0d-4934-9b24-0241783eff78.png)

**Comment by NickJAllen** [comment]
Thank you for implementing this but I still don't get how it should work. I want to set an exception breakpoint so that it will alway break when a certain exception is thrown (caught or uncaught) and to only break when another exception is thrown (but only when uncaught). So I want to specify the caught and uncaught behaviour separately for each exception type. But it seems that how this is implemented the caught and uncaught setting cannot be specified separately for each exception type. Or am I missing something?

**Comment by testforstephen** [comment]
> So I want to specify the caught and uncaught behaviour separately for each exception type. But it seems that how this is implemented the caught and uncaught setting cannot be specified separately for each exception type.

Based on current UI limitation, you can set caught/uncaught flag for all target exception types, but not individually for each exception type.

**Comment by NickJAllen** [comment]
Do you think this limitation will be lifted some time?

**Comment by heruan** [comment]
Has this been closed for good? I used individual exception breakpoints a lot in Eclipse, would really make use of it in VS Code now.
