### ISSUE TITLE
Hover instance variables

### ISSUE THREAD

**Issue by erihanse** [Microsoft/vscode-java-debug#297]
Is there any way we can get the field popup (not sure what it's called) when we hover on instance variables? It only seems to work if the variables are prepended with `this`. 

That is also what eclipse does.

**Comment by andxu** [comment]
I will take a look what's the current behavior and how to improve/

**Comment by andxu** [comment]
The flag is enable in https://github.com/Microsoft/java-debug/pull/208, closed since the code is checked-in
