### ISSUE TITLE
cannot find class to run in multi root workspace

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode-java-debug#299]
_From @myguddy on May 14, 2018 2:4_

VSCode Version: 1.23.1
OS Version: High Sierra 10.13.4
Steps to Reproduce:

1.Create simple java and configure the launch.json
{
"type": "java",
"name": "Debug (Launch)-Main",
"request": "launch",
"cwd": "${workspaceFolder}",
"console": "internalConsole",
"stopOnEntry": false,
"mainClass": "Main",
"args": ""
},
2.run task then ok
3.create multi-root-workspace
4.add the directory(step1.)
5. run task
error come out "java.lang.ClassNotFoundException: ...."

_Copied from original issue: redhat-developer/vscode-java#532_

**Comment by andxu** [comment]
@myguddy Thanks for using vscode java debugger, can you provide us the folder structure: by
```
cd <your project >
tree
# you can run `brew install tree` if you haven't installed tree
```
and give us the snapshot of the error popup?

**Comment by andxu** [comment]
@myguddy Do you check the Caught Exceptions while debugging:
![image](https://user-images.githubusercontent.com/17075863/41573650-4fd6e7b6-73b0-11e8-9412-e8f6f0c4fd32.png)

**Comment by andxu** [comment]
@myguddy Any update on this issue?
