### ISSUE TITLE
Step over hit on the comment

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-java-debug#30]
I'm using remote debug mode.

Screenshot:
<img width="1440" alt="screen shot 2017-09-21 at 11 21 49 am" src="https://user-images.githubusercontent.com/6193897/30677582-1b88b6ae-9ebf-11e7-8b34-1da0f9ca68ad.png">

**Comment by testforstephen** [comment]
cannot reproduce this, needs more info.

**Comment by jdneo** [comment]
Guessing this is because the target program to be debugged has its own JDK runtime. In this case, it is IntelliJ 2017 with JDK 1.8.152.

While the VS Code Java debugger will use the system's JDK. In this case, it is JdK 1.8.131.

**Comment by akaroml** [comment]
@testforstephen any updates?

**Comment by testforstephen** [comment]
Show a warning message to tell user the remote debuggee jvm version is different with jvm installed the working PC.

**Comment by testforstephen** [comment]
The fix is to show a warning message when the debugger and the debuggee are running in the different versions of JVMs.
