### ISSUE TITLE
Not hit breakpoint using mvnDebug spring-boot:run

### ISSUE THREAD

**Issue by qslcna** [Microsoft/vscode-java-debug#300]
##### Environment
- Operating System:win7
- JDK version:1.8
- Visual Studio Code version:1.23.1
- Java extension version:0.3.0
- Java Debugger extension version:0.9.0

##### Steps To Reproduce
1. [step 1]input `mvnDebug clean  spring-boot:run`

cmd shows:
>Preparing to Execute Maven in Debug Mode
>Listening for transport dt_socket at address: 8000

2. [step 2] add a breakpoint to somewhere in a controller.

3. [step 3] F5,using this configration
```
{
            "type": "java",
            "name": "Debug (Attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": 8000
}
```

4. [step 4] access the controller in browser `http://localhost:8080/fooControler/getList`

##### Current Result
skip the breakpoint 
##### Expected Result
pause on breakpoint

**Comment by qslcna** [comment]
sorry,it's not vscode-java-debug issue.
The right comand is `mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000"`

**Comment by andxu** [comment]
@qslcna if you are running at java 8+, it should be `-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=8000`, your command line args seems outdated.
