### ISSUE TITLE
how to debug spring mvc using tomcat7-maven-plugin

### ISSUE THREAD

**Issue by quaider** [Microsoft/vscode-java-debug#303]
[provide a description of the issue]

##### Environment
- Operating System: Windows 10
- JDK version: 1.8
- Visual Studio Code version: 1.24.0-insider
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. [step 1]
**part of pom.xml**
```xml
<plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <configuration>
            <source>1.8</source>
            <target>1.8</target>
          </configuration>
        </plugin>

        <plugin>  
          <groupId>org.apache.tomcat.maven</groupId>
          <artifactId>tomcat7-maven-plugin</artifactId>
          <version>2.2</version>
          <configuration>
            <port>18080</port>
            <path>/</path>
            <!-- 远程tomcat下manager路径 -->
            <!-- <url>http://localhost:18080/manager/html</url>       -->
            <server>tomcat8</server>    
          </configuration>                  
        </plugin>

      </plugins>
```
**and my tasks.json**
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "run on server",
      "type": "shell",
      "command": "mvn tomcat7:run",
      "group": "test"
    },
    {
      "label": "mvnDebug1",
      "type": "shell",
      "command": "set MAVEN_OPTS='-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=18080';mvn tomcat7:run",
      //"command": "mvnDebug tomcat7:run",
      "group": "test"
  }
  ]
}
```
then **launch.json**
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "java",
      "name": "Debug (Attach)",
      "request": "attach",
      "hostName": "localhost",
      "port": 18080,
      "timeout": 10000,
      "sourcePaths": [
        "${workspaceRoot}"
      ],
      "preLaunchTask": "mvnDebug1"
    }
  ]
}
```
2. [step 2]

run Debug in vs code, the server running and i can get result from `http://localhost:18080`, but debug can not work.

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
debug doest not work
##### Expected Result

when i request `http://localhost:18080`, i can debug my code

**Comment by testforstephen** [comment]
@quaider It looks like duplicated with this issue https://github.com/Microsoft/vscode-java-debug/issues/120.  The `mvn` command never returns an exit code so that the Debugger doesn't get a chance to connect to it.

**Comment by SummerSun** [comment]
@quaider 

```"command": "set MAVEN_OPTS='-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=18080';mvn tomcat7:run",```

Command mvn tomcat7:run does not start the debug mode.

**Comment by andxu** [comment]
@quaider can you take a try on SummerSun's comments?

**Comment by testforstephen** [comment]
See the demo about how to debug spring mvc using tomcat7-maven-plugin.
https://github.com/microsoft/vscode-java-debug/blob/master/Configuration.md#attach-to-embedded-maven-tomcat-server
