### ISSUE TITLE
Debugger slow when watching variables

### ISSUE THREAD

**Issue by erihanse** [Microsoft/vscode-java-debug#305]
Issue Type: <b>Bug</b>

If I add any entry to the watch panel, and the entry is shown, the debugger lags. It only happens if the variable being watched is shown, if I collaps the watch list or close the debug view, it behaves as normal. 

I tried to create a new project to see if I could reproduce it there, but with no success. Also tried to copy the project to somewhere else and debug from there, but the same behaviour occurs. Not sure what is going on behind the scenes, since I can watch the same variable as a local variable, still a simple assignment with no function call will execute with random delay. 

Extension version: 0.9.0
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (8.25GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details>

Stepping through this code is "laggy" while watching the variable `i`: 
```
public class Jalla {
    public static void main(String[] args) {
        int i = 0;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
    }
}
```

But by collapsing the watch list makes the UI responsive again. It only happens if I try to step too fast (if I wait a few seconds after a step before doing another step, it happens instantaniously), like the UI is waiting for something.

**Comment by andxu** [comment]
Hi @erihanse , Thank you for using vscode java debug, in vscode, if you collapse the watch list, the evaluation will not be executed, so the performance is better and the performance downgrade is not that much in your example, on the other side ,the variable in watch table and evaluation panel is different because we have no knowledge about your variable is simple enough to avoid the complex evaluation step:
1. compile your evaluation text to bytecode
2. execute the byte code

**Comment by sixlettervariables** [comment]
Performance is pretty terrible debugging with any watches. Both on an i5 desktop and a 2009 MacBook Pro. JDK 8 on the Desktop and JDK 10 on the MacBook Pro. The repositories in question are https://github.com/MegaMek/megamek and https://github.com/MegaMek/mekhq.

**Comment by yaohaizh** [comment]
@andxu Please help investigate this issue ASAP.

**Comment by andxu** [comment]
@sixlettervariables, thank you for using vscode java debugger, can you help me to address the question clearer:
1. which mode are you using? launch or attach 
2. how many expressions are you watching and can you give some examples of them
3. on which line of break you met the perf issue?

**Comment by sixlettervariables** [comment]
1. Launch.
2. 0, 1, or 2. Rarely more given the performance.
3. Doesn't really matter what line.

Steps with MekHQ:
- `ant jar`
- `Launch with Debugging`
- Place a breakpoint somewhere in the code (or a few)
- Test some bug report and step around the code.

Sometimes even pressing continue while on a breakpoint takes multiple clicks to register.

**Comment by andxu** [comment]
After removing the source container in hard-coded way, the step experience was too much improved:
![test](https://user-images.githubusercontent.com/17075863/44021916-9c21add4-9f18-11e8-9b10-4c7658447742.gif)

**Comment by andxu** [comment]
@sixlettervariables We will use your project as a perf benchmark base, and the fix will be available at 0.12.0 due to August 21, you can early try it using my personal build: https://github.com/andxu/mekhq/blob/master/vscode-java-debug-0.11.0%20(private).vsix( wish you known how to install vsix in vscode)

**Comment by sixlettervariables** [comment]
@andxu I appreciate the work on this! I will pull the build sometime this week and try it out. Thank you.

**Comment by andxu** [comment]
The code is ready on master branch
