### ISSUE TITLE
debugger broke in latest vscode update

### ISSUE THREAD

**Issue by clankill3r** [Microsoft/vscode-java-debug#308]
Today I had in a project that I could not run it anymore.
I was getting a ClassNotFoundException.
Since it was only one file and I wanted to get work done I copied the file to another project that still worked. Now later today (while working on a totally unrelated java file) I also get a ClassNotFoundException.

As a test I opened a third project that has always worked fine.
If I run it I get:

<img width="459" alt="screen shot 2018-06-11 at 22 25 56" src="https://user-images.githubusercontent.com/738650/41255396-af223576-6dc6-11e8-9448-a55e9e6830b6.png">

If I press 'Proceed' everything runs fine. (I guess it runs an old build then?).

All this is since today.

##### Environment
- Operating System: OSX 10.12.6
- JDK version: jdk-10 (that's where $JAVA_HOME points to, I have others installed as well)
- Visual Studio Code version: 1.24.0
- Java extension version: 0.3.0 (if you guys mean Java Extension Pack)
- Java Debugger extension version: 0.9.0

##### Steps To Reproduce
If I only knew...

##### Current Result
ClassNotFoundException

##### Expected Result
A running java program

##### Additional Informations

```json 
{
            "type": "java",
            "name": "IMGUITest",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopOnEntry": false,
            "mainClass": "com.github.imgui.IMGUITest",
            "projectName": "imgui",
            "args": ""
        },
```

It is a maven project.

**Comment by andxu** [comment]
@clankill3r Thank you for trying java debugger, could you please give us a snapshot of error shown ClassNotFoundException, based on your description, it has very high possibility to have a sync problem in project cache, could you please a try after cleaning all the files on the directory : C:\Users\<your user name>\AppData\Roaming\Code\User\workspaceStorage (in windows)

**Comment by andxu** [comment]
https://github.com/Microsoft/vscode-java-debug/issues/302

**Comment by clankill3r** [comment]
I removed all my workspace storage.

I just figured this out, I only get a ClassNotFoundException when I have Caught Exceptions on!

<img width="332" alt="screen shot 2018-06-12 at 10 38 53" src="https://user-images.githubusercontent.com/738650/41279725-8c48e556-6e2d-11e8-96f8-1d1862243e36.png">

Uncaught Exceptions don't matter, all off is also fine.

I also noticed that since yesterday, the test classes (`test/java/...`) don't compile to a class file anymore. At least not to this directory:

<img width="333" alt="screen shot 2018-06-12 at 10 39 23" src="https://user-images.githubusercontent.com/738650/41280134-7d65f6c2-6e2e-11e8-9e4a-0f4a0f9286bc.png">

Maybe this has always been the case. I never payed attention to that.
Anyway, maybe this is a problem with the `Maven for java` extension?

I have no idea, I hope the new info helps.

**Comment by andxu** [comment]
@clankill3r Integrated JVM has class loaders which will first throw ClassNotFoundException and then load the class. So if you check Caught Exceptions, you will get a lot of breaks on caught  ClassNotFoundException. Your test classes should be generated to output folder defined in .classpath(Java language server will generate this file if it is not here), please let me known  the content of your .classpath file, like: 
	<classpathentry kind="src" output="target/test-classes" path="src/test/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
      <classpathentry kind="output" path="target/classes"/>

**Comment by clankill3r** [comment]
Hi, here it is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="target/classes" path="src/main/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="target/test-classes" path="src/test/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.7">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" path="target/generated-sources/annotations">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="ignore_optional_problems" value="true"/>
			<attribute name="m2e-apt" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="target/test-classes" path="target/generated-test-sources/test-annotations">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="ignore_optional_problems" value="true"/>
			<attribute name="m2e-apt" value="true"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="output" path="target/classes"/>
</classpath>

```

**Comment by andxu** [comment]
checked `Caught Exceptions` will bring a lot of ClassNotFoundException which is by design since the class loader in JVM is try to catch ClassNotFoundException to determine whether a class is loaded or not, your build problem should be related to the java language server at https://github.com/redhat-developer/vscode-java/issues.  The output folder for 'src/test/java' is `target/test-classes`, you should look for .class files here.

**Comment by clankill3r** [comment]
They are there.
Just to make sure where on the same page, So it is correct that I get a ClassNotFoundException when Caught Exceptions is on although the class in `target/test-classes` does exist?

**Comment by andxu** [comment]
yes, ClassNotFoundException is expected although the class is here.
