### ISSUE TITLE
Visual Code can't debug java in the new version why ?

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode-java-debug#309]
_From @YousefSaber on November 18, 2017 4:39_

_From @YousefSaber on November 17, 2017 19:16_

![4](https://user-images.githubusercontent.com/33742499/32964649-923c5dba-cbdc-11e7-8f86-db04e9b50a4d.jpg)

![2](https://user-images.githubusercontent.com/33742499/32964555-5063679e-cbdc-11e7-85c3-48c67f303109.jpg)
![3](https://user-images.githubusercontent.com/33742499/32964557-5087c5c6-cbdc-11e7-956a-4215445042b4.jpg)
![4](https://user-images.githubusercontent.com/33742499/32964558-50aeb6ae-cbdc-11e7-894d-9f448e4b1ac4.jpg)
how can I debug java source code in the new version of VS Code ??

_Copied from original issue: Microsoft/vscode#38648_

_Copied from original issue: Microsoft/vscode-java-pack#11_

**Comment by yaohaizh** [comment]
_From @YousefSaber on November 18, 2017 4:39_

_From @weinand on November 17, 2017 19:24_

Please file issue against Java extension.

You can use this tool to move the issue: https://github-issue-mover.appspot.com

**Comment by yaohaizh** [comment]
_From @andxu on March 7, 2018 4:29_

@YousefSaber Could you provide the extension version you used to use?

![image](https://user-images.githubusercontent.com/17075863/37073647-21557d20-2203-11e8-9cd9-d184aae04099.png)

and the command result of `where java`,  `echo %JAVA_HOME%` and `echo %PATH%` to us:

C:\Users\andxu>where java
C:\Program Files\Java\jdk1.8.0_161\bin\java.exe

C:\Users\andxu>echo %JAVA_HOME%
C:\Program Files\Java\jdk1.8.0_161

C:\Users\andxu>echo %PATH%
...

**Comment by YousefSaber** [comment]
@andxu @yaohaizh 

yeah everything works fine now in the first VS Code couldn't accept user input and that was solved when debugging the code in external terminal( or integrated terminal )  as shown in screenshots 

![untitled](https://user-images.githubusercontent.com/33742499/41422998-83f95ec0-6ffa-11e8-8fc0-ae98422ff237.jpg)

after this problem I VS Code couldn't debug any java could but that was fixed later on 

![image](https://user-images.githubusercontent.com/33742499/41423053-a54601aa-6ffa-11e8-9c01-c4348e9193c1.png)

now everything works just fine 

![second](https://user-images.githubusercontent.com/33742499/41423089-b23a9236-6ffa-11e8-8b88-fa7108777866.jpg)

**Comment by yaohaizh** [comment]
Close this as the issue is fixed.
