### ISSUE TITLE
[Remote Debug]Step into doesn't act as expect

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-java-debug#31]
When the debugger hit the breakpoint as follows:
<img width="592" alt="screen shot 2017-09-21 at 11 29 40 am" src="https://user-images.githubusercontent.com/6193897/30677795-7500e944-9ec0-11e7-977e-24184f320dec.png">

Then I click step into:
the debugger doesn't step into the method: ```initFormContents()```, but goes into somewhere else:
<img width="736" alt="screen shot 2017-09-21 at 11 33 00 am" src="https://user-images.githubusercontent.com/6193897/30677815-a52c4ab4-9ec0-11e7-91ad-67af57efa793.png">

edit:
I tried to use IntelliJ to debug and click step into, the debugger goes into:
<img width="1403" alt="screen shot 2017-09-21 at 11 50 55 am" src="https://user-images.githubusercontent.com/6193897/30678222-4b6384c2-9ec3-11e7-8f92-32198ba929bc.png">

**Comment by andxu** [comment]
It is because IntelliJ add generated method $$$setupUI$$$ at runtime:

![image](https://user-images.githubusercontent.com/17075863/31331402-bd217f1a-ad14-11e7-941c-3b26d5bacd73.png)

**Comment by andxu** [comment]
Close because the debugger behavior is reasonable.
