### ISSUE TITLE
Debug/Run current active file

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode-java-debug#313]
When I opened a Java file, I want to debug/run current select file immediate.

**Comment by andxu** [comment]
The PR is abandoned at https://github.com/Microsoft/vscode-java-debug/pull/287

**Comment by Eskibear** [comment]
PR #329  fixes the "immediate" problem for single file debugging.
To directly debug a java file within a project, I suggest to trigger by a command instead of <F5>. Because when <F5> pressed, you never know whether the user is going to debug the whole project or the active file.

**Comment by andxu** [comment]
There are multiple choices:
1.  Use codelen to run 
1.  Use F5, and the active file will on the top of the list.
