### ISSUE TITLE
Should not start debug when build is not done or is failed

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#32]

**Comment by akaroml** [comment]
@ansyral any updates?

**Comment by ansyral** [comment]
this depends on [building workspace command](https://github.com/eclipse/eclipse.jdt.ls/pull/326)

**Comment by ansyral** [comment]
delivered but waiting for language server's next release because of https://github.com/redhat-developer/vscode-java/pull/357
