### ISSUE TITLE
Breakpoint hit two times on spring boot

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#324]
using the project attached, set a breakpoint at GreetingController.java#return new Greeting ...
F5 and  visit http://localhost:5000/greeting?name=a, you need to continue two times to get rid of the stopped breakpoints.

[mywebapi.zip](https://github.com/Microsoft/vscode-java-debug/files/2139754/mywebapi.zip)

**Comment by andxu** [comment]
external since eclipse has this bug too.

**Comment by yaohaizh** [comment]
@andxu, if this is an eclipse issue, could fire a issue targeting eclipse, you can related information from here: https://github.com/eclipse/eclipse.jdt.debug, and link to there.
