### ISSUE TITLE
when debug test case that vmargs  doesn't come into effect

### ISSUE THREAD

**Issue by tangboming** [Microsoft/vscode-java-debug#325]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by tangboming** [comment]
{
            "type": "java",
            "name": "Debug (Launch)",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "mainClass": "",
            "stopOnEntry": false,
            "vmArgs": "-Dtest.profiles.active=staging",
            "env": {
              "test_env":"true"
            },
            
        },

**Comment by testforstephen** [comment]
From your words, we cannot be sure where the problem happens. Can you launch your test case in terminal with the same launch options? The launch command likes `java -Dtest.profiles.active=staging -cp <your class path> mainClass`.
