### ISSUE TITLE
Running Java via launch config is Enhancing my logger with Mokito 

### ISSUE THREAD

**Issue by iamlothian** [Microsoft/vscode-java-debug#326]
The configuration of my logging classes seems to be affected by running the application via vscode launch configuration.

I as asking here as my assumption is vscode java debug might be wrapping application logging so that it can capture output and forward it to the nominated console

##### Environment
- Operating System: macOS High Sierra 10.13.5 (17F77)
- JDK version: Java(TM) SE Runtime Environment (build 1.8.0_171-b11) Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)- Visual Studio Code version:
- Java extension version: 0.3.0
- Java Debugger extension version: 0.10.0

##### Steps To Reproduce
The Spring Boot project that I am working on has a logger that extends SL4J to add some extra formatting features.

If I run the jar via the command line with -jar it all runs fine, and i can even attach the debugger to it.
If i run the application via the launch config then get a cast exception on startup

> com.xxx.logging.XLogger$$EnhancerByMockitoWithCGLIB$$a7cd3f10 cannot be cast to com.xxx.logging.XLoggerImpl

`XLoggerImpl` extends `XLogger` and is configured and returned by a bean
```
@Bean
public XLogger xLogger(
	LoggingProperties loggingProperties,
	RequestBasedExecutionContextHolder requestBasedExecutionContextHolder
) {
	return new XLoggerImpl(loggingProperties, requestBasedExecutionContextHolder);
}
```

```
@Autowired
public void setXLogger(XLogger xLogger) {
	this.xLogger = (XLoggerImpl)xLogger;
}

```

##### Current Result
> com.xxx.logging.XLogger$$EnhancerByMockitoWithCGLIB$$a7cd3f10 cannot be cast to com.xxx.logging.XLoggerImpl

##### Expected Result
No cast exception

**Comment by andxu** [comment]
Could you start the launch mode again with the console option "externalTerminal", like
![image](https://user-images.githubusercontent.com/17075863/42252284-7aa446cc-7f6e-11e8-8993-31193411dcd1.png)
and copy the command line shown at the terminal, remove the debug options like: -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:????
and try to launch it in the terminal(system terminal not vscode) and check whether the "cannot be cast to" is gone?


![image](https://user-images.githubusercontent.com/17075863/42252299-899145fe-7f6e-11e8-81f9-d9942911a784.png)

![image](https://user-images.githubusercontent.com/17075863/42252341-b7db202e-7f6e-11e8-988d-845ea12ee3f7.png)

**Comment by iamlothian** [comment]
I have tried with all console types and got the same result. 
I can run the app using: `agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:1044` and connect to it using the attach config with no issues from both the internal and external terminals

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug (Launch)-RunApplication<xxx-svc>",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "console": "externalTerminal",
            "stopOnEntry": true,
            "mainClass": "com.xxx.RunApplication",
            "projectName": "xxx-svc",
            "args": "",
            "env": {
                "X_LOGGER_LEVEL":"INFO",
                "SPRING_PROFILES_ACTIVE": "local,mock-eventEmitter,local-issuers,mock-security-redis"
            }
        },
        {
            "type": "java",
            "name": "Debug (Attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": 1044,
            "projectName": "xxx-svc",
        }
    ]
}
```

**Comment by andxu** [comment]
Remove that line -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:53027 and try to launch it in system terminal.

**Comment by iamlothian** [comment]
I have had mixed results since I last commented, where it will work sometimes, and not others. Which is rather unhelpful when trying to replicate and diagnose the issue.

**Comment by andxu** [comment]
Would you mind to upload your project here, in this way I can try your project to figure out what's the problem?

**Comment by iamlothian** [comment]
That will not be possible sorry. If i find some time this weekend. Ill try
make a small project to reproduce the issue.
