### ISSUE TITLE
Debugger should allow user to specify launching cli command in launch.json

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#33]
In order to debug spring mvc projects with vscode-java-debug, user need run `mvnDebug tomcat7:run` on cmd first, then configure attach options in launch.json.
Actually debugger can integrate the launch command in launch.json. And use `launchInTerminal` feature to execute the launching command in VSCode integrated terminal automatically. Then debugger attaches to the debug port to start debugging.

**Comment by akaroml** [comment]
The original issue can be resolved by adding preLaunchTask. It would be nicer if vscode provide an event to allow cleanups. But this issue can be closed for now.
