### ISSUE TITLE
Failed to resolve classpath: xyz

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-debug#331]
In launch mode, the debugger will auto resolve the classpath based on the given `mainClass` and `projectName`, but the mechanism is often error-prone. Especially when user configure a wrong the mainClass or projectName, it will throw the errors:

- Failed to resolve classpath: Main class '.*' doesn't exist in the workspace.
- Failed to resolve classpath: The project '.*' is not a valid java project.
- Failed to resolve classpath: Main class '.*' isn't unique in the workspace, please pass in specified projectname.

It's better to add pre-validation mechanism to prompt user about the configuration error.

**Comment by cjbailey** [comment]
I get this error quite a lot.  I'm not sure if this is related but I often get errors such as this:

Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	The method transform(TransformationInput, TransformationOutput) from the type CustomFieldMapping refers to the missing type StreamTransformationException

But then if I open the missing class in the editor and hit F5 again the error seems to get resolved.

**Comment by testforstephen** [comment]
@cjbailey Migrate your comment to another bug https://github.com/Microsoft/vscode-java-debug/issues/344

**Comment by cjbailey** [comment]
Thanks.  I've deleted my comment from here.

**Comment by testforstephen** [comment]
For the error case `Failed to resolve classpath: Main class '.*' isn't unique in the workspace, please pass in specified projectname.`, one possible reason is the search engine caching stale classes. When Java debugger try to search the corresponding project for the specified fully qualified class name, it will cause multiple projects existed. To solve this problem, need keep the search engine always sync with disk files.

**Comment by testforstephen** [comment]
The feature https://github.com/Microsoft/vscode-java-debug/issues/355 covered most of cases about `fail to resolve classpath`. Keep this issue open to track the edge case.

**Comment by testforstephen** [comment]
This issue has been fixed, close it.
