### ISSUE TITLE
Logpoint cannot evaluate string array

### ISSUE THREAD

**Issue by erihanse** [Microsoft/vscode-java-debug#338]
Issue Type: <b>Info</b>

Extension version: 0.10.0
VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:51:32.889Z)
OS version: Windows_NT x64 10.0.17134

I am getting what might be some unprecise error messages when trying to evaluate a string array. What is the correct way to evaluate lets say the first element in an array? Is it possible to evaluate the whole array?

![image](https://user-images.githubusercontent.com/9251274/42660487-a8d3309e-862b-11e8-96a6-b9b81870e3be.png)

![image](https://user-images.githubusercontent.com/9251274/42660545-ccf2b72e-862b-11e8-9a5f-e87f22e359b5.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (6.51GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by testforstephen** [comment]
The underlying implementation is using `System.out.printf("%s", args)` to log the message. So the expression wrapped by `{}` need be accepted by `printf`.

To log the first element, you can use `{ args[0] }`.
To log the whole array, you can use ` { String.join(",", args)}`.

If you still want to the Logpoint feature to support the array by itself, please vote the feature. We will see if this is a demand for high frequency or not.
