### ISSUE TITLE
[Pause on exception] cannot open src file at pausing when it is too deep in the callstack 

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode-java-debug#34]
Steps:

0. Open a complicated Java project, e.g. `azure-tools-for-java`
1. Open the same project in Eclipse, add VM options 
```-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=<PortNumber>```
and `Run` it in eclipse.
2. Check `Caught Exceptions`,  set corresponding port `<PortNumber>`, attach the debugger.
3. The main threads pauses on exception, but no available src files in top callstacks. At my first sight I don't know where the exception occurred.
![image](https://user-images.githubusercontent.com/2351748/30677841-de1ccab0-9ec0-11e7-8e51-1c42ec2711b2.png)

4. Click `Load More Stack Frames`, to show more frames:
![image](https://user-images.githubusercontent.com/2351748/30677844-e50fa8ba-9ec0-11e7-8a29-7dd1d16e4e29.png)

Should it find the first available src file in stack frames, and navigate to that file?

**Comment by ansyral** [comment]
this is by design. When source file is missing for 3rd party jars, we couldn't show the source.
