### ISSUE TITLE
Failed to resolve classpath for gradle project

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#349]
The issue isn't stable repro.
##### Environment
- Operating System: Windows x64
- JDK version: JDK10.0.2
- Visual Studio Code version: Vscode 1.25.1
- Java extension version: 0.29.0
- Java Debugger extension version: 0.11.0

##### Steps To Reproduce
1. Open the Gradle project in attachment
2. press F5 to generate launch configuration
3. Press F5 choose main class: "com.ms/samples.App" 

[attach a sample project reproducing the error]
[12.gradle.zip](https://github.com/Microsoft/vscode-java-debug/files/2251972/12.gradle.zip)
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
![image](https://user-images.githubusercontent.com/22470312/43560883-17dc2c54-9647-11e8-8977-f334eff17803.png)

##### Current Result
![image](https://user-images.githubusercontent.com/22470312/43560887-1ce1a6e8-9647-11e8-92d4-ddca2f8fe86a.png)
![image](https://user-images.githubusercontent.com/22470312/43560890-1f60d72c-9647-11e8-80d2-c4a2af5a0bbb.png)
![image](https://user-images.githubusercontent.com/22470312/43560892-21e76b96-9647-11e8-9d9b-2270e549ca74.png)

**Comment by testforstephen** [comment]
Duplicated with https://github.com/Microsoft/vscode-java-debug/issues/331
