### ISSUE TITLE
Remember least recently debugged main class

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode-java-debug#350]
When I have multiple main classes in current workspace, after pressing F5 the debugger pops up a list of main class to let me choose. (sorted alphabetically)

When I need to re-launch to debug the same main class, every time I have to look for it again in the list. Is it possible to remember the LRU main class, and put it ahead of the list. It improves my experience.

**Comment by testforstephen** [comment]
Another feedback is to put the mainClass from current active file in the top of the list too.

**Comment by testforstephen** [comment]
This feature only applies to the scenario where `mainClass` and `projectName` is emtpy. (See the following config)
```
        {
            "type": "java",
            "name": "Debug (Launch)",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopOnEntry": false,
            "mainClass": "",
            "args": ""
        }
```

**Comment by testforstephen** [comment]
PR https://github.com/Microsoft/vscode-java-debug/pull/372 merged. Close it.
