### ISSUE TITLE
Cannot pass multiple arguments to the debugger

### ISSUE THREAD

**Issue by jsnikhil** [Microsoft/vscode-java-debug#352]
My mainClass has a main(String[] args) method, and I'd like to pass multiple arguments to it. In launch.json the args only takes a String value. How can I pass multiple arguments with a string value? I tried putting commas in the string hoping it will get split into multiple arguments. Tried assigning a array value instead, however with that the Debugger won't even start.

Here is my launch.json with the current string value as args - 

> 
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug (Launch)-KeyExtractor<keystore-key-extractor>",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopOnEntry": false,
            "mainClass": "KeyExtractor",
            "args": "keyfile.jks",
            "projectName": "keystore-key-extractor"
        },
        {
            "type": "java",
            "name": "Debug (Attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": "<debug port of remote debuggee>"
        }
    ]
}

##### Environment
- Operating System: macOs High Sierra
- JDK version: Jdk8
- Visual Studio Code version: 1.25.1
- Java extension version: 0.3.0
- Java Debugger extension version: 0.11.0

**Comment by testforstephen** [comment]
@jsnikhil In the `args` field, you should use **white space** as the separator for multiple arguments.

**Comment by jsnikhil** [comment]
Awesome didn't think of that. Thanks @testforstephen
