### ISSUE TITLE
attach remote process for debugging

### ISSUE THREAD

**Issue by artivilla** [Microsoft/vscode-java-debug#354]
Related to #303. I'm using my CLI to run my application using mvn:
`"mvn clean compile tomcat7:run -Djava.awt.headless=true -Dmaven.test.skip=true -DskipTests=true -Duser.timezone=GMT -Plocal-logging -Ddevelopment"`

Here are my env vars set:
```
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk//Contents/Home"
export MAVEN_OPTS="-server -Xms4G -Xmx4G -Xss1024k -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Djavax.net.ssl.trustStore=/Users/chandoka/.artifactory_cacerts -Djavax.net.ssl.trustStorePassword=changeit"
```

##### Environment
- Operating System: OSX 10.12.6
- JDK version: 1.8
- Visual Studio Code version: Version 1.25.1 (1.25.1)
- Java extension version: 0.29.0
- Java Debugger extension version: 0.11.0

Likely there is no issue, I just don't know enough about configuring java applications to figure this out and I've looked through several issues.

With my current process running, when I try to run the debugger in my launch.json:
```
        {
            "type": "java",
            "name": "backend",
            "request": "attach",
            "hostName": "localhost",
            "port": 5005
        },
```
I'm getting the following err: `There is already a debug configuration backend running.`

Expected Result:
Stop on controller breakpoints.

Current Result:
Application runs however I can't get the debugger running.

**Comment by andxu** [comment]
@artivilla Do you mean you can visit the localhost url to get the final page without hitting the breakpoint?
If so, can you paste in the maven logs from `mvn clean compile tomcat7:run -Djava.awt.headless=true -Dmaven.test.skip=true -DskipTests=true -Duser.timezone=GMT -Plocal-logging -Ddevelopment`

**Comment by artivilla** [comment]
@andxu yes, I can visit the app without hitting the breakpoints. The logs are huge but here's a link: https://gist.github.com/artivilla/eb65636e8c5b0ee5fdfe78701404673c.js.

**Comment by andxu** [comment]
@artivilla , there is a fork parameter (default true if you have dev-tools or jvmArguments ) which means you app is spawned without the effect of MAVEN_OPTS, if you wish to enable debug mode, trying the  following snippet (or use pom xml provided by @SummerSun without MAVEN_OPTS)
```
 <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                 <configuration>
                    <fork>false</fork>
                </configuration>
            </plugin>
```

**Comment by artivilla** [comment]
So I got the debugger to work but then I can't run the application itself. Also, we're using spring MVC rather than spring boot so not sure if this plugin would work. Any other settings I should try or you could point me to another config around this.

**Comment by andxu** [comment]
@artivilla You are actually debug maven itself, since you have set the fork=true, your application is started not in debug mode, so the best way I think would be
```
<plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <version>2.0.2.RELEASE</version>
        <configuration>
          <jvmArguments>
            -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005
          </jvmArguments>
        </configuration>
```

**Comment by artivilla** [comment]
So to confirm, I'm using `mvn clean compile spring-boot:run -Djava.awt.headless=true -Dmaven.test.skip=true -DskipTests=true -Duser.timezone=GMT -Plocal-logging -Ddevelopment` with the ☝️ config in my pom.xml file.
I have multiple entry files that define `public static void main(String[] args) {}` so it's giving me `Unable to find a single main class from the following candidates`. Do I specify any?

**Comment by andxu** [comment]
Yes, if only one class with main method here in your project, you needn't, if multiple main classes are there, then you will need the mainClass right at the same level with jvmArguments
![image](https://user-images.githubusercontent.com/17075863/43934946-49085634-9c84-11e8-8234-ebbcb20eb17b.png)
