### ISSUE TITLE
'Build Failed' when launching app, needs more explanation

### ISSUE THREAD

**Issue by kdvolder** [microsoft/vscode-java-debug#358]
It happens occasionally that when I (try to) launch and app by pressing F5, I am greeted with a dialog to the effect that 'Build Failed'. My project looks fine as far as I can tell. There is really no way for me to know what this 'mysterious build' is not happy about. That is a very poor user experience. At least there should be some way to see the root error from this 'build' that was silently run on my behalf, without generating any output whatsoever in any place that I can read it.

Note: having some inkling that the error probably comes from the JDT language server, and having some experience with JDT + m2e in a 'real' Eclipse, I am guessing the problem may be that m2e thinks the 'project model is out of date with the pom'. (This is a common and annoying error we often see as m2e users). Typically you can make it go away by urging m2e to force a project update.  So... what I do in vscode, is open up the pom, type some whitespace, and  save. Then JDT LS extension will offer to do just that, rebuild project models. Lo and behold... this usually fixes the problem and makes that annoying error go away next time I try to launch.

To be honest, maybe this mess, isn't the fault of the vscode-java-debug plugin (but rather something that maybe jdt.ls should handle better). However, I think it would still be a good idea to add some more information to that annoying dialog (which I presume) vscode-java-debug is popping up.

This, 'the build has failed' dialog is truly infuriating. You are telling me there was an error, but you don't bother telling me what the error actually was? Really?

**Comment by yaohaizh** [comment]
@kdvolder I have logged related issue to vscode repo. You can follow or put more information in that issue. Thanks.

**Comment by hawkerm** [comment]
I just got a build failed issue too.  I had to clear the cache, it'd be nice if the build failed option had that as an option or did that as step if there are no error class problems.

It looks like I got in this state from opening a .java file in VS Code from outside of my Java Project.

**Comment by elisetreit** [comment]
I have also been having this problem, but if I click proceed it works approximately 30% of the time.  I have cleared the workspace cache, and while it worked this first time to stop having this error, it doesn't work anymore.

**Comment by JamesBewley** [comment]
I'm just configuring VS code to run as a debugger and have an exiting ant build process that works fine.

The debugger is working find now and I have a preLaunchTask to build the ant target but I still have to see the "Build failed, do you want to continue?" and click "Proceed" before the debugger will lanuch.

What exactly is the plugin trying to do?
Can it be disabled (the follow have no effect)?
`"java.autobuild.enabled": false,
  "java.completion.enabled": false,`

**Comment by andxu** [comment]
@JamesBewley disabling auto build is exactly the same operation of disabling the build automatically menu, but before launching debug we will force a build since we don't want you to run on out-dated project, if you want to disable the whole build and use custom build in prelaunch task, there is no-way by now, we can have the option/solution in future:
![image](https://user-images.githubusercontent.com/17075863/47189307-7e157980-d36e-11e8-9dff-eaf3ea12efa5.png)

**Comment by andxu** [comment]
yes, I suggest to move on maven for the workaround.

**Comment by aleyan** [comment]
Has there been any changes on this lately?

I get "Build failed: do you want to continue?" dialog every single time I launch the debugger with "Proceed" working 100% of the time. Reiterating kdvolder:

> There is really no way for me to know what this 'mysterious build' is not happy about. That is a very poor user experience.

Not a big deal because it works, but it is really annoying not being able to find out what this build failure is about.

**Comment by TomerFi** [comment]
I had the same problem, every time I try to `run` or `debug` a java project (working with maven) I get the following message, pressing `Proceed` ignores it and everything works well.
> Build failed: do you want to continue?

Finally, [this](https://github.com/microsoft/vscode-java-debug/issues/525#issuecomment-462218795) solved it for me and I'm not getting this message anymore.

**Comment by clankill3r** [comment]
Same issue.
What is a good way to clear the cache?

**Comment by testforstephen** [comment]
Here is the improvement for this error:
1. If there are errors found in the PROBLEMS view, will open PROBLEMS view directly.
2. Provide more fix suggestions.
![image](https://user-images.githubusercontent.com/14052197/66627125-4497e700-ec2d-11e9-8681-b6b09a15ae6e.png)
3. Click `Fix..`, list three fix suggestions.
![image](https://user-images.githubusercontent.com/14052197/66627232-993b6200-ec2d-11e9-8bbc-795d22239e60.png)
