### ISSUE TITLE
[Enhancement] Add variable to watch automatically

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-java-debug#36]
When I use IntelliJ to debug, it will add variable to watch automatically:
<img width="1407" alt="screen shot 2017-09-21 at 11 53 18 am" src="https://user-images.githubusercontent.com/6193897/30678344-3585fa08-9ec4-11e7-94cd-f189fe2a331d.png">

It will be better if vsc java debugger also support this
<img width="1403" alt="screen shot 2017-09-21 at 11 54 28 am" src="https://user-images.githubusercontent.com/6193897/30678360-499db99a-9ec4-11e7-89da-ca2d73048d95.png">

**Comment by yaohaizh** [comment]
VSCode debugger can add variable to watch now from the context menu.
