### ISSUE TITLE
Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-java-debug#367]
[provide a description of the issue]

##### Environment
- Operating System:Windows
- JDK version:1.8.0_181
- Visual Studio Code version:1.26.0
- Java extension version:0.29.0
- Java Debugger extension version:0.11.0
- Build:291

##### Steps To Reproduce
1. Open a java project, e.g. 3.thread
2. Press F5 to generate launch.json file
3. Set BP on line 13
4. F5 again to start debug, verify the BP on main is hit.
5. Do some step into ,step out and step over operations
6. Stop the debug session

##### Current Result
Cannot read property 'end' of undefined
![image](https://user-images.githubusercontent.com/28860891/44087477-8ab799f2-9ff2-11e8-98f9-0ff22d4badcd.png)

Attached the project:
[3.thread.zip](https://github.com/Microsoft/vscode-java-debug/files/2286595/3.thread.zip)

**Comment by testforstephen** [comment]
@sallyur Cannot reproduce the problem in my machine. Does it stably occur in your side?

**Comment by sallyur** [comment]
It is not stable repro, but it is high frequency happened yesterday on windows.

**Comment by bsaby** [comment]
I also encountered this issue when debugging java projects on Windows / Mac, but it can't be reproduced stably.
```
- Operating System:Windows/Mac
- JDK version: 8/10
- Java extension version:0.29.0
- Java Debugger extension version:0.12.0
- VScode: 1.26.1
```

**Comment by sallyur** [comment]
Closed it, since it not repro now.

VScode version: 1.28.2
JDK 8
java debugger version: 0.15.0
