### ISSUE TITLE
report InvalidStackFrameException during evaluating on conditional breakpoint

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#369]
![aa](https://user-images.githubusercontent.com/17075863/44245116-c3e88100-a209-11e8-945f-943e4c21d734.jpg)

**Comment by testforstephen** [comment]
@andxu Look likes this issue can be stably reproduced, please have a look.

**Comment by bsaby** [comment]
Configurations:
```
OS: Windows 10
Vscode 1.27.2
JDK: 1.8.0_181
Vscode extension:

1. Language server: 0.31.0
2. Debugger for Java: private build:#103

```

Steps:

1. Open project simple-java in vscode, write the following code:
```
package com.ms.samples;

public class App
{
    public static void main( String[] args )
    {
        int i = 0;
        for (; i <= 1000; i++) {
            if (i == 1000)  {
                System.out.println( "Hello World!" );        
            }
        }
        System.out.println( "Hello World!" );
    }
}  
```

2. Set the conditional breakpoint on line 13 with condition i ==1000, F5 and wait the breakpoint to be hit

Result:
![image](https://user-images.githubusercontent.com/22470312/46120466-613fc780-c242-11e8-8780-bef907770e1c.png)


Log file: 
[log.txt](https://github.com/Microsoft/vscode-java-debug/files/2422276/log.txt)
