### ISSUE TITLE
Request type "undefined" is not supported

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-java-debug#376]
##### Environment
- Operating System: Windows and Mac
- JDK version: JDK 8
- Visual Studio Code version: 1.26.1
- Java extension version: 0.29.0
- Java Debugger extension version: 0.11.0
- Build: 297

##### Steps To Reproduce
1. Open file Main.java in folder 21.single-file
2. Press ctrl+F5 to start without debugging
##### Result
Error: Request type "undefined" is not supported. Only "launch" and "attach" are supported.

![image](https://user-images.githubusercontent.com/28860891/44569699-d0db1680-a7ad-11e8-86d1-6a336c696def.png)

**Comment by Eskibear** [comment]
fixed. Could you verify build 299?

**Comment by sallyur** [comment]
Test passed.

Vscode version: 1.26.1
Build: 299

Now the behavior is:

1. Pressing Ctrl+F5 for a single file it start without debugging  
2. Pressing Ctrl+F5 for a first-time-opened project, it will generate a launch.json file. Pressing Ctrl+F5 again it start without debugging
