### ISSUE TITLE
Still include test classes in classpaths when auto resolve maven project

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#378]
@andxu 
##### Environment
- Operating System: Windows10
- JDK version: 1.8.0_181
- Visual Studio Code version: 1.26.1
- Java extension version: 0.29.0
- Java Debugger extension version: 0.11.0 (Build#301)

##### Current Result
![image](https://user-images.githubusercontent.com/22470312/44707609-8d4b1a00-aad7-11e8-92d9-cccae13dbfee.png)

##### Expected Result
Should not include test classes in classpaths

**Comment by andxu** [comment]
https://github.com/Microsoft/java-debug/pull/219
