### ISSUE TITLE
Feature Proposal: Make vmArgs accept an array

### ISSUE THREAD

**Issue by PeterLaComb-Availity** [Microsoft/vscode-java-debug#389]
I would like to propose that vmArgs accept an Array as an alternative to the current String. Keep the string for compatibility reasons, but allow an array because some projects accept a large number of arguments that would be easier to look at if presented as an array.

**Comment by andxu** [comment]
The PR is attached, to test it, add the following properties to launch.json of test case ArgsTest(in TestPlan.md)
```
"mainClass": "ArgsTest",
"args": [" \"bar"],
"vmArgs": ["-Xms64M",  "-Xmx128M",  "-Dfoo= \\bar"]
```
Add the following statement to get the properties:
```
  String foo = (String) System.getProperties().get("foo");
  List<String> proList = Arrays.asList(args);
```
the variables should be like this:
![image](https://user-images.githubusercontent.com/17075863/45271039-3893a000-b4d6-11e8-8bef-d97b13005148.png)
