### ISSUE TITLE
development documentation about how to contribute

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#391]
The documentation should cover the topics below. It will help other developers to contribute code to the extension.
-  how to set up environment.
- requirements.
- code convention/code styles
- how to debug the extension itself
- basic concepts

**Comment by testforstephen** [comment]
A good reference about the contributing page.
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by Eskibear** [comment]
For setting up Eclipse environment for the debug, I think it's much more clear to record a video.

**Comment by testforstephen** [comment]
development documentation is here https://github.com/Microsoft/vscode-java-debug/blob/master/CONTRIBUTING.md
