### ISSUE TITLE
env config in launch debug mode is not respected.

### ISSUE THREAD

**Issue by adashen** [Microsoft/vscode-java-debug#393]
env config in launch debug mode is not respected.

##### Environment
- Operating System: windows 10
- JDK version: 1.8
- Visual Studio Code version: 1.26.1
- Java extension version: 0.29.0
- Java Debugger extension version: 0.12.0

##### Steps To Reproduce
1. Add a launch config in launch.json and env block
"env" : {
  "EdgeHubConnectionString": "aaa",
   "EdgeModuleCACertificateFile": "bbbb"
}

2. Debug the program. The env variables could not be got.

**Comment by adashen** [comment]
Thx for the quick turn around! fixed in 0.12.1

**Comment by Eskibear** [comment]
A hotfix has been released for this.
