### ISSUE TITLE
Not allowing {fileBasenameNoExtension} to be used in main class launch configuration

### ISSUE THREAD

**Issue by Derivative20** [Microsoft/vscode-java-debug#398]
When configuring the property, main class in the launch.json file, the extension prevents the predefined ${fileBasenameNoExtension} from being used. The extension keeps saying that it is not a valid class name.  This issue was not present a week prior but now is.
##### Environment
- Operating System: Mac OS Current Version
- JDK version: Current
- Visual Studio Code version: Current
- Java extension version: Current
- Java Debugger extension version: Current

##### Steps To Reproduce
1. Configure a launch.json to have the main class to be a package name then the predefined variable fileBasenameNoExtension
2. Run the program with the configuration

**Comment by andxu** [comment]
Duplicate as https://github.com/Microsoft/vscode-java-debug/issues/85

**Comment by andxu** [comment]
How to Test:
set the following configuration as launch.json:

```
 "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopOnEntry": false,
            "mainClass": "${fileBasenameNoExtension}",
            "args":  [
                "${execPath}",
                "${env:APPDATA}",
                "${fileExtname}",
                "${workspaceRootFolderName}"
            ],
```
