### ISSUE TITLE
Step over the last sentence should exit the application

### ISSUE THREAD

**Issue by andxu** [microsoft/vscode-java-debug#40]
![image](https://user-images.githubusercontent.com/17075863/30680697-ad1b3ace-9ed3-11e7-99eb-6b240c139b3a.png)
Don't step over thread.java

**Comment by akaroml** [comment]
@testforstephen any updates?

**Comment by testforstephen** [comment]
Can be implemented by step filter feature. Suggest to expose step filter options in launch.json to allow user to specify the filter list.
