### ISSUE TITLE
Debugger ignores spring boot application.yml

### ISSUE THREAD

**Issue by dungang** [Microsoft/vscode-java-debug#408]
coded from https://code.visualstudio.com/docs/java/java-spring-boot
I added the file
'src/main/resources/application.yml'
with the following :
```yml
server:
    port:8888
```
I run the debugger with the following Launch configuration:
```json
        {
            "type": "java",
            "name": "Debug (Launch)-DemoApplication<demo>",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopOnEntry": false,
            "mainClass": "com.example.demo.DemoApplication",
            "args": "",
            "projectName": "demo"
        }
```
The debugger runs with the default port 8080 and ignores the application.yml file

**Comment by bobjiang1988** [comment]
Maybe you can find a solution here #402 .

**Comment by andxu** [comment]
version 0.12.2 will solve your problem, see https://marketplace.visualstudio.com/items/vscjava.vscode-java-debug/changelog, 
btw: your yaml is illegal:
port: 8888

**Comment by jmalbarran** [comment]
I have the same issue, and currently running the 0.32.1 version of Debugger for Java
