### ISSUE TITLE
UI for configuring step filters as workspace settings

### ISSUE THREAD

**Issue by andxu** [microsoft/vscode-java-debug#412]
Eclipse has provided a special page for step filter configuration, vscode java debugger only provides a json configuration in launch.json, the values are not easy to edit(even for sophisticated java developers)
![image](https://user-images.githubusercontent.com/17075863/45206632-11f81e00-b2b8-11e8-8e68-525ff9c4af18.png)

![image](https://user-images.githubusercontent.com/17075863/45206640-191f2c00-b2b8-11e8-81c4-ca7b0e09c73a.png)

**Comment by spottedmahn** [comment]
I'd like to be able to **break** on caught or uncaught exceptions **within my package namespace** but not external dependencies.

Seems like the [nodejs debugger has this option via `skipFiles`](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome).

>VS Code Node.js debugging has a feature to avoid source code that you don't want to step through (AKA 'Just My Code'). 

Would the above request encompass this request as well or is it a separate request? 🤔

**Comment by testforstephen** [comment]
Close this issue since "Just My Code" feature has been supported by https://github.com/microsoft/vscode-java-debug/issues/628#issuecomment-659269286.

**Comment by testforstephen** [comment]
> I'd like to be able to **break** on caught or uncaught exceptions **within my package namespace** but not external dependencies.
> 
> Seems like the [nodejs debugger has this option via `skipFiles`](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome).
> 
> > VS Code Node.js debugging has a feature to avoid source code that you don't want to step through (AKA 'Just My Code').
> 
> Would the above request encompass this request as well or is it a separate request? 🤔

@spottedmahn We have provided a setting `"java.debug.settings.exceptionBreakpoint.skipClasses"` to specify the skipped exception breakpoint, this might address your requirement.

However, I also created a new issue "Allow to break on caught/uncaught exceptions by name or package namespace #1175" for this. Let's see how many people like this feature.
