### ISSUE TITLE
Cannot run from src/test anymore

### ISSUE THREAD

**Issue by clankill3r** [Microsoft/vscode-java-debug#413]
(maven project)
Since today I noticed when I try to start debugging something from the `src/test` folder I get:

`Error: Could not find or load main class com.github.whatever.Whatever`

When I move the file to the `src/main` folder it works. Before this was not the case.

It broke from one day to the other, so I guess VSCode or one of the plugins broke.
I have no clue how to tackle this problem. Any help is welcome.
 

##### Environment
- Operating System: OSX 10.12.6
- JDK version: 1.8
- Visual Studio Code version: 1.27.1
- Java extension version: 0.30.0
- Java Debugger extension version: 0.12.2

**Comment by lashchev** [comment]
Same thing here (same VSCode, Java Tools and Java Debugger versions, but under Windows) - cannot debug unit tests anymore. I cannot move all unit tests to other folder - build and other tools rely on standard maven project structure.

1. Debug session starts, but after few (2-5) steps (F10) it hangs. Pressing Shift+F5 stops debug session.
2. Cannot add some local variables and method parameters to the Watch list.
3. Mouse over doesn't show values for many variables
4. Conditional breakpoints never stop. If I set them - debug session starts and runs forever.

Language Support for Java log panel shows "Exception processing async thread queue"

**Comment by andxu** [comment]
Unit test by click Debug Test code lens should not be influenced, please go to the   https://github.com/Microsoft/vscode-java-test/issues to raise an issue if you can not  run unit test, but if you want to run the main method at test classes, it should not work by now due to my change.

**Comment by joshryanne** [comment]
glad to know there wasn't wrong with my dev pc :) tried everything(uninstalling vs code, using insider edition, uninstalling plugins etc.  manual classpath) but coudn't fix it.  eventually went to eclipse temporarily :).   so i'm happy to know what was the cause. :)

**Comment by clankill3r** [comment]
No I hope it get's fixed fast :)

**Comment by joshryanne** [comment]
i rolled back mine to 0.11.0 till it is solved :)

**Comment by lashchev** [comment]
@andxu It fails for me from both places - from Test runner and Code Lens. Actually I rarely use Test Runner to start tests, because when I develop a method/test I run/debug tests that I am working on of fixing. I use Test Runner is for big/sweep runs.

**Comment by andxu** [comment]
@lasalame I will work on this items after the release 0.13.0, can you help to give me a sample project which doesn't work for both places(attach the project folder here in this issue)?

**Comment by andxu** [comment]
https://github.com/Microsoft/java-debug/pull/232

**Comment by clankill3r** [comment]
Can other people get this to work?
I get:
`Error: Could not find or load main class hello.GreeterTest`.

**Comment by clankill3r** [comment]
@joshryanne I want to roll back as well, do you happen to know what the VSIX link is?

It such a pain to find it. The link should be close to this:

`https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/vscjava.vscode-java-debug/0.12.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage`

But we are dealing with microsoft here...
