### ISSUE TITLE
Sometimes mainClass cannot accept variables immediately

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#421]
@andxu 
##### Environment
- Operating System: Win/Mac
- JDK version: 1.8
- Visual Studio Code version: 1.27.1
- Java extension version: 0.30.0
- Java Debugger extension version: CI build#316

##### Steps To Reproduce
1. Open 1.helloworld project
2. Press F5 to generate a launch.json
3. Change main class to a variable: e.g. ${workspaceFolderBaseName}
4. Press F5

##### Current Result
In a few cases,  mainClass cannot accept variables immediately
![image](https://user-images.githubusercontent.com/22470312/45414097-36376e80-b6ad-11e8-8247-d6ca89a7c168.png)
After several launches by pressing F5, the variable can be successfully accepted
![image](https://user-images.githubusercontent.com/22470312/45414103-3899c880-b6ad-11e8-8b59-aa805d032605.png)

Repro this issue in fileExtname/env.

**Comment by andxu** [comment]
by design , there is a typo in your example, the correct one is : workspaceFolderBasename,
