### ISSUE TITLE
Cannot read property 'uri' of undefined

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-java-debug#422]
##### Environment
- Operating System: Windows and Mac
- JDK version: 1.8.0_181
- Visual Studio Code version: 1.27.1
- Java extension version: 0.30.0
- Java Debugger extension version: 0.12.2
- Build: 316

##### Steps To Reproduce
1. Open file Main.java in folder 21.single-file
2. Use code lens to run or debug the program

##### Current Result
Error in toggle developer tools:
![image](https://user-images.githubusercontent.com/28860891/45415386-22d9d280-b6b0-11e8-8069-6b74b85ad334.png)

**Comment by testforstephen** [comment]
this error is thrown by `resolveVariables` function, @andxu please have a look.
@sallyur could you share the launch.json config?

**Comment by sallyur** [comment]
Open file Main.java and click on the code lens to debug or run the project, it doesn't generate launch.json file only reports error.
