### ISSUE TITLE
Single file doesn't compile will not show any problems, and cannot debug

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#423]
![image](https://user-images.githubusercontent.com/17075863/45460027-d03efb80-b72d-11e8-9a89-d24fd1e5adaa.png)

**Comment by michael-hawker** [comment]
Is this similar to #344?

**Comment by andxu** [comment]
Use redhat-developer/vscode-java#620 to discuss the single file, close this one
