### ISSUE TITLE
Endgame 0.13.0

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#433]
# Build
- [x] 9/19 - Bump version to 0.13.0 @andxu https://github.com/Microsoft/java-debug/pull/226, https://github.com/Microsoft/vscode-java-debug/pull/434
- [x] 9/19 - Add change log for 0.13.0 - @andxu https://github.com/Microsoft/vscode-java-debug/pull/435
- [x] 9/19 - Signed RC Bits @andxu 
https://vscjavaci.cloudapp.net/job/vscode-java-debug/job/vscode-java-debug.vsix-withSign/

# Test
- [x] 9/19 - Verify the changes for 0.13.0 release. 
- [x] 9/19 - Run test plan and new features listed below - @bsaby
- [x] 9/19 - Verify new feature: Use code lens to run java program in much simpler way - @andxu  
- [x] 9/19 - Verify new feature: Make vmArgs accept an array - @yaohaizh  [There is some known issues when vmArgs has quotes and slashes]
- [x] 9/19 - Verify new feature: mainClass Should Accept varaiable - @testforstephen  
- [x] 9/19 - Verify bug fix: [Logpoint]Should not pop up error window many times in a loop - @Eskibear   
- [x] 9/19 - Verify bug fix: Update Active Editor oct icon to file instead of clock - @andxu
- [x] 9/19 - Verify bug fix: Launching the same JDK as java language server other than JRE - @andxu
- [x] 9/19 - Verify bug fix: Duplicate class path during launching - @Eskibear
- [x] 9/19 - Verify telemetry: Distinguish conditional BP/logpoint user error from system error #288- @testforstephen  

# Release
- [x] 9/19 - Add 0.13.0 tag for vscode-java-debug and java-debug - @andxu
- [x] 9/19 - Release to marketplace/Maven Nexus Central Repository/Bintray p2 repository - @andxu

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by testforstephen** [comment]
# Verify 0.13.0 on Mac

1. Open a spring-boot project/5.breakpoint/3.thread, start debugging, the step/continue/restartStackFrame feature works as normal. Except that debug buttons still has issues when switching multiple threads. Keep the issue https://github.com/Microsoft/vscode-java-debug/issues/411 open to track the multiple threads scenario. **[Partial PASS]**
2. Open a Java program, and add variables in mainClass and args in launch.json. The debugger can be started normally. **[PASS]**
3. Open 5.breakpoint project, at the for loop, add a wrong logpoint expression `{i.toString()}`, the debugger will report compilation error. And telemetry doesn't log this kind of user error. **[PASS]**

**Comment by Eskibear** [comment]
## Verification on Windows

···
Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
···

1. Start with an empty springboot project in VSCode. Add a loop with logpoints set. 
```java
		for(int a = 0; a < 1000; a++){
			System.out.print("");   <---1    {a.toString()}
			System.out.print("");   <---2    {novar}
		}
```
2. Debug the project, from the verbose log, no duplicated classpath entries. **PASSED**
3. It pop up 2 message boxes for the errors respectively. **PASSED**

**Comment by sallyur** [comment]
### Run test plan: 
Following https://github.com/Microsoft/vscode-java-debug/blob/master/TestPlan.md

**1. Configuration**

Windows | Mac
-- | --
Vscode 1.27.2 JDK 10 | Vscode1.27.2 JDK 8

**2. Open bug**: #437

**3.Test result:**

Test   case | Windows | Mac
-- | -- | --
Configurations | Vscode 1.27.2 JDK 10 | Vscode1.27.2 JDK 8
Clean   install | Pass | Pass
Uninstall | Pass | Pass
Update | Pass | Pass
HelloWorld | Pass | Pass
CallStack | Pass | Pass
Multiple   Thread | Pass | Pass
Variables | Pass | Pass
Big   stack frame | Pass | Pass
Breakpoint   and inner class | Pass | Pass
Variable   Perform Test | Pass | Pass
No debug   information test | Pass | Pass
Maven   test | Pass | Pass
Gradle   test | Pass | Pass
PetClinic | \ | Pass
TODO   application | Pass | Pass
Single   file build | Pass | Pass
Console   application | Pass | Pass
Java 9   modular application | #437 | \
Multi-root | Pass | Pass
Step   filters | Pass | Pass
Hot Code   Replace | Pass | Pass
Conditional   Breakpoints | #369 | Pass
Restart   Frame | Pass | Pass
Encoding   Test for Project under Chinese directory | Pass | Pass
Encoding   Test for text file encoding | #260 | Pass
Caught   and Uncaught exceptions test | Pass | Pass
Restart   Frame | #294 | #294
Logpoint | Pass | Pass
Start   without debugging | Pass | Pass
Environment Variables | Pass | Pass
Runtime classpath entry | Pass | Pass
Resolve Variables | Pass | Pass
Attach   evaluation | Pass | Pass

**Comment by sallyur** [comment]
### Verify new features:

Features | Win10   x64 | Mac
-- | -- | --
Configurations | Vscode 1.27.2 JDK 10 | Vscode1.27.2 JDK 8
Use code   lens to run java program in much simpler way | Pass | Pass
Make   vmArgs accept an array | Pass | Pass
mainClass   Should Accept varaiable | Pass | Pass
Put last   used main class on top | Pass | Pass
