### ISSUE TITLE
Code lens debug java 9 test case: "ConfigError: 'com.microsoft.app.mymodule/com.microsoft.app.App' is not a valid class name."

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-java-debug#437]
##### Environment
- Operating System: Windows
- JDK version: 10
- Visual Studio Code version: 1.27.2
- Java extension version: 0.31.0
- Java Debugger extension version: 0.13.0
- Build: 61

##### Steps To Reproduce
1. Open the project 19. java9 - app
2. Open App.java
3. Use code lens to debug or run the project

##### Result: report error
![image](https://user-images.githubusercontent.com/28860891/45745698-fa178700-bc33-11e8-9d5e-dcc9353d73fd.png)

**Comment by testforstephen** [comment]
Currently we use the regular expression `([$\\w]+\\.)*[$\\w]+` to validate the class name, it doesn't cover Java 9 case. This is a bug.

**Comment by testforstephen** [comment]
Java command line supports two kinds of main class format: <mainclass> and <module>[/<mainclass>]

The regular expression should support these two cases.
