### ISSUE TITLE
Debug Bar greys out after a few steps

### ISSUE THREAD

**Issue by gerardov1** [Microsoft/vscode-java-debug#442]
Issue Type: <b>Bug</b>

Open a java project (yeah, debugging on single files still doesnt work or is supported)
Set a breakpoint
Start Debug
Step In to the next line, - after a few steps the debug bar will grey out all means to step in to the code and will keep just stop and restart available. All else is still responsive, it just simple stops allowing you to step in the code

Extension version: 0.13.0
VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (6.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by testforstephen** [comment]
@gerardov1 Can you attach a sample project to help us to investigate?

**Comment by gerardov1** [comment]
The project is attached. Very simple project. I used the Mave plugin to create a quick archetype project and the code is just test code. I am using as required by the plugins the red hat java sdk.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by gerardov1** [comment]
Hi Stephen, sorry, seems the attachments did not go through as I answered via email. I tried the project again today and funnily enough it worked flawlessly. Has there been any update? I was able to consistently repro it. Anyway... Will also try the insiders version. What version are you guys flighting?

**Comment by testforstephen** [comment]
Glad to see it works for you again. We observed the issue in 0.12.0 https://github.com/Microsoft/vscode-java-debug/issues/411, so provided a fix for it in 0.13.0.  Did you reload your VS Code window ever when you retried the project?

**Comment by testforstephen** [comment]
Since it works for you, close this issue first. Feel free to reopen it if you're still bothered by the issue.
