### ISSUE TITLE
Running spring-boot process is not killed after I close VS Code.

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-java-debug#443]
When I start a spring-boot project without debugging, and close the VS Code as soon as the debug session is launched, the process will not be killed and will become an orphan.

##### Environment
- Operating System: Windows 10 Ent. x64
- JDK version:1.8.0_181 x64
- Visual Studio Code version: 1.27.2
- Java extension version: 0.31.0
- Java Debugger extension version: 0.13.0

##### Steps To Reproduce
1. Open a simple spring-boot project, which will listen to a port (e.g. 8080 by default)
2. Start it **without debugging**. 
3. [Important] Before it is completely running, close the VS Code.
4. The spring-boot process will not be killed, instead it's now an orphan process. 
5. Reopen the project in VS Code, try to start/debug it again. 

##### Current Result
Port 8080 is occupied, you are not able to start the project again. 

##### Expected Result
The previous process should be killed after VS Code exits.

##### Additional Informations

![run-issue](https://user-images.githubusercontent.com/2351748/45794076-73ac8500-bcc7-11e8-84f6-caccf364304d.gif)

**Comment by fbricon** [comment]
I got the same problem in debug mode, after reloading vscode due to changes in installed extensions. This is *very* annoying.

**Comment by testforstephen** [comment]
With VS Code 1.62, i cannot reproduce it on macOS with spring-petclinic.

@fbricon @Eskibear Does this issue still exist in your machine?

**Comment by Eskibear** [comment]
Cannot reproduce with either internalConsole or integratedTerminal. For externalTerminal, the terminal stays open but it's not a problem.
