### ISSUE TITLE
CreateProcess error=206, The filename or extension is too long ...

### ISSUE THREAD

**Issue by thiagoalvescosta** [Microsoft/vscode-java-debug#445]
My maven java project has many libraries and it generates a huge line command. How can i solve it? Is there any options to use classpath @argsFile or classpath file ?

##### Environment
- Operating System: Windows 10
- JDK version: Java 10
- Visual Studio Code version: latest 
- Java extension version: latest 
- Java Debugger extension version: latest

##### Steps To Reproduce
1. Create a project with a big pom.xml 
2. Run the project

**Comment by andxu** [comment]
Dup as https://github.com/Microsoft/vscode-java-debug/issues/110

**Comment by testforstephen** [comment]
@thiagoalvescosta Did you run the project on cmd? cmd has limitation of 8192 characters on the command line. You can change your terminal to powershell, which doesn't have the limitation.

**Comment by thiagoalvescosta** [comment]
> @thiagoalvescosta Did you run the project on cmd? cmd has limitation of 8192 characters on the command line. You can change your terminal to powershell, which doesn't have the limitation.

Open vscode from powershell and then start debug ?

**Comment by testforstephen** [comment]
Would you mind share us your project? i try to reproduce it in my machine, but no luck.

**Comment by testforstephen** [comment]
This is a Windows Create Process limitation issue. 32k chars on the total command line. Will track the future update on issue #110.

**Comment by thiagoalvescosta** [comment]
You cloud use classpath file or java 9+ @argsfile, like IntelliJ ! Without that, anyone could use vscode to debug projects with large number of maven libs

**Comment by thiagoalvescosta** [comment]
You cloud use classpath file or java 9+ @argsfile, like IntelliJ ! Without that, no one could use vscode to debug projects with large number of maven libs

**Comment by andxu** [comment]
Use https://github.com/Microsoft/vscode-java-debug/issues/110 to discuss file too long issue.

**Comment by testforstephen** [comment]
latest version 0.17.0 has fixed this issue. please let us know if you still have problems. thanks.

**Comment by thiagoalvescosta** [comment]
Excellent! I try to open again my project! Thanks
