### ISSUE TITLE
SetVariablesRequest: property 'name' is missing, null, or empty

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-java-debug#458]
##### Environment
- Operating System: Windows & Mac
- JDK version: 8/10
- Visual Studio Code version: 1.28.0
- Java extension version: 0.32.0
- Java Debugger extension version: 0.14.0
- Build: 62

##### Steps To Reproduce

1. Open test project 4.variable
2. Set BP on the last statement of VariableTest#test
3. Press F5 to generate launch.json and press F5 again to start debug and wait for BP to be hit
4. Open the debug view and right click one variable to set value

##### Result
Set value failed and pop up an error 
![image](https://user-images.githubusercontent.com/28860891/46717023-bfd06100-cc98-11e8-9260-def1b088c2cd.png)

[attach logs]
[log.txt](https://github.com/Microsoft/vscode-java-debug/files/2463399/log.txt)

**Comment by testforstephen** [comment]
Tracked in vscode https://github.com/Microsoft/vscode/issues/60444

**Comment by testforstephen** [comment]
this issue is fixed in vscode 1.28.1 patch release.
