### ISSUE TITLE
Java Language Server Error

### ISSUE THREAD

**Issue by toutiay** [microsoft/vscode-java-debug#459]
[provide a description of the issue]

##### Environment
- Operating System:win10.1803
- JDK version:
java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

javac -version
javac 1.8.0_161-1-redhat

- Visual Studio Code version:1.28.0
- Java extension version:0.4.0
- Java Debugger extension version:0.14.0

##### Steps To Reproduce
1. [step 1]
Change a normal java file name to a pure number(such as 456) and debug
2. [step 2]
Change the pure numeric java file name back to the normal file name and debug
3. [step 3]
Then all debugs will prompt this error
[Error - 12:21:24 AM] 2018-10-11 0:21:24 Error occured while building workspace. Details: 
message: The project was not built since the source file /jdt.ls-java-project/src/456.java could not be read;code: 0

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by testforstephen** [comment]
this is related with rename, assign @yaohaizh to have a look.

**Comment by testforstephen** [comment]
Could you update `Language Support for Java(TM) by Red Hat` to latest version, and try again?
