### ISSUE TITLE
Beetle emoji is not rendered on linux

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode-java-debug#461]
Beetle :beetle:  emoji used by java language server is not rendered on linux:
![image](https://user-images.githubusercontent.com/7345761/46680420-bfc95600-cbf1-11e8-822b-7e049ddb7beb.png)

`    "editor.fontFamily": "'Twitter Color Emoji', 'Fira Code','Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback', 'Noto Color Emoji'"`

Seems like there is color-emoji rendering problem on linux, kubuntu 18.04

Not sure if it's the right place, see also https://github.com/Microsoft/vscode/issues/32840

Previously opened here https://github.com/redhat-developer/vscode-java/issues/680

**Comment by yaohaizh** [comment]
@Yanpas, thanks for reporting this issue. Since this emoji is not vision friendly in some cases, @testforstephen will remove this icon in next release, only keep the run triangle.

**Comment by Yanpas** [comment]
Hmm, opened vs code today and it works...
![image](https://user-images.githubusercontent.com/7345761/47371917-59642d80-d6f1-11e8-96d2-e9143901ce46.png)

**Comment by akaroml** [comment]
Please remove the bug emoji... Looks ugly and unnecessary.

**Comment by testforstephen** [comment]
In latest 0.16.0, the emoji is removed. Close it.
