### ISSUE TITLE
[Feature]add a new option for disabling the build and use custom build in prelaunch task

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#462]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by JamesBewley** [comment]
+1

**Comment by testforstephen** [comment]
Add a new user setting `java.debug.settings.forceBuildBeforeLaunch` to control whether to build the workspace before launch/debug.
