### ISSUE TITLE
Add way to disable run and debug buttons on main function definition.

### ISSUE THREAD

**Issue by ThadHouse** [Microsoft/vscode-java-debug#464]
I have a build where if you just attempt to run the main function, it fails to start, because I have some native dependencies that need to be configured. I am providing this build to a large amount of users, and it is confusing our users, as those buttons do not work, and they throw very confusing errors. Could a property be added to disable these buttons from showing up?

**Comment by ThadHouse** [comment]
Quick question maybe @testforstephen 

Is there an estimated release cadence for this repo? I can't find one, and this bug at least for me is a blocker that would be really nice to have fixed by sometime in mid November at the latest. Is that possible?

**Comment by andxu** [comment]
We will release it tomorrow.

**Comment by andxu** [comment]
@ThadHouse 0.15.0 is released https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug
