### ISSUE TITLE
Single file build, the actual behavior is different from the expected behavior

### ISSUE THREAD

**Issue by sallyur** [microsoft/vscode-java-debug#469]
##### Environment

- JDK version: 8/10/11
- Visual Studio Code version: 1.28.2
- Java extension version: 0.33.0
- Java Debugger extension version: 0.15.0
- Build: 64

##### Steps To Reproduce

1. Open the file in folder 21.single-file.(Open folder or Open file)
2. Press F5, make sure it debugs well.
3. Update the src to introduce a compilation error. For example, change String s = "1"; to String s = 1;. Then hit F5

##### Current Result
Exception message in debug console, and no error message popped out:
![image](https://user-images.githubusercontent.com/28860891/47775363-69e85980-dd2a-11e8-8a25-7cd2a465dcde.png)

##### Expected Result
vscode pop out an error message "Build fails, do you want to proceed"

**Comment by andxu** [comment]
@sallyur  Sally Liu reports this issue again, @testforstephen  for investigation.
