### ISSUE TITLE
Support Java 9 

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode-java-debug#47]
1. Java 9 is officially out
2. The JDT.LS is WIP here: https://github.com/eclipse/eclipse.jdt.ls/pull/324/files

We need prepare the support for Java 9

**Comment by testforstephen** [comment]
TODO:
- Support set breakpoint in java 9 source file.
- Auto resolve module path from project settings.
- Support launch options in java 9. (e.g. --module-path, -m)

**Comment by testforstephen** [comment]
Implemented by PRs:
https://github.com/Microsoft/vscode-java-debug/pull/124
https://github.com/Microsoft/java-debug/pull/90
