### ISSUE TITLE
Investigate the debugger with decompiler support

### ISSUE THREAD

**Issue by yaohaizh** [microsoft/vscode-java-debug#48]
There is a PR on the JDT.LS for decompilers. This may help our debugger for binary code. We might follow with this PR: https://github.com/eclipse/eclipse.jdt.ls/pull/360

**Comment by andxu** [comment]
There is already a extension done this: https://marketplace.visualstudio.com/items?itemName=dgileadi.java-decompiler

**Comment by xiaods** [comment]
@andxu 
I want to add a breakpoint on decompile java class, the eclipse already supports this feature, I wonder the java-debug plugin also can support it. could you do me a favor?

**Comment by mozhuanzuojing** [comment]
> @andxu
> I want to add a breakpoint on decompile java class, the eclipse already supports this feature, I wonder the java-debug plugin also can support it. could you do me a favor?

install guxgn.decompilet

**Comment by xiaods** [comment]
> decompiler

you 

> guxgn.java-decompiler

where is the guxgn.java-decompiler.  thanks for your sharing

**Comment by mozhuanzuojing** [comment]
> > decompiler
> 
> you
> 
> > guxgn.java-decompiler
> 
> where is the guxgn.java-decompiler. thanks for your sharing, it is http://java-decompiler.github.io/ ?


https://marketplace.visualstudio.com/items?itemName=guxgn.java-decompiler

**Comment by xiaods** [comment]
> > > decompiler
> > 
> > 
> > you
> > > guxgn.java-decompiler
> > 
> > 
> > where is the guxgn.java-decompiler. thanks for your sharing, it is http://java-decompiler.github.io/ ?
> 
> https://marketplace.visualstudio.com/items?itemName=guxgn.java-decompiler

cool, thanks a  lot

**Comment by testforstephen** [comment]
Currently "Debugger for Java" extension doesn't support setting breakpoint in decompiled classes. The line number between the decompiled code and the actual source code may be different, it requires some extra work to correct the line mapping in order for debugging to work properly.

**Comment by xiaods** [comment]
> Currently "Debugger for Java" extension doesn't support setting breakpoint in decompiled classes. The line number between the decompiled code and the actual source code may be different, it requires some extra work to correct the line mapping in order for debugging to work properly.

https://marketplace.visualstudio.com/items?itemName=guxgn.java-decompiler&ssr=false#overview  can do it.

**Comment by qwertycody** [comment]
+1 for this - I feel like this should be part of THIS extension instead of having to install another one that piggybacks off another.

**Comment by joyouscoder0001** [comment]
Really need this. Every time when I need to debug decompiled code , I have to change my tools into idea to get a better experience.

**Comment by testforstephen** [comment]
This has been supported. redhat java extension has integrated a built-in fernflower decompiler, and the debugger will auto adjust the line mappings when it detects the decompiler is invoked during debugging.
