### ISSUE TITLE
Extension 'vscjava.vscode-java-debug' uses a document selector without scheme

### ISSUE THREAD

**Issue by yaohaizh** [microsoft/vscode-java-debug#482]
From extension host log: 

EXTHOST-LOG:::::
["Extension 'vscjava.vscode-java-debug' uses a document selector without scheme. Learn more about this: https://go.microsoft.com/fwlink/?linkid=872305"]
EXTHOST-LOG:::::
["Extension 'vscjava.vscode-java-test' uses a document selector without scheme. Learn more about this: https://go.microsoft.com/fwlink/?linkid=872305"]

**Comment by testforstephen** [comment]
Don't observe this message in latest vscode.
