### ISSUE TITLE
run junit4  read spring config file -- FileNotFoundException

### ISSUE THREAD

**Issue by lfzy** [Microsoft/vscode-java-debug#486]
To run the junit unit test, read the spring context configuration file, but  cannot ， then throw a FileNotFoundException. This program is running correctly on the idea.

![image](https://user-images.githubusercontent.com/12446762/49325648-195e5900-f581-11e8-8456-b6d2c26a5ade.png)

I tried a lot of ways to change the working directory and it didn't work

![image](https://user-images.githubusercontent.com/12446762/49325662-54608c80-f581-11e8-850d-f9aed50ddb45.png)

##### Environment
- Operating System: Mac OS 14.1
- JDK version: 1.8
- Visual Studio Code version: 1.29.1
- Java extension version: new
- Java Debugger extension version:new

**Comment by jdneo** [comment]
@lfzy You can try to `run with configuration` , which can refer to a configuration file to define the working directory.

This issue may help you: https://github.com/Microsoft/vscode-java-test/issues/143

**Comment by lfzy** [comment]
@jdneo  Sorry, I didn't find a solution in that answer.

This is my file(launch.test.json)
`
{
                "name": "eight",
                "projectName": "eight",
                "workingDirectory": "c:\\Users\\zwjlf\\IdeaProjects\\eightdragon\\eight",
                "args": [],
                "vmargs": [],
                "env": {},
                "preLaunchTask": ""
            }
`
**cwd ： this command is also useless.**

**eightdragon**  is project.It has multiple modules.eight is a module. eightdragon is workspace.
what can I do?

**Comment by lfzy** [comment]
@jdneo I want to configure eight's working directory. that's also,
` user.dir = c:\\Users\\IdeaProjects\\eightdragon\\eight`

**Comment by jdneo** [comment]
@lfzy 

A valid launch.test.json may format as following: 

```json
{
    "run": {
        "default": "eight",
        "items": [
            {
                "name": "eight",
                "projectName": "eight",
                "workingDirectory": "c:\\Users\\IdeaProjects\\eightdragon\\eight",
                "args": [],
                "vmargs": [],
                "env": {},
                "preLaunchTask": ""
            }
        ]
    },
    "debug": {
        "default": "eight",
        "items": [
            {
                "name": "eight",
                "projectName": "eight",
                "workingDirectory": "c:\\Users\\IdeaProjects\\eightdragon\\eight",
                "args": [],
                "vmargs": [],
                "env": {},
                "preLaunchTask": ""
            }
        ]
    }
}
```

You need to set the value of `default` to the name of the configuration item you want to use.

**Comment by lfzy** [comment]
@jdneo Thanks!!!   I didn't find a description of the default attribute.But it's useful. ：）

**Comment by jdneo** [comment]
@lfzy Glad to know the problem is solved.

Actually, this feature is not well designed, we will consider to improve it in the near future.

If you have other problems related with the Test Runner extension, feel free to open issues at: https://github.com/Microsoft/vscode-java-test/issues
