### ISSUE TITLE
Improve the extension load time by using webpack

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode-java-debug#492]
References: 

1.	[VS Code extension sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/webpack-sample)
2.	[Improving load times and performance of Python Extension for VS Code with WebPack](https://medium.com/@don.jayamanne/improving-performance-of-python-extension-for-vs-code-with-webpack-8e4469533f09)

**Comment by testforstephen** [comment]
close with PR #533
