### ISSUE TITLE
Cannot launch module from workspace launch config

### ISSUE THREAD

**Issue by maarek** [Microsoft/vscode-java-debug#504]
I have a multi-module project setup and instead of using the launch.json under .vscode, I have setup my launch config inside of myproject.code-workspace. 

In this configuration, I can't seem to get the debugger to run. I do not receive any errors in the console, pop-ups, or logs. Pressing the debug run for launch configuration, the debugger just quickly disappears.

Using the same config inside of launch.json, I can get the mainClass/projectName to run the debugger without a problem. 

My main project and modules have a .project, .classpath, .factorypath, etc files. The setup is standard module/src/main/java/com/example/Main.java path structure.

##### Environment
- Operating System: OSX
- JDK version: 1.8
- Visual Studio Code version: 1.29.1
- Java extension version: 0.35.0
- Java Debugger extension version: 0.15.0

##### Steps To Reproduce
1. Create a multi-module Java/Maven project with a parent pom and modules. 
2. Define "launch" : {} inside of the .code-workspace file.
3. Debug/Launch Main Class in a specific module.

##### Additional Informations
myproject.code-workspace
```
{
  "folders": [
    {
      "name": "MyProject Parent",
      "path": "."
    },
    {
      // MyProject Service
      "name": "MyProject Service",
      "path": "myproject-service"
    }
  ],
  "settings": {},
  "launch": {
    "configurations": [
      {
        "type": "java",
        "name": "Debug MyProjectService",
        "request": "launch",
        "cwd": "${workspaceFolder}/myproject-service",
        "console": "internalConsole",
        "stopOnEntry": false,
        "mainClass": "com.example.service.MyService",
        "args": "",
        "projectName": "com.example.service"
      }
    ]
  }
  "extensions": {
    "recommendations": [
      "redhat.java",
      "vscjava.vscode-java-debug",
      "vscjava.vscode-java-test",
      "vscjava.vscode-maven",
      "vscjava.vscode-java-pack"
    ]
  }
}
```

**Comment by testforstephen** [comment]
@maarek 
See the vscode doc https://code.visualstudio.com/updates/v1_20#_improved-debugging-support-for-multi-root-workspaces.  In your myproject.code-workspace file, there are multiple roots. And you should change the config `"cwd": "${workspaceFolder}/myproject-service"` to `"cwd": "${workspaceFolder:myproject-service}"`
