### ISSUE TITLE
Chinese language pack can't be removed completely

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-java-debug#513]
##### Environment
- Operating System: All
- JDK version: 8/11
- Visual Studio Code version: 1.29.1
- Java extension version: 0.35.0
- Java Debugger extension version: 0.16.0
- Build: 65

##### Steps To Reproduce
1. Install chinese language pack from vscode marketplace and restart vscode
2. Verify the display language switch to chinese
3. Uninstall chinese language pack and restart vscode

Result: 

The user settings about java debug also display chinese language
![image](https://user-images.githubusercontent.com/28860891/49856954-2fdf9c80-fe2c-11e8-9da6-636ddaf52dfa.png)

The hover of some variables in launch.json also display chinese language
![image](https://user-images.githubusercontent.com/28860891/49857182-dd52b000-fe2c-11e8-8f06-9ff1b4561457.png)

**Comment by testforstephen** [comment]
Can you share the locale.json file?  You can pop it via vscode command `Configure Display Language` or `配置显示语言`

**Comment by sallyur** [comment]
After uninstall chinese language pack my locale.json display as below:

```
{
    "locale": "zh-cn"
}
```

**Comment by testforstephen** [comment]
comment the `locale` field, and restart again.

**Comment by sallyur** [comment]
If I comment the `locale` filed and restart vscode, display language change to English.

**Comment by testforstephen** [comment]
This is by design
