### ISSUE TITLE
Is is possible to view only the values for non-primitive variables

### ISSUE THREAD

**Issue by manastalukdar** [Microsoft/vscode-java-debug#521]
Is is possible to view only the values for non-primitive variables while debugging?

![image](https://user-images.githubusercontent.com/2075466/50426800-2f8fca00-084c-11e9-9526-179051d6dc49.png)

For example, in the above screenshot of a HashMap, instead of all the "metadata" if we could view just the k-v data that would be great. Currently, we have to drill down to view the actual k-v data.

This seems to be true for all non-primitive variables.

**Comment by testforstephen** [comment]
By default, the debugger will show the Object physical structure directly. For some types, the Object structure is too trivial. We have plan to refine this.

There will be two steps to simplify the variable display.
- Show the logical structure for the types `<? extends java.util.Map>` and `<? extends java.util.Collection>`. This will be covered by https://github.com/Microsoft/vscode-java-debug/issues/227
- Add options to control whether to display static and final members. The debugger already exposed an user setting `showStaticVariables`, but it's enabled by default.

**Comment by testforstephen** [comment]
The debugger release 0.18.0 has enabled the logical structure view for the collection variables. 
![image](https://user-images.githubusercontent.com/14052197/56573821-7d4af200-65f4-11e9-890d-a0a71681bb23.png)

It should mitigate this issue. Feel free to reopen it if you want more discussion.
