### ISSUE TITLE
envFile option for debugger in launch mode

### ISSUE THREAD

**Issue by adashen** [microsoft/vscode-java-debug#523]
This is an enhance requirement.
When configuring the debug in launch.json for launch mode. And envFile option will be helpful instead of key in all the env variables.
envFile option has been supported in c#, python, nodejs... debuggers.

**Comment by wpcfan** [comment]
Yes, this feature is needed, we use .env for docker-compose and I hope we could reuse the file when debugging in VSCode

**Comment by Eskibear** [comment]
`.env` is commonly used for storing envs esp. for credentials. If specified in `env` instead of `envFile`, the credentials are uploaded to GitHut along with `launch.json`. That's risky and inconvenient.
