### ISSUE TITLE
add 'java.debug.settings.onBuildFailed' config

### ISSUE THREAD

**Issue by SupinePandora43** [Microsoft/vscode-java-debug#525]
i trying to port java project from classpath, to gradle.
but i always have 'Build failed, do you want to continue?', and if press 'Proceed', code normal runs!
can you add config 'java.debug.settings.onBuildFailed' ['proceed', 'abort']?

**Comment by SupinePandora43** [comment]
or may be issue is 'gradle project always say 'Build Failed', but in proceed runs normal'

**Comment by testforstephen** [comment]
@SupinePandora43 You can set the user settings `java.debug.settings.forceBuildBeforeLaunch` to `false` to disable build failed message.

**Comment by SupinePandora43** [comment]
ОК
