### ISSUE TITLE
Offline install failed

### ISSUE THREAD

**Issue by snowThinker** [Microsoft/vscode-java-debug#528]
[provide a description of the issue]

##### Environment
- Operating System: Win10
- JDK version: 1.8
- Visual Studio Code version: 1.30.2
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. code --install-extension vscjava.vscode-java-debug-0.16.0.vsix
2. read ECONNRESET

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Expected Result
success

**Comment by testforstephen** [comment]
@snowThinker Have you tried offline install with vscode ui?
![image](https://user-images.githubusercontent.com/14052197/52775273-354ea280-307a-11e9-9ef1-ffd3bac756f3.png)

**Comment by snowThinker** [comment]
I have been settle down by using synchronize ${user.home}/.vscode/extensions directory. Thank you.

**Comment by testforstephen** [comment]
thanks for the info. I will close it because you find the fix. Feel free to reopen it if you want to continue discussing it.
