### ISSUE TITLE
Debug console does not wrap properly when parameters is at line edge of screen

### ISSUE THREAD

**Issue by bkbonner** [microsoft/vscode-java-debug#529]
[provide a description of the issue]

##### Environment
- Operating System:  OSX
- JDK version:  1.8
- Visual Studio Code version:  1.3.1
- Java extension version:   0.38.0
- Java Debugger extension version:  0.16.0

1.  Size the debug window so the package breaks right at the parameter.

The parameter gets truncated on the screen

If the edge of the screen occurs in a package or classname, then it wraps properly.  
##### Current Result
See attached image:  console_with_parameters_at_edge.

screenshot w/o wrapping.  stack trace is truncated on parameter names

##### Expected Result
See attached image:  console_with_package_or_classname_at_edge.

screenshot w/ wrapping.   I'd expect the other result to look something like this.

##### Additional Informations
It would also be desirable if there was a flag in settings to not wordwrap the stack trace....and if this happens to show a horizontal scroll in the debug console.
![console_with_parameters_at_edge](https://user-images.githubusercontent.com/667769/52417843-bde9a380-2aba-11e9-9b70-e2fe7ddbbcd2.png)
![console_with_package_or_classname_at edge](https://user-images.githubusercontent.com/667769/52417862-cb069280-2aba-11e9-9e82-73ba0c7693f0.png)

**Comment by yaohaizh** [comment]
@testforstephen Is there any user setting to configure the word wrap for the debug output console?

**Comment by testforstephen** [comment]
VS Code doesn't provide the work wrap settings for DEBUG CONSOLE view.

**Comment by testforstephen** [comment]
Now VS Code has a setting for this `debug.console.wordWrap`.
