### ISSUE TITLE
Adopt extension for no reload on install

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-java-debug#531]
Hi, I am a developer from VS Code and in the last release `1.31`, we added a new feature - no reload is required on installing an extension - https://code.visualstudio.com/updates/v1_31#_no-reload-on-install

But there are some exceptions to it as mentioned in the doc. If the extension is contributing to external contribution points, then the extension requires reload after installing. Hence, we added a new listener API for the owners of the external contribution point to listen to extension addition/removal and can update its state - https://code.visualstudio.com/updates/v1_31#_extensions-change-event.

Our plan is to give extensions one milestone/month for adopting to the above API and make the other extensions consuming their contribution points ready for no reload. It means that from next release, above exception will be removed and all extensions are added to VS Code window immediately after installation and no reload is shown.

We scanned the extensions in the marketplace and found out that this extension uses an external contribution point `javaExtensions` and requires reload on install.
Found out that https://github.com/redhat-developer/vscode-java extension owns this contribution point. I have already filed an issue against that extension https://github.com/redhat-developer/vscode-java/issues/794 for adoption. Filing the issue also here as this extension is impacted and can use other issue for follow up.

Thanks

**Comment by jdneo** [comment]
The issue is handled on the vscode java side. Thanks.

**Comment by testforstephen** [comment]
Currently all Java extensions use reloading to keep the state consistent, no plan to change this behavior.
