### ISSUE TITLE
Debug console does not autocomplete when a .class file is open

### ISSUE THREAD

**Issue by dmarrazzo** [Microsoft/vscode-java-debug#535]
Debugging a remote process, in the debug console, I cannot get any suggestion to inspect the code.

##### Environment
- Operating System: Fedora 29
- JDK version: openjdk version "1.8.0_201"
- Visual Studio Code version: 1.31.1
- Java extension version: 0.38
- Java Debugger extension version: 0.16

##### Steps To Reproduce
1. run a server in debug mode
2. launch the debug session

##### Current Result
Debug console: CRTL - SPACE says `no suggestions`

##### Expected Result
Autocomplete based on the current classes where the debugger paused.

**Comment by testforstephen** [comment]
@yaohaizh could you have a look?

**Comment by dmarrazzo** [comment]
I found that this problem is related to file .class.
In other words, when the source file is opened (because vscode is able to retrieve the sources), but the file is read-only. I think that this limit the debug console suggestion capability.

**Comment by dmarrazzo** [comment]
Hi @yaohaizh ,

this problem that I have noticed in attached mode is really simple to reproduce.
Write a simple code that use an opensource library like apache commons.
Step into the library code, it will open the *.class file (showing the source code).
In this situation the debug console is not able to provide suggestions.

If you need I can provide a reproducer project and a video.

Thank you

**Comment by yaohaizh** [comment]
https://github.com/Microsoft/java-debug/pull/261

**Comment by testforstephen** [comment]
PR merged, will release in 0.18.0.
