### ISSUE TITLE
Debug not work with this situtional

### ISSUE THREAD

**Issue by thanh125643** [Microsoft/vscode-java-debug#537]
Issue Type: <b>Bug</b>

this is my launch.json file

```
{
    "configurations": [
        {
            "type": "java",
            "name": "CodeLens (Launch) - MixedRadix",
            "request": "launch",
            "mainClass": "MixedRadix",
            "cwd": "${workspaceFolder}\\exercise1",
            "args": [
                "input.txt",
                "output.txt"
            ],
            "projectName": "StudentID1_3bfe4195"
        },
        {
            "type": "java",
            "name": "CodeLens (Launch) - Graycodes",
            "request": "launch",
            "cwd": "${workspaceFolder}\\exercise2",
            "args": [
                "input.txt",
                "output.txt"
            ],
            "mainClass": "Graycodes"
        }
    ]
}
```

the first program work fine with debug but the second is missing mainClass:"Graycodes"

but program have it

```
import java.io.*;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;
import java.util.Scanner;

public class Graycodes {
  public Writer fileOut;
  Vector<Integer> m = new Vector<>();
  public Graycodes(String output_name) {
    try {
      fileOut = new FileWriter(output_name);
    } catch (IOException e) {
      System.out.println(e);
    }
  }

  public void display(int n, int num_of_bit) {
    try {
      ArrayList<Integer> a = new ArrayList<>();
      for (int i = 0; i < num_of_bit; i++) {
        if (n % 2 == 0) {
          a.add(0);
          n /= 2;
        } else {
          a.add(1);
          n /= 2;
        }
      }
      Collections.reverse(a);
      fileOut.write(a.toString());
      fileOut.close();
    } catch (IOException e) {
      System.out.print(e);
    }
  }

  public void readFile(String input_name) {
    try {
      FileReader reader = new FileReader(input_name);
      Scanner fileIn = new Scanner(reader);
      while (fileIn.hasNextInt()) {
        int value = fileIn.nextInt();
        m.addElement(value);
      }
      fileIn.close();
    } catch (IOException e) {
    }
  }

  public static void main(String[] args) {
    String input_name = args[0];
    String output_name = args[1];
    Graycodes obj = new Graycodes(output_name);

    try {

      obj.readFile(input_name);
      obj.display(6, 3);
      // Close file
      obj.fileOut.close();
    } catch (IOException e) {
      System.out.println(e);
    }
  }
}
```

and this is my folder have all of my file
[https://imgur.com/qPO94rQ](https://imgur.com/qPO94rQ)
[https://drive.google.com/file/d/1BZr1ZODtrEVCXjdydac2K6Fq7t35JcJR/view?usp=sharing](https://drive.google.com/file/d/1BZr1ZODtrEVCXjdydac2K6Fq7t35JcJR/view?usp=sharing)

Extension version: 0.16.0
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.13GB free)|
|Process Argv|C:\Users\thanh\Desktop\StudentID1|
|Screen Reader|no|
|VM|80%|

</details>

**Comment by testforstephen** [comment]
@thanh125643 Could you show the result of vscode command `Java: List all Java source paths`
![image](https://user-images.githubusercontent.com/14052197/53311420-d0057780-38eb-11e9-91c0-1c82d17c23ab.png)

If it just lists "StudentID1\exercise1" at the result, then you need use the context menu "Add Folder to Java Source Path" to add the `exercise 2` as a source folder.
![image](https://user-images.githubusercontent.com/14052197/53311460-fa573500-38eb-11e9-8a0f-55d9a79aa163.png)

![image](https://user-images.githubusercontent.com/14052197/53311499-1e1a7b00-38ec-11e9-9ea6-a327333b253c.png)

After that, re-run vscode command `Java: List all Java source paths` to verify whether exercise 2 folder is a source folder.
![image](https://user-images.githubusercontent.com/14052197/53311633-8cf7d400-38ec-11e9-98e5-cebda2ae20be.png)

Please let me know whether the steps above fix your problem or not.

**Comment by testforstephen** [comment]
@thanh125643 this is a good suggestion. i will consider adding some tutorials about how to debug standalone files. thanks.

@hexiaokai could we add a topic in our document to specially promote how to debug standalone java files?

**Comment by hexiaokai** [comment]
We do have multiple source folder support documented https://code.visualstudio.com/docs/java/java-project#_multiple-source-folders. Maybe we should just list this in our Faq again? Any suggestion on how to make the document structure more useful for questions like this?

**Comment by testforstephen** [comment]
@hexiaokai  It's definitely necessary to link our vscode docs to the java debugger github repo to improve the discovery.

It's ok to keep the structure of our official docs in https://code.visualstudio.com/docs/java, because it's targeting to help user quickly get started with java in vscode. I'd prefer to extend java debugger's wiki page, and add more tutorials to teach how to troubleshoot issues when debugging standalone java files, maven project.
