### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by sallyur** [microsoft/vscode-java-debug#538]
##### Environment
- Operating System: All
- JDK version: 8 &11
- Visual Studio Code version: 1.31.1
- Java extension version: 0.39.0
- Java Debugger extension version: 0.16.0
- Build: 359

##### Steps To Reproduce
1.Install the build 359
2. Open one java project

##### Current Result
After the extension active, there is one error in toggle developer tools
![image](https://user-images.githubusercontent.com/28860891/53332204-b08f3e80-392d-11e9-8494-26ad2054c737.png)

##### Expected Result
There is no error in toggle developer tools.

This issue is not repro in market place version, so I think maybe it related web pack.

**Comment by testforstephen** [comment]
Duplicated with https://github.com/microsoft/vscode/issues/67534
