### ISSUE TITLE
Error: Data tree node not found

### ISSUE THREAD

**Issue by sallyur** [microsoft/vscode-java-debug#539]
##### Environment
- Operating System: Win & Mac
- JDK version: 8 &11
- Visual Studio Code version: 1.31.1
- Java extension version: 0.39.0
- Java Debugger extension version: 0.16.0
- Build: 359

##### Steps To Reproduce
1. Open one java project
2. Press F5 to generate launch.json file 

[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Error in toggle developer tools:
![image](https://user-images.githubusercontent.com/28860891/53332390-37dcb200-392e-11e9-943e-2bd97ce30454.png)
In addition， .Vscode won't automatically show up in the sidebar unless you manually refresh

**Comment by testforstephen** [comment]
Cannot reproduce. Please uninstall other extensions and only keep Java Language Server and Java Debugger. Try again.

**Comment by sallyur** [comment]
I only install Java Language Server and Java Debugger, then click F5, it can stable repro.
Attached the video
[ErrorRepro.zip](https://github.com/Microsoft/vscode-java-debug/files/2914020/ErrorRepro.zip)

**Comment by testforstephen** [comment]
do you mean you can reproduce this issue in any java project? both windows and mac?

**Comment by sallyur** [comment]
Yes, we can stable repro this issue with windows and mac when click F5 to generate launch.json.

**Comment by testforstephen** [comment]
Could you share a project that can reproduce the issue?

**Comment by testforstephen** [comment]
This is vscode bug. https://github.com/Microsoft/vscode/issues/68627

Could you try the latest vscode-insider version?

**Comment by sallyur** [comment]
I used vscode-insider 1.32.0, this issue also repro.

**Comment by testforstephen** [comment]
Didn't observe this error on vscode@1.62.3
