### ISSUE TITLE
When run the longclasspath project, sometimes the debug icon will gone

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-java-debug#540]
##### Environment
- Operating System: Win & Mac
- JDK version: 8 &11
- Visual Studio Code version: 1.31.1
- Java extension version: 0.39.0
- Java Debugger extension version: 0.16.0
- Build: 359

##### Steps To Reproduce
1. Open the project "longclasspath"
2. F5 to generate launch.json 
3. Modify the launch.json with the following combinations:
  "shortenCommandLine": ""/"auto"/"jarmanifest"/"argfile", 
  "console": ""/"internalConsole"/"integratedTerminal"/"externalTerminal"
4. Click Run  CodeLens

##### Current Result
Sometimes the debug icon as below will gone
![image](https://user-images.githubusercontent.com/28860891/53333914-33b29380-3932-11e9-922b-2f0f0af4e8bc.png)
Mac:
![image](https://user-images.githubusercontent.com/28860891/53334020-812f0080-3932-11e9-8804-791958ee49b9.png)
Windows:
![image](https://user-images.githubusercontent.com/28860891/53334084-afacdb80-3932-11e9-9e0c-b477dcf2b498.png)

**Comment by testforstephen** [comment]
In `Run` mode, if the `console` is `integratedTerminal` or `externalTerminal`, the program is started in the external shell, it's life cycle is out of control. The debug toolbar is useless in such situation, so disable it. This is by design.

**Comment by sallyur** [comment]
Now the behavior of our extension is that the debug toolbar will not disappear when running some other projects, but when running longclasspath project sometimes the debug toolbar will disappear.
I think this behavior should be consistent with all projects.

**Comment by testforstephen** [comment]
In `Run` mode, the debug toolbar auto disappear is by design. If not, please open a new bug.

**Comment by sallyur** [comment]
If the console is `internalConsole` in `Run` mode the debug toolbar never disappear, it is also by design?
