### ISSUE TITLE
In some cases, debug longclasspath project failed

### ISSUE THREAD

**Issue by sallyur** [microsoft/vscode-java-debug#541]
##### Environment
- Operating System: Win & Mac
- JDK version: 8 & 11
- Visual Studio Code version: 1.31.1
- Java extension version: 0.39.0
- Java Debugger extension version: 0.16.0

##### Steps To Reproduce
1. Open the project "longclasspath"
1. F5 to generate launch.json
1. Modify the launch.json with the following combinations:
  "shortenCommandLine": ""/"auto"/"jarmanifest"/"argfile", // argfile requires your Java version is 9 and higher.
  "console": ""/"internalConsole"/"integratedTerminal"/"externalTerminal"
1. Click debug codelens

##### Current Result
Mac:
It will failed when the combinations are “externalTerminal" + "auto" or "intergratedTerminal”+“auto"
![image](https://user-images.githubusercontent.com/28860891/53335129-922d4100-3935-11e9-84c1-ca0c51d02533.png)

Windows:
Sometimes debug also failed in windows, attached the log
[log.txt](https://github.com/Microsoft/vscode-java-debug/files/2900365/log.txt)

**Comment by testforstephen** [comment]
When launching the program in the terminal (integrated terminal or external terminal), the terminal will echo the total command line strings in the shell before executing the command. In the case of this bug, the command line strings are long, so the terminal needs more time to print the command line strings. Current timeout for launching in terminal is only 10 seconds. It's not enough for the long command line case. Needs increase the timeout.

**Comment by testforstephen** [comment]
Fixed with PR #662
