### ISSUE TITLE
Trying to transfer "use classpath of module" from intellij

### ISSUE THREAD

**Issue by tendonstrength** [microsoft/vscode-java-debug#542]
I'm trying to migrate from Intellij to vscode, and I'm having trouble setting up my launch configuration.

In my Intellij run configuration I have a setting called "use classpath of module".

I'm trying to set up a launch configuration like this in vscode, but I don't see a place for that sort of option. I see a classPath option, but conversely that doesn't map to anything in my Intellij config. 

Anybody have any experience with this?

Note that I'm in the parent directory of a project that has several different modules.

##### Environment
- Operating System: Mac OS
- JDK version: 1.8.0_181
- Visual Studio Code version: 1.31.1
- Java extension version: 0.6.0
- Java Debugger extension version: 0.16.0

**Comment by testforstephen** [comment]
@tendonstrength "use classpath of module" is mapped to "projectName" in launch.json. This option is used to specify the preferred project in which the debugger searches for classes to run the application.

**Comment by testforstephen** [comment]
@tendonstrength Does the explanation above solve your question?
