### ISSUE TITLE
Could not load source '': SourceRequest: property 'sourceReference' is missing, null, or empty.

### ISSUE THREAD

**Issue by cshung** [Microsoft/vscode-java-debug#550]
Cannot load source code during Java debugging in a certain scenario.

##### Environment
- Operating System: OSX
- JDK version: 1.8.0_201
- Visual Studio Code version: 1.30.2
- Java extension version:0.6.0
- Java Debugger extension version:0.17.0

##### Steps To Reproduce
1. Clone and build the google closure compiler at https://github.com/google/closure-compiler
2. Set a breakpoint at src/com/google/javascript/jscomp/PeepholeCollectPropertyAssignments.java
3. Build the project using maven (instruction included at the front page of the repo)
4. Debug

##### Current Result

The breakpoint hits, but then loading sour code fails with this error.
`Could not load source '': SourceRequest: property 'sourceReference' is missing, null, or empty.`

##### Expected Result

Loading source code should work.

**Comment by testforstephen** [comment]
duplicated with https://github.com/Microsoft/java-debug/issues/259
