### ISSUE TITLE
Java JDK and JRE can not be located error splash.

### ISSUE THREAD

**Issue by SirTwsted** [Microsoft/vscode-java-debug#551]
VS Code Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

Im getting this same error, even though I have Java v1.8.0.201-b09  installed.
Everytime I want to do something in Java, this stupid message comes up saying I dont have Java JDK and JRE installed when I do.  Its really annoying.
.
![Screenshot_32](https://user-images.githubusercontent.com/15247713/54483263-c1451d00-4826-11e9-8877-35642504aa7e.png)
![Screenshot_33](https://user-images.githubusercontent.com/15247713/54483265-c7d39480-4826-11e9-8994-a5790f99ae98.png)

**Comment by yaohaizh** [comment]
@SirTwsted Could you run "where java" to see whether you use the JDK instead of JRE?

**Comment by SirTwsted** [comment]
Its a bit strange because I have the 64-bit version installed and when I search for it within the OS
it says its located in C:\Program Files\Java\jdk1.8.0_202
but this says its not,  so really confused now.
.
![Screenshot_34](https://user-images.githubusercontent.com/15247713/54483643-269c0c80-482d-11e9-95fd-7c21c7757804.png)

**Comment by yaohaizh** [comment]
Yep, Orcale installs a default java runtime path on your C:\\ProgramData folder as I remember.
 
You need specify the java home value for the VSCode Java extension to work: 

Either set JAVA_HOME value in the system environment: 
![image](https://user-images.githubusercontent.com/17268517/54483746-cd1af880-4893-11e9-97b9-974e7a61b9ff.png)

Or set the value in the VSCode setting: 
```json
"java.home": "C:\\Program Files\\Java\\jdk1.8.0_202"
```

**Comment by SirTwsted** [comment]
Ya those are set, its the first place I went to when I got the error

**Comment by SirTwsted** [comment]
though im also starting to get this annoying popup notice everytime I select a java file, a bit annoying.
.
![Screenshot_36](https://user-images.githubusercontent.com/15247713/54483823-d45cea80-4830-11e9-88d0-3ddc84851e54.png)

**Comment by yaohaizh** [comment]
See this link https://github.com/redhat-developer/vscode-java/wiki/%22Classpath-is-incomplete%22-warning for the first one.  

For the second one, just click the 'Never', it will not display anymore.

**Comment by SirTwsted** [comment]
Thank you  <3

**Comment by testforstephen** [comment]
I saw this problem is solved, close the issue. Feel free to reopen it if you want more support.
