### ISSUE TITLE
Cannot find a class with a main method, looking in wrong directory, caps sensetive

### ISSUE THREAD

**Issue by richard-fairthorne** [Microsoft/vscode-java-debug#552]
VSCode cannot find main method in Java on OSX. The errors show that it has capitalized the first segment of the path:

/Users/rich/...

becomes:

/USERS/rich/...

##### Environment
- Operating System: OSX 10.14.3
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. Create a single Java file on a caps filesystem in your home directory
2. Try to debug in vscode

##### Example program
Main.java
```java
class Main {
  public static void main (String [] args) { }
}
```

##### Current Result

<img width="1327" alt="Screen Shot 2019-03-18 at 3 57 44 PM" src="https://user-images.githubusercontent.com/1225460/54559823-4f401580-4997-11e9-9999-973dd7bb50cf.png">

```
[Error - 4:02:04 p.m.] 18-Mar-2019 4:02:04 PM Error in JDT Core during AST creation
File not found: /USERS/rich/Code/misc/joverhead/Main.java.
Java Model Exception: Core Exception [code 368] File not found: /USERS/rich/Code/misc/joverhead/Main.java.
	at org.eclipse.jdt.internal.core.util.Util.getResourceContentsAsCharArray(Util.java:1209)
	at org.eclipse.jdt.internal.core.util.Util.getResourceContentsAsCharArray(Util.java:1181)

[...]
```

##### Expected Result

Program runs.

##### Additional Informations

**Comment by testforstephen** [comment]
@richard-fairthorne Do you mind sharing the whole log file for our investigation? Thanks.

Open VS Code command palette, and run command `Java: Open Java Language Server log file` to get the log file.
