### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by agumpg** [Microsoft/vscode-java-debug#554]
- Issue Type: `Performance`
- Extension Name: `vscode-java-debug`
- Extension Version: `0.17.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/agumpg/vscjava.vscode-java-debug-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by testforstephen** [comment]
Thanks for reporting the issue.

There's a chance that we observe high CPU load when multiple extensions get updated simultaneously. Currently, we are not able to fix this from our side.

Please find more details in Microsoft/vscode-java-pack#81. And I'm closing this issue now.
