### ISSUE TITLE
Adding more source for debug

### ISSUE THREAD

**Issue by yedane** [Microsoft/vscode-java-debug#557]
##### Environment
- Operating System: Win 10
- JDK version: 8
- Visual Studio Code version: 1.32.3
- Java extension version: 0.42.1
- Java Debugger extension version: 0.17.0

I'm trying to debug a local tomcat war with additional source code for dependencies. 
I declared in launch.json theses extra source directories like below, but it seems not taking in consideration in the call stack, Unknown source label is displayed. 

Launch.json 

![image](https://user-images.githubusercontent.com/8882331/55560380-664d6a00-56f0-11e9-89e8-e51f309058d3.png)

Need I more configuration ?

**Comment by yedane** [comment]
I'm using "Tomcat for java" vscode extension to launch on debug my war file. I can debug the main source folder with it but not the dependencies.

**Comment by testforstephen** [comment]
The extension "Tomcat for java" doesn't pass your launch configuration to java debugger, so `sourcePaths` config doesn't take affect. Suggest opening an issue there to support extra source directories. https://github.com/adashen/vscode-tomcat/issues

**Comment by yedane** [comment]
I solved my problem for the moment by running my local tomcat in remote. In that way I can in debugger attach external source, and it works !

**Comment by njneer** [comment]
@yedane can you be specific how you fixed the issue, I am also using the extension and when I hit a breakpoint it says Unknown Source. I've set tomcat to run with debug and can attach using the launch.json configuration but still can't find source. Any help would be appreciated.

**Comment by yedane** [comment]
I didn't solve definitively the problem, just bypassed it.
I launch my tomcat in remote with the "Tomcat for java" by specifying -Xdebug: 
https://stackoverflow.com/questions/3835612/remote-debugging-tomcat-with-eclipse

And in my launch.json, I attach my app by specifying the hostname : 127.0.0.1 and the port in the JVM options

**Comment by testforstephen** [comment]
The issue is migrated to https://github.com/adashen/vscode-tomcat/issues/247
