### ISSUE TITLE
[HCR] Action button to apply code changes to running app

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-java-debug#559]
The UX of HCR can be improved by making it explicit. With the latest update of VS Code, you can now add a button in the debug toolbar to expose this feature. And this is how Dart guys did:
![image](https://user-images.githubusercontent.com/16755094/55795846-41476580-5afb-11e9-9363-5719d2a9e3a5.png)

Please refer to this issue for more details: Microsoft/vscode#69153

**Comment by testforstephen** [comment]
Add a new debug settings `java.debug.settings.hotCodeReplace` to control how to trigger HCR. Defaults to `manual`.
-  manual - Click the toolbar to apply the changes.
![image](https://user-images.githubusercontent.com/14052197/58237044-ce2a4380-7d76-11e9-983b-61bcbf1aed43.png)
- auto - Automatically apply the changes after compilation. This is the old behavior.
- never - Never apply the changes.
