### ISSUE TITLE
Logical structure don't work with JDK 11

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-java-debug#571]
##### Environment
- Operating System: Win & Mac & Ubuntu
- JDK version: 11
- Visual Studio Code version: 1.33.1
- Java extension version: 0.42.1
- Java Debugger extension version: 0.18.0

##### Steps To Reproduce

1. - Open 28.debugfeatures project in VS Code.
2. - Open LogicalStructure.java file, and add a breakpoint at line 30.
3. - Click Debug CodeLens, check the Variable viewlet

##### Current Result
Logical structure feature doesn't work for jdk 11, it will fall back to old view:
![image](https://user-images.githubusercontent.com/28860891/56198780-31390400-606e-11e9-8aa9-3e174cfd1078.png)
![image](https://user-images.githubusercontent.com/28860891/56198878-56c60d80-606e-11e9-9360-125800d39869.png)

##### Expected Result
It should works fine like JDK 8
![image](https://user-images.githubusercontent.com/28860891/56197424-6132d800-606b-11e9-9fd4-1374a0c222cf.png)
![image](https://user-images.githubusercontent.com/28860891/56199110-d5bb4600-606e-11e9-8da7-c5da9b0a1674.png)

**Comment by testforstephen** [comment]
Java debugger is invoking the evaluation engine to get the logical structure. In JDK 11, the upstream jdt evaluation engine has a bug on parsing the compiled expression `return entrySet();` for Map class. See eclipse bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=543604

The possible fix is to discard the evaluation approach we are using, but use the pure JDI method to get the logical value instead. For example, use ObjectReference.invokeMethod() api to get the entrySet of Map class.
