### ISSUE TITLE
Debug console not scrolling to bottom

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-java-debug#572]
OSX 10.12.6
VSCode 1.33.1
Extention 0.17.0

Not sure if this is due to the extention or vscode (I tested with python in VSCode and had no problem there so it might be java).
But for me the debug console doesn't stay scrolled at the bottom after a while.
The lines keep coming in but the scrollbar stays at a certain position.
Also I get blank lines that I don't print:

<img width="111" alt="Screen Shot 2019-04-16 at 21 28 34" src="https://user-images.githubusercontent.com/738650/56238531-0317ec00-608f-11e9-9bfc-3b3cfdf0b084.png">

**Comment by testforstephen** [comment]
The blank links is a bug from vscode, it should be fixed vscode-insider nightly build.
https://github.com/Microsoft/vscode-java-debug/issues/560

**Comment by cruizba** [comment]
I have this problem too. I'm programming a Spring Boot application and when the debug console starts to show the log of the application, the output does not follow the sequence of logs. I have to scroll to the bottom all the time to see the log in real time

**Comment by synchronos-t** [comment]
I'm debugging Node on 1.37 and I have this problem as well.

**Comment by sguillia** [comment]
This may be related to https://github.com/microsoft/vscode/issues/77837

**Comment by lookipol** [comment]
> OSX 10.12.6
> VSCode 1.33.1
> Extention 0.17.0
> 
> Not sure if this is due to the extention or vscode (I tested with python in VSCode and had no problem there so it might be java).
> But for me the debug console doesn't stay scrolled at the bottom after a while.
> The lines keep coming in but the scrollbar stays at a certain position.
> Also I get blank lines that I don't print:
> 
> <img alt="Screen Shot 2019-04-16 at 21 28 34" width="111" src="https://user-images.githubusercontent.com/738650/56238531-0317ec00-608f-11e9-9bfc-3b3cfdf0b084.png">

**Comment by testforstephen** [comment]
The upstream issue microsoft/vscode#77837 has been fixed. Closing it, feel free to reopen it if the issue still exists.
