### ISSUE TITLE
program args doesn't support Chinese

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#58]
![image](https://user-images.githubusercontent.com/17075863/30845312-65dfd41c-a2c5-11e7-9172-6355b3f170e8.png)

**Comment by testforstephen** [comment]
Cannot reproduce it, @andxu What's the encoding type of your project.

**Comment by andxu** [comment]
This bug refers the problem of the encoding in the source file and the encoding in  the compiled class file and the encoding settings during run-time,  any mismatch of it will cause messy code. The eclipse ide provides full control of these encoding settings, I think we can simplify it in vscode through encoding settings in project level.

**Comment by andxu** [comment]
The encoding is utf-8 for the launch.json, the source file, there is no way of  reading Chinese arguments in java.

**Comment by yaohaizh** [comment]
@andxu, @testforstephen  I think we have fixed the encoding problems?  If cannot fix this, close it as designed.

**Comment by testforstephen** [comment]
Duplicated with bug https://github.com/Microsoft/vscode-java-debug/issues/234, see the comments there for workaround.
