### ISSUE TITLE
Terminal for output does not work with miniconda installed

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-java-debug#580]
OSX 10.12.6, jdk1.8.0_144.jdk, VSCode 1.33.1,  java extension pack 0.7.1, java debugger 0.18.0 

Since I installed miniconda, https://docs.conda.io/en/latest/miniconda.html I can no longer use the terminal for the debug output. This is for both `"console": "externalTerminal"` and `"console": "internalTerminal"`. 

This is when running the code, else everything just works fine (both internal and external terminal(s).

I tested if the issue also happens with happens with other languages, both python and javascript / nodejs work fine.

**Comment by testforstephen** [comment]
What error do you see when you say the terminal doesn't work?
