### ISSUE TITLE
External Terminal needs to be shut down before launch

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-java-debug#581]
OSX 10.12.6, jdk1.8.0_144.jdk, VSCode 1.33.1, java extension pack 0.7.1, java debugger 0.18.0

When using a external terminal, then it only works proper if I close the terminal before launch.
If I don't then 9 out of 10 times it will not work, or it will take really long before it is ready.
I notice that this is only the case with the vscode-java-debug extension, for other languages I don't have the problem.

**Comment by testforstephen** [comment]
what error do your see when it doesn't work? i'm curious why it doesn't work. The java debug extension doesn't do anything special here, just follow the debug protocol definition to pass the required launch parameters to vscode for run in terminal.

**Comment by clankill3r** [comment]
I do not have the issue anymore
