### ISSUE TITLE
Releases do not contain vsix files

### ISSUE THREAD

**Issue by ibuziuk** [microsoft/vscode-java-debug#583]
Most of the vscode extentions contain dedicated `vsix` files in the releases e.g.:

- https://github.com/redhat-developer/vscode-java/releases
- https://github.com/microsoft/vscode-go/releases
- https://github.com/microsoft/vscode-python/releases

Will it be possible to add dedicated releases to the `vscode-java-debug` - https://github.com/microsoft/vscode-java-debug/releases

**Comment by testforstephen** [comment]
vsix added to the release page.

**Comment by ibuziuk** [comment]
@testforstephen thank you!
