### ISSUE TITLE
Cannot exit external terminal when run java project on Windows

### ISSUE THREAD

**Issue by bsaby** [microsoft/vscode-java-debug#598]
##### Environment
- Operating System: windows10/Mac
- JDK version: 8+11
- Visual Studio Code version: 1.35.1
- Java extension version: 0.46.0
- Java Debugger extension version: 0.19.0(build number:390)

##### Steps To Reproduce
1. Open longclasspath project in VS Code.
2. On Windows, modify the launch.json with the following combinations. 
      - "shortenCommandLine": ""/"auto"/"jarmanifest"/"argfile",
      - "console": "externalTerminal"
3. Click Run codelens

##### Current Result
In the external cmd, you can't use Ctrl + C to exit, you can only click the "X" in the upper right corner.
![image](https://user-images.githubusercontent.com/22470312/59757932-63115580-92bf-11e9-9f66-68ff2f6e2fb0.png)

**Comment by testforstephen** [comment]
This is external terminal's behavior, no much we can do in the debugger side.
