### ISSUE TITLE
endgame 0.20.0

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-debug#604]
# Build
- [x] 07/01 - Bump version to 0.20.0 @testforstephen 
- [x] 07/01 - Add change log for 0.20.0 - @testforstephen 
- [x] 07/01 - Signed RC Bits @testforstephen 

# Test
- [x] 07/01 - Run test plan and verify new changes listed in [0.20.0 changelog](https://github.com/microsoft/vscode-java-debug/blob/master/CHANGELOG.md#0200---2019-07-01)- @bsaby @sallyur
 
# Release
- [x] 07/01 - Add 0.20.0 tag for vscode-java-debug and java-debug - @testforstephen
- [x] 07/01 - Release to marketplace/Maven Nexus Central Repository/Bintray p2 repository - @testforstephen

# Notes
Before you check an item, please reply to this issue with the following details:

What are the steps and details of your check?
What are the configurations?
What are the issues found in the process?
What's your conclusion?

**Comment by bsaby** [comment]
###  Run test plan
Following https://github.com/Microsoft/vscode-java-debug/blob/master/TestPlan.md

#### 1. Configuration

Win | Mac | Linux 
-- | -- | --
VS   Code: 1.35.1   JDK:   12.0.1 | Vscode:   1.35.1   JDK:   1.8.201 | Vscode: 1.35.1   JDK: 12.0.1

#### 2. Bug
No new issues

#### 3. Test result

Test case | Windows | Mac | Linux
-- | -- | -- | --
Clean   install | Pass | pass | pass
Uninstall | Pass | pass | pass
Update | Pass | pass | pass
Activation   time < 1000ms | Pass | pass | pass
Telemetry   data goes to application insights | Pass | pass | pass
HelloWorld | Pass | pass | pass
CallStack | Pass | pass | pass
Multiple   Thread | Pass | pass | pass
Variables | Pass | Pass | pass
Big   stack frame | Pass | pass | pass
Breakpoint   and inner class | Pass | pass | pass
Variable   Perform Test | (7-8s) | Pass(4s) | pass
No   debug information test | Pass | pass | pass
Maven   test | Pass | Pass | pass
Gradle   test | Pass | Pass | pass
PetClinic | Pass | Pass | pass
TODO   application | Failed  #74 | Failed  #74 | Failed  #74
Single   file build | pass | pass | pass
Console application | Pass | Pass | pass
Java 9 modular application | Pass | Pass | pass
Multi-root | Pass | pass | pass
Step filters | Pass | pass | pass
Hot   Code Replace | Pass | pass | pass
Conditional Breakpoints | Pass | pass | pass
Restart   Frame | Pass | pass | pass
Encoding   Test for Project under Chinese directory | pass | pass | pass
Encoding   Test for text file encoding | Pass | pass | pass
Caught   and Uncaught exceptions test | Pass | pass | pass
Restart   Frame | Pass | pass | pass
Logpoint | Pass | pass | pass
Start   without debugging | Pass | pass | pass
Environment   Variables | Pass | pass | pass
Runtime   classpath entry | Pass | Pass | pass
Resolve   Variables | Pass | Pass | pass
Attach   evaluation | Pass | Pass | Pass
Classpath   shortener for long classpath project | #598 | #541  | pass
Jump to source   code when clicking stack trace in DEBUG CONSOLE | Pass | Pass | pass
Show the logical   structure view for the Map and List variables | Pass | Pass | pass
Enable Java 12   preview for standalone Java files | Pass | pass | pass
Auto   resolve classpath for maven projects | Pass | Pass | pass

**Comment by bsaby** [comment]
### Verify new changes listed in 0.20.0 changelog
#### 1. Configuration
Win | Mac | Linux
-- | -- | --
VS Code: 1.35.1 JDK: 12.0.1 | Vscode: 1.35.1 JDK: 1.8.201 | Vscode: 1.35.1 JDK: 12.0.1

#### 2. Bug
No new bugs
#### 3. Test Result
Test case | Win | Mac  | Linux 
-- | -- | -- | --
Fix: Adding wrong jar version to the classpath. #566 | Pass | Pass | Pass
Fix: Adding wrong classpath at runtime for multi modules         maven projects. #584 | Pass | pass | Pass
Contribution         from tom-shan:         Should break earlier when destroying temporary launch file. PR#280 | Pass | pass | Pass

**Comment by testforstephen** [comment]
0.20.0 is released. close it.
