### ISSUE TITLE
Ask Microsoft to develop a Tomcat server support plug-in, Please support tomcat servers for the development environment of Spring MVC. Spring MVC in China accounts for more than 70% #379

### ISSUE THREAD

**Issue by beyond369** [microsoft/vscode-java-debug#610]
Ask Microsoft to develop a Tomcat server support plug-in, Please support tomcat servers for the development environment of Spring MVC. Spring MVC in China accounts for more than 70% #379

**Comment by testforstephen** [comment]
There is a Tomcat extension for VS Code.

Please give it a try
https://marketplace.visualstudio.com/items?itemName=adashen.vscode-tomcat
