### ISSUE TITLE
The extension doesn't work when switching versions 

### ISSUE THREAD

**Issue by bsaby** [microsoft/vscode-java-debug#615]
[provide a description of the issue]

##### Environment
- Operating System: Windows
- JDK version: 8
- Visual Studio Code version: 1.36.1
- Java extension version: 0.47.0
- Java Debugger extension version: 0.20.0

##### Steps To Reproduce
1. Install extension 0.20.0
2. Open a java project in Vscode and open a java file to activate debugger extension
3. Switch version to 0.19.0 and reload.
4. Wait for 👍 
5. Press F5

##### Current Result
1. Can't create launch.json file.
2. No codelens 

![image](https://user-images.githubusercontent.com/22470312/61614502-7c2e6d00-ac96-11e9-8be8-14d97853d039.png)

**Comment by testforstephen** [comment]
This is related with https://github.com/eclipse/eclipse.jdt.ls/issues/1146

**Comment by testforstephen** [comment]
Current workaround: Reload VS Code is able to fix it.

**Comment by russau** [comment]
Is it possible to downgrade a version to fix this?  It looks like vscode-java grabs whatever is in github when is it built: https://github.com/redhat-developer/vscode-java/blob/v0.48.0/Jenkinsfile#L22

Experimenting with this...

**Comment by testforstephen** [comment]
vscode-java-0.49.0 will be released this week, it will fix this issue.

**Comment by russau** [comment]
Great, thanks!  I did manage to fix things by reverting the version like this:

```
ver=${ver-0.46.0}
code --install-extension vscjava.vscode-java-pack --force && \
code --uninstall-extension vscjava.vscode-java-dependency && \
code --uninstall-extension vscjava.vscode-java-test && \
code --uninstall-extension vscjava.vscode-java-debug && \
code --uninstall-extension redhat.java
wget https://github.com/redhat-developer/vscode-java/releases/download/v${ver}/redhat.java-${ver}.vsix
code --install-extension redhat.java-${ver}.vsix 
code --install-extension vscjava.vscode-java-dependency && \
code --install-extension vscjava.vscode-java-test && \
code --install-extension vscjava.vscode-java-debug
```

And this configuring `"extensions.autoUpdate": false`.

**Comment by testforstephen** [comment]
vscode-java 0.49.0 has fixed this issue. close it.
