### ISSUE TITLE
Unable to print Chinese characters correctly

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/vscode-java-debug#618]
##### Environment
- Operating System: Windows10
- JDK version:1.8.0_211
- Visual Studio Code version:1.36.1
- Java extension version:0.47.0
- Java Debugger extension version:0.21.0-RC

##### Steps To Reproduce
1. Open a java project with Chinese characters.
2. Click F5 to run it.

##### Current Result
![image](https://user-images.githubusercontent.com/44559777/62194256-18015c80-b3ac-11e9-8e2a-5dcfea0f8798.png)

##### Expected Result
Result of Chinese characters.

**Comment by Eskibear** [comment]
Try enabling system-wide UTF-8  support.
![image](https://user-images.githubusercontent.com/2351748/62259647-a116a300-b441-11e9-879c-bfe77ea75082.png)

**Comment by EricZhangzf** [comment]
Fixed by check Beta: Use Unicode UTF-8 for worldwide language support.

**Comment by Eskibear** [comment]
Ideally we should not require users to modify system-wide settings. Re-open to see if we have any alternative solutions.

**Comment by Eskibear** [comment]
please keep the system-wide local unchanged, and verify the latest private build, see if the issue is gone.

**Comment by EricZhangzf** [comment]
Test pass on 0.20.0
