### ISSUE TITLE
Could not find or load main class App under Chinese characters folder

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/vscode-java-debug#619]
##### Environment
- Operating System: Windows10
- JDK version: 1.8.0_211
- Visual Studio Code version: 1.36.1
- Java extension version: 0.47.0
- Java Debugger extension version: 0.21.0-RC

##### Steps To Reproduce
1. Open a java project under Chinese characters folder.
2. Click F5 to run it.

##### Current Result
![image](https://user-images.githubusercontent.com/44559777/62194640-d58c4f80-b3ac-11e9-9ccd-6817d4105106.png)

##### Expected Result
no error.

**Comment by Eskibear** [comment]
it's because https://github.com/microsoft/vscode-java-debug/blob/ea07ad3022297f20e7c648d58423c045b00ed541/testprojects/26.environmentVariables/.vscode/launch.json#L13

Please change it to integrated terminal and retry.

**Comment by Eskibear** [comment]
Try enabling system-wide UTF-8  support.
![image](https://user-images.githubusercontent.com/2351748/62259647-a116a300-b441-11e9-879c-bfe77ea75082.png)

**Comment by EricZhangzf** [comment]
This issue still repro with check Beta: Use Unicode UTF-8 for worldwide language support box.
![image](https://user-images.githubusercontent.com/44559777/62440795-37213500-b784-11e9-88f0-98def1b547d4.png)
![image](https://user-images.githubusercontent.com/44559777/62440810-4607e780-b784-11e9-98ae-bdbc7c091c97.png)
