### ISSUE TITLE
The log should be displayed on the DEBUG CONSOLE.

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/vscode-java-debug#620]
##### Environment
- Operating System: Windows10
- JDK version: 1.8.0_211
- Visual Studio Code version: 1.36.1
- Java extension version: 0.47.0
- Java Debugger extension version: 0.21.0-RC

##### Steps To Reproduce
1. Git clone https://github.com/microsoft/vscode-java-debug.git
2. Open 26.environmentVariables in vscode
3. Press F5 to start.

##### Current Result
The log should be displayed on the DEBUG CONSOLE
![image](https://user-images.githubusercontent.com/44559777/62195035-b0e4a780-b3ad-11e9-9ce0-cd5b849b608c.png)

##### Expected Result
The log should be displayed on the TERMINAL instead of the DEBUG CONSOLE.

**Comment by Eskibear** [comment]
it's because https://github.com/microsoft/vscode-java-debug/blob/ea07ad3022297f20e7c648d58423c045b00ed541/testprojects/26.environmentVariables/.vscode/launch.json#L13

Please change it to integrated terminal and retry.

**Comment by EricZhangzf** [comment]
Fixed it by change console to integrated terminal.
