### ISSUE TITLE
"copy value" from variables debugger window not working

### ISSUE THREAD

**Issue by pelukron** [microsoft/vscode-java-debug#624]
When in debug mode I open contextual menu to Copy value from variable and this does not work.

##### Environment
- Operating System: Windows 10 (Windows_NT x64)
- JDK version: java version "1.8.0_221"
- Visual Studio Code version: 1.36.1
- Java extension version:  0.47.0 (redhat.java)
- Java Debugger extension version: 0.20.0 (vscjava.vscode-java-debug)

##### Steps To Reproduce
1.- Press F5 to start debugging session
2.- Go to VARIABLES panel and rigth click to show contextual menu on a variable
3.- select Copy Value

##### Current Result
copy value from menu is disable

##### Expected Result
copy value from menu as enable

##### Additional Informations
this ticket is related with this one
https://github.com/Microsoft/vscode-python/issues/1398

https://user-images.githubusercontent.com/38342960/38767732-4cf57758-3fe7-11e8-9c04-fdb1195fbd94.png

**Comment by testforstephen** [comment]
Cause: In the Variable Response, the value for evaluateName is not returned for top-level variables.

**Comment by youssefgh** [comment]
Workaround :
1 - Go to VARIABLES panel and right click to show contextual menu on a variable
2 - Select Set Value
3 - CTRL+C
(tested on java not JS)

**Comment by testforstephen** [comment]
Duplicated with https://github.com/microsoft/vscode-java-debug/issues/819. Now it's doable with the new VS Code capabilities.
