### ISSUE TITLE
Support step "Just My Code"

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-debug#628]
Provide a feature to only step my files from my own project, and skip the library files. It's like 'Just my code' feature in Visual Studio.

**Comment by testforstephen** [comment]
Actually VS Code Java Debugger supports filter the library code during stepping. The approach is to add `stepFilters` config in launch.json.

Below is a sample to filter the common jdk library.

        {
            "type": "java",
            "name": "CodeLens (Launch) - Main",
            "request": "launch",
            "mainClass": "client.Main",
            "projectName": "kie-client",
            "stepFilters": {
                "classNameFilters": [
                    "java.*",
                    "javax.*",
                    "com.sun.*",
                    "sun.*",
                    "sunw.*",
                    "org.omg.*"
                ],
                "skipSynthetics": false,
                "skipStaticInitializers": false,
                "skipConstructors": false
            }
        }

**Comment by testforstephen** [comment]
Currently the debugger provides launch config to support **not** stepping into classes. If the user wants to achieve "Just My Code", he/she needs list all libraries in the config manually and that would become hard to use if the dependency list is large. 

A better way is to support **Only step into classes**. But the underlying JVM implementation ([jpda](https://docs.oracle.com/en/java/javase/13/docs/api/jdk.jdi/com/sun/jdi/request/EventRequest.html) protocol) doesn't allow multiple include filters well. If you add multiple include filters, and jpda would consider it as "A and B and C", **not** "A or B or C". That means if your project source is under a same common package (e.g. org.springframework.samples.petclinic.*), that works. But if you have multiple common packages, the include filters become useless. There is already a [JDK-8039561](https://bugs.openjdk.java.net/browse/JDK-8039561?jql=text%20~%20%22step%20classFilter%20or%22) ticket there to ask supporting more than one ClassFilter well for StepRequest. 

A current workaround is to let the debugger side to handle the filter instead of the debuggee (jpda), but it probably has performance issue, because each filter event will suspend the JVM. So need more evaluation on the solution.

**Comment by testforstephen** [comment]
When you just want to step into "Just My Code", then you can 
```
    "java.debug.settings.stepping.skipClasses": [
        "$JDK", // Skip the JDK classes from the default system bootstrap classpath, such as rt.jar, jrt-fs.jar.
        "$Libraries" // Skip the classes from application libraries, such as Maven, Gradle dependencies.
       // "java.myPackage.myClasses"
    ]
```

**Comment by mKay00** [comment]
This doesn't work for me.

![image](https://user-images.githubusercontent.com/19666187/110328048-19304c00-801b-11eb-8bab-cf178418fefa.png)

My launch.json looks like this:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "java",
      "name": "Debug (Attach)",
      "projectName": "myproject",
      "request": "attach",
      "hostName": "localhost",
      "port": 5800
    },
  ]
}
```

and in my settings.json I added the following setting:
```  
"java.debug.settings.exceptionBreakpoint.skipClasses": [
    "$JDK", // Skip the JDK classes from the default system bootstrap classpath, such as rt.jar, jrt-fs.jar.
    "$Libraries", // Skip the classes from application libraries, such as Maven, Gradle dependencies.
 ],
```
