### ISSUE TITLE
Local variable values not shown

### ISSUE THREAD

**Issue by bojan96** [microsoft/vscode-java-debug#634]
Local variable value (`local`) not shown while debugging 
![Debugger](https://user-images.githubusercontent.com/22708468/63377421-647aff00-c390-11e9-93fd-0031d65850ee.png)
Also typing variable name in Debug Console results in following error:

 **Cannot evaluate because of compilation error(s): local cannot be resolved to a variable.**
Also trying to add variable to watch section fails with same error.
Note that watching `member` variable works fine.

##### Environment
- Operating System: Windows 10
- JDK version: 11.0.4

- Visual Studio Code version: 1.37.1
- Java extension version: 0.47.0
- Java Debugger extension version: 0.20.0

##### Steps To Reproduce
1. Debug project using provided debug configuration

[Project](https://1drv.ms/u/s!AgHTF3ThTdC5gTT2IMZFTGDQ9zOv?e=8U7XcQ)

##### Current Result
Local variables not shown
##### Expected Result
Local variable value shown
##### Additional Informations

My debug configuration
```
{
            "type": "java",
            "name": "Debug Test",
            "request": "launch",
            "mainClass": "Test.Main",
            "classPaths": ["."]
 }
```

**Comment by testforstephen** [comment]
Cannot reproduce this issue.
![image](https://user-images.githubusercontent.com/14052197/63564641-762ef300-c598-11e9-9f11-7bb41923a445.png)

Does the **DEBUG CONSOLE** show the right output?

**Comment by falco467** [comment]
Had the same problem. My build script did not compile with the debug symbols included.
Anyone else facing this issue - make sure you are using "javac -g" to include debug symbols for local variables.
