### ISSUE TITLE
Failed to debug some vertx-sql-client's unit tests

### ISSUE THREAD

**Issue by Heromyth** [microsoft/vscode-java-debug#643]
Some unit tests in vertx-sql-client can be run and debugged (like testSettingSchema in https://github.com/eclipse-vertx/vertx-sql-client/blob/3.8/vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectionTest.java), and some can't (like testWriteHexString in https://github.com/eclipse-vertx/vertx-sql-client/blob/3.8/vertx-pg-client/src/test/java/io/vertx/pgclient/UtilTest.java).

When failed to run the unit tests, nothing useful message can be got in the console's output.

##### Environment
- Operating System: Windows 10 x64
- JDK version: OpenJDK Runtime Environment (build 1.8.0_181-1-redhat-b13)
- Visual Studio Code version:  1.37.0-insider
- Java extension version:  0.7.1
- Java Debugger extension version: 0.21.0
- Java Test Runner version: 0.19.0

##### Steps To Reproduce
1. get a vertx-sql-client release at https://github.com/eclipse-vertx/vertx-sql-client/releases
2. Open this project use VS Code.
3. Run some unit tests like PgConnectionTest or UtilTest

##### Current Result
It's not all the unit tests in vertx-sql-client can be run and debugged, 

##### Expected Result
Unit tests in PgConnectionTest  can be run and debugged, 

##### Additional Informations
All the unit tests can be run and debugged in Eclipse.

**Comment by Heromyth** [comment]
Finally, I found out what happend for this. 
There is an Exception thrown in https://github.com/eclipse-vertx/vertx-sql-client/blob/3.8/vertx-pg-client/src/test/java/io/vertx/pgclient/junit/PgRule.java#83

The VS Code doesn't gives any useful message for this Exception.

The real reason is that the targetDir is not detected during the debug procession in VS Code.

**Comment by testforstephen** [comment]
Given it's an usage error, i will close this issue. If you want more discussion about it, feel free to reopen it.
