### ISSUE TITLE
Cannot start to debug spring boot app.

### ISSUE THREAD

**Issue by zhoudotnet** [microsoft/vscode-java-debug#644]
Issue Type: <b>Bug</b>

When I press F5 to debug spring boot app, it returned below message:
Failed to launch debuggee in terminal. Reason: com.sun.jdi.connect.TransportTimeoutException

Extension version: 0.21.0
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.32GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by testforstephen** [comment]
@zhoudotnet Could you share your VS Code Terminal Screenshot when failed to debug spring boot app?

**Comment by testforstephen** [comment]
See https://github.com/microsoft/vscode-java-debug/issues/637#issuecomment-525121005 for a workaround.

**Comment by zhoudotnet** [comment]
![image](https://user-images.githubusercontent.com/21075212/63902592-d57b8000-ca3c-11e9-9240-676c1d7af3c9.png)

**Comment by zhoudotnet** [comment]
When I add below config in the vscode setting, it is OK. Thank you for your help.
"java.debug.settings.console": "internalConsole"

What's the root cause for above issue?

**Comment by testforstephen** [comment]
We need more info for investigation. 
Could you share your VS Code Terminal Screenshot when failed to debug spring boot app?

**Comment by SledKnight** [comment]
I would see that exact message while experiencing the issue described in #646.  When system policy killed the .BAT execution, debugging would fail, and then this message would pop up a few seconds later.  Not sure if it's related, but just make sure that BAT execution isn't dying and causing this error for you.

**Comment by Nikegamerjjjj** [comment]
https://github.com/microsoft/vscode-java-debug/issues/1045#issue-982054966
