### ISSUE TITLE
Debugger is not working

### ISSUE THREAD

**Issue by shivambhatt24** [microsoft/vscode-java-debug#645]
Issue Type: <b>Feature Request</b>

configured debug type "JAVA" is not supported.

Extension version: 0.21.0
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 6.3.9600

**Comment by SledKnight** [comment]
I randomly saw this while troubleshooting #646.  Have you tried reinstalling the extensions, restarting VSCode, and waiting for the "thumbs up" in the lower right corner before debugging?

**Comment by msimms** [comment]
I'm seeing the same issue while attempting to start a remote debugging session on an Ubuntu 1804 Desktop machine.

**Comment by msimms** [comment]
Reinstalled everything and now it appears to work.

**Comment by testforstephen** [comment]
Could you check whether the `Debugger for Java` extension is activated or not?

You can run VS Code command `Developer: Showing Running Extensions` to list all activated extensions in your workspace.

**Comment by shanthi4647** [comment]
This issue exists.
![image](https://user-images.githubusercontent.com/4685287/66534755-d8d25300-eb34-11e9-9665-d8c52f6b6b64.png)
I just created azure function app(HttpTrigger-Java) and not able to debug on F5. Added debug configuration in launch.json file and tried debugging, but no luck. There is a message 'Configured debug type 'java' is not supported'
Installed required extensions to enable java debugging. No clue what is missing
![image](https://user-images.githubusercontent.com/4685287/66534927-7168d300-eb35-11e9-8a07-0a5585605274.png)

**Comment by testforstephen** [comment]
could you uninstall this extension? because it conflicts with `Debugger for Java` extension.
![image](https://user-images.githubusercontent.com/14052197/66535893-c4e71b00-eb4d-11e9-8680-831c3dc75cd6.png)

**Comment by shanthi4647** [comment]
uninstalled.. but didn't work
![image](https://user-images.githubusercontent.com/4685287/66536970-78dfaa80-eb3c-11e9-8003-09ac6ba1ac74.png)

**Comment by gonerodes** [comment]
I have the same issue.

**Comment by testforstephen** [comment]
> I have the same issue.

@gonerodes please open a new issue to describe the problem. A more efficient way is to provide reproduce steps and a sample project to help us dig the problem.
