### ISSUE TITLE
Launching BAT for UTF-8 fix is incompatible with Security Policies disallowing BAT execution.

### ISSUE THREAD

**Issue by SledKnight** [microsoft/vscode-java-debug#646]
Strict IT policy forbids the execution of BAT files in our environment.  Fix #625 is breaking debug, due to policy restrictions, and I've had to rollback to v0.20.0

Is there a way to address the UTF-8 issues in #524, #622, #618 without using a launcher.bat execution?  Or at minimum, make it optional?

##### Environment
- Operating System: Windows 10 Enterprise 1709
- JDK version: 1.8.0_222
- Visual Studio Code version: 1.37.1 (also impacts 1.37.0)
- Java extension version: 0.7.1
- Java Debugger extension version: 0.21.0

##### Steps To Reproduce
1. Configure network policy to forbid execution of .BAT files.
2. Try to start debugger from VSCode for any Java project.

**Comment by testforstephen** [comment]
@Eskibear could you help a look?

**Comment by SledKnight** [comment]
Any update on this?  I have, so far, managed to work around it by using the "internalConsole" option, but "integratedTerminal" still breaks.
