### ISSUE TITLE
Debugger not highlighting source lines

### ISSUE THREAD

**Issue by OmarTawfik** [microsoft/vscode-java-debug#656]
Hi,

I've a custom build of https://github.com/eclipse/eclipse.jdt.ls (for prototyping reasons).
I'm trying to setup this debugger to work with it, so cloned this extension and made the following changes:

1) I'm bundling the `java-debug` binaries by directly initializing the `bundles` property of `InitializationOptions` that I send to the server.
2) I rerouted the requests going to the `vscode-java` extension to go directly to the server, since I don't want to use the original server.
3) I could start the debugger, and can do the following successfully:
    * step over/in/out of source files.
    * see locals populated and updated correctly.
    * see the call stack populated and updated correctly (with `Unknown Source`).
4) However, the following are not working at all:
    * the current source line is not highlighted.
    * hovering doesn't work (I only get the hover info of source code from the Java LSP).
    * Stepping into methods doesn't open the file containing the method.
    * I'm also seeing this in the call stack.

<img width="360" alt="Screen Shot 2019-09-11 at 12 58 51 AM" src="https://user-images.githubusercontent.com/15987992/64678884-579d7880-d42f-11e9-9947-d02c405924b1.png">

I'm suspecting this has something to do with how the debug configuration is provided, or maybe the class path, but I cannot figure it out. Here is my debug config after it is resolved:

```json
{
  "type":"java",
  "name":"Debug (Launch) - Current File",
  "request":"launch",
  "mainClass":"project.lib.Main",
  "modulePaths":[],
  "classPaths":["THE_CORRECT_CLASS_PATHS_RESOLVED_FROM_SERVER"],
  "cwd":"THE_CORRECT_CWD",
  "debugServer":49831,
  "sourcePaths": ["/folder1", "/folder2"]
}
```

can you please tell me what else might be missing? Is there a way to debug the debugger and see what gets sent back and forth between the editor and the active adapter?

**Comment by testforstephen** [comment]
vscode-java-debug can only be run by relying on vscode-java extension. For your custom eclipse.jdt.ls build, not sure what's your gap. For debug, please set user setting `"java.debug.logLevel": "verbose"`.

**Comment by OmarTawfik** [comment]
Thanks! turns out my problem was that the debugger wasn't able to locate some of the source files, which I solved by explicitly providing a more comprehensive list of paths.
