### ISSUE TITLE
Java Language server error

### ISSUE THREAD

**Issue by ProgrammerAI** [microsoft/vscode-java-debug#659]
Issue Type: <b>Bug</b>

1: Modify file
2: Press F5
3: Get error

Extension version: 0.21.0
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU B960 @ 2.20GHz (2 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.82GB (1.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by testforstephen** [comment]
Could you share us the logs?

You need run VS Code commands `Java: Open Java language server log file` and `Java: Open Java extension log file` to get the log file.
