### ISSUE TITLE
how to use the vscode to debug a javaweb project

### ISSUE THREAD

**Issue by wangwsk** [microsoft/vscode-java-debug#661]
[how to use the vscode to debug a javaweb project

##### Environment
- Operating System: win10
- JDK version: JDK8
- Visual Studio Code version: 1.38.1

i am a javaweb coder, i try to user the vscode to code ,but i find only the spring-boot project with the embeded devtools can use the debugger to resolve the debug of browser to vscode ,now i want to ask  how to debug for traditional project like SSM which is base maven ,i try to set a breakpoint in controller ,but when i start a request from browser,it not step into the controller ,thank you verymuch

**Comment by testforstephen** [comment]
Could you have a look at [tomcat](https://marketplace.visualstudio.com/items?itemName=adashen.vscode-tomcat) and [jetty](https://marketplace.visualstudio.com/items?itemName=SummerSun.vscode-jetty) extension?

**Comment by akaroml** [comment]
@wangwsk Could you let us know more about the feature you want to enable? It looks like you are looking for something like this:
![image](https://user-images.githubusercontent.com/16755094/66732501-d05c7e00-ee8e-11e9-9dd9-cb10df5a8e0e.png)

Please confirm if we are on the same page.

**Comment by testforstephen** [comment]
Here is the sample about how to debug Java webapps using the tomcat7-maven-plugin.
https://github.com/microsoft/vscode-java-debug/blob/master/Configuration.md#attach-to-embedded-maven-tomcat-server
