### ISSUE TITLE
Here is an error about timeout exception when I change default terminal to run a java project.

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/vscode-java-debug#669]
#### Environment
          Operating System: Windows
          JDK version: 8/11/12
          Visual Studio Code version: 1.38.1
          Java extension version: 0.49.0
          Java Debugger extension version: 0.22.0
#### Steps To Reproduce

1. Open a java project
2. Press F5 to debug
3. Change your default terminal from powershell to cmd or git bash in settings.json
4. Press F5 again

#### Result:
Wait about 10s, it will pop up an error about timeout.
![image](https://user-images.githubusercontent.com/44559777/65410635-7af7f880-de1d-11e9-8499-412dd3a58d11.png)
`Toggle Developer Tools:`
![image](https://user-images.githubusercontent.com/44559777/65410704-a4188900-de1d-11e9-8db8-bcef270890e9.png)

**Comment by testforstephen** [comment]
This is upstream issue https://github.com/microsoft/vscode/issues/81345
