### ISSUE TITLE
Set Vscode default terminal to git bash, it always open new terminal when i click run or debug code lens.

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/vscode-java-debug#670]
#### Environment
      Operating System: Windows
      JDK version: 8/11/12
      Visual Studio Code version: 1.38.1
      Java extension version: 0.49.0
      Java Debugger extension version: 0.22.0
#### Steps To Reproduce
1.  Set vscode default terminal from powershell to git bash.
2. Click debug or run code lens.

#### Result:
**Vscode always open a new terminal window to start debugging session.**
![image](https://user-images.githubusercontent.com/44559777/65412133-2a829a00-de21-11e9-880e-2f9f59f4ee4f.png)

**Comment by testforstephen** [comment]
This is the upstream issue https://github.com/microsoft/vscode/issues/81344
