### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bastipv** [microsoft/vscode-java-debug#672]
- Issue Type: `Performance`
- Extension Name: `vscode-java-debug`
- Extension Version: `0.22.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

[vscjava.vscode-java-debug-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-java-debug/files/3649778/vscjava.vscode-java-debug-unresponsive.cpuprofile.txt)

**Comment by bastipv** [comment]
[vscjava.vscode-java-debug-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-java-debug/files/3649775/vscjava.vscode-java-debug-unresponsive.cpuprofile.txt)

**Comment by testforstephen** [comment]
duplicated. See https://github.com/microsoft/vscode-java-debug/issues/554#issuecomment-487332778
