### ISSUE TITLE
Immediately  exit after launch Spring boot application

### ISSUE THREAD

**Issue by Damdias** [microsoft/vscode-java-debug#674]
[provide a description of the issue]

##### Environment
- Operating System: Windows 10
- JDK version: 1.8
- Visual Studio Code version: 1.38.1
- Java extension version: 0.8.0
- Java Debugger extension version: 0.22.0

##### Steps To Reproduce
1. Create new spring boot maven project with Spring Initializr
2. when try to run using F5 it runs the app and immediately exit.

launch configuration :
  {
            "type": "java",
            "name": "Debug (Launch)-DemoApplication<email>",
            "request": "launch",
            "mainClass": "com.example.email.DemoApplication",
            "projectName": "email"
        }

![image](https://user-images.githubusercontent.com/16229310/65652491-99cdd900-e02f-11e9-9ae4-1570b60a9553.png)

**Comment by testforstephen** [comment]
Could you share a sample project to help us reproduce it?

**Comment by Damdias** [comment]
[email.zip](https://github.com/microsoft/vscode-java-debug/files/3679315/email.zip)
here the sample project

**Comment by Damdias** [comment]
hi Jinbo,

sorry for the late reply,

there the project please find the attachment

Thanks
Damith

**Comment by shimikano** [comment]
I ran into the same issue with a Spring Boot Gradle project using the same versions of the extensions.

Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-64-generic

**Comment by testforstephen** [comment]
@Damdias i tried to use intellij IDEA to run your sample project, it also exited immediately. The behavior is same as VS Code. So this looks like a problem of your project.

**Comment by Damdias** [comment]
@testforstephen this is not expected answer project has been created through the vs code  then issue with VS code. can you share working project that has created through the vs Code.

Note: I follow the steps in Vs code doc

**Comment by testforstephen** [comment]
how do you create the project via VS Code?

**Comment by Damdias** [comment]
i followed this doc
https://code.visualstudio.com/docs/java/java-spring-boot

**Comment by testforstephen** [comment]
Here is a project i created via VS Code, it works.
[bug.zip](https://github.com/microsoft/vscode-java-debug/files/3705129/bug.zip)

**Comment by Invertisment** [comment]
This occurs when trying this tutorial too: https://spring.io/quickstart
