### ISSUE TITLE
Debugger stuck on every other step

### ISSUE THREAD

**Issue by ym222bs** [microsoft/vscode-java-debug#676]
[provide a description of the issue]

##### Environment
- Operating System: Windows 10 Pro
- JDK version: 12.0.2
- Visual Studio Code version: 1.38.1
- Java extension version: 0.8.0 ( Java extension pack (?))
- Java Debugger extension version:  0.22.0

The debugger was working fine just a day before and without changing any code I tested to run the debugger on it again. Now its always stuck on pending on the second break point, where ever I change it to. Under "Variables" -> "Local" there is a loading circle which is turning for about 2-4 minutes before it moves on to the next step.

(The program runs fine without the debugger and is executed as expected).

I tried to uninstalling all java related extensions and reinstalling those, but with no luck.

##### Steps To Reproduce
1. Start vscode with Java extension pack ( Java debugger)
2. Write some classes and methods
3. Set a few break points to test
2. Debug

**Comment by testforstephen** [comment]
cannot repro it in my machine. could you share a sample project to us to reproduce it?

**Comment by ym222bs** [comment]
The problem disappeared after a few days right after I made a new copy of the original .classpath,
I suspect it was a problem with how the .classpath was automated and not a problem with the extension it self,
but I'm not sure as I can not recreate it either.

**Comment by mon205** [comment]
I am facing a similar issue, I think that you can find the hanging thread in the call stack view. I think that the bug https://github.com/microsoft/vscode/issues/57253 has been re-opened again. We hope someone fix it.
