### ISSUE TITLE
Support hot class reloading

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode-java-debug#68]
While debugging, making a non breaking change to a source file (i.e don't change method signature, add new method...) should make the debugger restart the current method call, without breaking the debugging session (same as in Eclipse).

**Comment by yaohaizh** [comment]
Work item for this issue:
[ ] Hook up with the current build cycle and debug adapter to trigger hot code replacement
[ ]

**Comment by mojo2012** [comment]
You should try DCEVM - it allows you to change nearly everything (even introduce new classes) during runtime.
It works independent of the used IDE. You just have to start the JVM with special arugments.

**Comment by yaohaizh** [comment]
@mojo2012, If you use the DCEVM for the running JVM, the vscode java HCR will support those scenarios.  The HCR will try the underlying behavior of the JVM.

**Comment by yaohaizh** [comment]
Close this as the main is completed. Other features will be tracked in logged issues.
