### ISSUE TITLE
Build failed, do you want to continue?

### ISSUE THREAD

**Issue by rainbowyy** [microsoft/vscode-java-debug#680]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by testforstephen** [comment]
duplicated with https://github.com/microsoft/vscode-java-debug/issues/358
