### ISSUE TITLE
Improve debugger extension name

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-java-debug#69]
![image](https://user-images.githubusercontent.com/6461412/30916815-988e96e8-a39a-11e7-93f8-8285bbc33957.png)

- The extension name is very long. 'for Visual Studio Code' should be removed, it is true for all extensions in the Visual Studio Code marketplace
- Also, searching for 'Java debugger' doesn't list it in the top entries

Some suggesions
- Java Debugger
- Debugger for Java
- Language Support for Java Debugger

There's already the Java Debugger from Don Jayamanne, but I think people will see it is from Microsoft 

The description could say: `Debugger extension for the Java Language Support by Red Hat`.

**Comment by yaohaizh** [comment]
Fixed in https://github.com/Microsoft/vscode-java-debug/pull/92
