### ISSUE TITLE
Change source file

### ISSUE THREAD

**Issue by jeusdi** [microsoft/vscode-java-debug#690]
[provide a description of the issue]

##### Environment
- Operating System: ubuntu 18.08
- JDK version: 1.8_131
- Visual Studio Code version: 
- Java extension version: 0.8.0
- Java Debugger extension version: 0.22.0

I've created a debug point.

It's attached, but when it's reached, appears other source file:

![image](https://user-images.githubusercontent.com/941639/66748454-86bc6500-ee87-11e9-8987-7de37fad1a9a.png)

I mean, as you can see, I set the breakpoints on `ServicesConfiguration.java` source file. Nevertheless, when break point is reached, the source file loaded other. It's located on other place.

I mean, when breakpoint is reached, source file shown is other:

![image](https://user-images.githubusercontent.com/941639/66748829-6fca4280-ee88-11e9-80eb-56d6b97c7705.png)

**Comment by testforstephen** [comment]
Looks like there are multiple versions  for the file `ServicesConfiguration.java` existing in your machine. Could you check why there are multiple versions for the same source file?

**Comment by smit-onshape** [comment]
I'm facing the same issue. Basically we have few classes with same name but under different packages.
