### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by jadelike-wine** [microsoft/vscode-java-debug#692]
I can run my code in cmd . But my code can't run in vscode.
error: java.lang.ClassNotFoundException
![image](https://user-images.githubusercontent.com/46087189/67135696-e2536d80-f24e-11e9-8bca-3c504754d1bc.png)
PS C:\Users\10156\vscode\Test> cd 'c:\Users\10156\vscode\Test'; & 'C:\Users\10156\.vscode\extensions\vscjava.vscode-java-debug-0.22.0\scripts\launcher.bat' 'C:\Program Files\Java\jdk-12.0.2\bin\java' '--enable-preview' '-Dfile.encoding=UTF-8' '-cp' 'C:\Users\10156\AppData\Roaming\Code\User\workspaceStorage\64ad1d34ecc58c3f8dcf9119a054a187\redhat.java\jdt_ws\Test_dff30b5c\bin' 'test' 
错误: 找不到或无法加载主类 test
原因: java.lang.ClassNotFoundException: test

**Comment by testforstephen** [comment]
Could you share the log to us?
**F1 -> "Java: Open Java language server log file"**

**Comment by jadelike-wine** [comment]
[.log](https://github.com/microsoft/vscode-java-debug/files/3749172/default.log)

**Comment by jadelike-wine** [comment]
> Could you share the log to us?
> **F1 -> "Java: Open Java language server log file"**

[.log](https://github.com/microsoft/vscode-java-debug/files/3749175/default.log)

**Comment by testforstephen** [comment]
> !MESSAGE Error occured while building workspace. Details: 
 message: Preview features enabled at an invalid source release level 12, preview can be enabled only at source level 13; code: 2098258; resource: C:/Users/10156/vscode/Test/t.java;
 message: Preview features enabled at an invalid source release level 12, preview can be enabled only at source level 13; code: 2098258; resource: C:/Users/10156/vscode/Test/test.java;

This is a known issue redhat-developer/vscode-java#1086, which is already fixed in the **Language Support for Java(TM) by Red Hat** extension 0.51.0 release.

Could you update the Java extension to latest version and try again?

**Comment by jadelike-wine** [comment]
> > !MESSAGE Error occured while building workspace. Details:
> > message: Preview features enabled at an invalid source release level 12, preview can be enabled only at source level 13; code: 2098258; resource: C:/Users/10156/vscode/Test/t.java;
> > message: Preview features enabled at an invalid source release level 12, preview can be enabled only at source level 13; code: 2098258; resource: C:/Users/10156/vscode/Test/test.java;
> 
> This is a known issue [redhat-developer/vscode-java#1086](https://github.com/redhat-developer/vscode-java/issues/1086), which is already fixed in the **Language Support for Java(TM) by Red Hat** extension 0.51.0 release.
> 
> Could you update the Java extension to latest version and try again?

![image](https://user-images.githubusercontent.com/46087189/67180634-bbdb3100-f40c-11e9-97ce-2b49b0220f41.png)
Is this in photo? I have been the latest version.

**Comment by testforstephen** [comment]
Yes, it's the latest version. Could you try **F1 -> Java: clean the Java language server workspace**?

**Comment by jadelike-wine** [comment]
> Yes, it's the latest version. Could you try **F1 -> Java: clean the Java language server workspace**?

The problem is solved.I am gratitude to you for helping me.

**Comment by wiazur** [comment]
> Yes, it's the latest version. Could you try F1 -> Java: clean the Java language server workspace?

I am having the same problem, and I also have the v0.51.0 version. I don't know how to do this command **F1 -> Java: clean the Java language server workspace** could you elaborate?

**Comment by testforstephen** [comment]
@wiazur Try the following steps:

1. Open VS Code **Command Palette...** via shortcut key F1 (or Ctrl + Shift + P)
2. Execute command **Java: clean the Java language server workspace**

![cleanWorkspace](https://user-images.githubusercontent.com/14052197/67253864-8ede5b00-f4ac-11e9-9828-6a84cf6b8a7e.gif)

**Comment by vartdalen** [comment]
I am facing this problem.

I can build .war file with maven and run it successfully.
I can also debug the project in IntelliJ.

But in VSCode, I get NoClassDefFoundError.
I have tried the fixes mentioned above, but they did not help.

Java server log
[.log](https://github.com/microsoft/vscode-java-debug/files/6251117/default.log)

VSCode debug log
[vscode-debug-log.txt](https://github.com/microsoft/vscode-java-debug/files/6251128/vscode-debug-log.txt)

Project .war log
[war-log.txt](https://github.com/microsoft/vscode-java-debug/files/6251134/war-log.txt)

Project can be cloned from https://github.com/image-store-org/image-store-sql

**Comment by Shaz-L** [comment]
Same problem here

**Comment by samochod23** [comment]
yes ,is naw no my conto is dasen"tsynchronised

**Comment by YukiEmeralis** [comment]
I think this problem has reared its head again. Same issue down here, VSCode version 1.55, language support version 0.77.0, JDK version 15. Cleaning the language server workspace doesn't fix it.
![image](https://user-images.githubusercontent.com/71955428/115119226-83b2a100-9f64-11eb-8a96-094ce2bbda8b.png)

**Comment by sage-blue** [comment]
> I think this problem has reared its head again. Same issue down here, VSCode version 1.55, language support version 0.77.0, JDK version 15. Cleaning the language server workspace doesn't fix it.
> ![image](https://user-images.githubusercontent.com/71955428/115119226-83b2a100-9f64-11eb-8a96-094ce2bbda8b.png)

im having the same issue.

**Comment by gaurav0116** [comment]
> Yes, it's the latest version. Could you try **F1 -> Java: clean the Java language server workspace**?

this is working

**Comment by SinhaAkshat** [comment]
> Yes, it's the latest version. Could you try **F1 -> Java: clean the Java language server workspace**?

could 

> @wiazur Try the following steps:
> 
> 1. Open VS Code **Command Palette...** via shortcut key F1 (or Ctrl + Shift + P)
> 2. Execute command **Java: clean the Java language server workspace**
> 
> ![cleanWorkspace](https://user-images.githubusercontent.com/14052197/67253864-8ede5b00-f4ac-11e9-9828-6a84cf6b8a7e.gif)

Could you elaborate on why is this error happening ??

**Comment by khaled909** [comment]
I has the same problem and i do exactly what you said but it doesn't work! please help me

**Comment by Mogez** [comment]
Still no clue.

**Comment by EICHOSAMA** [comment]
I am also facing this problem. It seems like JVM receives classpath arg with MOJIBAKE.

![image](https://user-images.githubusercontent.com/6964772/185431204-cb5fe3d8-0f2d-4795-8cb6-c6a671ab38f4.png)

**File content is like this,** while the Chinese string “虎猫儿” is my Win username. It gets MOJIBAKE while passing the JVM by the command **java '@C:\Users\虎猫儿\Desktop\options.txt' 'per.eicho.demo.sdk.Test'**, BTW, the file is UTF-8 encoding.
![~~G(@NIL4{JT1$B8Z39SJ1P](https://user-images.githubusercontent.com/6964772/185433279-b76a6bb7-ca4c-449f-899c-b0d7ceb8be20.png)

Test code:
![M}VRIM58{58GMF8D9%S076X](https://user-images.githubusercontent.com/6964772/185433612-62a8cdbf-7407-4c21-8291-c75a7dbf1a4a.png)

**Comment by EICHOSAMA** [comment]
Guys, I found 2 temporary approaches to solve this problem.

1. change your windows username, avoid using Chinese or Japanese characters in windows username, just use English letters + digits.
2. move the localRepository location of Maven from **${user.home}/.m2/repository** to another place, absolute path of the new location should not contains any Chinese or Japanese characters.

while those 2 approaches didn't solve the MOJIBAKE.  Let's look at the command below.

 **_java '@C:\Users\虎猫儿\Desktop\options.txt' 'per.eicho.demo.sdk.Test'_**

I have no idea about the meaning of **'＠filePath'**, it doesn't seem like any syntax of shell. I guess HotSpot JVM will load the file content as JVM arguments, and maybe something gets wrong in HotSpot JVM while parsing the UTF-8 text file. :(

**Comment by emrebuzkiran** [comment]
![javasinir](https://user-images.githubusercontent.com/67521326/197353058-5769de56-6744-43a5-b761-64fd0b2683f2.png)
i use spring boot with maven. how can i fix it

**Comment by ViniPorto** [comment]
> 

I have the same issue. It happens when I'm using a maven dependency in pom.xml. If I remove the dependency, the code works.
PS: I noticed that the command in terminal changes when using a dependency in pom.xml, I have no ideia why
![image](https://user-images.githubusercontent.com/81120004/204140384-b46e4ec2-4c81-445a-9da6-57d5e831f5c4.png)

**Comment by sagarpjpt** [comment]
> Could you share the log to us? **F1 -> "Java: Open Java language server log file"**

thanks a lot bro

**Comment by xerofenix** [comment]
> Yes, it's the latest version. Could you try **F1 -> Java: clean the Java language server workspace**?

why does this happen?

**Comment by NCPlays11** [comment]
I've seen this happens a lot when creating a brand new program, though I might be wrong on this.

**Comment by shilpee-0311** [comment]
PS C:\Users\mails\OneDrive\Desktop\EM-PROJECT>  & 'C:\Program Files\Java\jdk-20\bin\java.exe' '-XX:+ShowCodeDetailsInExceptionMessages' '-cp' 'C:\Users\mails\AppData\Roaming\Code\User\workspaceStorage\e0a49873c7a88b699c4e0435a910dd88\redhat.java\jdt_ws\jdt.ls-java-project\bin' 'com.example.em_project.EmProjectApplication' 
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
        The method run(Class<EmProjectApplication>, String[]) is undefined for the type SpringApplication

        at com.example.em_project.EmProjectApplication.main(EmProjectApplication.java:13)

**Comment by marianatorres444** [comment]
@testforstephen Man, I love youuuu, i've been trying a thousand ways and I had already desperate. Thank you!! <3

**Comment by iamchinu97** [comment]
Hey guys I am still facing this issue. what is the resolution

**Comment by xerofenix** [comment]
> Hey guys I am still facing this issue. what is the resolution

Kindly share the issue in detail. **Try F1 -> Java: clean the Java language server workspace** one more time
