### ISSUE TITLE
Breakpoints ignored

### ISSUE THREAD

**Issue by kecoliva** [microsoft/vscode-java-debug#697]
Breakpoints are being ignored. I was wondering does the extension support 1.8.0_231? or it only supports 1.8.0_221?

- Operating System: Windows
- JDK version: 1.8.0_231
- Visual Studio Code version: 1.39.2
- Java extension version: 0.8.0
- Java Debugger extension version: 0.22.0

**Comment by testforstephen** [comment]
Yes, the debugger supports JDK 8 and above. 

Could you share us a project to help reproduce the issue?

**Comment by kecoliva** [comment]
Hi @testforstephen you can check it out here https://github.com/kecoliva/workbench

Try breaking at line 16 on WorkbenchTwo.java

**Comment by testforstephen** [comment]
i tried you code, the breakpoint works. My jdk is `1.8.0_171`.

![bug](https://user-images.githubusercontent.com/14052197/67548755-366dbe80-f735-11e9-8ef2-372e83680b61.gif)

Could you share the extensions you installed?

**Comment by kecoliva** [comment]
Here's a list of the extensions I have

- :emojisense:
- Beautify
- C/C++
- Debugger for Java
- Docker
- Dracula Official
- Excel Viewer
- GitHub Sharp Theme
- GitLens – Git supercharged
- Java Dependency Viewer
- Java Extension Pack
- Java Test Runner
- Language Support for Java(TM) by Red Hat
- Live Server
- Material Icon Theme
- Maven for Java
- Prettier - Code formatter
- Remote - WSL
- Spring Boot Dashboard
- Spring Boot Tools
- Spring Initializr Java Support
- Visual Studio IntelliCode
- vscode-icons
- XML Tools

**Comment by testforstephen** [comment]
OK, then i need look at your log file to see any exception there.  Click **F1** -> **Java: Open Java language server log file** will open the log file.

**Comment by kecoliva** [comment]
Here it is

```
!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-30 10:34:44.428
!MESSAGE >> java/buildWorkspace (incremental)

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-30 10:34:45.434
!MESSAGE >> workspace/executeCommand vscode.java.validateLaunchConfig

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-30 10:34:45.437
!MESSAGE >> workspace/executeCommand vscode.java.resolveClasspath

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-30 10:34:45.453
!MESSAGE >> workspace/executeCommand vscode.java.checkProjectSettings

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-30 10:34:45.562
!MESSAGE >> workspace/executeCommand vscode.java.inferLaunchCommandLength

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-30 10:34:45.566
!MESSAGE >> workspace/executeCommand vscode.java.startDebugSession

!ENTRY java-debug 2 0 2019-10-30 10:34:47.683
!MESSAGE Failed to destory launch files, will retry again.

!ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-30 10:34:48.187
!MESSAGE >> workspace/executeCommand vscode.java.fetchUsageData
````

**Comment by kecoliva** [comment]
I finally got it to work. Though I still don't know what caused it I simply just recreated the project and manually copy the files.
