### ISSUE TITLE
Improve market place description

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-java-debug#70]
- The first sentence contains a link to 'https://github.com/Microsoft/java-debug'
   - it is currently still private
   - it is, IMO, rather an implementation detail, a normal user can't do much with that

-> Better mention in the first sentence that this one extends the Java Language Support by Red Hat.

> A lightweight Java Debugger that extends the Language Support for Java by Red Hat: 
> Here's a list of features:
> ...

- needs a link to this repo (once public): https://github.com/Microsoft/vscode-java-debug

**Comment by yaohaizh** [comment]
Fixed in:  https://github.com/Microsoft/vscode-java-debug/pull/92
