### ISSUE TITLE
Could not find or load main class with Chinese characters

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/vscode-java-debug#700]
#### Environment
- Operating System: Win
- JDK version: jdk13.0.1
- Visual Studio Code version:1.39.2
- Java extension version: 0.52.0
- Java Debugger extension version: 0.23.0

#### Steps To Reproduce
1. Copy a project to under Chinese characters folder
2. Open project by VSCode, set a breakpoint and F5 to debug.

#### Result
Error: Could not find or load main class
![image](https://user-images.githubusercontent.com/51812626/67669668-55768580-f9ad-11e9-8560-10c2fd88602d.png)

**Comment by testforstephen** [comment]
duplicated with https://github.com/microsoft/vscode-java-debug/issues/623
