### ISSUE TITLE
"Build failed, do you want to continue?" happening frequently

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-java-debug#702]
I have "Build failed, do you want to continue?" problems again.

<img width="471" alt="Screen Shot 2019-10-29 at 21 23 26" src="https://user-images.githubusercontent.com/738650/67806599-7fa27300-fa93-11e9-837d-009323930433.png">

If I proceed everything works fine. 

Under fix, clearing the cache worked, but earlier today it did not and I had to remove the workspaceStorage.

This was the log that can be found under fix.

> !SESSION 2019-10-29 20:33:30.576 -----------------------------------------------
> eclipse.buildId=unknown
> java.version=1.8.0_202
> java.vendor=Oracle Corporation
> BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_NL
> Command-line arguments:  -data /Users/doekewartena/Library/Application Support/Code/User/workspaceStorage/730cdcb5bcba641b841038b7a4e3c29c/redhat.java/jdt_ws
> 
> This is a continuation of log file /Users/doekewartena/Library/Application Support/Code/User/workspaceStorage/730cdcb5bcba641b841038b7a4e3c29c/redhat.java/jdt_ws/.metadata/.bak_0.log
> Created Time: 2019-10-29 20:34:07.047
> 
> !ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-29 20:34:07.048
> !MESSAGE >> workspace/executeCommand vscode.java.resolveBuildFiles
> 
> !ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-29 20:34:09.607
> !MESSAGE >> document/didClose
> 
> !ENTRY org.eclipse.jdt.ls.core 1 0 2019-10-29 20:34:09.609
> !MESSAGE >> workspace/executeCommand java.resolvePath
> 

What also is happening really frequent is that it shows like the file has errors like this:

<img width="390" alt="Screen Shot 2019-10-29 at 20 31 11" src="https://user-images.githubusercontent.com/738650/67806985-34d52b00-fa94-11e9-826e-7808407ac683.png">

Then when I go to a file, the errors disappear for that specific file. 

I reinstalled VSCode several times.
I almost have no extensions, the ones I have:
- the 6 for java (why so much?)
 - kotlin
- Visual Studio IntelliCode
- Gradle Language Support
- Cursor Align
- Bracket Pair Colorizer

I hope I can provide better information in the future that might narrow the cause down of this problem.

##### Environment
- Operating System: OSX 10.12.6
- JDK version: jdk1.8.0_202
- Visual Studio Code version: 1.39.2
- Java extension version: do you mean java extension pack version? if so 0.8.0
- Java Debugger extension version: 0.23.0

**Comment by clankill3r** [comment]
Right now when I reopen the editor I have that it shows errors, and they are gone when I go to the file. 

Also the "Build failed" will show.

"Clean workspace cache" does not work.

removing the workspaceStorage probably will but it's so annoying to keep doing that.

**Comment by testforstephen** [comment]
Did you paste the whole log file here? 

Below is the command to get the log file:
Click **F1** -> **Java: Open Java language server log file**

Search the keyword `build workspace` or `building workspace` to find more details about the build errors.

**Comment by clankill3r** [comment]
@testforstephen yes that was the whole log.

I posted the  **Java language server log file** here:
https://pastebin.com/ZYaAD3xF
A lot of problems will be from when I was setting up the project (I guess).

**Comment by testforstephen** [comment]
See the logs:
> !MESSAGE Error occured while building workspace. Details:
 message: The import doeke_sfjl cannot be resolved; code: 268435846; resource: /Data/github_clankill3r/p5_terminal_graphics/src/doeke_p5_terminal_graphics/TPGraphics.java; line: 16
...

Apparently there are many build errors existed in your workspace. You must fix these errors first.

**Comment by clankill3r** [comment]
I will open a new issue, I recreated the project and I have some more info. It really seems like a bug.

**Comment by Martin-Melody** [comment]
meow mix
