### ISSUE TITLE
Remote debug is so slow.

### ISSUE THREAD

**Issue by chenhebing** [microsoft/vscode-java-debug#704]
[provide a description of the issue]
Using idea to debug can get results quickly, but with vscode debug, it takes a long time to get to the breakpoint. Wait a long time about ten minutes, the value will not appear. 
##### Environment
- Operating System: macos catalina
- JDK version: 1.8
- Visual Studio Code version:  1.39.2
- Java extension version: 0.8.0
- Java Debugger extension version: 0.23.0

**Comment by KevinGuancheDarias** [comment]
Reproduced in a Spring boot app

* Time in Ecllipse: Less than 15 seconds
![image](https://user-images.githubusercontent.com/6832422/76434866-2d148400-63ae-11ea-9ab4-c0a4980f9816.png)

* Time in VSCode Java: Almost two minutes
![image](https://user-images.githubusercontent.com/6832422/76436440-21c25800-63b0-11ea-9040-2b2f286a133c.png)

When running without debug both apps take the same time.

* Operating System: Windows 7 SP1
* JDK version: Java 11 Plan9 JDK
* Visual Studio Code version: 1.43.0
* Java Debugger extension version: 0.25.1

**Comment by testforstephen** [comment]
The underlying Java debug protocol JPDA is pretty chatty, and not suitable for remote debugging scenario. There is not much the Java debugger can improve right now. I would suggest you have a look at https://code.visualstudio.com/docs/remote/ssh.

**Comment by testforstephen** [comment]
@KevinGuancheDarias your scenario is not related with remote debugging. Please open a new issue to describe your issue. It's better to provide reproduce steps and your environment config such as user setting/launch.json.

**Comment by Ricbet** [comment]
I think it should be here.
![image](https://user-images.githubusercontent.com/20262815/110511058-ccde2c80-813e-11eb-885e-89a3209b679d.png)

If there are many threads (e.g 200).
`isCollected()` and `name()` will send the command packet to the target vm through JDI and wait for reply.
That would request 200*2 times. I don’t know if it can be optimized

**Comment by testforstephen** [comment]
This may cause lots of roundtrip with the debuggee, but it's not the only place that needs to be optimized. The main problem is the underlying JPDA is chatty and not efficient for remote debugging. There is not a good way to solve this problem completely.

At the comment we recommend you to take a look at VS Code remote development support.
