### ISSUE TITLE
`;` not possible in vmArgs

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-java-debug#707]
good day,

If I use the following vmArgs:

```json
"vmArgs": "-ea -javaagent:build/static_agent.jar=\"doeke.application.TestApplication;test\"",
```

Then in `public static void premain(String agentArgs, Instrumentation inst) {`

the string `agentArgs` will be `"doeke.application.TestApplication"` instead of the expected `"doeke.application.TestApplication;test"`.

For now I use `:` instead of `;` but since it feels like a bug I thought I report.
In the terminal using `;` works fine so it is really a problem in vscode.

##### Environment
- OSX
- 1.8
- 1.39.2
- 0.8.0

**Comment by testforstephen** [comment]
When running in terminal, it seems VS Code didn't handle the double quotes inside the argument well. See the bug https://github.com/microsoft/vscode/issues/84235.

Current workaround is changing the console option in launch.json to **internalConsole**

**Comment by testforstephen** [comment]
tracked with external issue microsoft/vscode#84235
