### ISSUE TITLE
Debugger not able to launch - command not found

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-java-debug#708]
@pdonnelly3 reported this in gitter channel:

> Hello! I am running into an error and cannot find a solution for it. Just trying to switch to VSCode for Java and running a basic hello world program I am getting this issue after installing the java pack - C:\Users\donne.vscode\extensions\vscjava.vscode-java-debug-0.22.0\scripts\launcher.bat "C:\Program Files\Java\jdk1.8.0_161\bin\java" -Dfile.encoding=UTF-8 -cp "C:\Users\donne\Desktop\projects\cmsc351\Merge Sort\Experiment\bin" app.Experiment
C:Usersdonne.vscodeextensionsvscjava.vscode-java-debug-0.22.0scriptslauncher.bat: command not found

**Comment by akaroml** [comment]
@singhalrbl replied with the answer of switching to cmd instead of using wsl as default terminal to solve the problem. We need to cover the wsl case as more and more users adopt it.

> ya i got the answer use cmd not wsl in default terminal as .bat files can't be launched in wsl terminal

**Comment by tianyouhui** [comment]
I also meet this problem, maybe it cause by **wsl**, please have a check.

**Comment by testforstephen** [comment]
In latest debugger extension, we have removed launcher.bat from the command line. @pdonnelly3 @tianyouhui Could you try the latest debugger 0.37.0 to see if the issue still exist? thanks.
