### ISSUE TITLE
jumpt to definition on break

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-java-debug#714]
I think it would be really great if you use "Go to Defenition" on a `break` that you jump to the `while` or `for` loop that will break.

Think about it.

**Comment by testforstephen** [comment]
`Go to Definition` feature is contributed by https://github.com/redhat-developer/vscode-java, please open an issue there.

**Comment by clankill3r** [comment]
https://github.com/redhat-developer/vscode-java/issues/1145
