### ISSUE TITLE
Where in the source does it add file links for the debug console?

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-java-debug#716]
On the right there are those file links:

<img width="1060" alt="Screen Shot 2019-11-17 at 20 20 26" src="https://user-images.githubusercontent.com/738650/69012608-f1295f00-0977-11ea-8fb9-4c818552a9ec.png">

I'm assuming the vscode-java-debug extension is responsible for those because I only have that and the redhat extension installed. And it makes no sense for the redhat extension to do that since it can not run anything.

If I do a `println` with a **at** line myself it also works (as long as the file exists):

<img width="1042" alt="Screen Shot 2019-11-17 at 20 23 46" src="https://user-images.githubusercontent.com/738650/69012623-30f04680-0978-11ea-9377-2de0853c5c2b.png">

I was wondering, where in the source code does this magic happen?
I can't find it.

**Comment by testforstephen** [comment]
Yes, it's the debugger providing this feature. You may have a look at this issue https://github.com/microsoft/vscode-java-debug/issues/506
