### ISSUE TITLE
Reuse the same terminal window

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-java-debug#717]
I am using the external terminal, and every time I run java it opens a new terminal window.
Is there anyway of reusing the external terminal window?

**Comment by testforstephen** [comment]
It's determined by upstream VS Code, probably open an issue in VS Code. https://github.com/Microsoft/vscode/issues

**Comment by clankill3r** [comment]
https://stackoverflow.com/questions/58911300/reuse-the-same-terminal-window
