### ISSUE TITLE
[bug] workspace storage is breaking vscode-java-debug

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-java-debug#720]
I reported this before, but I had issues isolating it. Now I made a small project to reproduce the problem.

**The issue:**
The project is working fine. When I close and open vscode then I can't run the debugger anymore. 
I get:

> Build failed, do you want to continue? 
> 
> Source: Debugger for Java (Extension)

If I remove the workspace storage then the problem is gone.

##### Environment
- Operating System: OSX 10.12.6 / Ubuntu 18.04lts
- JDK version: 1.8.0_202
- Visual Studio Code version: 1.40.1
- Java extension version: ?
- Java Debugger extension version: 0.23.0
--Red Hat extension: 0.53.1

##### Steps To Reproduce

[1]
Download:
https://github.com/clankill3r/vscode-java-debug_broken_example
Have it at the root of the HD so it starts with `/java`!

<img width="137" alt="Screen Shot 2019-11-22 at 16 06 36" src="https://user-images.githubusercontent.com/738650/69436657-17694900-0d42-11ea-80bc-ade5c2155b42.png">

[2]
Open the folder `/java/projects/ws_root`, when you get the message prompt about the workspace folder containing a workspace then click `open workspace`.

[3]
Open the file `nasa/src/doeke_nasa/Nasa.java`, and press `F5` to run it.
The first time it should print "here" in the debug console.

[4]
Close VSCode, start VSCode again and try to run the same file again. Now you will get an:

> Build failed, do you want to continue? 
> 
> Source: Debugger for Java (Extension)

[5]
Close VSCode,
Remove the workspace storage,
Start VSCode again, and run again, now it should work again.

##### Current Result
Build failed message

##### Expected Result
Have everything working fine

##### Additional Informations
-

**Comment by testforstephen** [comment]
By the design of current [vscode-java](https://github.com/redhat-developer/vscode-java) extension, actually `/java/projects/ws_root/.classpath` is not visible to java files in the other folder `nasa/src/doeke_nasa/Nasa.java`, so the Nasa.java will report library missing, and unresolved type error.

We're designing a new approach to manage the library for VS Code java project. Keep a watch at issue https://github.com/microsoft/vscode-java-dependency/issues/174

**Comment by clankill3r** [comment]
Will that mean, once that is out that I need a new `.classpath` for every project, but that I can point to folders instead of individual jar files, making the life a bit more easy?

**Comment by testforstephen** [comment]
The shared libraries would be saved in VS Code user settings, so that the VS Code workspace is able to share them.

**Comment by clankill3r** [comment]
That sounds awesome!

**Comment by jdneo** [comment]
Here is the update: https://github.com/microsoft/vscode-java-dependency/issues/174#issuecomment-573491623

**Comment by clankill3r** [comment]
I wanted to point out that removing the VSCode workspace storage to get rid off all errors no longer works.

Now I have to visit all the files to get rid of the errors and make sure to not close VSCode.

![2020-03-26 12 25 10](https://user-images.githubusercontent.com/738650/77641849-041ef200-6f5d-11ea-87ad-555df17aa964.gif)

**Comment by testforstephen** [comment]
This is a classpath issue, and now we allow you to use setting to customize the classpath for the no-buildtool project.

Go to .vscode/settings.json of your workspace folder, you can explicitly specify source roots and referenced libraries.
```json
{
    "java.project.sourcePaths": [
        "src/main",
        "src"
    ],
    "java.project.referencedLibraries": [
        "lib/**/*.jar"
    ]
}
```

I'm closing it, feel free to reopen it if your issue is not resolved.
