### ISSUE TITLE
Unhappy "Run Java" experience

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-java-debug#724]
As filled by @jrieken here https://github.com/microsoft/vscode/issues/86086

* open java-12 dev container
* rename .vscode folder to .vscode-off
* open debug viewlet, select "Run with Java"
* 🐛 no run... there is a progress message about generating configuration and a launch.json file is shown but that is all...

My comment: This is up to the Java extension, they can handle the No Workspace Run however the extension wants. I suggest that the Java extension handles run more gracefully and if the `launch.json` can get generated the program could be run as well. as part of the experience.

@testforstephen let me know what you think

**Comment by testforstephen** [comment]
What's the expected behavior with **Run with Java** button? Run the active Java file directly? 

Besides, if the active Java file doesn't include main method, it won't able to run directly. But **Run with Java** button is also enabled. What to do for this case?

**Comment by isidorn** [comment]
I think the expected would be to try to figure out the project and the same way you generate the `launch.json` you can generate one in memory and just start running using that in memory launch configuration.
So you would pick a java file that includes a main method ideally.

At least from my point of view that makes the most sense.

**Comment by testforstephen** [comment]
Make sense.

One stupid question about the sequence of the buttons. Is there any reason to put **Debug with Java** in front? Because from our statistics, run is more commonly used than debug.

**Comment by isidorn** [comment]
That is interesting data and definetely not a stupid question. If you have more statistics to share that would be very useful to us.
We first put Debug becuase Debug is a more polished experience. In order to put Run in front we would first like to improve the overall run experience which is captured via this issue https://github.com/microsoft/vscode/issues/85759
Once we have that I would not mind having Run in front.

**Comment by testforstephen** [comment]
In the latest improvement, the run entries such as `F5`, code lens and `Run` context menu will run the program directly without generating launch.json file.
![runJava](https://user-images.githubusercontent.com/14052197/71429039-83531e80-26ff-11ea-9481-06783d12cce6.gif)

If you want to persist the launch config, you need click `create a launch.json file` button in the debug viewlet. 
![image](https://user-images.githubusercontent.com/14052197/71429065-b2699000-26ff-11ea-93d7-174492161fb0.png)

**Comment by isidorn** [comment]
Sounds good to me, thanks!
