### ISSUE TITLE
Attach source in remote debug

### ISSUE THREAD

**Issue by yedane** [microsoft/vscode-java-debug#729]
##### Environment
- Operating System: Win 10
- JDK version: 8
- Visual Studio Code version: 1.40.2
- Java extension version: 0.54.2
- Java Debugger extension version: 0.23.0

After attaching my debugger to my remote server application, I can only debug with my main project, but I would like to enter on source attached, it's like the debugger doens't for the extra sources. 

Is specific configuration or project structure needed ? 
Is there any logs that I can check ? 

    {
      "type": "java",
      "name": "Debug",
      "request": "attach",
      "hostName": "43.9.99.222",
      "port": 8000,
      "projectName": "rest",
      "sourcePaths": [
        "D:/xxxxx/ddddd/ws_rest/stcws_rest_aaa/int/src",
        "D:/xxxxx/ddddd/ws_rest/stcws_rest_bbb/int/src",
        "D:/xxxxx/ddddd/ws_rest/stcws_rest_ccc/int/src",
        "D:/xxxxx/ddddd/ws_rest/stcws_rest_ddd/int/src"
        ]
    },

**Comment by testforstephen** [comment]
YES, `sourcePaths` option in launch.json is used to specify extra source paths. From the info you provided, i didn't see anything wrong. Could you share a sample project for us to reproduce it?

**Comment by yedane** [comment]
Sorry, 
I cannot reproduce it on a sample project.
Actually I have two projects which have extra sources, the first one work fine but the second not.
The first one launch.json is as below: 
{
      "type": "java",
      "name": "Debug",
      "request": "attach",
      "hostName": "43.9.99.222",
      "port": 8000,
      "projectName": "stcws_aaaaa",
      "sourcePaths": [
        "D:/xxxxx/ccccc/ws/stcws_aaaaa/int/src",
        "D:/xxxxx/ccccc/ws/stcws_bbbbb/int/src",
        "D:/xxxxx/ccccc/ws/stcws_ccccc/int/src",
        "D:/xxxxx/ccccc/ws/stcws_ddddd/int/src",
        "D:/xxxxx/ccccc/ws/stcws_eeeee/int/src",
        ]
    }

Is the problem come from my project structure ? 
How can I check it ?

**Comment by testforstephen** [comment]
Maybe. A reproducible sample project would help us to investigate the root cause.

**Comment by tarekahf** [comment]
I am facing exactly the problem. See details in the link below: 

https://stackoverflow.com/q/75304937/4180447

Any update would be greatly appreciated.
