### ISSUE TITLE
String variable cannot be copied because it's trimmed by debugger

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#73]
![image](https://user-images.githubusercontent.com/14052197/30947731-e65dfc9e-a43d-11e7-96a1-3dc62a6a9f0f.png)

For this case, i want to copy the string variable to a txt and compare it with another program result. But the debugger gives me a trimmed string instead of the complete string. And the user doesn't have any other way to get the full string.

We need figure out how to handle the long string variable more reasonably.

**Comment by andxu** [comment]
https://github.com/Microsoft/vscode-java-debug/pull/81
