### ISSUE TITLE
Run/Debug with a custom JVM

### ISSUE THREAD

**Issue by rustyx** [microsoft/vscode-java-debug#731]
Is it possible to run/debug a Java main class using a JVM other than the `java.home` JVM? I couldn't find a launch setting for a custom JVM.

If not, would it be possible to implement this feature?

I want it because I want to run trava-jdk-11-dcevm, under which the VSCode Java language server fails to start. So I want to run only my debug session with it.

**Comment by testforstephen** [comment]
Not supported. Could you open an issue against [vscode-java](https://github.com/redhat-developer/vscode-java/issues) about Java language server fails to start in trava-jdk-11-dcevm,?

**Comment by testforstephen** [comment]
See https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements#setting-the-jdk, you can use the user setting `"java.configuration.runtimes"` to add a new JDK for your project.
