### ISSUE TITLE
Cannot find or load main class when set shortenCommandLine to argfile on Linux

### ISSUE THREAD

**Issue by pl07** [microsoft/vscode-java-debug#737]
##### Environment
- Operating System:linux
- JDK version:1.8.0_181
- Visual Studio Code version:1.41.1
- Java extension version:0.55.1
- Java Debugger extension version:0.24.0

##### Steps To Reproduce
1. Open testprojects/longclasspath.
2. Create launch.json, add "shortenCommandLine": "argfile".
3. Press F5 to debug it.

##### Current Result
![image](https://user-images.githubusercontent.com/46642771/71441556-e616db00-273c-11ea-802c-3d28ab367334.png)

##### Expected Result
![image](https://user-images.githubusercontent.com/46642771/71441608-2413ff00-273d-11ea-8393-f0e108acf069.png)

**Comment by testforstephen** [comment]
`argfile` is not supported in java 8. You must use it in java 9 and above.
