### ISSUE TITLE
How to run to cursor

### ISSUE THREAD

**Issue by kuafuwang** [microsoft/vscode-java-debug#739]
The project didn't support GotoTargets  request .
But I debug on vscode. It can go to cursor.
How can I make the debugger  run to cursor.

**Comment by testforstephen** [comment]
`Run to Cursor` works for me.

Move the cursor to the target line, and click the context menu "Run to Cursor", it will run your program to the target line.

**Comment by kuafuwang** [comment]
I'm going to using java.debug on our IDE. I want to know how to impliment run to cursor.  At firs  i thought it may using the GotoTargets request. But i find out the  request didn't impliment in java.debug
``

**Comment by kuafuwang** [comment]
> `Run to Cursor` works for me.
> 
> Move the cursor to the target line, and click the context menu "Run to Cursor", it will run your program to the target line.

I'm going to using java.debug on our IDE. I want to know how to impliment run to cursor. At firs i thought it may using the GotoTargets request. But i find out the request didn't impliment in java.debug
```INITIALIZE("initialize", InitializeArguments.class),
        LAUNCH("launch", LaunchArguments.class),
        ATTACH("attach", AttachArguments.class),
        DISCONNECT("disconnect", DisconnectArguments.class),
        CONFIGURATIONDONE("configurationDone", ConfigurationDoneArguments.class),
        NEXT("next", NextArguments.class),
        CONTINUE("continue", ContinueArguments.class),
        STEPIN("stepIn", StepInArguments.class),
        STEPOUT("stepOut", StepOutArguments.class),
        PAUSE("pause", PauseArguments.class),
        STACKTRACE("stackTrace", StackTraceArguments.class),
        RESTARTFRAME("restartFrame", RestartFrameArguments.class),
        SCOPES("scopes", ScopesArguments.class),
        VARIABLES("variables", VariablesArguments.class),
        SETVARIABLE("setVariable", SetVariableArguments.class),
        SOURCE("source", SourceArguments.class),
        THREADS("threads", ThreadsArguments.class),
        SETBREAKPOINTS("setBreakpoints", SetBreakpointArguments.class),
        SETEXCEPTIONBREAKPOINTS("setExceptionBreakpoints", SetExceptionBreakpointsArguments.class),
        SETFUNCTIONBREAKPOINTS("setFunctionBreakpoints", SetFunctionBreakpointsArguments.class),
        EVALUATE("evaluate", EvaluateArguments.class),
        COMPLETIONS("completions", CompletionsArguments.class),
        RUNINTERMINAL("runInTerminal", RunInTerminalRequestArguments.class),
        REDEFINECLASSES("redefineClasses", RedefineClassesArguments.class),
        EXCEPTIONINFO("exceptionInfo", ExceptionInfoArguments.class),
        UNSUPPORTED("", Arguments.class)`
Look there is no gototarget request in you code. So i need you help ,how do you implement run to cursor.

**Comment by kuafuwang** [comment]
[RunToCursorAction](https://github.com/microsoft/vscode/blob/2f72da18a62a46578968e20e169d8d902594b85d/src/vs/workbench/contrib/debug/browser/debugEditorActions.ts)
I find  the answer here.
