### ISSUE TITLE
First time debug DYLD_LIBRARY_PATH & LD_LIBRARY_PATH not set

### ISSUE THREAD

**Issue by AustinShalit** [microsoft/vscode-java-debug#742]
The first time a debug task is run the debugger does not load the DYLD_LIBRARY_PATH or the LD_LIBRARY_PATH env variables from the launch.json file.

##### Environment
- Operating System: macOS 10.15.2
- JDK version: 13.0.1
- Visual Studio Code version: 1.41.1
- Java extension version: 0.8.1
- Java Debugger extension version: 0.24.0

##### Steps To Reproduce
1. Clone this minimum example repo: https://github.com/ThadHouse/JavaEnvTest
2. Run the Debug (Launch) - Current File task on Main.java. Do NOT close the debug console.
3. Observe output
4. Run the Debug (Launch) - Current File task again
4. Observe output

https://github.com/ThadHouse/JavaEnvTest

```
git/JavaEnvTest [ /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:54616 --enable-preview -Dfile.encoding=UTF-8 -cp "/Users/austinshalit/Library/Application Support/Code/User/workspaceStorage/9f22dc02e5fc3a676a98917a1ffd479a/redhat.java/jdt_ws/JavaEnvTest_5258814c/bin" Main 
null
null
MyVal
git/JavaEnvTest [ cd /Users/austinshalit/git/JavaEnvTest ; env LD_LIBRARY_PATH=LdPath DYLD_LIBRARY_PATH=DyldPath TestVar=MyVal /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:54619 --enable-preview -Dfile.encoding=UTF-8 -cp "/Users/austinshalit/Library/Application Support/Code/User/workspaceStorage/9f22dc02e5fc3a676a98917a1ffd479a/redhat.java/jdt_ws/JavaEnvTest_5258814c/bin" Main 
LdPath
DyldPath
MyVal
```

##### Current Result

DYLD_LIBRARY_PATH and LD_LIBRARY_PATH env variables not loaded on first debugging session.

##### Expected Result

All env variables always loaded.

**Comment by testforstephen** [comment]
Cannot reproduce it both in my Mac and Windows 10.

One weird thing is `MyVal` is printed correctly in the first launch. Right?

**Comment by AustinShalit** [comment]
Correct. MyVal is always printed correctly. I've only seen this happen on macOS. What version of macOS is your Mac running?

**Comment by testforstephen** [comment]
Here is my environment:
- macOS 10.15.2 Catalina
- OpenJDK 11
- VS Code 1.41.1
- Terminal: zsh
- Java Debugger extension version: 0.24.0

**Comment by AustinShalit** [comment]
That is almost the same as me except for OpenJDK.  Do you have SIP enabled?

**Comment by AustinShalit** [comment]
`csrutil status` returns `System Integrity Protection status: enabled.` for me

**Comment by testforstephen** [comment]
it's disabled for me.

**Comment by AustinShalit** [comment]
That is probably what is causing the difference in results. I just tested on another computer (specs below) and got the same results as when I was testing earlier. This computer also has SIP enabled.


Operating System: macOS 10.14.6
JDK version: 11.0.5
Visual Studio Code version: 1.41.1
Java extension version: 0.8.1
Java Debugger extension version: 0.24.0

**Comment by AustinShalit** [comment]
Just poking around the code, this seems like it is actually an issue in https://github.com/microsoft/vscode and not in the extension itself?

**Comment by testforstephen** [comment]
Could you link the related vscode issue here?

**Comment by AustinShalit** [comment]
Well... I mean that I should open an issue there if you agree that it is an upstream issue.

**Comment by testforstephen** [comment]
oh, hold on first. Need find out the root cause and then assign to the right product.

**Comment by AustinShalit** [comment]
Just checking in to see if a root cause had been found.

**Comment by testforstephen** [comment]
Could you try the same scenario for node.js? I need make sure whether it's a common issue for all languages.

app.js code snippet:
```javascript
console.log(process.env.DYLD_LIBRARY_PATH);
console.log(process.env.LD_LIBRARY_PATH);
console.log(process.env.MyVal);
```

Launch.json sample:
```json
{
	"type": "node",
	"request": "launch",
	"name": "Launch Program",
	"program": "${workspaceFolder}/app.js",
	"console": "integratedTerminal",
	"env": {
		"LD_LIBRARY_PATH": "LdPath",
		"DYLD_LIBRARY_PATH": "DyldPath",
		"TestVar": "MyVal"
	}
}
```

**Comment by AustinShalit** [comment]
This same behavior is exhibited when using node.js. I had to modify your last log print to print `process.env.TestVar` instead of `MyVal`.  Here is the console out:
```
Downloads/NodeTest [ /usr/local/bin/node --inspect-brk=26072 app.js                                                                                                                                            ] 8:38 AM
Debugger listening on ws://127.0.0.1:26072/c4a78ce0-d855-4d88-83b9-914fc1a404a3
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
undefined
undefined
MyVal
Waiting for the debugger to disconnect...
[1]    1870 killed     /usr/local/bin/node --inspect-brk=26072 app.js
Downloads/NodeTest [ cd /Users/austinshalit/Downloads/NodeTest ; env LD_LIBRARY_PATH=LdPath DYLD_LIBRARY_PATH=DyldPath TestVar=MyVal /usr/local/bin/node --inspect-brk=47526 app.js                            ] 8:38 AM
Debugger listening on ws://127.0.0.1:47526/771baf86-ad34-4dec-b233-9eedcdf0fe64
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
DyldPath
LdPath
MyVal
Waiting for the debugger to disconnect...
[1]    1881 killed     env LD_LIBRARY_PATH=LdPath DYLD_LIBRARY_PATH=DyldPath TestVar=MyVal   app.js
```

**Comment by testforstephen** [comment]
So it's a common VS Code issue, could you help open an issue in the upstream https://github.com/microsoft/vscode/issues

**Comment by AustinShalit** [comment]
Sure. It looks like https://github.com/microsoft/vscode/issues/88306 is similar enough so I left a comment on it.

**Comment by AustinShalit** [comment]
@testforstephen Do you think that issue describes what is occurring accurately or should I open a new one?

**Comment by AustinShalit** [comment]
This was fixed upstream. Thank you for the assistance.
