### ISSUE TITLE
Java 11 features not supported?

### ISSUE THREAD

**Issue by feeho** [microsoft/vscode-java-debug#743]
[provide a description of the issue]

##### Environment
- Operating System:win10
- JDK version:oracle jdk 13
- Visual Studio Code version:newest
- Java extension version:0.8.1
- Java Debugger extension version:0.24.0

There is my code :
public static void main(String[] args) {
        var s = "Hello Java 11";
        System.out.println(s);
    }

It show "var cannot be resolved to a type" when I run the code.

**Comment by akaroml** [comment]
Thanks for reaching out @feeho.

We support all newer versions of Java. But you need to turn them on in your project settings like this:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.0</version>
    <configuration>
        <release>11</release>
    </configuration>
</plugin>
```

Here's a tutorial about this:
https://winterbe.com/posts/2018/08/29/migrate-maven-projects-to-java-11-jigsaw/
