### ISSUE TITLE
No need to resolve variables in debug configs

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-java-debug#750]
In VS Code 1.42 we will introduce a new hook `resolveDebugConfigurationWithSubstitutedVariables` in the extension API that receives the debug configuration with all variables resolved.

So there is no need to resolve the variables yourself anymore [here](https://github.com/microsoft/vscode-java-debug/blob/5f15f9ab721b5be455d33d23952031a57df1744c/src/configurationProvider.ts#L49).

**Comment by akaroml** [comment]
Perfect! @weinand thanks for the info. We'll follow up.
