### ISSUE TITLE
Consider to use the DebugAdapterDescriptorFactor

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-java-debug#751]
Instead of making VS Code start new debug sessions by connecting to a port via [this code](https://github.com/microsoft/vscode-java-debug/blob/5f15f9ab721b5be455d33d23952031a57df1744c/src/configurationProvider.ts#L225) we suggest that you use the official API that we've introduced for this use case.

Mock debug shows how the DebugAdapterDescriptorFactory can be used to [start a server and make VS Code connect to it](https://github.com/microsoft/vscode-mock-debug/blob/28b4fde41228b0aabe93eab9064992e276859405/src/extension.ts#L118-L142).

The factory can be registered for Java in the extension's activate function like this:
```js
context.subscriptions.push(vscode.debug.registerDebugAdapterDescriptorFactory('java', factory));
```

**Comment by akaroml** [comment]
@weinand thanks for the info. We'll follow up.

**Comment by weinand** [comment]
@testforstephen thanks a lot
