### ISSUE TITLE
ignore unknown source in stepFilters

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode-java-debug#757]
Is there a way to ignore code when the source is unknown?

![image](https://user-images.githubusercontent.com/14079228/74163010-b7bb6500-4bef-11ea-807d-f6d8439c4191.png)

```
"stepFilters": {
    "classNameFilters": [
        "java.*",
        "javax.*",
        "com.sun.*",
        "sun.*",
        "sunw.*",
        "org.omg.*"
    ],
    "skipSynthetics": false,
    "skipStaticInitializers": false,
    "skipConstructors": false
}
```

##### Environment
- Operating System: Win10
- JDK version: 
- Visual Studio Code version: 1.41.1
- Java extension version: 0.55.1
- Java Debugger extension version: 0.24.0

##### Current Result
The debugger is breaking

![image](https://user-images.githubusercontent.com/14079228/74163183-02d57800-4bf0-11ea-9758-240e2b36fae9.png)

##### Expected Result
The debugger shouldn't break

**Comment by testforstephen** [comment]
The unknown source generally happens in the libraries. Currently you need manually add the package pattern from the library of missing source to the stepFilters. Besides, you could attach missing source to the library, see more details here https://github.com/redhat-developer/vscode-java/issues/233#issuecomment-438486647

We have plan to improve the experience for "Just My Code" requirement, but it may not happen immediately.

**Comment by spottedmahn** [comment]
Hi @testforstephen - thanks for the reply 🤝

>Currently you need to manually add the package pattern from the library of the missing source to the `stepFilters`

Hmm, sounds like you're saying I can ignore this code w/ `stepFilters`, correct?  Can you provide a concrete example or point me in the direction of a wiki/readme page that describes this?  Thanks!

**Comment by testforstephen** [comment]
No, `stepFilters` didn't serve for caughtException/UncaughtException breakpoint. This option is used to skip the specified classes or methods when you step into a stack frame. It cannot help you to ignore the Unknown Source.

If you want to learn more about the `stepFilters` use case, see here https://github.com/microsoft/vscode-java-debug/blob/master/Configuration.md#dont-step-into-the-specified-classes-or-methods

**Comment by spottedmahn** [comment]
>No, `stepFilters` didn't serve for caughtException/UncaughtException breakpoint.

Ok, thanks for your help 😀!  Hopefully, #756 will get implemented sooner than later!
