### ISSUE TITLE
[Junit] Junit support for java debug

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#76]

**Comment by ansyral** [comment]
1 language server generate and resolve junittest codelens
2 investigate junit interface for invoking a test in commandline
3 customized junit test runner which could run/debug test suites and print test structure and test duration, test status(failure with stacktrace)
4 vscode extension adds commands for junittest run/debug codelens

**Comment by ansyral** [comment]
https://github.com/eclipse/eclipse.jdt.ls/pull/420

**Comment by claycephas** [comment]
Regarding 2. [JUnitCore](http://junit.sourceforge.net/javadoc/org/junit/runner/JUnitCore.html) allows for running a single class. But it looks like you might need [another solution](https://stackoverflow.com/questions/9288107/run-single-test-from-a-junit-class-using-command-line) in order to run a specific method.

**Comment by ansyral** [comment]
@claycephas  JunitCore doesn't provide a way to run a single test, so we have to provide a customized junit  runner. About how to run a single test, i 'm thinking to use this method : http://junit.sourceforge.net/javadoc/org/junit/runner/Request.html#method(java.lang.Class, java.lang.String)

**Comment by claycephas** [comment]
Yes, I think you could use the [Request class](http://junit.sourceforge.net/javadoc/org/junit/runner/Request.html) together with [JUnitCore](http://junit.sourceforge.net/javadoc/org/junit/runner/JUnitCore.html). Something like this.

When running a single method from method code lens:
```
new JUnitCore(Request.method(MyClass.class, "methodName"))
```

When running an entire class from class code lens:
```
new JUnitCore(Request.aClass(MyClass.class))
```

**Comment by yaohaizh** [comment]
This feature is on This feature is on https://github.com/Microsoft/vscode-java-test
