### ISSUE TITLE
Ignoring settings for Java version

### ISSUE THREAD

**Issue by chriscamplejohn** [microsoft/vscode-java-debug#768]
I have JAVA_HOME set to /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
I also have "java.home": "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home" in my user configuration file.

##### Environment
- Operating System: macOS Catalina 10.15.1
- JDK version: Multiple (AdoptOpenJDK 11, AdoptOpenJDK 8, Java SE 8)
- Visual Studio Code version: 1.42.1
- Java extension version: 0.25.0

##### Steps To Reproduce
1. Set the settings detailed above with the above JDKs installed
2. Debug or Run a Java application

##### Current Result
Runs with Open JDK 11.
<img width="1145" alt="Java Version Issue" src="https://user-images.githubusercontent.com/2816218/75444456-5f0ffa00-595b-11ea-9e07-f83105cca153.png">

##### Expected Result
Runs with Open JDK 8.

##### Additional Informations
When I run the same project with IntelliJ it happily picks up my JAVA_HOME environment variable and uses the correct version of Java.

**Comment by testforstephen** [comment]
Could you share us the following info?

- In VS Code, run **Help -> Open Process Explorer**, Copy All and share the process explorer data.
- What Java version is your project using? Debugger 0.25.0 adds a feature to use the project's Java runtime to launch the application.

**Comment by chriscamplejohn** [comment]
So...having closed the application in IntelliJ, closed vs code, re-opened the project in vs code to get the process explorer data, it has now picked up the correct version. I has closed down vs code before, so not sure what has changed this time. What do you mean by what Java version is my project using? It is built with gradle and no specific version of Java is set anywhere other than the places I outlined.

![image](https://user-images.githubusercontent.com/2816218/75965714-19a27e00-5ec1-11ea-990a-a1092c774bd2.png)

**Comment by testforstephen** [comment]
> What do you mean by what Java version is my project using? It is built with gradle and no specific version of Java is set anywhere other than the places I outlined.

For gradle project, it will use the current JVM version if you didn't specify java version explicitly. So you cannot reproduce the issue, right?

**Comment by chriscamplejohn** [comment]
No - not at present.
