### ISSUE TITLE
debug attach error

### ISSUE THREAD

**Issue by spiritelf** [microsoft/vscode-java-debug#770]
[provide a description of the issue]

##### Environment
- Operating System:windows7
- JDK version:1.8
- Visual Studio Code version:1.41.1
- Java extension version:0.8.1
- Java Debugger extension version:0.25.0

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
"version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "tomcat-attach",
            "request": "attach",
            "hostName": "localhost",
            "port": 8000
        }
  ]

error:
Running the contributed command: 'java.execute.workspaceCommand' failed.

**Comment by testforstephen** [comment]
Does this error always exist? Could you reload vscode and try again?

**Comment by spiritelf** [comment]
reload is ok




| |
hq-power
|
|
邮箱：hq-power@163.com
|

Signature is customized by Netease Mail Master

On 03/05/2020 11:05, Jinbo Wang wrote:

Does this error always exist? Could you reload vscode and try again?
