### ISSUE TITLE
Debug Java13Feature cannot hit breakpoint

### ISSUE THREAD

**Issue by pl07** [microsoft/vscode-java-debug#773]
#### Environment
- Operating System: win, mac, linux
- JDK version: 13.0.1
- Visual Studio Code version: 1.42.1
- Java extension version: 0.58.0
- Java Debugger extension version: 0.25.0

#### Steps To Reproduce
1. Open singlefolderdemo
2. Add breakpoint and debug Java13Feature

#### Current Result
Debug the file cannot hit the breakpoint
#### Expected Result
Debug the file should stop at the breakpoint

**Comment by testforstephen** [comment]
i can reproduce it.

**Comment by testforstephen** [comment]
The root cause is the class using Java 13 text blocks, which is a new syntax. The current ASTParser just sets the highest version to 9. Update ASTParser version would fix it.
