### ISSUE TITLE
In multi-root workspace, source paths of one project also contain paths of other projects, should be excluded

### ISSUE THREAD

**Issue by emvau** [microsoft/vscode-java-debug#776]
##### Environment
- Operating System: Win 10 x64
- JDK version: corretto-jdk-8.232.09.1-x64
- Visual Studio Code version: 
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

- Java extension version: 0.58.0
- Java Debugger extension version: 0.25.1

##### Steps To Reproduce
1. Set up a multi-root workspace in VS Code with 3 projects (or "roots").
2. In one of the projects create a .vscode/launch.json with a debug configuration
3. Having the multi-root workspace opened, launch this debug configuration

##### Current Result
Java compilation fails ("Problems" tab) because of errors in another project which is also part of the multi-root workspace.

##### Expected Result
Other projects are not considered (i.e. they are not included in the compilation's java source paths).
Acc. to https://code.visualstudio.com/docs/java/java-debugging#_configuration, at the "sourcePaths" argument's description, "The debugger looks for source code from project settings by default." - and I expect the "project" to be 1 of my 3 projects in my multi-root workspace, not the whole workspace.

##### Additional Informations
Manually setting the sourcePaths argument could be an option (didn't check it yet), but IMO the docs should still be clarified in that way.

**Comment by testforstephen** [comment]
The build service is provided by the extension [Language Support for Java by RedHat](https://github.com/redhat-developer/vscode-java/issues). Currently it only supports building the whole workspace, not provide lower granularity control at which root or project. So this feature will need make the upstream extension to expose the more control at the building command first.

**Comment by emvau** [comment]
@testforstephen, thx for the analysis

Meanwhile I made my setup work by adding the problematic projects to the above extension's exclusions in workspace settings:
```
"settings": {
    "java.import.exclusions":[
      "**/node_modules/**",
      "**/.metadata/**",
      "**/archetype-resources/**",
      "**/META-INF/maven/**",
      "**/problematic-project1/**",
      "**/problematic-project2/**"
    ],
```
This works for my special case and I now believe that "the right way" would be to first fix the problems of the workspace's projects before complaining about the Language Support Extension missing a feature to have these problems ignored, that is, supporting my laziness to fix them.

= Closing this issue. Feel free to reopen if you still consider this feature as valuable.
