### ISSUE TITLE
Java Debugger not able to evaluate Java Expression in Vaadin Spring-Boot project

### ISSUE THREAD

**Issue by underscores** [microsoft/vscode-java-debug#781]
The Java Debugger is not able to WATCH Java Expressions. It is not possible to do this in the Debug Console or the WATCH side-window. This Project is a Vaadin-Spring tutorial project we created for educational purposes for our apprentices and adds a Data Grid to a HomeView as well as an H2 Database Backend. 

The error message is always the same:
Cannot evaluate because of compilation error(s): Evaluations must contain either an expression or a block of well-formed statements.

##### Environment
- Operating System: Windows 10
- JDK version: 1.11
- Visual Studio Code version: 1.43.1
- Java extension version: 0.8.1
- Java Debugger extension version: 0.25.1

##### Steps To Reproduce
1. Add Breackpoint to particular Code-Block
2. Run Debugger
3. Add a Java statement to the 

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Error Message: "Cannot evaluate because of compilation error(s): Evaluations must contain either an expression or a block of well-formed statements."
##### Expected Result
The return value of the expression
##### Screenshots
![vs_code_completion](https://user-images.githubusercontent.com/9943925/77046275-eed91f00-69c2-11ea-99d7-cefd5e48f8cd.png)

![vs_code_error_console](https://user-images.githubusercontent.com/9943925/77046250-e4b72080-69c2-11ea-9854-9414278793ff.png)

##### Additional Informations
[vaadin-workshop-starter-master-debug.zip](https://github.com/microsoft/vscode-java-debug/files/4353411/vaadin-workshop-starter-master-debug.zip)

**Comment by testforstephen** [comment]
i saw `btDelete` is a local variable defined in a lambda expression. Evaluating lambda expression is not supported yet. This is a known issue https://github.com/microsoft/vscode-java-debug/issues/754.

**Comment by underscores** [comment]
Ah okay, thanks for the information. I guess we can close the bug than since it was already reported.
