### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by BrianKiarieMwaniki** [microsoft/vscode-java-debug#784]
Issue Type: <b>Bug</b>

Every time I run a java program I get a "Build Failed, do you want to continue?"
The nofication also indicates that the source of my issue is the --Debugger for Java(Extension)

Extension version: 0.25.1
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 4.15.0-91-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 1895)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 2|
|Memory (System)|3.79GB (0.12GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by testforstephen** [comment]
The debugger just invoked the command provided by vscode-java extension. Duplicated with [redhat-developer/vscode-java#495](https://github.com/redhat-developer/vscode-java/issues/495). Please provide a sample project to reproduce this issue.
