### ISSUE TITLE
How to debug the class in jar without source package? It seems to be useless to set a breakpoint

### ISSUE THREAD

**Issue by alfred-ac** [microsoft/vscode-java-debug#786]
[provide a description of the issue]

##### Environment
- Operating System:win7
- JDK version:1.8
- Visual Studio Code version:1.43.2
- Java extension version:0.8.1
- Java Debugger extension version:0.25.1

##### Steps To Reproduce
1. set a breakpoint at class in jar without source package
2. debug

**Comment by testforstephen** [comment]
When supporting line breakpoint, we must know which location to enable a breakpoint. When your class doesn't contain source code, i don't believe the debugger has the ability to set the breakpoint at the correct location.
