### ISSUE TITLE
The declared package "org.sonatype.nexus.internal.app" does not match the expected package "src.main.java.org.sonatype.nexus.internal.app

### ISSUE THREAD

**Issue by jeffzhu503** [microsoft/vscode-java-debug#791]
I am opening two different github Java projects in VSCode.  
https://github.com/sonatype/nexus-public
https://github.com/apache/archiva
In the nexus-public project, I always hit the error message as 'The declared package "org.sonatype.nexus.internal.app" does not match the expected package "src.main.java.org.sonatype.nexus.internal.app'.  But the second project has no problem.  
In Nexus-public, the correct behavior is Code shall parse src.main.main just as the folder in the Java Dependencies.  Instead Code see "src.main.java" as part of the classpath.
I tried to compare these two projects and don't see the difference.  Any help? 

##### Environment
- Operating System: Mac Pro
- JDK version: 1.8
- Visual Studio Code version:  1.44.0
- Java extension version: Java Exension Pack 0.8.1
- Java Debugger extension version: 0.25.1

##### Steps To Reproduce
git clone two projects
open the project at the root.  

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
the error message as 'The declared package "org.sonatype.nexus.internal.app" does not match the expected package "src.main.java.org.sonatype.nexus.internal.app'. 
##### Expected Result
Nexus-public shall not have this compile error.

**Comment by testforstephen** [comment]
This error is reported by https://github.com/redhat-developer/vscode-java/issues, could you open an issue there?
