### ISSUE TITLE
import spring-boot project，can‘t start

### ISSUE THREAD

**Issue by spiritelf** [microsoft/vscode-java-debug#792]
[provide a description of the issue]

i report in https://github.com/spring-projects/sts4/issues/448#issue-599676594

https://github.com/redhat-developer/vscode-java/issues/1392#issue-599690617

sprint-boot dashboard depends on the java debugger extension to run. 

there is something wrong for   java debugger extension？

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Additional Informations
i find some log  C:\Users\huang\AppData\Roaming\Code\User\workspaceStorage\e406f8770b36c6011c6c8dcbb6ca3f3f\redhat.java\ss_ws\.metadata\\.log

!SESSION 2020-04-15 23:33:16.089 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_40
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Command-line arguments:  -data c:\Users\huang\AppData\Roaming\Code\User\workspaceStorage\e406f8770b36c6011c6c8dcbb6ca3f3f\redhat.java\ss_ws

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:33:25.222
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:33:26.000
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:33:26.390
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:33:26.415
!MESSAGE Initializing Java Language Server 0.54.0.202004031121

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:33:26.515
!MESSAGE Creating the Java project jdt.ls-java-project

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:33:26.628
!MESSAGE >> initialized

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:33:30.712
!MESSAGE Finished creating the Java project jdt.ls-java-project

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:33:32.488
!MESSAGE Workspace initialized in 5979ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:33:32.537
!MESSAGE >> initialization job finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:33:32.548
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:33:32.556
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:33:32.568
!MESSAGE >> workspace/didChangeConfiguration

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:34:45.830
!MESSAGE >> shutdown

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:34:46.082
!MESSAGE >> exit

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:34:46.083
!MESSAGE Shutdown received... waking up main thread

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-04-15 23:34:46.178
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is stopping:

**Comment by testforstephen** [comment]
The debugger is only responsible for generating the command line to start your program. Looks like the program ran itself wrong. Unless you can share a sample project to help reproduce the issue, otherwise nothing we can do right now.

**Comment by spiritelf** [comment]
this is  my project，in doc folder for sql

**Comment by spiritelf** [comment]
https://github.com/spiritelf/beam-test

i upload this project

**Comment by martinlippert** [comment]
Due to the Lombok usage of the project I am not able to import that into my environment easily, but what jumped to my eye is your reference to the `local` profile in your IntelliJ launch config. In case that is important, you should make sure that the profile is set there, too (via a system property that you can add to the launch config in your VSCode).

This is just a wild guess, but maybe it helps... :-)

**Comment by spiritelf** [comment]
> Due to the Lombok usage of the project I am not able to import that into my environment easily, but what jumped to my eye is your reference to the `local` profile in your IntelliJ launch config. In case that is important, you should make sure that the profile is set there, too (via a system property that you can add to the launch config in your VSCode).
> 
> This is just a wild guess, but maybe it helps... :-)
which file ?

**Comment by spiritelf** [comment]
![image](https://user-images.githubusercontent.com/8556186/79578142-6603ef00-80f8-11ea-99fd-eb9cb7154ae8.png)

today for this

**Comment by spiritelf** [comment]
> > Due to the Lombok usage of the project I am not able to import that into my environment easily, but what jumped to my eye is your reference to the `local` profile in your IntelliJ launch config. In case that is important, you should make sure that the profile is set there, too (via a system property that you can add to the launch config in your VSCode).
> > This is just a wild guess, but maybe it helps... :-)
> > which file ?

ok,thanks , as you say, i set prod profile  happen this in idea
