### ISSUE TITLE
An error show “Cannot find a class with main method" when run simple gradle project

### ISSUE THREAD

**Issue by pl07** [microsoft/vscode-java-debug#793]
##### Environment
- Operating System: Windows
- JDK version: 1.8.0_231
- Visual Studio Code version: 1.44.1
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1.  Git clone https://github.com/eclipse/eclipse.jdt.ls.git
2. Open eclipse.jdt.ls/org.eclipse.jdt.ls.tests/projects/gradle/simple-gradle
3. Run or debug 

##### Result
![image](https://user-images.githubusercontent.com/46642771/79433968-5acd9800-8000-11ea-8719-ba2d4f17fb98.png)

**Comment by testforstephen** [comment]
i don't think that project contains any main class. Please new a main method there and try again.
