### ISSUE TITLE
Java debugging spring application startup

### ISSUE THREAD

**Issue by mmanashirov** [microsoft/vscode-java-debug#795]
Setting a breakpoint inside a bean definition of a spring configuration class stops at sun.reflect.NativeMethodAccessorImpl.class somewhere in the middle of the stack. The top of the stack where the breakpoint was set is grayed out. Clicking on the grayed out stack frame does not show the code in the editor but does show the variables in that stack frame. Is this a bug or a configuration issue?
Another potentially relevant detail is that this is running through WSL.
![image](https://user-images.githubusercontent.com/6738713/80154007-b19d1980-858c-11ea-8e61-e4dc0cbb9893.png)

##### Environment
- Operating System: Windows 10
- JDK version: OpenJDK Runtime Environment Corretto-8.252.09.1 (build 1.8.0_252-b09)
- Visual Studio Code version: 1.44.2
- Java extension version: 0.9.0
- Java Debugger extension version: 0.25.1

##### Steps To Reproduce
1. Set a breakpoint in a bean definition of a java-based spring configuration class.
2. Start debugging
3. Trigger bean definition to be invoked

##### Additional Information
Only tested when running through WSL remote session. Using WSL 2 with Ubuntu 19.10 as the distro.

**Comment by testforstephen** [comment]
By design. The gray means cannot find the source for the corresponding stack frame code. Please see the issue https://github.com/redhat-developer/vscode-java/issues/233 about how to attach the missing source.
