### ISSUE TITLE
Classes are not reloaded when debugging a Quarkus 1.4 application

### ISSUE THREAD

**Issue by fbricon** [microsoft/vscode-java-debug#796]
##### Environment
- Operating System: Mac OS 10.15.3
- JDK version: AdoptOpenJDK 11.0.6 Hotspot
- Visual Studio Code version: 1.44.0
- Java extension version: 0.60.0
- Java Debugger extension version: 0.25.1

##### Steps To Reproduce
1. Clone this Quarkus 1.4.1 Hello World application: https://github.com/fbricon/onefour/
2. Open in vscode
3. Click the Debug code lens on the [Main class](https://github.com/fbricon/onefour/blob/master/src/main/java/foo/bar/onefour/Main.java#L14) 
4. Hit http://localhost:8080/hello
5. Make some changes in [GreetingResource.hello()](https://github.com/fbricon/onefour/blob/f6a184b4fac22358e8b5b2d10e35f9224d963d55/src/main/java/foo/bar/onefour/GreetingResource.java#L13-L16) (e.g change log output and/or return value), save the file
6. reload http://localhost:8080/hello

The changes should be visible immediately. They're not. This scenario works fine in Eclipse, so there's something fishy with the class replacement here.

**Comment by testforstephen** [comment]
It won't auto HCR by default. Did you click the icon⚡?
![image](https://user-images.githubusercontent.com/14052197/80356075-8166bb00-88ab-11ea-8ca2-942ed36e8d8f.png)

**Comment by fbricon** [comment]
Ok my bad. I totally forgot it was disabled by default.
Added "java.debug.settings.hotCodeReplace": "auto" and it works as in Eclipse now

Why is it disabled by default BTW?

**Comment by testforstephen** [comment]
We want to better expose the feature by explicitly showing a button .
