### ISSUE TITLE
clickable stack trace in java debugger output

### ISSUE THREAD

**Issue by mentaloaf** [microsoft/vscode-java-debug#798]
If I am running in the Java debugger and there is an exception, it would be nice if you could command click on a stack trace element to go to that line of the class you clicked on - just like you can when you are compiling and you click on errors that take you to the source of the compile error.

##### Environment
- Operating System:
macOS 10.14.6
- JDK version:
13+33
- Visual Studio Code version:
1.44.2
- Java extension version:
- Java Debugger extension version:
0.25.1

##### Steps To Reproduce
1. Run a Java program in the debugger which throws an exception and causes a stack trace to be printed to the debugger output window

If possible, it would be great for the Java debugger extension to parse output and make each stack trace element for which it has a source path clickable.  Not sure how easy detection of stack trace output would be but parsing for *Exception: on one line followed by lots of lines with "*at (*.java:###)" might catch most instances.  Thank for for an awesome integrated Java debugger!

**Comment by testforstephen** [comment]
if your output is printed the **TERMINAL**, not supported yet. Not sure whether the upstream VS Code expose the interface for the extensions to render clickable link.

But if your output is printed to **DEBUG CONSOLE**, it already supports jumping to stack trace source code. You can add a user setting `"java.debug.settings.console": "internalConsole"` to make output go to DEBUG CONSOLE.
![image](https://user-images.githubusercontent.com/14052197/80563600-1093e000-8a1e-11ea-9121-6be31256a9f2.png)

**Comment by mentaloaf** [comment]
Yeah I see this works in the debug console.  I should be able to just use that.  Thanks for the guidance!

**Comment by tgodzik** [comment]
@testforstephen Hi, we've been looking into adding jumping to a stack trace source code in out extension, but I can't seem to find how it's being done here. Is it coming from DAP? Is it a specific property or is this handled inside the extension here? It would be awesome if you could give me any hints.

**Comment by tgodzik** [comment]
Ignore me, I found how it's done :smile:

**Comment by testforstephen** [comment]
BTW in the latest debugger, we also support jumping to source code when printing stack trace in the TERMINAL.

**Comment by mentaloaf** [comment]
Oh that’s very good to know thank you for mentioning this!

**Comment by Dmole** [comment]
> BTW in the latest debugger, we also support jumping to source code when printing stack trace in the TERMINAL.

Is there a way to make something like `cat stack.txt` clickable?

**Comment by testforstephen** [comment]
> > BTW in the latest debugger, we also support jumping to source code when printing stack trace in the TERMINAL.
> 
> Is there a way to make something like `cat stack.txt` clickable?

What does it mean to make `cat stack.txt` clickable?

**Comment by testforstephen** [comment]
Such case is already supported by VS Code Java Debugger extension. Java Debugger is able to detect the Java callstack link printed by any command running in VS Code terminal.

**Comment by Dmole** [comment]
> Such case is already supported by VS Code Java Debugger extension. Java Debugger is able to detect the Java callstack link printed by any command running in VS Code terminal.

That's what you said before but I can't seem to get it working with vscjava.vscode-java-debug-0.41.0 
`cat stack.txt` is "any command" and I also tried using `(cat stack.txt >&2 ; exit 1)` and looked through @feature:terminal but can't find what the condition a callstack is linked in VS Code terminal?
