### ISSUE TITLE
If no launch.json is generated yet, press `F5` and choose Java will not start debugging

### ISSUE THREAD

**Issue by yaohaizh** [microsoft/vscode-java-debug#8]
Console Error: 

`
Missing property 'type' for the chosen launch configuration.: Error: Missing property 'type' for the chosen launch configuration.
`

**Comment by rcelebrone** [comment]
I had the same problem but i fixed with setting up the JAVA_HOME (https://stackoverflow.com/a/50206239/4908263).

**Comment by bradparks** [comment]
note, if that didnt work, then click the following menu option, and Visual Studio Code will generate a launch.json for you. 

"Run | Add Configuration"
