### ISSUE TITLE
Error "Cannot determine executable for debug adapter '{0}'." when trying to debug a simple Gradle project.

### ISSUE THREAD

**Issue by qpflxk** [Microsoft/vscode-java-debug#80]
![image](https://user-images.githubusercontent.com/32587873/31313230-0cb9987a-abab-11e7-95ff-e7555f474335.png)

As shown in the snapshot above, just had a simple gradle java project setup following their instruction here (https://guides.gradle.org/building-java-applications/). As long as the java goes, it runs fine and produced a line output in the terminal.

![image](https://user-images.githubusercontent.com/32587873/31313241-548864b0-abab-11e7-9501-4e182dbecf20.png)

However, can't get the debugger to run. Keep getting the error code shown: "Cannot determine executable for debug adapter '{0}'."

![image](https://user-images.githubusercontent.com/32587873/31313252-90aa698e-abab-11e7-9c03-05c701a40333.png)

.classpath and .project files were generated normally

What could be an issue here and how would I be able to resolve it?

Still new to java and Gradle / Maven stuff so might be missing the obvious. So please point it out if I did.
Thank you.

**Comment by andxu** [comment]
The mainClass is wrong, should be "App", but the error message has showed our debug server is not getting started, cannot reproduce on my machine, can you open the console by click help=>Toggle develop tools in vscode, and give us the error log?

{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    
    {
      "type": "java",
      "name": "Debug (Launch)",
      "request": "launch",
      "mainClass": "App",
      "args": ""
    }
  ]
}
![image](https://user-images.githubusercontent.com/17075863/31322610-7cb2ed0c-accd-11e7-9b97-76cdc85cd56f.png)

**Comment by qpflxk** [comment]
I wasn't really sure about that since I have just started JAVA and was used to working with single JAVA file projects. Because I wasn't sure about the mainClass argument, I actually tried that too before posting this.

![image](https://user-images.githubusercontent.com/32587873/31324431-768b6910-ac80-11e7-800b-c73f23349fcb.png)

Still doesn't work.

I will attach the error messages shown in the developer tools section:

![image](https://user-images.githubusercontent.com/32587873/31324524-78309d0c-ac81-11e7-82ad-8ce458111a84.png)

![image](https://user-images.githubusercontent.com/32587873/31324526-7bae3eda-ac81-11e7-9f83-a61344f3ab74.png)

**Comment by andxu** [comment]
I can repro it now on insider version, we will support insider version on 0.2.0 which has the new version of debug protocol, so  now, you can switch to normal version to have a try, I will keep this issue open until the code fix for new version vscode is done.

**Comment by andxu** [comment]
Dup as https://github.com/Microsoft/vscode-java-debug/issues/82
