### ISSUE TITLE
cant set hostname as localhost

### ISSUE THREAD

**Issue by xwzheng1020** [microsoft/vscode-java-debug#800]
[provide a description of the issue]
try to attach hadoop resourcemanager and nodemanager, when use exact ip in `hostname`, all things fine. But when fill the `hostname` with `localhost`, it will emerge: #221 
```
Failed to attach to remote debuggee VM. Reason: com.sun.jdi.connect.spi.ClosedConnectionException
```

##### Environment
- Operating System:   win10 -> ubuntu16.04
- JDK version:  Debugger JVM version: 1.8.0_181    Debuggee JVM version: 1.8.0_242
- Visual Studio Code version:1.44.2
- Java extension version: Language support for Java ™ for Visual Studio Code 0.60.0
- Java Debugger extension version: 0.25.1

##### Steps To Reproduce
my launch.json:
```
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "type": "java",
            "name": "Debug (Launch)",
            "request": "launch",
            "cwd": "${workspaceFolder}/src/main/java",
            "mainClass": "com.leinao.app.App"
        },

        {
            "type": "java",
            "name": "Debug (Attach) - RM - Remote",
            "request": "attach",
            "hostName": "localhost",
            "port": 8000,
        },

        {
            "projectName": "hadoop-yarn-server-nodemanager",
            "type": "java",
            "name": "Debug (Attach)-NM-Remote",
            "request": "attach",
            "hostName": "192.168.22.23",
            "port": 10001,
        },
    ]
}
```

When I choose to debug with "Debug (Attach) - RM - Remote", although the hostname is set to `localhost`, it can attach to debugee. But when I choose to debug with "Debug (Attach)-NM-Remote", I can only set hostname to exact ip.  

The processes of resourcemanager and nodemanager run in the same machine, with the opts:
```
echo 'export YARN_RESOURCEMANAGER_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000"' >> etc/hadoop/yarn-env.sh
echo 'export YARN_NODEMANAGER_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=10001"' >> etc/hadoop/yarn-env.sh
```
```
sbin/yarn-daemon.sh start resourcemanager && sbin/yarn-daemon.sh start nodemanager
```

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by testforstephen** [comment]
Resolving the host name to the ip depends on your system setting. There is not much the debugger can do.

**Comment by testforstephen** [comment]
This looks like a system issue, i'm closing it. Feel free to reopen it if you want more discussion.

**Comment by Erick20000** [comment]
sethostname: usa o miniaplicativo 'Rede' no 'Painel de controle' para definir
o nome do host. alguem poderia me orientar com essa duvida?
