### ISSUE TITLE
Encoding  problem?

### ISSUE THREAD

**Issue by FengTai-Red** [microsoft/vscode-java-debug#813]
Chinese cannot be displayed normally

##### Environment
- Operating System:Windows 10
- JDK version:14.0.1
- Visual Studio Code version:1.45
- Java extension version:Java Extension Pack 0.9.0
- Java Debugger extension version: 0.25.1

##### Steps To Reproduce
My English is poor. I tried to translate it as faithfully as possible.
On my computer,running the code below,return chinese is null.

`import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

public class testA {
    public static void main(String[] args) throws IOException {
        InputStream a = System.in;
        InputStreamReader b = new InputStreamReader(a, "UTF-8");
        BufferedReader br = new BufferedReader(b);
        System.out.println("===Output===");
        System.out.print("输入:");
        String msg = br.readLine();
        System.out.print("输出:" + msg + "\n");
        System.out.println("===Output===");
    }
}`

![A](https://user-images.githubusercontent.com/48521235/81717409-17eecb00-94ad-11ea-9afe-cb061fa30e11.jpg)

**Comment by H749119662** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS D:\File\Java\SXT\02>  & 'c:\Users\User\.vscode\extensions\vscjava.vscode-java-debug-0.25.1\scripts\launcher.bat' 'D:\Software\Java\jdk-14.0.1\bin\java.exe' '-Dfile.encoding=UTF-8' '@C:\Users\User\AppData\Local\Temp\cp_2dq6usd00k9gcoqw4k2itw4jk.argfile' 'testA'
===Output===
输入:中文English
输出:  English
===Output===
PS D:\File\Java\SXT\02> mode

Status for device CON:
----------------------
    Lines:          20
    Columns:        150
    Keyboard rate:  31
    Keyboard delay: 1
    Code page:      65001

PS D:\File\Java\SXT\02>

**Comment by testforstephen** [comment]
The debugger is only responsible for generating the required command line, and the execution and display is controlled by the terminal. So it looks like a terminal or your program issue.

And i manually compile your sample class and run it terminal, it also has the same issue. And no Chinese characters are ignored.
 ```
javac testA.java
java testA
```
