### ISSUE TITLE
documentation - first steps - link to configuration required

### ISSUE THREAD

**Issue by aisbergde** [microsoft/vscode-java-debug#815]
documentation at https://code.visualstudio.com/docs/java/java-debugging is missing some more information how to start

for example a link to
https://code.visualstudio.com/docs/java/java-tutorial

##### Environment
- Operating System: Windows 10
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce

Try to start to use JAVA in VS Code and you will directed to the page:
https://code.visualstudio.com/docs/java/java-debugging

documentation starts with
- install
- Use
  - CodeLens
  
But following these steps it will not work
Before the debugger can be startet the extensions needs to be configured.
Please add a link or a chapter "Configuration" between Install and Use or anywhere in this place.

##### Current Result

some errors about some variables which needs to set when a new user tries to "Debug"

No link at this place is provided which could explain the required configuration

##### Expected Result

a link describing first steps for configuration

##### Additional Informations

I person which never programmed in JAVA (like me) should be able to go step by step to get the debugger enabled.

**Comment by testforstephen** [comment]
> Before the debugger can be started the extensions needs to be configured.

Could you explain a little more about the extensions needs to be configured? Generally when you click the codelens, it's supposed to be able to starting the debugger directly.

**Comment by testforstephen** [comment]
// @yaojinyang

**Comment by yaojinyang** [comment]
[https://code.visualstudio.com/docs/java/java-debugging]https://code.visualstudio.com/docs/java/java-debugging)

Document is updated per feedback. @aisbergde thanks for the feedback.

**Comment by testforstephen** [comment]
Since the document has addressed the feedback, close it. Thank @yaojinyang for the update.
