### ISSUE TITLE
Bug Exception stack missing link

### ISSUE THREAD

**Issue by kkyeer** [microsoft/vscode-java-debug#816]
**Environment:**

- VS Code Version: 1.45.1
- Extension Version: 0.9.1
- JDK Type & Version:  Oracle jdk 1.8.0_251
- OS Type & Version:Windows10

**Step to Reproduce:**
spring boot web environment  ,in any controller,log exception stack to debug console

**Expected Behavior:**
all lines in the exception stack can be traced to source code.

**Actual Behavior:**
only a few lines can be identified to traced to source code.
![pic](https://cdn.jsdelivr.net/gh/kkyeer/picbed/微信图片_20200523193458.png)

**Related Issues:**

**Comment by testforstephen** [comment]
It looks the source code for those libraries are missing. The debugger won't render links if it cannot find the corresponding source code for the call stack. 

Could you attach a sample project to help reproduce the issue?
