### ISSUE TITLE
java debug console code completion

### ISSUE THREAD

**Issue by jzdayz** [microsoft/vscode-java-debug#817]
[provide a description of the issue]

##### Environment
- Operating System: mac os 10.15.4
- JDK version: 1.8
- Visual Studio Code version: April 2020 (version 1.45)
- Java extension version: 0.9.1
- Java Debugger extension version: 0.26.0

##### Steps To Reproduce
please visit https://github.com/microsoft/vscode/issues/98468

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by testforstephen** [comment]
It works in my side.
![image](https://user-images.githubusercontent.com/14052197/82855567-3a1d2a00-9f3e-11ea-94ba-913d33c9095b.png)

Could you mind share your launch.json if existed and attach a sample project for me to reproduce it?

**Comment by jzdayz** [comment]
> It works in my side.
> ![image](https://user-images.githubusercontent.com/14052197/82855567-3a1d2a00-9f3e-11ea-94ba-913d33c9095b.png)
> 
> Could you mind share your launch.json if existed and attach a sample project for me to reproduce it?



I found something strange
1.  i  create new springboot project on https://start.spring.io/
2. i debug the project 
3. i write code `new demo`
![image](https://user-images.githubusercontent.com/35563513/82856773-8ddd4280-9f41-11ea-90cd-8fd5aae22399.png)
4. i retry wirte code `new demo`
![image](https://user-images.githubusercontent.com/35563513/82856798-9fbee580-9f41-11ea-998c-7bf5f9797d71.png)
5. it's looks like on and off

**if i wait some time,it's ok,  wirte code `new` and wait some time,then i write `demo` ,it's ok,but if i just wirte `new demo`,it's bad**

**Comment by jzdayz** [comment]
> It works in my side.
> ![image](https://user-images.githubusercontent.com/14052197/82855567-3a1d2a00-9f3e-11ea-94ba-913d33c9095b.png)
> 
> Could you mind share your launch.json if existed and attach a sample project for me to reproduce it?

1. new + space + demo
![image](https://user-images.githubusercontent.com/35563513/82857446-95055000-9f43-11ea-9388-0911cb3b59c2.png)
2. new + space + esc + demo
![image](https://user-images.githubusercontent.com/35563513/82857461-a3536c00-9f43-11ea-9483-10e8f2962f42.png)

**Comment by testforstephen** [comment]
Looks like vscode adds some delay mechanism (aka. debounce) for code completion when you type code. if you type fast, what the debugger received is the previous word, so you see a different completion list. This also explains why `new + space + esc + demo` works, because `esc` is cancelling the current completion list and resend completion request.
