### ISSUE TITLE
filter for call stack

### ISSUE THREAD

**Issue by blassmegod** [microsoft/vscode-java-debug#825]
[provide a description of the issue]

##### Environment
- Operating System: any
- JDK version: any
- Visual Studio Code version: latest
- Java extension version: latest
- Java Debugger extension version: latest

##### Steps To Reproduce
1. [step 1]
- connect the debugger to a running process
2. [step 2]
- stop on some breakpoints

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Call Stack view has no filtering option.
##### Expected Result
Call Stack view to have a filtering option.
##### Additional Informations
Would be nice to have a filtering option so one can filter either by thread name or by status of threads, like RUNNING, SUSPENDED, or whatever status there is. It can help a lot in situations where there are many threads running and the breakpoints stop on multiple parallel threads, so switching from one to the other would be much quicker.

**Comment by testforstephen** [comment]
vscode already supports this. You can click on call stack view and start typing.
![callstackfilter](https://user-images.githubusercontent.com/14052197/84025059-83995a80-a9bd-11ea-855d-7f015b26c710.gif)

**Comment by the21st** [comment]
I want to filter by file (so that I only see my files in the stack), but that's not possible
