### ISSUE TITLE
"UNC path is missing sharename: \\java"

### ISSUE THREAD

**Issue by James-Oswald** [microsoft/vscode-java-debug#830]
Clicking Run or Debug above main or pressing F5 to debug using `launch.json` yields notification window saying "UNC path is missing sharename: \\\\java"

Picture of notification window:
![Window](https://raw.githubusercontent.com/James-Oswald/Logic-Gate-Simulator/Java-Debug-UNC-Bug/bug-report/error.png)

Gif of error occurring:
![gif](https://raw.githubusercontent.com/James-Oswald/Logic-Gate-Simulator/Java-Debug-UNC-Bug/bug-report/bug.gif)

##### Environment
- Operating System: Windows 10
- JDK version: JDK 10.0.2
- Visual Studio Code version: 1.46.0
- Java extension version: 0.62.0
- Java Debugger extension version: 0.26.0 

##### Steps To Reproduce
Not sure, It works fine on other projects

Project causing error: [here](https://github.com/James-Oswald/Logic-Gate-Simulator/tree/Java-Debug-UNC-Bug)

Picture of logs:
![logs](https://raw.githubusercontent.com/James-Oswald/Logic-Gate-Simulator/Java-Debug-UNC-Bug/bug-report/log.png)

Text of logs: [here](https://github.com/James-Oswald/Logic-Gate-Simulator/blob/Java-Debug-UNC-Bug/bug-report/logs.txt)

##### Current Result
Error, "UNC path is missing sharename: \\Java"

##### Expected Result
No error, normal debugging.

##### Additional Information
N/A

**Comment by James-Oswald** [comment]
I think I found the source of this issue, After a bit more testing I realized this issue wasn't exclusive to this project, but rather I was unable to run anything without getting this error. 

My primary java compiler is located in `C:\Program Files\Java\jdk-10.0.2\bin`

However I had recently created a new folder to store different versions of java compilers on my D: drive in hopes of being able to have multiple JDKs on my system without getting notification messages telling me to delete previous versions. I then changed my java compiler in my `settings.json` file to include:
```json
"java.configuration.runtimes": [
        {
            "name":"JavaSE-10",
            "path": "D:\\Programming\\JavaVersions\\jdk-10.0.2\\bin",
            "default":  true
        },
```
despite still having `C:\Program Files\Java\jdk-10.0.2\bin` on my path.

In the end I changed the "path" back to  `C:\\Program Files\\Java\\jdk-10.0.2\\bin` and this error no longer appears. If this is still an issue that needs be resolved please let me know if you need the verbose logs.

**Comment by testforstephen** [comment]
You need set java home without bin suffix (e.g. "D:\\Programming\\JavaVersions\\jdk-10.0.2") in the "path".

**Comment by James-Oswald** [comment]
Thank you, this completely fixed my issue.

**Comment by Ohhama1** [comment]
我が実力では、理解不能です

**Comment by Hane248** [comment]
hello, I have the same issue although I have .json file like this 
"{
    "workbench.colorTheme": "Visual Studio Dark",
    "java.configuration.runtimes": [{
        "name": "JavaSE-20",
        "path": "C:\\Program Files\\Java\\jdk-20",
        "default": true
    }
],
"code-runner.executorMap": {

    "javascript": "node",
    "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
    "c": "cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
    "zig": "zig run",
    "cpp": "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
    "objective-c": "cd $dir && gcc -framework Cocoa $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
    "php": "php",
    "python": "python -u",
    "perl": "perl",
    "perl6": "perl6",
    "ruby": "ruby",
    "go": "go run",
    "lua": "lua",
    "groovy": "groovy",
    "powershell": "powershell -ExecutionPolicy ByPass -File",
    "bat": "cmd /c",
    "shellscript": "bash",
    "fsharp": "fsi",
    "csharp": "scriptcs",
    "vbscript": "cscript //Nologo",
    "typescript": "ts-node",
    "coffeescript": "coffee",
    "scala": "scala",
    "swift": "swift",
    "julia": "julia",
    "crystal": "crystal",
    "ocaml": "ocaml",
    "r": "Rscript",
    "applescript": "osascript",
    "clojure": "lein exec",
    "haxe": "haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt",
    "rust": "cd $dir && rustc $fileName && $dir$fileNameWithoutExt",
    "racket": "racket",
    "scheme": "csi -script",
    "ahk": "autohotkey",
    "autoit": "autoit3",
    "dart": "dart",
    "pascal": "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
    "d": "cd $dir && dmd $fileName && $dir$fileNameWithoutExt",
    "haskell": "runghc",
    "nim": "nim compile --verbosity:0 --hints:off --run",
    "lisp": "sbcl --script",
    "kit": "kitc --run",
    "v": "v run",
    "sass": "sass --style expanded",
    "scss": "scss --style expanded",
    "less": "cd $dir && lessc $fileName $fileNameWithoutExt.css",
    "FortranFreeForm": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
    "fortran-modern": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
    "fortran_fixed-form": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
    "fortran": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
    "sml": "cd $dir && sml $fileName"
},
"code-runner.runInTerminal": false,
"java.jdt.ls.java.home": ""
}"
