### ISSUE TITLE
Incorrect output syntax

### ISSUE THREAD

**Issue by Mazeral** [microsoft/vscode-java-debug#831]
I've created a java source file that should excute the following code:

public class GalToLitTable {
   public static void main(String args[]) {
      double gallons;
      double liters;
      int counter;

      counter = 0;
      for (gallons = 1; gallons <= 100; gallons++) {

         liters = gallons * 3.7854;
         System.out.println(gallons + "Gallons is " + liters + " liters.");
         ++counter;
         if (counter == 10) {
            System.out.println();

            counter = 0;

         }

      }

   }
}
however,the double gallon are not to the left of the string,
ALL the outputs looks like the following:

1.0Gallons is 3.7854 liters.
2.0Gallons is 7.5708 liters.
3.0Gallons is 11.356200000000001 liters.
4.0Gallons is 15.1416 liters.
5.0Gallons is 18.927 liters.
and as you can you see,the double gallons are not in the right place.

Extension version: 0.26.0
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 3591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    74	  5844	code main
    0	     9	  4128	   electron-crash-reporter
    0	    55	  5008	   window (undefined)
    1	    69	  6320	   window (Issue Reporter)
    0	    82	  6584	   shared-process
    0	   135	  6816	   gpu-process
    0	    18	  6868	   utility
    0	   286	  7124	   window (Java Overview - Hellojava - Visual Studio Code [Administrator])
    0	   143	   368	     extensionHost
    0	   287	   920	       "C:\Program Files\AdoptOpenJDK\jdk-14.0.1.7-hotspot\bin\java" --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -DwatchParentProcess=false -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -jar c:\Users\user\.vscode\extensions\redhat.java-0.62.0\server\plugins\org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar -configuration c:\Users\user\AppData\Roaming\Code\User\globalStorage\redhat.java\0.62.0\config_win -data c:\Users\user\AppData\Roaming\Code\User\workspaceStorage\d8895972f04bfc94a89c81c4d67df04e\redhat.java\jdt_ws
   81	   158	  4988	       "C:\Program Files\AdoptOpenJDK\jdk-14.0.1.7-hotspot\bin\java" -jar c:\Users\user\.vscode\extensions\sonarsource.sonarlint-vscode-1.16.0\server\sonarlint-ls.jar 59445 file:///c:/Users/user/.vscode/extensions/sonarsource.sonarlint-vscode-1.16.0/analyzers/sonarjava.jar file:///c:/Users/user/.vscode/extensions/sonarsource.sonarlint-vscode-1.16.0/analyzers/sonarjs.jar file:///c:/Users/user/.vscode/extensions/sonarsource.sonarlint-vscode-1.16.0/analyzers/sonarphp.jar file:///c:/Users/user/.vscode/extensions/sonarsource.sonarlint-vscode-1.16.0/analyzers/sonarpython.jar file:///c:/Users/user/.vscode/extensions/sonarsource.sonarlint-vscode-1.16.0/analyzers/sonarhtml.jar
    0	     9	  1920	     watcherService 
    0	    32	  6004	     searchService
    0	     4	  6948	     winpty-process
    0	     3	  5724	       C:\Windows\System32\cmd.exe
```

**Comment by testforstephen** [comment]
i don't understand what is your question. Please explain more about what is expected.
