### ISSUE TITLE
Extension host terminated unexpectely and cannot debug java projects neither run java maven extension

### ISSUE THREAD

**Issue by juanluelguerre** [microsoft/vscode-java-debug#832]
Issue Type: <b>Bug</b>

Hi,
I'm trying to run Java Projects and the message bellow is comming up, after open Visual Studio Code:

Here my tools versiones:
- OS: MacOS Catalina 10.15.4
- node: 14.4.0
- npm: 6.14.5
- VS Code: Latest

ERROR DETAIL:
WARNING: You are likely using a version of node-tar or npm that is incompatible with this version of Node.js.Please use either the version of npm that is bundled with Node.js, or a version of npm (> 5.5.1 or < 5.4.0) or node-tar (> 4.0.1) that is compatible with Node.js 9 and above./private/var/folders/tv/k2n51f4j7q5376gm1zgcl9540000gn/T/AppTranslocation/FF792062-30E8-4F36-8DD6-556D5EC15CC3/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)[90785]: ../../third_party/electron_node/src/node_zlib.cc:568:static void node::(anonymous namespace)::ZlibStream::Init(const FunctionCallbackInfo<v8::Value> &): Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed. 1: 0x10f950be5 node::Abort() [/private/var/folders/tv/k2n51f4j7q5376gm1zgcl9540000gn/T/AppTranslocation/FF792062-30E8-4F36-8DD6-556D5EC15CC3/d/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 2: 0x10f95096f node::Assert(node::AssertionInfo const&) [/private/var/folders/tv/k2n51f4j7q5376gm1zgcl9540000gn/T/AppTranslocation/FF792062-30E8-4F36-8DD6-556D5EC15CC3/d/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 3: 0x10f9d9f43 node::options_parser::SplitHostPort(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) [/private/var/folders/tv/k2n51f4j7q5376gm1zgcl9540000gn/T/AppTranslocation/FF792062-30E8-4F36-8DD6-556D5EC15CC3/d/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 4: 0x10b7ef58c v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) [/private/var/folders/tv/k2n51f4j7q5376gm1zgcl9540000gn/T/AppTranslocation/FF792062-30E8-4F36-8DD6-556D5EC15CC3/d/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 5: 0x10b7b02a7 v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) [/private/var/folders/tv/k2n51f4j7q5376gm1zgcl9540000gn/T/AppTranslocation/FF792062-30E8-4F36-8DD6-556D5EC15CC3/d/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 6: 0x10b7af8e2 v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) [/private/var/folders/tv/k2n51f4j7q5376gm1zgcl9540000gn/T/AppTranslocation/FF792062-30E8-4F36-8DD6-556D5EC15CC3/d/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 7: 0x10c176219 v8::internal::compiler::ZoneStats::ReturnZone(v8::internal::Zone*) [/private/var/folders/tv/k2n51f4j7q5376gm1zgcl9540000gn/T/AppTranslocation/FF792062-30E8-4F36-8DD6-556D5EC15CC3/d/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 8: 0x10c0fc1c1 v8::internal::compiler::ZoneStats::ReturnZone(v8::internal::Zone*) [/private/var/folders/tv/k2n51f4j7q5376gm1zgcl9540000gn/T/AppTranslocation/FF792062-30E8-4F36-8DD6-556D5EC15CC3/d/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 9: 0x10c0f7a7d v8::internal::compiler::ZoneStats::ReturnZone(v8::internal::Zone*) [/private/var/folders/tv/k2n51f4j7q5376gm1zgcl9540000gn/T/AppTranslocation/FF792062-30E8-4F36-8DD6-556D5EC15CC3/d/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

Extension version: 0.26.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by testforstephen** [comment]
Where did you get this error detail? i didn't see anything related with Java Debugger.

**Comment by juanluelguerre** [comment]
Using Developer Tool trying to debug Java project (after press F5 key). 
Same launch setting I'm using in Windows.

**Comment by juanluelguerre** [comment]
Hi,
I've attached some screen shoots about the process to debug the java project:

1) VS Code Popup message ("_Cannot find debug adapter for type 'java'._") ![Screenshot 2020-06-21 at 21 44 05](https://user-images.githubusercontent.com/5904157/85233689-860da280-b408-11ea-8a28-5b8756b25e5a.png)

2) VS Developer Tool (same stack trace as I've added in this thread) ![Screenshot 2020-06-21 at 21 44 30](https://user-images.githubusercontent.com/5904157/85233693-89a12980-b408-11ea-9185-0e61f13ac2fb.png)

Thanks in advance
Juanlu

**Comment by testforstephen** [comment]
Still no errors related with Java Debugger. Please share the whole console log.

**Comment by juanluelguerre** [comment]
After remove several extensions trying to found a solution, the errors continue, but I think is a problem from VS Code, no just for Java Debugger. Isn't?

**Log Detail:**
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5064 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/juanlu/.vscode/extensions/redhat.vscode-yaml-0.8.0/syntaxes/yaml.tmLanguage.json
register @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5064
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4516 Extension Host
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4516 {  message: 'Starting Java server with: /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /Users/juanlu/.vscode/extensions/redhat.java-0.63.0/server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar -configuration /Users/juanlu/Library/Application Support/Code/User/globalStorage/redhat.java/0.63.0/config_ss_mac -data /Users/juanlu/Library/Application Support/Code/User/workspaceStorage/854d650900f4e1d309e4c8d883e39ac1/redhat.java/ss_ws',  level: 'info',  timestamp: '2020-06-24 01:09:36.311'}{  message: 'Starting Java server with: /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /Users/juanlu/.vscode/extensions/redhat.java-0.63.0/server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar -configuration /Users/juanlu/Library/Application Support/Code/User/globalStorage/redhat.java/0.63.0/config_mac -data /Users/juanlu/Library/Application Support/Code/User/workspaceStorage/854d650900f4e1d309e4c8d883e39ac1/redhat.java/jdt_ws',  level: 'info',  timestamp: '2020-06-24 01:09:36.345'}
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:265 [Extension Host] [vscode-icons] v10.1.1 activated!
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4516 Extension Host
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4516 WARNING: You are likely using a version of node-tar or npm that is incompatible with this version of Node.js.Please use either the version of npm that is bundled with Node.js, or a version of npm (> 5.5.1 or < 5.4.0) or node-tar (> 4.0.1) that is compatible with Node.js 9 and above./Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)[2771]: ../../third_party/electron_node/src/node_zlib.cc:568:static void node::(anonymous namespace)::ZlibStream::Init(const FunctionCallbackInfo<v8::Value> &): Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed. 1: 0x112bcdbe5 node::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 2: 0x112bcd96f node::Assert(node::AssertionInfo const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 3: 0x112c56f43 node::options_parser::SplitHostPort(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 4: 0x10ea6c58c v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 5: 0x10ea2d2a7 v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 6: 0x10ea2c8e2 v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 7: 0x10f3f3219 v8::internal::compiler::ZoneStats::ReturnZone(v8::internal::Zone*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4068 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
_onExtensionHostCrashed @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4068
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2932 Extension host terminated unexpectedly.
onDidChangeNotification @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2932
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.

**Comment by juanluelguerre** [comment]
Finally, I've **uninstall all VS Code Extensions and install them again**, and now, I can work properly. VS Java Debugger start to work as usual, and of course other extensions.

I'm not sure which extension was the one caused the issue, but at the end everything start to work  again.

I hope this help.
Regards
