### ISSUE TITLE
Can't evaluate variables in debug console

### ISSUE THREAD

**Issue by llgcode** [microsoft/vscode-java-debug#835]
Hi,
In this sample archive you will found two eclipse projects, one with the code and a jar dependency. The other depends on the first project and is used in the launcher config. Note, the objective of this sample is to show you the issue with a minimal configuration. We use this configuration in a larger project with multiple dependencies and complex configuration. The problem is that we can't evaluate variables in debug console, we also can't see the variable value in tooltip when hovering the cursor on the variable.

##### Environment
- Version: 1.46.1 (user setup)
- Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
- Date: 2020-06-17T21:13:20.174Z
- Electron: 7.3.1
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Windows_NT x64 10.0.18363
- Java extension version: 0.9.1
- Java Debugger extension version: 0.26.0

##### Steps To Reproduce
1- Unzip the attached file provided ([java-ws-2.zip](https://github.com/microsoft/vscode-java-debug/files/4219737/java-ws-2.zip)) and open the folder with vscode
2- Debug launcher "Debug App" 
3- Open Debug Console
4- write data1 and enter to inspect data1 variable.

![image](https://user-images.githubusercontent.com/524083/84689537-69bdc180-af41-11ea-8cee-25be40df09a8.png)

##### Current Result
Cannot evaluate because of compilation error(s): Evaluations must contain either an expression or a block of well-formed statements.

##### Expected Result
"Data{property1:hello}"

##### Additional Informations

it's very disabling when analysing an issue.

[java-ws-2.zip](https://github.com/microsoft/vscode-java-debug/files/4219737/java-ws-2.zip)

**Comment by testforstephen** [comment]
Duplicated with https://github.com/microsoft/vscode-java-debug/issues/763, hover and evaluate both leverage the same evaluate request to get the variable result.

**Comment by llgcode** [comment]
Any news on a possible correction ?
