### ISSUE TITLE
Remote Debugging Support - High Latency

### ISSUE THREAD

**Issue by DanielSaunders** [microsoft/vscode-java-debug#836]
I am trying to debug a Java application remotely over an SSH tunnel and on a VPN. The network connection between me and this application is relatively poor and interacting with the debugger seems to be impossible. After attaching to the remote application, it takes a significant amount of time for any information to appear (such as running threads) and setting a breakpoint just causes the application's thread to hang for a long time and nothing ever appears to happen. I've resorted to using SSH to connect to the machine and running jdb locally on the server to debug the application. While that works well enough, it would certainly be nice to be able to use VS Code as the interface for debugging.

This may be a "bug," but I'm not really sure if the VS Code java debug extension should be expected to function in this scenario. Is there anything that I can do in order to get the VS Code extension to work over a poor network connection?

##### Environment
- Operating System: Mac OS X
- JDK version: 8
- Visual Studio Code version: 1.46.1
- Java extension version: v0.9.1
- Java Debugger extension version: v0.26.0

##### Steps To Reproduce
Run a Java application on a remote server where the network quality between me and that server is poor. Try to connect to the application and then after waiting for information to show up (such as running threads), set a breakpoint.

##### Current Result
Breakpoints just cause the remote application to hang

##### Expected Result
I should be able to set breakpoints during code execution and investigate the state of the application, even if it takes a few seconds between each instruction sent to the application being debugged.

**Comment by testforstephen** [comment]
The underlying Java debug protocol JPDA is pretty chatty, and not suitable for remote debugging scenario. There is not much the Java debugger can improve right now. I would suggest you have a look at https://code.visualstudio.com/docs/remote/ssh.

**Comment by DanielSaunders** [comment]
Thanks. I've investigated that option, and it looks like it will work well enough for my purposes. Appreciate the help!
