### ISSUE TITLE
Class name refactor bug

### ISSUE THREAD

**Issue by shirok1** [microsoft/vscode-java-debug#837]
Issue Type: <b>Bug</b>

After using F2 to rename class name in editor, file name will sync automatically, however the tab title won't and the java plugin will point the divorce between  class name and file name (in the title) as an error

![image](https://user-images.githubusercontent.com/12044683/86796546-4bab3300-c0a1-11ea-9091-eb8868cedbec.png)

Extension version: 0.26.0
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19042

**Comment by testforstephen** [comment]
Save these files (e.g. `Ctrl+K S`) will fix the build error.

**Comment by testforstephen** [comment]
If you still need more discussion about this, could you please open an issue at https://github.com/redhat-developer/vscode-java/issues? The rename feature is provided there.

**Comment by shirok1** [comment]
Saving these files won't fix it, only a full reboot can.

**Comment by testforstephen** [comment]
I see. If you only change the file name from lower case to upper case, e.g. from factory -> Factory. It's a VS Code bug.

**Comment by testforstephen** [comment]
If you rename the file name from File Explorer directly, for example, change it from factory.java to Factory.java, the editor title doesn't change either. So it's a generic VS Code bug, not a Java specific issue. I would suggest you open an issue at https://github.com/microsoft/vscode/issues

**Comment by shirok1** [comment]
Maybe you are right. I tried to reproduce this bug for a few times and the refactoring works. But when I tired to create a file called A.java straightly:
![image](https://user-images.githubusercontent.com/12044683/86798711-af366000-c0a3-11ea-9a75-9b5a2ba96d4b.png)

**Comment by testforstephen** [comment]
Can reproduce it with other file name too.

1. open a.txt in VS Code, 
2. then rename a.txt to A.txt in 资源管理器，
3. the editor title is still a.txt.

So it's a generic VS Code issue.

**Comment by shirok1** [comment]
The sequences between refreshing language server and renaming file is strange...
In cases like this:
![image](https://user-images.githubusercontent.com/12044683/86801873-0c7fe080-c0a7-11ea-90eb-cab864054db2.png)
… re-typing the last letter t will fix it
