### ISSUE TITLE
build.gradle: Unresolved dependency

### ISSUE THREAD

**Issue by noel-yap** [microsoft/vscode-java-debug#840]
I have the following in a `build.gradle` file:

```
dependencies {
…
  testImplementation 'org.assertj:assertj-vavr:+'
…
}
```

`./gradlew dependencies --write-locks; ./gradlew build` works fine from the command line.

VSCode refuses to run tests since it's reporting an unresolved dependency for `assertj-vavr:0.2.0`. Killing gradle daemons and servers and restarting VSCode _sometimes_ fixes the issue (until the next time).

##### Environment
- Operating System: Linux

- JDK version:
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)

- Visual Studio Code version:
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:30:34.302Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-62-generic

- Java extension version: 0.9.1

- Java Debugger extension version: 0.1.5

##### Steps To Reproduce
Add and remove `assertj-vavr` dependency a few times and interspersing builds. Once the issue occurs, it sticks until the Gradle daemon and server are killed and `.vscode` directory is removed.

**Comment by testforstephen** [comment]
I added assertj-vavr to build.gradle, i didn't see any build error about unresolved dependencies.

@noel-yap Could you please share a sample project to reproduce the issue?

**Comment by noel-yap** [comment]
The error started occurring when I added the dependency, ran `./gradlew
dependencies --write-locks`, worked with that a bit, removed the
dependency, then ran `./gradlew dependencies --write-locks`.
