### ISSUE TITLE
Fail to debug in Lightweight server, error message not useful

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-java-debug#841]
LS in Lightweight mode, try attaching to a port, I got below message. Not clear for futher actions. Suggest to improve the message, or even add a choice to enable standard LS. 

![image](https://user-images.githubusercontent.com/2351748/87264202-fd0ef600-c4f1-11ea-983a-45b6dde15ca0.png)

**Comment by testforstephen** [comment]
will be fixed with PR https://github.com/microsoft/vscode-java-debug/pull/838
