### ISSUE TITLE
specify output directory in non maven project

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-java-debug#847]
I have a simple java project where I add the libraries using this:

<img width="426" alt="Screen Shot 2020-07-16 at 15 01 44" src="https://user-images.githubusercontent.com/738650/87673797-605c8a80-c775-11ea-84b7-b496257c56c7.png">

Now how can I specify the output folder for the .class files?

Adding a file `.classpath` with the following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

Does not work.

**Comment by testforstephen** [comment]
please provide the user scenario why you need specify the output directory.

**Comment by clankill3r** [comment]
I moved away from things like maven and graddle. Specially with students it takes to much time to set up on all their machines and they don't provide any functionality that we really need (I know this can be quite personal).
I much more prefer simple scripts to build my jar files, I use a simple shell scripts like:

```
#!/usr/bin/env bash

cd /java/bin
mkdir -p /java/libs/doeke_sfjl_ui
jar cfm /java/libs/doeke_sfjl_ui/sfjl_ui_widget_agent.jar doeke_sfjl_ui/sfjl_ui_widget_agent_MANIFEST.MF doeke_sfjl_ui/sfjl_ui_widget_agent*.class
cd /java/projects/sfjl_ui/src
jar uf /java/libs/doeke_sfjl_ui/sfjl_ui_widget_agent.jar doeke_sfjl_ui/sfjl_ui_widget_agent.java
```

But now the bin file is located here:

`/Users/doekewartena/Library/Application Support/Code/User/workspaceStorage/95e850bb40bbc92a4f5e7bd720c0b61e/redhat.java/jdt_ws/imui_1a91146f/bin`

This location is fragile, and so long that it gives me problems with executing the jar command when to many files are involved. This is also due that the `jar` program is really bad, for example there is the `-C` command to specify a path, but then wildcards don't work anymore.

**Comment by testforstephen** [comment]
I see. BTW, there is a PR https://github.com/microsoft/vscode-java-dependency/pull/271 working on providing export jar feature in the Java Dependency view. I guess that may satisfy your requirement.

**Comment by jdneo** [comment]
It has been supported by https://github.com/redhat-developer/vscode-java/pull/1694

You can set the setting `java.project.outputPath` in WORKSPACE scope
