### ISSUE TITLE
Provide option to exclude files and folders from showing up in Problems.

### ISSUE THREAD

**Issue by noel-yap** [microsoft/vscode-java-debug#848]
I'm working with gRPC which generates files with lots of items showing up in Problems. Since there's not much I can do about those problems, they only add noise.

Please provide a setting to specify files and folders to be ignored from the Problems list.

**Comment by testforstephen** [comment]
@noel-yap Did you try the Problem Filter?
![image](https://user-images.githubusercontent.com/14052197/87761199-a3852f00-c843-11ea-9098-5700fabd45b0.png)

Also i'm interested in the gPRC generated files showing up with errors. Would you mind sharing a sample project to help reproduce the Problems? I want to take a look whether there is some potential bug that's not handled well at the generated code.

**Comment by noel-yap** [comment]
Yes, as a workaround, I'm currently using Problem Filter so it shows only the problems for the file in focus. I would like to be able to see all the problems I can do something about.

Hmm, I'm no longer seeing all the problems in gRPC generated code. That could be because I've included the `build` directory in `.gitignore` or in `files.exclude` and it too a restart of the IDE to pick up those settings.

As for example projects, https://github.com/saturnism/grpc-by-example-java has a bunch.

**Comment by testforstephen** [comment]
This is a duplicate feature request to Java language support extension.
https://github.com/redhat-developer/vscode-java/issues/2150
