### ISSUE TITLE
mainClass Should Accept varaiable

### ISSUE THREAD

**Issue by rajarshikhare** [Microsoft/vscode-java-debug#85]
If i put ${fileBasenameNoExtension} on mainClass inside launch.json it does'nt resolve it as a file name
or their should be something  that should take filename as mainClass automatically.

**Comment by akaroml** [comment]
Please see how we can let VS Code resolve the variables before passing the string to us. In this way, we support any variables that are available in VS Code.

**Comment by andxu** [comment]
attached with the issue in vscode.

**Comment by andxu** [comment]
I will refine the flow of the verification work in launch request other than during providing debugger configuration.

**Comment by andxu** [comment]
We should consider this in recent release.
