### ISSUE TITLE
Hot code replace not working

### ISSUE THREAD

**Issue by Mike-the-one** [microsoft/vscode-java-debug#850]
I have a spring boot application, hot code replace was working fine, until I recently to latest VS code (1.47.1).
Tried to delete the workspace storage folder, still the same.
Tried both jdk 1.8 and java 11, same problem
Tried the change HCR from auto to manual, got this message whenever I click the lightning icon after I change the code and save: 

>　Cannot find any changed classes for hot replace!

Thanks

##### Environment
- Operating System: Deepin 15.11
- JDK version: Both 1.8 and 11
- Visual Studio Code version: latest, 1.47.1
- Java extension version: 4.5
- Java Debugger extension version: 0.27.0

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by Mike-the-one** [comment]
Hmm, not sure what happened, replaced with 1.47.2 or 1.46.1 same problem.  It was working fine

**Comment by testforstephen** [comment]
What's your version of "Debugger for Java" extension? Could you try to downgrade it to 0.26.0 to see whether it still happens?

**Comment by Mike-the-one** [comment]
@testforstephen Thanks!!! it works in 0.26.0... did not realize that debugger for java was recently updated, otherwise I would have downgraded it first :-) wasted me a couple hours downgrade VSCode, clean install etc :)

**Comment by testforstephen** [comment]
@Mike-the-one Would you mind sharing a sample project and some steps to reproduce the issue? A minimum project that can reproduce the issue would be helpful to find the root cause?

**Comment by Palidino** [comment]
I'm also having this issue, but I don't have a sample project for reproduction of the bug. All I know is that since the update, it doesn't work for either project I work on. It just says there are no changes. Like OP, with Java 8 and 11.

**Comment by testforstephen** [comment]
i reproduced it. Actually HCR succeeds, just reproduce a wrong status about no changes found. Will push a hotfix for it.

**Comment by testforstephen** [comment]
The latest 0.27.1 already has the fix.

**Comment by Mike-the-one** [comment]
@testforstephen Thanks for fixing this!

**Comment by Palidino** [comment]
I'm on 0.27.1 and still get told: "cannot find any changed classes for hot replace!"

**Comment by testforstephen** [comment]
@Palidino Could you try a private fix at https://github.com/microsoft/vscode-java-debug/issues/855#issuecomment-666262103?
