### ISSUE TITLE
URGENT- "Java 11 or more recent is required to run. Please download and install a recent JDK"

### ISSUE THREAD

**Issue by shanewaz-abbas** [microsoft/vscode-java-debug#852]
I don't understand why today I'm getting this error. All the java commands are not working. Reloaded window, reinstalled and still not working. 

![image](https://user-images.githubusercontent.com/61433809/88202517-617f3300-cc1f-11ea-9d19-4f5af414d73d.png)

![image](https://user-images.githubusercontent.com/61433809/88202138-d30ab180-cc1e-11ea-8ee4-d961842b2ff7.png)

##### Environment
- Operating System: Windows_NT x64 10.0.20161 (remote ssh to ubuntu 18)
- JDK version:  Open jdk 8
- Visual Studio Code version: 1.47.2 (user setup)
- Java extension version: 0.9.1
- Java Debugger extension version: 0.27.1

**Comment by shanewaz-abbas** [comment]
Figured out that language support for java from redhat is what broke things. Temporarily fixed by downgrading. Gonna log this issue there.

**Comment by alvarofernandoms** [comment]
I think that is related with this: https://devblogs.microsoft.com/java/java-on-visual-studio-code-update-june-2020/

🤷

**Comment by shanewaz-abbas** [comment]
https://github.com/redhat-developer/vscode-java/issues/1543, yeah

**Comment by lorenzznerol** [comment]
if you have a 32bit system https://stackoverflow.com/questions/62436626/oracle-jdk-14-32bit-x86-for-windows-10-needed-or-workaround-for-this-for-visu

**Comment by testforstephen** [comment]
Just briefly recap the solution from redhat-developer/vscode-java#1543

This requirement is just asking you to install JDK 11 to run vscode-java extension itself, because it's also a Java program.

If you want to run your program at JDK 8, you can install both JDK 8 and JDK 11 in your machine, and configure them in the user settings below.
```json
    "java.home": "C:\\AdoptOpenJDK\\jdk-11.0.8.10-hotspot",
    "java.configuration.runtimes": [
        {
          "default": true,
          "name": "JavaSE-1.8",
          "path": "C:\\Java\\openjdk8u181-b13",
        }
    ]
```

**Comment by meatashu** [comment]
what if we do not want to install jdk 11, is downgrading the only solution. Any other workarounds

**Comment by testforstephen** [comment]
@meatashu Is there any reason to prevent you from installing jdk 11?

**Comment by pelegri** [comment]
If I understand correctly the situation (from https://github.com/microsoft/vscode-java-debug/issues/879, and from my experience), the situation is that JDK11 is downloaded and installed, then it is used for the PLS, but it is also used by the debugged process.  In my personal case, I have an application that fails when running on JDK11 under the debugger.

I'd be very happy if I misunderstood the situation, though.
