### ISSUE TITLE
Cannot start debugger with JDK 1.8

### ISSUE THREAD

**Issue by maxiwu** [microsoft/vscode-java-debug#853]
It prompt me to install Java 11. But I am working on a legacy project which only compile on Java 1.8. 

##### Environment
- Operating System: Windows 7
- JDK version: 1.8.0_210
- Visual Studio Code version: 1.47.2
- Java extension version: v0.9.1
- Java Debugger extension version: v0.27.1

##### Steps To Reproduce
1. Create a Spring project using maven and target Java 1.8
2. Try to start debugger

[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
```
[2020-07-24 13:52:32.474] [exthost] [error] Activating extension redhat.java failed due to an error:
[2020-07-24 13:52:32.475] [exthost] [error] {"message":"Java 11 or more recent is required to run. Please download and install a recent JDK","label":"Get the Java Development Kit","command":"vscode.open","commandParam":{"$mid":1,"path":"/products/openjdk/download/","scheme":"https","authority":"developers.redhat.com","query":"sc_cid=701f2000000RWTnAAO"}}
```

##### Current Result
Cannot start debugger

##### Expected Result
Start debugging

##### Additional Informations
It was working fine yesterday. I didn't change anything. Except for restarting VSCode. Didn't event reboot my computer.

**Comment by maxiwu** [comment]
I figured it out. related to [redhat change minimum to java 11](https://github.com/redhat-developer/vscode-java/issues/1410)
I have to rollback the extension Lang. support for Java to v0.64.1. Today's version v0.65.0 force us to upgrade to Java 11.

**Comment by testforstephen** [comment]
@maxiwu This requirement is just asking you to install JDK 11 to run vscode-java extension itself, because it's also a Java program.

Also, you could install both JDK 8 and JDK 11 in your machine, and configure them in the user settings below. 
````
    "java.home": "C:\\AdoptOpenJDK\\jdk-11.0.8.10-hotspot",
    "java.configuration.runtimes": [
        {
          "default": true,
          "name": "JavaSE-1.8",
          "path": "C:\\Java\\openjdk8u181-b13",
        }
    ],
````

Learn more at https://github.com/redhat-developer/vscode-java/issues/1543

**Comment by thiscantbeserious** [comment]
From my short test the debugger also works - it will give you a warning that the debugger itself is using JDK11 while your project is using JDK8 and that the source-mapping could be off. However the results were the same from my testing (so no bugs, that I've found so far). 

Maybe in the future this issue will be worse when the versions are so far across, so maybe specifying the JDK in which the debugger runs could help (if there isn't any setting already?). Not sure if that's feasible to implement/would require to much work from your side.

**Comment by testforstephen** [comment]
> it will give you a warning that the debugger itself is using JDK11 while your project is using JDK8 and that the source-mapping could be off. 

@thiscantbeserious are you using attaching debugger feature when you observed this warning?

**Comment by thiscantbeserious** [comment]
Yep, I'm attaching to a Tomcat instance in that case.

**Comment by testforstephen** [comment]
I see, there is room for debugger to improve.  Currently it compares the extension's JVM with the debuggee's JVM, that's not accurate. It should use your project's target runtime to compare with the debuggee's JVM.
