### ISSUE TITLE
Unicode Characters on Java Debugger Console

### ISSUE THREAD

**Issue by JorgeJo-GT** [microsoft/vscode-java-debug#854]
Issue Type: <b>Bug</b>

Java Debug Console won't accept any characters with tilde or ñ

Extension version: 0.27.1
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

Input:

![image](https://user-images.githubusercontent.com/56206021/88457972-aa193500-ce47-11ea-96eb-fc5085368db3.png)

Debugger:
![image](https://user-images.githubusercontent.com/56206021/88457990-de8cf100-ce47-11ea-9e10-fed830da1692.png)

**Comment by testforstephen** [comment]
Handling unicode characters in windows terminal is a little tricky, you may take a look at https://github.com/microsoft/vscode-java-debug/issues/622

**Comment by BlueMoonWolf** [comment]
there also an problem about  characters.
 I use vscode1.48.2 ,
if you external jar path have Chinese characters，when you debug or run,it will report an error message like this:
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils.

**Comment by Eskibear** [comment]
@BlueMoonWolf  With vscode 1.51.1, the "Chinese in classpath" issue is gone. (though encoding of stdout is still a problem)

![image](https://user-images.githubusercontent.com/2351748/99050735-28563e80-25d3-11eb-8698-78653df298f5.png)

**Comment by BlueMoonWolf** [comment]
@Eskibear thanks ,I'll try  it.

**Comment by craM-Hub** [comment]
Tengo el mismo problema con vscode, o lo que es lo mismo, con la terminal de windows, ¿conseguiste arreglarlo?

Es como si el input del teclado estuviese siempre en windows1252, haga lo que haga, pues solamente poniendo ese formato tanto en el terminal como en el .java funciona como debe :S

**Comment by JorgeJo-GT** [comment]
@craM-Hub no, no he conseguido arreglarlo y ya no se le dio seguimiento.

**Comment by testforstephen** [comment]
Recently we improved the encoding issues on debugger extension. Could you try the latest 0.37.0 to see if the issue still exists? thanks.
