### ISSUE TITLE
Debug does not reload dependency source code

### ISSUE THREAD

**Issue by lrkwz** [microsoft/vscode-java-debug#858]
IF between two debug session I change and `mvn install` a dependency, the second session still reads the old source code (obviously executes the new dependency compiled code) leading to confusion.

The workaround is to 'Java: Clean the Java language server workspace` between the two sessions.

**Comment by testforstephen** [comment]
Could you please provide some detailed steps to reproduce the issue? It's better to provide some project to allow us to easily understand the issue.
