### ISSUE TITLE
Debug -> variables -> copy value: cropped!

### ISSUE THREAD

**Issue by sir-farfan** [microsoft/vscode-java-debug#860]
I want to copy the values of a lengthy JWT token, from a variable, while using the debugger, but when I click "copy value" I only get a cropped version of the variable:
`"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.IjEyMzQeyJhY2NpZCI61NnJzYTQ...+816 more"` 

I also tried just writing the variable name in the console, but I only got that cropped string.

Putting a bunch of fmt.Println all over the place defeats the purpose of the debugger... right? 

##### Environment
- Operating System: Darwin x64 19.5.0
- JDK version: javac 14.0.1
- Visual Studio Code version: 1.47.3
- Java extension version:
- Java Debugger extension version: GoLang

##### Steps To Reproduce
1. Initialize some string variable with a thousand characters
2. Start debugger
3. Attempt to copy the value

[attach a sample project reproducing the error]
https://gist.github.com/sir-farfan/b81eb9788ce44db93fd677d19f0c2299
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
"The Eurasian crag martin (Ptyonoprogne rupestris) is a small swa...+921 more"

##### Expected Result
Full wikipedia paragraph

**Comment by testforstephen** [comment]
@sir-farfan Are you debugging golang program? That's out of scope of Java debugger.

Could you please open an issue at https://github.com/golang/vscode-go/issues?
