### ISSUE TITLE
Unknown source while debugging

### ISSUE THREAD

**Issue by mlang97** [microsoft/vscode-java-debug#864]
When you debug a remote java application, the debugger can not recognize external dependencies (external jars).

![image](https://user-images.githubusercontent.com/35968713/90410695-f6ecd600-e0aa-11ea-92d6-f65160cde56c.png)

### Example launch.json:
``` json
        {
            "type": "java",
            "name": "Debug (Attach) - Remote",
            "request": "attach",
            "hostName": "localhost",
            "port": 8000,
            "projectName": "project name"
        }
```

I also tried to add the sourcePaths array in the launch.json but that doesn't work for me.

##### Environment
- Operating System: Ubuntu 20.04.1 LTS
- JDK version: 11.0.8
- Visual Studio Code version: 1.47.3
- Java extension pack version: 0.10.0
- Java Debugger extension version: 0.27.1

**Comment by testforstephen** [comment]
Can you use `Ctrl + T` to go to the symbol's source?

**Comment by mlang97** [comment]
That's working, but when i would step into while the debugger is running, it would not work.

**Comment by testforstephen** [comment]
would you mind sharing a minimum sample project to help reproduce the issue?

**Comment by mlang97** [comment]
Sorry for the misunderstanding. Meanwhile it works, but strangely enough i didn't change anything
