### ISSUE TITLE
Wrong source when debugging 

### ISSUE THREAD

**Issue by IcedAnt** [microsoft/vscode-java-debug#865]
I have 2 maven projects, basically one is a newer version of the other rewritten in another framework. Let's call the old one A and the new one B.

A and B both depend on 2 other projects that are almost identical. Let's call these ones A-1 and B-1.

A is working fine but B is using sources from A when debugging. That means that my breakpoint on a file on B-1 is hit correctly, but vscode still shows the file from A-1.

My pom files are configured correctly, A is using version 1.x of A-1 and B is using version 2.x of B-1. The 2 projects even have different, albeit similar, names.

I tried resetting the language server, cleaning and installing my projects again, changing the versions on my poms, using older versions of this and the vscode-java plugins, I even tried deleting and re-cloning everything. The only thing that worked was completely removing A-1 from the disk, which obviously is not a solution as I need it for A.

I have the exact same issue on Eclipse but I can work around it, since I have to option to manually set the Source Lookup Path for each project. I haven't found anything similar for vscode. Is it possible to add this option? Or is there some other way to do this?

##### Environment
- Operating System: Windows Server 2016
- JDK version: JavaSE-1.8
- Visual Studio Code version:
        Version: 1.46.1 (system setup)
        Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
        Date: 2020-06-17T21:13:20.174Z
        Electron: 7.3.1
        Chrome: 78.0.3904.130
        Node.js: 12.8.1
        V8: 7.8.279.23-electron.0
        OS: Windows_NT x64 10.0.14393
- Java extension version: 0.64.1
- Java Debugger extension version: 0.27.1

##### Steps To Reproduce
I cannot add steps to reproduce or a sample project since this is proprietary code.

##### Current Result
Breakpoint is hit but wrong file is shown

##### Expected Result
Breakpoint is hit but correct file is shown

**Comment by testforstephen** [comment]
Could you share a sample to help reproduce the issue? thanks.
