### ISSUE TITLE
Will not run class in visual studio code

### ISSUE THREAD

**Issue by tman1051** [microsoft/vscode-java-debug#869]
![Error](https://user-images.githubusercontent.com/70188733/91122383-d3ec9400-e65f-11ea-9d08-8f392b4b986e.PNG)
I can not run or compile anything and gives me this error saying there is no main when I have done everything the introduction has told me to.
It is giving me the thumbs up like the support says it is supposed to.

**Comment by testforstephen** [comment]
The file name should be Quickstart.java, not Quickstart.class.

**Comment by testforstephen** [comment]
Will close the issue. If you need more support, feel free to reopen it.
