### ISSUE TITLE
The debugger exits with migration failed error.

### ISSUE THREAD

**Issue by sumitdhungana14** [microsoft/vscode-java-debug#872]
While trying to debug a project using liquibase, the debugger exits with ```Migration failed! Liquibase encountered an exception.
liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: File does not exist: classpath:db/migrations/tracersynthesisrequests/alter_table_tracer_synthesis_requests_drop_column_target_category_id.sql``` even though this particular file exists and this change set has already been addressed in previous runs. So, I guess this change set should have been skipped automatically. Also, even though I disable liquibase, the issue still persists. The application builds/runs just fine on ```gradlew run/build``` command.

Edit: The issue also exists when I try to run the application with ```run without debugging```. 

##### Environment
- Operating System: linux
- JDK version: 8
- Visual Studio Code version: 1.48.1
- Java extension version: 
- Java Debugger extension version: 0.27.1

**Comment by testforstephen** [comment]
The debugger doesn't have the specific knowledge about your project, but depends on the Java language server to get the classpath of your project. If there is not found error during running, theoretically Java language server will report compilation error too. 

Please share a sample project to reproduce the issue.

**Comment by sumitdhungana14** [comment]
I don't quite understand what you mean by "not found error during running". There is no such error while running the project with build tool if that is what you are trying to refer.

**Comment by testforstephen** [comment]
`Migration failed! Liquibase encountered an exception. liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: File does not exist: classpath:db/migrations/tracersynthesisrequests/alter_table_tracer_synthesis_requests_drop_column_target_category_id.sql`

This error is from your application output, not from debugger itself. There must be some gap when resolving your project's build information. Based on current information, i can't tell what's it.

**Comment by sumitdhungana14** [comment]
How do we know if the project's build information is correctly setup so that the debugger works as expected? Has it got anything to do with the classpath provide by Java language server as you mentioned earlier?

**Comment by sumitdhungana14** [comment]
The above mentioned issue is gone after I disable liquibase. The project builds and runs fine with debugger. But now, the runtime behavior is not quite as expected. For eg, when sending a request to exposed REST API, the application responses with 404 not found.

**Comment by testforstephen** [comment]
The debugger is only responsible for calculating the classpath for your application, the runtime behavior discussion of your application is out of scope of the debugger.

If you launch your application in terminal, you should see the full command line to launch your application. And your application's classpath will be shortened to a temp file like cp_1vhf0tyk70xv5fwor5rgno356.jar. Please check first to see whether it's a classpath issue.

**Comment by sumitdhungana14** [comment]
The generated classpath seems to be fine, here is a snippet ```-classpath "/home/sumit/.../bin/main:/home/sumit/.gradle/caches/modules-2/files-2.1/org.apache.poi/poi-ooxml/4.1.0/42d7913de1a6360058e8d14bb7769a33633a639b/poi-ooxml-4.1.0.jar:/home/sumit/.gradle/caches/modules-2/files-2.1/org.apache.poi/poi-scratchpad/4.1.2/1be379e91d3d3fb0cd11425451acdbfb0d2264e7/poi-scratchpad-4.1.2.jar:/home/sumit/.gradle/caches/modules-2/files-2.1/org.apache.poi/poi/4.1.2/964bf41cf68bce08e4ef6b2279b559fdf8d454f4/poi-4.1.2.jar:/home/sumit/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.8.5/f645ed69d595b24d4cf8b3fbb64cc505bede8829/gson-2.8.5.jar:..``` it seem to contain classpath to all the dependency class as well.

**Comment by testforstephen** [comment]
You mentioned the classpath is generated well, i assume it's an internal error from the program itself. I'll close the issue first. If you need more discussion on it, feel free to reopen it.
