### ISSUE TITLE
Cannot evaluate lambda expression 

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [microsoft/vscode-java-debug#875]
Cannot evaluate lambda expression

##### Environment
- Operating System: ubuntu 18 tls
- JDK version: 14 
- Visual Studio Code version: 1.48.0
- Java extension version:0.10 
- Language support for Java:0.65
- Java Debugger extension version:0.28.0

##### Steps To Reproduce
[javaProject.zip](https://github.com/microsoft/vscode-java-debug/files/5148350/javaProject.zip)

1. Unzip and open the folder with vscode
2. Set a breakpoint to' u.sayName()'
3.Debug and run the mian function of App.java

##### Current Result
Cannot evaluate because of compilation error(s): Evaluations must contain either an expression or a block of well-formed statements.

![screenscast_20200831_124611](https://user-images.githubusercontent.com/57204004/91683766-10505080-eb88-11ea-97f4-c3c907571225.gif)

##### Expected Result
Able to perform expression evaluation correctly
##### Additional Informations
I use different jdk and operating system and build tool (window10 and ubuntu, jdk 11, 14,Maven,Eclipse) for debugging, the result is the same, still unable to perform expression evaluation

**Comment by YU5Z8X2CvH1fv4ep** [comment]
This bug is a headache when debugging large projects. Please help. IDEA is successful in running and debugging the above code, but I like vscode

**Comment by YU5Z8X2CvH1fv4ep** [comment]
I tried the same code today, and I can debug it again. emmmmm...?

**Comment by testforstephen** [comment]
The language support for Java released a new version yesterday, not sure whether it's the reason.

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> Java语言支持昨天发布了一个新版本，不确定是否是这个原因。

不是版本的问题,这个Bug我难受很久了,大哥你没有没有微信或其他联系方式,我又发现了一个诡异的问题.

**Comment by testforstephen** [comment]
gitter里面有chat privately功能，你可以用gitter私信我。
https://gitter.im/Microsoft/vscode-java-debug

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> gitter里面有chat privately功能，你可以用gitter私信我。
> https://gitter.im/Microsoft/vscode-java-debug

好的,我私信你啦

**Comment by praxem** [comment]
I have the same issue...

![image](https://user-images.githubusercontent.com/3449037/93502165-60e3df80-f8e4-11ea-8223-164605ccc3ec.png)

Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

Name: Debugger for Java
Version: 0.28.0

Name: Language Support for Java(TM) by Red Hat
Version: 0.67.0

**Comment by ahmednrana** [comment]
This is a critical feature. Its in work in progress.

**Comment by testforstephen** [comment]
Duplicate with #754, let's use that issue to track the progress.
