### ISSUE TITLE
Add setting to enable asserts.

### ISSUE THREAD

**Issue by safield** [microsoft/vscode-java-debug#876]
Currently when I run the debugger, my asserts are not being triggered.

It would be nice if there was a way I could turn on asserts, potentially in an extension setting or something.

**Comment by testforstephen** [comment]
What's asserts? Please explain your user scenario with more details.

**Comment by safield** [comment]
assert is a keyword in Java, and it behaves like assert does in c++.

https://docs.oracle.com/javase/7/docs/technotes/guides/language/assert.html

They can be enabled normally by adding a flag to java at runtime. They are not enabled by default when debugging using the vscode extension.

**Comment by testforstephen** [comment]
Thanks for the details. Currently you can add vmArgs to "-ea" in the launch.json to enable assert. In future, we're planning to expose a global vmArgs in the user settings, where you can add "-ea" as the default value.

**Comment by safield** [comment]
I currently don't have a launch.json. Should I be expecting one to be present?

**Comment by testforstephen** [comment]
By default, the debugger just generates the config in memory. But you could go the debug view to create a launch.json.

![image](https://user-images.githubusercontent.com/14052197/92203646-39d4e900-eeb4-11ea-837c-d707b6fde7ba.png)

**Comment by testforstephen** [comment]
With the latest debugger, you could achieve this by adding user setting `"java.debug.settings.vmArgs": "-ea"`.

**Comment by mediad02** [comment]
> With the latest debugger, you could achieve this by adding user setting `"java.debug.settings.vmArgs": "-ea"`.

um is there a way to enable asserts for C#?

**Comment by testforstephen** [comment]
> um is there a way to enable asserts for C#?

sorry, this extension for Java only. You have to go to C# extension for that.

**Comment by Shemuel2060** [comment]
I am having two classes where one implements the other. The implemented class is the one that uses an assertion statement but when I test it on conditions that evaluate to false, the code still runs and does not print out the error as I expect it to do.

The code in the implemented class is here:

` if (A == 0) {
            throw new IllegalArgumentException("A cannot be zero");
        }
        double disc = B * B - 4 * A * C;
        assert (disc >=0) : ("Discriminant should be >0");`

My configuration file is below:
`{
    "configurations": [
        {
            "type": "java",
            "name": "Equations",
            "request": "launch",
            "mainClass": "Exceptions.Equations",
            "projectName": "Arrays_exceptions_algorithms_820eac63"
        },
        {
            "type": "java",
            "name": "Launch Current File",
            "request": "launch",
            "mainClass": "${file}",
            "vmArgs": "-enableassertions"
        }
    ]
}`

What could be wrong?
