### ISSUE TITLE
Integrated terminal option does not open workspace default terminal

### ISSUE THREAD

**Issue by masbicudo** [microsoft/vscode-java-debug#877]
If my default integrated terminal in Visual Studio Code is git-bash then an error happens. I found out that a workaround is to change the default integrated terminal to cmd or powershell. I tried changing the current terminal in my workspace settings to cmd.exe, but when I hit F5 to start debugging it incorrectly uses git-bash.

If I change the global settings files, then the debugger works as expected... but I don't want to change it globally as I work with git-bash in most of my other projects.

If I press the + button to create a new terminal, it creates a new cmd terminal as expected, using the workspace settings file definition for the default terminal.

##### Environment
- Operating System: Windows 10
- JDK version: 14
- Visual Studio Code version: 1.48.2
- Java extension version: 0.10.0
- Java Debugger extension version: 0.28.0

##### Steps To Reproduce
1. Set git-bash as default integrated terminal in your global settings.
2. Set cmd as default integrated terminal in your workspace settings.
3. Press F5 to launch and start debugging

##### Current Result

It starts debugger using git-bash (which does not work for me):

![image](https://user-images.githubusercontent.com/1653710/92139170-c19ff200-ede5-11ea-99e7-015eae56994d.png)

##### Expected Result

Start debugging in a cmd.exe terminal (which works nicely):

![image](https://user-images.githubusercontent.com/1653710/92139371-09267e00-ede6-11ea-8133-85f0a611713c.png)

(to get this screenshot I had to set the global default terminal)

**Comment by testforstephen** [comment]
Open an issue at https://github.com/microsoft/vscode/issues/108559
