### ISSUE TITLE
Correct use of java.configuration.runtimes for debug configuration

### ISSUE THREAD

**Issue by jahan01** [microsoft/vscode-java-debug#879]
How to use `java.configuration.runtimes`? I have below settings, purposely removed 1.8 from the configuration so that my code runs on 1.11 and when I run the debugger still java version used is 1.8

```jsonc
"java.configuration.runtimes": [
        {
            "name": "JavaSE-11",
            "path": "/Library/Java/JavaVirtualMachines/sapmachine-jdk-11.0.6.0.1.jdk/Contents/Home"
        }
    ],
```
Application.java
```java
public static void main(String[] args) {
		System.out.println(System.getProperty("java.version"));
		System.out.println(System.getProperty("java.runtime.name"));
		System.out.println(System.getProperty("java.runtime.version"));
		System.out.println(System.getProperty("java.vendor"));
}
```
```
1.8.0_252
OpenJDK Runtime Environment
1.8.0_252-b09
AdoptOpenJDK
```

##### Environment
- Operating System: Mac 10.15
- JDK version: 11
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Current Result

```
1.8.0_252
OpenJDK Runtime Environment
1.8.0_252-b09
AdoptOpenJDK
```

##### Expected Result

Debugger runs using JDK 11

**Comment by testforstephen** [comment]
Could you open a Java file, hover at the icon below and share what it displays? The debugger will use the same runtime as the language level mapped runtime.
![image](https://user-images.githubusercontent.com/14052197/90472455-2525f080-e153-11ea-984e-93f5146bbb67.png)

**Comment by jahan01** [comment]
@testforstephen: its JavaSE-8, even though my runtime configurations doesn't include 1.8. So the issue should belong to java language server process ?

**Comment by testforstephen** [comment]
It should be Java language server issue for macOS, it still find the jdk 1.8 even though you didn't configure it.

**Comment by whylostu** [comment]
> @testforstephen: its JavaSE-8, even though my runtime configurations doesn't include 1.8. So the issue should belong to java language server process ?

![image](https://user-images.githubusercontent.com/7161493/93316312-9afaa600-f83e-11ea-99b4-c0e339602421.png)

**Comment by whylostu** [comment]
> @testforstephen: its JavaSE-8, even though my runtime configurations doesn't include 1.8. So the issue should belong to java language server process ?

![QQ图片20200916170749](https://user-images.githubusercontent.com/7161493/93316771-34c25300-f83f-11ea-9278-bf0fa0764fcb.png)

**Comment by testforstephen** [comment]
The debugger will use the same the runtime as the language server recognized. This is nothing much the debugger can do here. Please open an issue at https://github.com/redhat-developer/vscode-java/issues

**Comment by pelegri** [comment]
It would be useful to spell this out in the documentation, as a warning, so people can avoid going a deadend.
