### ISSUE TITLE
Provides class not found exception.

### ISSUE THREAD

**Issue by devil250** [microsoft/vscode-java-debug#887]
Issue Type: <b>Bug</b>

VS Code gives always a single error and that is class not found exception for any java program without showing any other errors.

Extension version: 0.28.0
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:27:59.353Z)
OS version: Windows_NT ia32 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.26GB free)|
|Process Argv|--crash-reporter-id 399a198e-d00f-41b3-9d98-f46823c7e0df|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by testforstephen** [comment]
Could you provide a sample project to reproduce the issue?
