### ISSUE TITLE
Java multiprject workspaces build fail prompt

### ISSUE THREAD

**Issue by srfrnk** [microsoft/vscode-java-debug#888]
When debugging in a workspace with multiple Java projects some may not be building at the moment and so the build will fails.
This triggers a prompt each time you try to debug your project even if it is building correctly.
Until now a configuration flag as been added to disable the build process to this case but if you still want to have your project built you cannot use it.

A better solution would be to add a configuration flag to allow building and proceeding with the debug session even if the build fails.

##### Steps To Reproduce
1. Create workspace
2. Add two Java projects
3. Make one project buildable
4. Make another project un-buildable (introduce a syntax error)
5. Try to debug the buildable project

##### Current Result
Prompts for build failure with following options: "Proceed","Fix...","Cancel"
If "Proceed" selected - allows debugging.

##### Expected Result
If a configuration flag exists with value "Proceed" allow proceeding with debug session.

**Comment by srfrnk** [comment]
Created PR https://github.com/microsoft/vscode-java-debug/pull/889

**Comment by shaochris** [comment]
I'm wondering that if I have multiple separate projects in a single workspace, is that possible to build each single project individually without relating to other projects in the same workspace ?

**Comment by testforstephen** [comment]
Currently the build command doesn't support building a single project yet, could you open a feature request at https://github.com/redhat-developer/vscode-java/issues?

**Comment by srfrnk** [comment]
@shaochris if you open this I'd love to +1 it! If you could please link it here?

**Comment by shaochris** [comment]
@srfrnk No problem.😁

https://github.com/redhat-developer/vscode-java/issues/1651
