### ISSUE TITLE
Debug console should be displayed when in use

### ISSUE THREAD

**Issue by fbricon** [microsoft/vscode-java-debug#894]
With  "java.debug.settings.console": "internalConsole", when you run a Java program that writes to the System.out/err, if the Debug Console view is not opened, it doesn't show up. This is inconsistent with "integratedTerminal", where the Terminal view is opened as soon as the program starts.
```java
public class Foo {
    public static void main(String[] args) {
        System.out.println("Shazaaam");
    }
}
```

**Comment by testforstephen** [comment]
There is a user setting for that. It auto switches to the debug console only on the first session by default. You could change that to below.
```json
{
"debug.internalConsoleOptions": "openOnSessionStart"
}
```
