### ISSUE TITLE
Always getting com.sun.jdi.AbsentInformationException when trying to run a simple file

### ISSUE THREAD

**Issue by PunkIslamist** [microsoft/vscode-java-debug#899]
When I try to run the most basic Hello World program from a single file, I always get an AbsentInformationException.

##### Environment
- Operating System: Windows 10
- JDK version: AdoptOpenJDK 15.0.1 with OpenJ9
- Visual Studio Code version: 1.50.1
- Java extension version: 0.69.0
- Java Debugger extension version: 0.29.0

##### Steps To Reproduce
1. Create Test.java
2. Paste in the following code:
```java
public class Test {
    public static void main(String[] args) {
        System.out.println("Hi");
    }
}
```
3. Press Run on the top right

[log.txt](https://github.com/microsoft/vscode-java-debug/files/5459233/log.txt)

##### Current Result

I receive the following popup and nothing else happens:
![image](https://user-images.githubusercontent.com/26367652/97589534-e8516200-19fd-11eb-9866-5aa6d175d11b.png)

##### Expected Result

It runs the program

##### Additional Informations

I can `javac Test.java && java Test` just fine.

**Comment by testforstephen** [comment]
Are you using adoptopenjdk-openj9-jre? You're supposed to use JDK instead of JRE to launch VS Code Java.

**Comment by PunkIslamist** [comment]
> Are you using adoptopenjdk-openj9-jre? You're supposed to use JDK instead of JRE to launch VS Code Java.

That was indeed the problem! I uninstalled `adoptopenjdk-openj9-jre`, installed `adoptopenjdk-openj9` and now it is working flawlessly. Thanks for the help!

But the problem still surprises me as the build tools were bundled in the installation as well. But I guess this is not the place to discuss it.

Thanks again!
