### ISSUE TITLE
Support update the invalid breakpoint into next valid line.

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#90]
https://code.visualstudio.com/updates/v1_17#_debug-adapter-protocol

**Comment by andxu** [comment]
title updated

**Comment by andxu** [comment]
first step: fix an bp bug: https://github.com/Microsoft/java-debug/pull/129/files

**Comment by andxu** [comment]
While vscode support the breakpoint line number change, but it is still not a smooth experience when user set the breakpoint, the line number is not checked until debug session is started, that makes user very strange after press F5( his breakpoints are changes), so my fix will not update the line number but to make all **invalid** breakpoints invalid.
