### ISSUE TITLE
Remote Debugging is not showing the source file

### ISSUE THREAD

**Issue by willianm** [microsoft/vscode-java-debug#905]
Something happened from v0.28.0 to v0.29.0. After I upgraded the extension "Debugger from Java", VS Code doesn't show me the source code when it stops in a breakpoint. Instead, it shows me the ".class" file. It's weird, because:
1. I can see in the Call Stack that it is stopping in the correct line
2. I can still add the break point in the source code file
3. It just doesn't show me the source code and it doesn't highlight the line of code

If I downgrade the extension to v0.28.0, then it shows the correct source code file and highlights the correct line of code.

I'm using Remote Development Extension

##### Environment
- Remote Operating System: Docker image: lambci/lambda
- Local Operating System: macOS Catalina
- JDK version: 8
- Visual Studio Code version: 1.51.0
- Java extension version: v0.10.0
- Java Debugger extension version: v0.29.0

##### Steps To Reproduce
1. Setup your environment to use VS Code remote development
2. Add a breakpoint and run the application in a docker container
3. Attach the debugger
4. Wait for it to hit the breakpoint

##### Current Result
It will show a .class file with the skeleton of the class

##### Expected Result
Show the source code and highlight the line

**Comment by mdcashion** [comment]
Good find!
I pulled my hair out trying to figure out why I couldn't debug .java code because the debugger was showing .class files.
This is a major problem and should be fixed ASAP!

**Comment by testforstephen** [comment]
Does this issue still exist in the latest debugger 0.37.0?

**Comment by mdcashion** [comment]
The problem does not exist in Debugger for Java v0.37.0.

**Comment by testforstephen** [comment]
thank you for confirm. I'm closing it, feel free to reopen it if you suffered the issue again.

**Comment by hichits** [comment]
am seeing the same problem in v0.55.2023121302

**Comment by iisystems** [comment]
I'm also seeing this on v0.57.0

**Comment by V4sec** [comment]
I'm also seeing this on v0.57.0, it shows "Could not load source 'XXX.java': SourceRequest: property 'sourceReference' is missing, null, or empty."
