### ISSUE TITLE
Cannot set JVM for debugger

### ISSUE THREAD

**Issue by mentaloaf** [microsoft/vscode-java-debug#907]
No matter what I do to try and force the Debugger for Java vscode extension to use JVM 14.0.1, it uses 1.8.0_60.  I have searched far and wide and made the system default 14.0.1, set my JAVA_HOME to 14.0.1, set the vscode setting to 14.0.1, verified in the shell and a vscode task that the JVM is set to 14.0.1 (see below and attached pictures).  I must be missing something but how can I force the Debugger for Java to use the JVM of my choice?

##### Environment
- Operating System:
macOS Mojave 10.4.6

- JDK version:
1.8, 14.0.1

- Visual Studio Code version:
1.51.1

- Java extension version:
Java extension pack: 0.10.0
Language support for Java:  0.70.0

- Java Debugger extension version:
0.29.0

##### Steps To Reproduce
1. Verify system wide java version is 14.0.1:
```
[jj@macpro backtester (master)]$ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home
[jj@macpro backtester (master)]$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home/
[jj@macpro backtester (master)]$ unset JAVA_HOME
[jj@macpro backtester (master)]$ echo $JAVA_HOME

[jj@macpro backtester (master)]$ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home
[jj@macpro backtester (master)]$ which java
/usr/bin/java
[jj@macpro backtester (master)]$ ls -l /usr/bin/java
lrwxr-xr-x  1 root  wheel  74 Nov 14  2018 /usr/bin/java -> /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java
[jj@macpro backtester (master)]$ /usr/bin/java --version
java 14.0.1 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
[jj@macpro backtester (master)]$ java --version
java 14.0.1 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
[jj@macpro backtester (master)]$ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home
![debugger_warning](https://user-images.githubusercontent.com/22648656/99319411-8ff7ce00-280d-11eb-8d1d-4601177acf79.png)

```

2. Run vscode and run a task to verify the JVM version is 14.0.1 as well (see attached screenshots).
3.  Attach to a JVM which is running 14.0.1.
4.  See warning about debugger JVM version being 1.8.0_60 not matching expected remote JVM version 14.0.1.

##### Current Result
[Warn] The debugger and the debuggee are running in different versions of JVMs. You could see wrong source mapping results.
Debugger JVM version: 1.8.0_60
Debuggee JVM version: 14.0.1

##### Expected Result
Java debugger used would correspond to one set by JAVA_HOME, java.home vscode setting and system wide default - all of which are 14.0.1.  I have done everything I could find and think of to force the Java Debugger to use JVM 14.0.1.  What setting controls this?  I thought it was the java.home property in the .vscode/settings.json file.

##### Additional Informations
![settings_json_pic](https://user-images.githubusercontent.com/22648656/99319087-07792d80-280d-11eb-852d-706d60e052ef.png)
![java_home_echo_task_output](https://user-images.githubusercontent.com/22648656/99319244-45765180-280d-11eb-904a-f89f0975ce22.png)
![java_home_task](https://user-images.githubusercontent.com/22648656/99319248-460ee800-280d-11eb-8fec-87992652873c.png)

**Comment by testforstephen** [comment]
"java.home" setting is just used to provide a runtime for Java tooling itself. Your project JDK is specified by the build configuration file such as pom.xml and build.gradle. 

Could you share your project's actual language level. You can open a Java file, hover at the icon below and share what it displays? 
![image](https://user-images.githubusercontent.com/14052197/90472455-2525f080-e153-11ea-984e-93f5146bbb67.png)

**Comment by mentaloaf** [comment]
Yes thank you that was it!  FWIW I added this to y ~/.gradle/gradle.properties:

org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home/

And I made sure my build.gradle had the following lines:

sourceCompatibility = 14
targetCompatibility = 14

And then my language level showed correctly and I no longer got the debugger JVM mismatch warning.  Thank you so much for your help!

**Comment by testforstephen** [comment]
Nice to know you solved it by yourself.

BTW you could also map a different JDK for your project via the following setting. "java.home" is used to launch the Java tooling itself, and "java.configuration.runtimes" is used to specify a JDK for your project.

```json
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-1.8",
            "path": "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home"
        },
        {
            "name": "JavaSE-11",
            "path": "/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home"
        }
    ]
```

I'm going to close this issue. Feel free to reopen it if you need more discussion about it.
