### ISSUE TITLE
Cannot evaluate because of compilation error(s): Variable information unavailable for native methods.

### ISSUE THREAD

**Issue by tomasblahut** [microsoft/vscode-java-debug#917]
##### [provide a description of the issue]
Debugger fails to evaluate local variable expressions, while being paused inside a method, that was invoked on an object, declared as lambda expression, using reflection. Hovering over these variables also doesn't show variable information popup dialog.

![lambda](https://user-images.githubusercontent.com/11849936/101277707-8cc18380-37b6-11eb-89ee-dbd20c3b0f97.png)

Issue cannot be reproduced, if the given method is invoked on an object, declared as anonymous class instead.

![anonclass](https://user-images.githubusercontent.com/11849936/101277711-90550a80-37b6-11eb-8899-f59d73c79df8.png)

##### Environment
- Docker version: 19.03.14, build 5eb3275d40
- Host Operating System version: Linux Mint 20 Ulyana, kernel 5.4.0-56
- Container Operating System: Debian GNU/Linux 10 (buster), kernel 5.4.0-56-generic
- JDK version: openjdk 11.0.9 2020-10-20
- Visual Studio Code version: 1.51.1
- Java extension version: 0.12.0
- Java Debugger extension version: 0.29.0
- Remote Development extension version: 0.20.0
- Remote - Containers extension version: 0.148.1

##### Steps To Reproduce
1. Download attached sample project, extract and open it in VS Code
2. Install Remote Development extension
3. Execute "Remote-Containers: Reopen in Container" command
4. Add breakpoint on line 12 in Main.java source file
5. Start Debugger by pressing F5
6. Execution is paused at breakpoint on Main.java:12
7. Navigate to VS Code Run View and add a new watch witch "parameter" expression -> Cannot evaluate because of compilation error(s): Variable information unavailable for native methods.
8. Hover over "parameter" variable on Main.java:10 -> no variable information popup is displayed

##### [attach a sample project reproducing the error]
[java-debugger-issue.zip](https://github.com/microsoft/vscode-java-debug/files/5648654/java-debugger-issue.zip)

##### [attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
[logs.zip](https://github.com/microsoft/vscode-java-debug/files/5648680/logs.zip)

##### Current Result
1. Watches in VS Code Run view don't display variable values. Instead a "Cannot evaluate because of compilation error(s): Variable information unavailable for native methods" error is shown
2. No variable information popup dialog is displayed while hovering over a variable

##### Expected Result
1. Watches in VS Code Run view display current variable values.
2. While hovering over a variable, the variable information popup dialog is displayed

**Comment by testforstephen** [comment]
There is some limitation about evaluation support inside the lambda function at the moment. This is also reproduced in the eclipse, have to fix it in the upstream jdt first.

**Comment by testforstephen** [comment]
Duplicate with #754, let's use that issue to track the progress.
