### ISSUE TITLE
ClassNotFoundException with nested maven projects

### ISSUE THREAD

**Issue by GaZaTu** [microsoft/vscode-java-debug#920]
I have the following project structure: parent-pom -> sub-parent-pom -> lib1-pom; parent-pom -> main-pom
If i run the main-pom project using a default launch.json config the lib1-pom `target/classes` won't be in the classpath (visisble in `System.getProperty(java.class.path)`), and i'll get a `ClassNotFoundException`.
Would be nice if the child modules of sub-parent-pom would be resolved aswell.
A workaround would be if i could add classpath entries manually in the launch.json without overriding the default classpath generated by [export function resolveClasspath(mainClass: string, projectName: string) {](https://github.com/microsoft/vscode-java-debug/blob/b41dabe19a7904d8a72d5cb25e4da7cb91077670/src/languageServerPlugin.ts#L48). The current behavior only adds the default classpath if i didn't specify `"classPaths"` at all.

##### Environment
- Operating System: openSUSE Leap 42.2
- JDK version: 11.0.8, 2020-07-14
- Visual Studio Code version: 1.50.0, 2020-10-07
- Java extension version: 0.72.0, [2020-12-02]
- Java Debugger extension version: v0.29.0, 2020-10-16

**Comment by testforstephen** [comment]
Could you please provide a minimum sample project to help reproduce the issue?

**Comment by GaZaTu** [comment]
Turns out it works by default and stops working if i add a classifier to my dependency (which i need kinda).
[repro-nested-maven-debug.zip](https://github.com/microsoft/vscode-java-debug/files/5693962/repro-nested-maven-debug.zip)

**Comment by testforstephen** [comment]
Starting from 0.34.0, the debugger allows you to append extra classpaths to launch.json. See https://github.com/microsoft/vscode-java-debug/issues/980#issuecomment-848462735 about the usage.
