### ISSUE TITLE
Show long path in terminal after click run button multiply 

### ISSUE THREAD

**Issue by SunnyChen1** [microsoft/vscode-java-debug#924]
**Environment**
Operating System: Win10
JDK version: 13.0.2
Visual Studio Code version: 1.52.0
Vscode java project manager: 0.16.0
Java Debugger extension version: 0.30.0

**Steps To Reproduce**
1.Open spring-petclinic in vscode.
2.Click run button from JAVA PROJECTS multiply
3. Show  long path in terminal and can't run sucessfully

**Current Result**
![image](https://user-images.githubusercontent.com/63633836/102436392-6bcd1e00-4053-11eb-89ab-95815bf45ac9.png)

**Comment by testforstephen** [comment]
Cannot reproduce it in macOS, will try more machine to see whether it's reproducible.
