### ISSUE TITLE
Support set extra classpath with maven project

### ISSUE THREAD

**Issue by jopbrown** [microsoft/vscode-java-debug#93]
I need to add an extra classpath based on a maven project.
If I add the extra classpath to `classPaths`, the main class can't be found.

It seems launch option `classPaths` will overwrite classpaths automatically resolved from maven project.

Dose the debugger support set extra classpath and preserve automatically resolved classpaths just like eclipse?
![2017-10-13_150917](https://user-images.githubusercontent.com/6345470/31534203-892fc6dc-b028-11e7-8ee3-0eb170a52574.png)

**Comment by akaroml** [comment]
Please see if we can inherit whatever classpath from Maven project and append what's specified in launch.json instead of replacing.

**Comment by andxu** [comment]
The extra class path is reasonable, but the removed class path is not reasonable, I will impl this feature in 0.4.0

**Comment by andxu** [comment]
Because of the schedule change, I will move this feature to backlog

**Comment by studro** [comment]
Is there any plan to revisit this issue? I have a project configured in a strange way that runs with custom classpath entries (Gradle build output dirs) in Eclipse and IntelliJ. I'd like to be able to add these entries to the classpath in the `launch.json` file without having to hack at the generated `.classpath` file.

**Comment by ErwanDL** [comment]
I would also very much like to see this feature implemented, I need to add extra classpath entries to a Maven project without overriding the project's default ones. This feature would help a ton 😃

**Comment by akaroml** [comment]
@studro @ErwanDL Thanks for reaching out.

@testforstephen would you please take over this issue take a further look?

**Comment by CarlosLoboZamarro** [comment]
I have the same problem as @jopbrown and @ErwanDL, I need to add extra folder into classpath.
As @ErwanDL says, This feature would help a ton :smile: 
Thanks!!

**Comment by testforstephen** [comment]
The debugger 0.34.0 supports the following predefined variables in classPaths/modulePaths configs of launch.json.
- $Auto - Automatically resolve the classpaths of current project
- $Runtime - The classpaths within 'runtime' scope of current project
- $Test - The classpaths within 'test' scope of current project
- !\<path\> - Exclude the specified path from classpaths.

You can see the sample below to add extra classpath to launch.json.

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Launch Foo",
            "request": "launch",
            "mainClass": "foo.bar.Foo",
            "classPaths": [
                "$Auto",
                "<extra class path>"
            ]
        }
    ]
}

```
