### ISSUE TITLE
How can I keep the startup command when I start debugging for the first time

### ISSUE THREAD

**Issue by refcell** [microsoft/vscode-java-debug#930]
Keeping the startup command is very important to be able to configure `launch.json` correctly, but the startup command will flash by when I start debugging for the first time, so I can only get the startup command by starting debugging again, which is very unnatural.
If possible, hope to add a option to configure this feature.

##### Environment
- Operating System: Windows 10
- JDK version: 1.8.0_265
- Visual Studio Code version: 1.52.1
- Java extension version: v0.73.0
- Java Debugger extension version: v0.30.0

##### Steps To Reproduce
Debug a Java project.

##### Current Result
Debug twice
![image](https://user-images.githubusercontent.com/14192199/103606603-c8847000-4f51-11eb-9ba6-2b6ce21038f0.png)

##### Expected Result
Debug once
![image](https://user-images.githubusercontent.com/14192199/103606627-dcc86d00-4f51-11eb-8d65-9c61a98f6b04.png)

**Comment by testforstephen** [comment]
What do you mean the startup command will flash?

I cannot reproduce it.

https://user-images.githubusercontent.com/14052197/103870928-55245f00-5107-11eb-90cd-d3ebdc0116fb.mov

**Comment by refcell** [comment]
My situation is as follows

https://user-images.githubusercontent.com/14192199/103885897-a9d1d500-511b-11eb-9028-a7fdca2e8b9c.mp4

And this is my settings.json

```json
{
    "window.restoreWindows": "none",
    "window.openFilesInNewWindow": "default",
    "workbench.settings.useSplitJSON": true,
    "workbench.settings.editor": "json",
    "workbench.startupEditor": "newUntitledFile",
    "extensions.ignoreRecommendations": false,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "terminal.integrated.rendererType": "dom",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "C_Cpp.updateChannel": "Insiders",
    "workbench.iconTheme": "vscode-icons",
    "vsicons.dontShowNewVersionMessage": true,
    "workbench.list.openMode": "doubleClick",
    "debug.allowBreakpointsEverywhere": true,
    "debug.onTaskErrors": "showErrors",
    "search.searchOnType": false,
    // "debug.console.wordWrap": false,
    "java.semanticHighlighting.enabled": true,
    "liveServer.settings.donotShowInfoMsg": true,
    "java.home": "C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.8.10-hotspot",
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-1.8",
            "path": "C:\\Program Files\\AdoptOpenJDK\\jdk-8.0.265.01-hotspot",
            "default": true
        }
    ],
    "java.project.importOnFirstTimeStartup": "automatic",
    "java.refactor.renameFromFileExplorer": "autoApply",
    "java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:\"c:\\Users\\Admin\\.vscode\\extensions\\gabrielbb.vscode-lombok-1.0.1\\server\\lombok.jar\"",
    "liveServer.settings.donotVerifyTags": true,
    "shellformat.flag": "-i 2",
    "rust-analyzer.notifications.cargoTomlNotFound": false
}
```

**Comment by testforstephen** [comment]
very weird. I also tried it in another windows 10 machine, cannot reproduce the issue either.

Could you try to disable other extensions and only keep Java related extensions? 

If this issue still exists, i would suggest you to open an issue at https://github.com/microsoft/vscode/issues, since the terminal behavior is controlled by the VS Code platform, not by extensions.

**Comment by refcell** [comment]
This problem exists on both of my Windows 10 machines, and my colleague’s Windows 10 machine is also the same.

For testing, I installed a virtual machine with Windows 7 32bit, and vscode installed, and only the Java Extension Pack was installed. The problem also exists.

Here is the configuration of vscode in my virtual machine.

```json
{
    "java.home": "C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.9.101-hotspot",
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-1.8",
            "path": "C:\\Program Files\\AdoptOpenJDK\\jdk-8.0.275.01-hotspot",
            "default": true
        }
    ],
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue"
}
```

**Comment by testforstephen** [comment]
this needs to create an issue at https://github.com/microsoft/vscode/issues
