### ISSUE TITLE
Changes during preLaunchTask and postDebugTask are not registered

### ISSUE THREAD

**Issue by fredg1** [microsoft/vscode-java-debug#934]
Changes to the current files happening during `preLaunchTask` and/or `postDebugTask` does not cause the debugger to refresh its version of the files/cache.

##### Environment
- Operating System: Windows 10
- JDK version:  java version "15.0.1" 2020-10-20
  Java(TM) SE Runtime Environment (build 15.0.1+9-18)
  Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
- Visual Studio Code version: 1.52.1 (user setup)
- Java extension version: Language Support for Java(TM) by Red Hat, version 0.73.0 (***everything** else is disabled*)
- Java Debugger extension version: 0.30.0
![Code_h5MniYyaUs](https://user-images.githubusercontent.com/22716338/104981143-12e80100-59d6-11eb-80cf-8c1f9d1281ea.png)

##### Steps To Reproduce
1. Make a `launch.json` with a `preLaunchTask` and/or a `postDebugTask`
2. Have said task(s) edit the current project in any way, directly or indirectly.
3. Start debugging
4. Use Print statements or breakpoints to keep track of the modifications you made in the Java file. Notice how they no longer reflect what you can see in the Editor.
  (note: if you only used a `postDebugTask`, there will obviously not be anything different the first time you run the project.)

5. (optional) Keep running the project, again and again. Notice how the debugger keeps refusing to pick up the changes made by the tasks.
6. Make any manual edit to the Java file (one that will still successfully compile, of course), and save.
7. Start debugging, one last time. Notice how all the edits made by the previous tasks suddenly appear (excluding the ones from the `preLaunchTask` of this very debug session).

Here is the simplest/most straightforward example I could get:
![firefox_NGNHUNGZV7](https://user-images.githubusercontent.com/22716338/104987437-bd1a5580-59e3-11eb-81a2-f8fa69752e1d.png)
![firefox_JNm2zLOHgp](https://user-images.githubusercontent.com/22716338/104988118-42523a00-59e5-11eb-81cb-134bbdd042ae.png)
![firefox_rVHhlKFGD1](https://user-images.githubusercontent.com/22716338/104988125-45e5c100-59e5-11eb-987c-21325f024b29.png)
![sJNi3hlcni](https://user-images.githubusercontent.com/22716338/104988127-48e0b180-59e5-11eb-9a47-033539e47bcf.png)

[attached log](https://github.com/microsoft/vscode-java-debug/files/5833658/log.txt)

##### Additional Informations
Before executing the preLaunchTask or the postDebugTask, you will be asked if you want to save. Whether you do save, or not, has no impact on the result of this issue.

Worked fine a few months ago...

**Comment by testforstephen** [comment]
Could you share your user settings? Also could you try other languages such as javascript with the same steps to see whether it can reproduced?

**Comment by fredg1** [comment]
I did try with python and JavaScript (the built-in Node debugger). I can confirm this only occurs with Java.

**Comment by fredg1** [comment]
User `setting.json` :
```{
    "git.autofetch": true,
    "editor.insertSpaces": false,
    "task.saveBeforeRun": "prompt",
    "files.autoSave": "off",
    "update.showReleaseNotes": false,
    "extensions.autoUpdate": false,
    "diffEditor.renderSideBySide": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "java.semanticHighlighting.enabled": true,
    "java.configuration.checkProjectSettingsExclusions": false,
    "todo-tree.tree.showScanModeButton": false,
    "gremlins.showInProblemPane": true,
    "cSpell.enableFiletypes": [
        "xml"
    ],
    "java.test.log.level": "verbose",
    "editor.wordWrap": "on",
    "diffEditor.ignoreTrimWhitespace": false,
    "python.languageServer": "Microsoft",
    "gitlens.gitCommands.closeOnFocusOut": true,
    "editor.minimap.enabled": false,
    "cSpell.userWords": [],
    "editor.columnSelection": false,
    "cSpell.ignoreWords": [],
    "terminal.integrated.shell.windows": "C:\\windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "editor.renderControlCharacters": true,
    "editor.renderWhitespace": "all",
    "breadcrumbs.enabled": true,
    "svn.detectIgnored": false,
    "svn.detectExternals": false,
    "workbench.editorAssociations": [],
    "github-actions.org-features": true,
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "[css]": {
        "editor.defaultFormatter": "aeschli.vscode-css-formatter"
    },
    "[javascript]": {
        "editor.defaultFormatter": "mblode.pretty-formatter"
    }
}```

**Comment by fredg1** [comment]
`workspace.code-workspace` :
(this was only done to have as little extraneous information as possible filling the logs. The issue happens without those settings. Only showing them to be thorough)
```
{
	"folders": [
		{
			"path": ".."
		}
	],
	"settings": {
		"java.trace.server": "verbose",
		"java.debug.settings.showToString": false,
		"java.debug.settings.showLogicalStructure": false,
		"java.debug.settings.hotCodeReplace": "never",
		"java.debug.settings.enableRunDebugCodeLens": false,
		"java.codeGeneration.toString.listArrayContents": false,
		"java.completion.enabled": false,
		"java.completion.overwrite": false,
		"java.format.comments.enabled": false,
		"java.format.onType.enabled": false,
		"java.foldingRange.enabled": false,
		"java.import.gradle.enabled": false,
		"java.import.gradle.wrapper.enabled": false,
		"java.import.maven.enabled": false,
		"java.references.includeAccessors": false,
		"java.selectionRange.enabled": false,
		"java.semanticHighlighting.enabled": false,
		"java.configuration.checkProjectSettingsExclusions": false,
		"java.configuration.updateBuildConfiguration": "disabled",
		"java.format.enabled": false
	}
}

**Comment by testforstephen** [comment]
Actually it has nothing to do with preLaunchTask and postDebugTask. I can reproduce it by manually running a powershell command to modify the Java file, then running that Java file with debugger, what it reads is still the old contents.

![builderModified](https://user-images.githubusercontent.com/14052197/105327891-6e023980-5c0a-11eb-9bad-19b3280a3886.gif)

Looks like the Java builder didn't detect the file change from external tool, and didn't recompile the class. This needs to be fixed at https://github.com/eclipse/eclipse.jdt.ls

**Comment by fredg1** [comment]
That's weird? The very first message of the logs is the one saying there was a change...
```
[Trace - 23 h 23 min 16 s] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/Frederic/Desktop/VScode_test/test.java",
        "version": 90
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 2,
                    "character": 0
                },
                "end": {
                    "line": 3,
                    "character": 0
                }
            },
            "rangeLength": 48,
            "text": "\t\tString PRE_VARIABLE = \"This text was modified\";\r\n"
        }
    ]
}

**Comment by fredg1** [comment]
Should I close this issue, then?

**Comment by testforstephen** [comment]
@fredg1 thank you to create new issue at eclipse.jdt.ls project. Yes, we can move the further discussion there.
