### ISSUE TITLE
  Maven warehouse directory${ user.home }/. m2 / repository instead of custom

### ISSUE THREAD

**Issue by xiuluodaren** [microsoft/vscode-java-debug#941]
Maven warehouse directory${ user.home }/. m2 / repository instead of custom
maven 仓库目录总是 ${user.home}/.m2/repository 而不是自定义的

**Comment by testforstephen** [comment]
You have to configure your custom settings.xml in VS Code user settings.

You could configure Maven's user settings via `java.configuration.maven.userSettings`.
Maven's global settings via `java.configuration.maven.globalSettings`.

**Comment by hudayee** [comment]
I have set `java.configuration.maven.userSettings` and  `java.configuration.maven.globalSettings` ,but it not working in wsl2
