### ISSUE TITLE
Support debugging the decompiled classes

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [microsoft/vscode-java-debug#945]

**Comment by YU5Z8X2CvH1fv4ep** [comment]
有一个反编译插件可以点进类,但是无法直接 跳转到符号,这也是一个很蛋疼的问题

啥时候能支持啊大哥们,这一个小功能就足以让我这用vscode的跳转到IDEA了.
然后调试和写代码分开一会用IDEA一会用vscode很难受啊~~~

**Comment by testforstephen** [comment]
> 有一个反编译插件可以点进类,但是无法直接 跳转到符号

We're working on fix it for "Go to definition" feature. After the basic language features such as go to definition work in the decompiled classes, then we're going to consider the debug support.

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> > 有一个反编译插件可以点进类，但是无法直接重定向到符号
> 
> 我们正在为“转到定义”功能进行修复。在反编译类中使用了诸如定义定义之类的基本语言功能之后，我们将考虑调试支持。

等这个功能做出来了,vscode就真的可以和IDEA一分高下了。不仅仅被IDEA党们喷:"vscode 仅仅是一个编辑器". >_<

**Comment by testforstephen** [comment]
Stay tuned at https://github.com/eclipse/eclipse.jdt.ls/pull/1632.

So far, you could also use "Attach Source" feature to attach the associated source jar to your binary class.
![image](https://user-images.githubusercontent.com/14052197/106440204-89473180-64b3-11eb-8e4f-fa0993e92779.png)

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> 请继续关注[eclipse / eclipse.jdt.ls＃1632](https://github.com/eclipse/eclipse.jdt.ls/pull/1632)。
> 
> 到目前为止，您还可以使用“附加源”功能将关联的源jar附加到您的二进制类。
> ![图片](https://user-images.githubusercontent.com/14052197/106440204-89473180-64b3-11eb-8e4f-fa0993e92779.png)

这个我知道,但是有时候调试没源码的功能就比较麻烦.

哎我在想,是否可以直接对jar反编译后,然后打包后attach源进去然后断点?

等下试试哈哈哈

**Comment by testforstephen** [comment]
反汇编的代码，行号可能会对不上。需要做一层转换，重新映射class和反汇编代码的行号关系。

The line numbers between the decompiled code and source code are not consistent, need some extra mapping translator to remap the line numbers.

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> 需要做一次转换，重新映射类和反汇编代码的行号关系。
> 
> 反编译代码与源代码之间的行号不一致，需要一些额外的映射转换器才能重新映射行号。

哦哦也是,不过除了行号问题,反编译调试的的最大问题就是对反编译的类的符号进行定位了,比如调试时候的步近和步出,不但要源码->反编译源码 还要求 反编译源码-->反编译源码 这些要做好了就没问题了.
