### ISSUE TITLE
When debugging, pause at the time of uncaught exception, can you filter the class name

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [microsoft/vscode-java-debug#946]
在调试的时候有一个对未捕获的异常进行自动断点的功能,能否对这捕获的类进行断点过滤?

因为我有时候只想看一个类中未捕获的异常,但是一下子出来很多

**Comment by YU5Z8X2CvH1fv4ep** [comment]
全部都停下来了,我只想让某一个类,或者某个包下的类的断点

**Comment by testforstephen** [comment]
Take a look at https://github.com/microsoft/vscode-java-debug/issues/756#issuecomment-659264364.

If you want to break on exception for "Just My Code", you can add the following settings for that.
```
    "java.debug.settings.exceptionBreakpoint.skipClasses": [
        "$JDK", // Skip the JDK classes from the default system bootstrap classpath, such as rt.jar, jrt-fs.jar.
        "$Libraries", // Skip the classes from application libraries, such as Maven, Gradle dependencies.
        // "java.myPackage.myClass"
    ],
```

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> 看一下[＃756（评论）](https://github.com/microsoft/vscode-java-debug/issues/756#issuecomment-659264364)。
> 
> 如果要中断“ Just My Code”的例外，则可以为此添加以下设置。
> 
> ```
>     "java.debug.settings.exceptionBreakpoint.skipClasses": [
>         "$JDK", // Skip the JDK classes from the default system bootstrap classpath, such as rt.jar, jrt-fs.jar.
>         "$Libraries", // Skip the classes from application libraries, such as Maven, Gradle dependencies.
>         // "java.myPackage.myClass"
>     ],
> ```

好的谢谢
