### ISSUE TITLE
Can't press Ctrl+F5 to start without debugging

### ISSUE THREAD

**Issue by chenyuanmac** [microsoft/vscode-java-debug#947]
##### Environment
- Operating System:Linux
- JDK version:14.0.2
- Visual Studio Code version:1.52.1
- Java extension version:0.74.0
- Java Debugger extension version:0.31.0

##### Steps To Reproduce
1. Open a Hello world project in VS Code
2. Set a breakpoint
3. Press Ctrl+F5to start without debugging

##### Current Result
The program cannot be run and vscode windows will be closed auto.

##### Expected Result
The program starts without hitting the breakpoint.

**Comment by testforstephen** [comment]
Duplicates with https://github.com/microsoft/vscode/issues/115600
