### ISSUE TITLE
onBuildFailureProceed setting is ignored

### ISSUE THREAD

**Issue by rothfels** [microsoft/vscode-java-debug#949]
I noticed that our Java debug launch configuration stopped producing the `Build failed, do you want to continue?` message even when the project has compiler errors.

According to the language server log, the workspace does fail to build when I run the debugger:

```
!ENTRY org.eclipse.jdt.ls.core 1 0 2021-02-22 13:13:52.570
!MESSAGE >> java/buildWorkspace (incremental)

!ENTRY org.eclipse.jdt.ls.core 4 0 2021-02-22 13:13:52.572
!MESSAGE Error occured while building workspace. Details: 
[[redacted]]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-02-22 13:13:53.579
!MESSAGE >> workspace/executeCommand vscode.java.validateLaunchConfig

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-02-22 13:13:53.580
!MESSAGE >> workspace/executeCommand vscode.java.resolveClasspath

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-02-22 13:13:53.739
!MESSAGE >> workspace/executeCommand vscode.java.resolveJavaExecutable

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-02-22 13:13:53.741
!MESSAGE >> workspace/executeCommand vscode.java.checkProjectSettings

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-02-22 13:13:53.741
!MESSAGE >> workspace/executeCommand vscode.java.fetchPlatformSettings

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-02-22 13:13:53.741
!MESSAGE >> workspace/executeCommand vscode.java.inferLaunchCommandLength

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-02-22 13:13:53.754
!MESSAGE >> workspace/executeCommand vscode.java.startDebugSession
```

I can verify the project build failure by directly running the `Java: Force Java Compilation` command:

![image](https://user-images.githubusercontent.com/1095573/108771288-4c011d00-7510-11eb-9c7b-03a865a0e192.png)

I tried explicitly setting these extension configs (but I believe they are the defaults):

```
  "java.debug.settings.forceBuildBeforeLaunch": true,
  "java.debug.settings.onBuildFailureProceed": false
```

##### Environment
- Operating System: `MacOS 11.2`
- JDK version: `openjdk 15.0.1 2020-10-20`
- Visual Studio Code version: `1.53.2`
- Java extension version: `0.75.0`
- Java Debugger extension version: `0.31.0`

##### Steps To Reproduce
- Add config to `launch.json`

```
{
      "type": "java",
      "name": "<file>",
      "request": "launch",
      "cwd": "${workspaceFolder}",
      "console": "internalConsole",
      "internalConsoleOptions": "openOnSessionStart",
      "stopOnEntry": false,
      "mainClass": "<class>",
      "projectName": "<project>"
    }
```
- add compiler error to source
- run launch config

##### Current Result

No warning / popup.

##### Expected Result

![image](https://user-images.githubusercontent.com/1095573/108771811-ff6a1180-7510-11eb-8cb6-008c630f1dc0.png)

**Comment by testforstephen** [comment]
The root cause is from https://github.com/microsoft/vscode/issues/116932#issuecomment-787816529
