### ISSUE TITLE
Generate debug configuration with correct mainClass

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-debug#95]
To decrease the user error of main class, let's generate a working launch.json by default.

Currently, the generated launch.json does not have main class specified. With the help of new configuration provider mechanism of VS Code, we have the chance to calculate the correct configuration and return to VS Code to persist as launch.json.

When generating debug configuration, we iterate all the main classes inside the current workspace and generate one launch config for each main class. Then a user can pick whichever they want to launch and they will probably succeed.

**Comment by ansyral** [comment]
delivered in 0.2.0
