### ISSUE TITLE
Question: Step filters do not affect Java Test Runner?

### ISSUE THREAD

**Issue by aderchox** [microsoft/vscode-java-debug#954]
Why do "step filter"s not work when running Java tests? I'm a noob, but is it the responsibility of the "Java Test Runner" extension to provide an additional option for skipping the debugging of the code from certain packages(e.g. library packages)? (Something like the "Step Filters" in vscode's Java debugger extension.) Currently, I am forced to specify a main class for the java debugger while a test class is not a main class, so I don't know how to make the launch configuration I make to affect the test runner as well. Thanks in advance.

##### Environment
- Operating System: Win
- JDK version: 15
- Visual Studio Code version: 1.53.2
- Java extension version: Language Support by RedHat v0.75.0
- Java Debugger extension version: 0.31.0

##### Steps To Reproduce
1. Add step filters in launch configuration
2. Debug tests
3. The debugger steps into the library code

##### Current Result
Steps into library code
##### Expected Result
Not step into library code

**Comment by testforstephen** [comment]
Java Test Runner will auto generate the test configuration and pass it to debugger, and it won't read your local launch.json. @jdneo please correct me if i'm wrong.

Please use the user setting "java.debug.settings.stepping.skipClasses" to specify the step filters.

**Comment by jdneo** [comment]
Yes, currently the test configuration does not support the `stepFilters`

duplicated with https://github.com/microsoft/vscode-java-test/issues/1152

**Comment by testforstephen** [comment]
ok, i will close this issue in debugger, and let Java test runner to handle it.
