### ISSUE TITLE
Not a project with java nature.

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#96]
stackTrace: 'org.eclipse.core.runtime.CoreException: Not a project with java nature.\n\tat com.microsoft.java.debug.plugin.internal.JdtSourceLookUpProvider.getJavaProjectFromName(JdtSourceLookUpProvider.java:227)\n\tat com.microsoft.java.debug.plugin.internal.JdtSourceLookUpProvider.searchDeclarationFileByFqn(JdtSourceLookUpProvider.java:237)\n\tat com.microsoft.java.debug.plugin.internal.JdtSourceLookUpProvider.getSourceFileURI(JdtSourceLookUpProvider.java:186)\n\tat com.microsoft.java.debug.core.adapter.handler.StackTraceRequestHandler.lambda$convertDebuggerSourceToClient$0(StackTraceRequestHandler.java:115)\n\tat com.microsoft.java.debug.core.adapter.handler.StackTraceRequestHandler$$Lambda$70/315835248.apply(Unknown Source)\n\tat java.util.HashMap.computeIfAbsent(HashMap.java:1118)\n\tat java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672)\n\tat com.microsoft.java.debug.core.adapter.handler.StackTraceRequestHandler.convertDebuggerSourceToClient(StackTraceRequestHandler.java:114)\n\tat com.microsoft.java.debug.core.adapter.handler.StackTraceRequestHandler.convertDebuggerStackFrameToClient(StackTraceRequestHandler.java:86)\n\tat com.microsoft.java.debug.core.adapter.handler.StackTraceRequestHandler.handle(StackTraceRequestHandler.java:72)\n\tat com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:73)\n\tat com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:208)\n\tat com.microsoft.java.debug.core.adapter.ProtocolServer.processData(ProtocolServer.java:177)\n\tat com.microsoft.java.debug.core.adapter.ProtocolServer.start(ProtocolServer.java:99)\n\tat com.microsoft.java.debug.plugin.internal.JavaDebugServer$2.run(JavaDebugServer.java:139)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)',

**Comment by akaroml** [comment]
@andxu please provide detailed steps of how to reproduce this issue.

**Comment by akaroml** [comment]
Close because further info is missing.
