### ISSUE TITLE
I can't run a Java program in vscode

### ISSUE THREAD

**Issue by edoolivero** [microsoft/vscode-java-debug#963]
I can't run a Java program in Visual Studio Code while the same program run throw the terminal. The error that appears is in the photo below.
![Schermata 2021-03-09 alle 20 20 33](https://user-images.githubusercontent.com/75736141/110803631-ac69bb80-827f-11eb-859b-9ce25aba5e6d.png)

##### Environment
- Operating System: macOS High Sierra 10.13.6
- JDK version: 15.0.2
- Visual Studio Code version: 1.54.1
- Java extension version: 0.13.0
- Java Debugger extension version: 0.31.0

[attach a sample project reproducing the error]
public class prova {
public static void main(String[] args){
    System.out.println("Ciao");
}
}

##### Current Result
command 'java.debug.runJavaFile' not found
##### Expected Result
Ciao

**Comment by testforstephen** [comment]
Could you reload the window and try again?

**Comment by edoolivero** [comment]
> Could you reload the window and try again?

Yes, I can but it doesn't work anyway.

**Comment by testforstephen** [comment]
Cannot reproduce. No clue what's wrong in your machine.

Could you share the logs and the reproduce steps?

**F1 -> Java: Open All Log Files**

**Comment by edoolivero** [comment]
> Cannot reproduce. No clue what's wrong in your machine.
> 
> Could you share the logs and the reproduce steps?
> 
> **F1 -> Java: Open All Log Files**

{
  message: 'Starting Java server with: /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -jar /Users/edoardoolivero/.vscode/extensions/redhat.java-0.76.0/server/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration /Users/edoardoolivero/Library/Application Support/Code/User/globalStorage/redhat.java/0.76.0/config_ss_mac -data /Users/edoardoolivero/Library/Application Support/Code/User/workspaceStorage/29ecf1bc397f02f1cb0be8a4aedf2877/redhat.java/ss_ws',
  level: 'info',
  timestamp: '2021-03-15 10:56:54.387'
}
{
  message: 'Starting Java server with: /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -jar /Users/edoardoolivero/.vscode/extensions/redhat.java-0.76.0/server/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration /Users/edoardoolivero/Library/Application Support/Code/User/globalStorage/redhat.java/0.76.0/config_mac -data /Users/edoardoolivero/Library/Application Support/Code/User/workspaceStorage/29ecf1bc397f02f1cb0be8a4aedf2877/redhat.java/jdt_ws',
  level: 'info',
  timestamp: '2021-03-15 10:56:54.713'
}
{
  message: 'WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.jpackage\n',
  level: 'info',
  timestamp: '2021-03-15 10:56:54.932'
}
{
  message: 'WARNING: Using incubator modules: jdk.incubator.jpackage, jdk.incubator.foreign\n',
  level: 'info',
  timestamp: '2021-03-15 10:56:55.009'
}
{
  message: 'Starting Java server with: /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -jar /Users/edoardoolivero/.vscode/extensions/redhat.java-0.76.0/server/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration /Users/edoardoolivero/Library/Application Support/Code/User/globalStorage/redhat.java/0.76.0/config_ss_mac -data /Users/edoardoolivero/Library/Application Support/Code/User/workspaceStorage/29ecf1bc397f02f1cb0be8a4aedf2877/redhat.java/ss_ws',
  level: 'info',
  timestamp: '2021-03-15 11:14:38.196'
}
{
  message: 'Starting Java server with: /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -jar /Users/edoardoolivero/.vscode/extensions/redhat.java-0.76.0/server/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration /Users/edoardoolivero/Library/Application Support/Code/User/globalStorage/redhat.java/0.76.0/config_mac -data /Users/edoardoolivero/Library/Application Support/Code/User/workspaceStorage/29ecf1bc397f02f1cb0be8a4aedf2877/redhat.java/jdt_ws',
  level: 'info',
  timestamp: '2021-03-15 11:14:38.312'
}
{
  message: 'WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.jpackage\n',
  level: 'info',
  timestamp: '2021-03-15 11:14:38.491'
}
{
  message: 'WARNING: Using incubator modules: jdk.incubator.jpackage, jdk.incubator.foreign\n',
  level: 'info',
  timestamp: '2021-03-15 11:14:38.733'
}
{
  message: 'Starting Java server with: /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -jar /Users/edoardoolivero/.vscode/extensions/redhat.java-0.76.0/server/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration /Users/edoardoolivero/Library/Application Support/Code/User/globalStorage/redhat.java/0.76.0/config_ss_mac -data /Users/edoardoolivero/Library/Application Support/Code/User/workspaceStorage/29ecf1bc397f02f1cb0be8a4aedf2877/redhat.java/ss_ws',
  level: 'info',
  timestamp: '2021-03-15 11:15:41.532'
}
{
  message: 'Starting Java server with: /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -jar /Users/edoardoolivero/.vscode/extensions/redhat.java-0.76.0/server/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration /Users/edoardoolivero/Library/Application Support/Code/User/globalStorage/redhat.java/0.76.0/config_mac -data /Users/edoardoolivero/Library/Application Support/Code/User/workspaceStorage/29ecf1bc397f02f1cb0be8a4aedf2877/redhat.java/jdt_ws',
  level: 'info',
  timestamp: '2021-03-15 11:15:41.625'
}
{
  message: 'WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.jpackage\n',
  level: 'info',
  timestamp: '2021-03-15 11:15:41.915'
}
{
  message: 'WARNING: Using incubator modules: jdk.incubator.jpackage, jdk.incubator.foreign\n',
  level: 'info',
  timestamp: '2021-03-15 11:15:41.961'
}

**Comment by testforstephen** [comment]
> Could you share the logs and the reproduce steps?
> F1 -> Java: Open All Log Files

Ping again. It should open two logs file: client.log and .log. Could you please share the .log as well?

**Comment by testforstephen** [comment]
@edoolivero does this issue still exist in the latest debugger extension?
