### ISSUE TITLE
JDK is not set to the current global JDK version when start a debug session.

### ISSUE THREAD

**Issue by apzentral** [microsoft/vscode-java-debug#964]
Hi,

I could not update the JDK version to use when debug. Please see below,

[Warn] The debugger and the debuggee are running in different versions of JVMs. You could see wrong source mapping results.
Debugger JVM version: 11.0.2
Debuggee JVM version: 11.0.9.1

My JAVA_HOME as well as in VS Code mapping to the global JDK version which is, 

openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)

I am not sure why the debugger is not picking up the 11.0.10 version.

Thank you.

##### Environment
- Operating System: OSX Big Sur 11.2.3
- JDK version: openjdk 11.0.10 2021-01-19
- Visual Studio Code version:

Version: 1.54.2
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:09.783Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

- Java extension version: v0.13.0
- Java Debugger extension version: v0.32.0

##### Steps To Reproduce
1. Just run the debug mode and somehow it could not pick up the right JDK version

[vs-code-java-debug.log](https://github.com/microsoft/vscode-java-debug/files/6132616/vs-code-java-debug.log)

##### Expected Result

I think the JDK should be matching with the global one which is 11.0.10

**Comment by testforstephen** [comment]
Could you please run command via "**F1 -> Java: Configure Java Runtime**"? This page will list what Java runtime your project is using.

![image](https://user-images.githubusercontent.com/14052197/111098498-8a718100-857e-11eb-9c25-756ce4a7b074.png)

**Comment by apzentral** [comment]
Thank you very much, once I check on this page. Seem like VS Code only identifies on the JDK in `/Library/Java/JavaVirtualMachines` folder only.

Please see below,

![image](https://user-images.githubusercontent.com/3866678/111198503-d91e1b80-857c-11eb-9a38-6cc082969016.png)

This is all JAVA versions in my jenv,

![image](https://user-images.githubusercontent.com/3866678/111198791-35813b00-857d-11eb-9e54-8a4e8e546152.png)

Seem like it does not detect the one from 11.0.10 from jenv.

In this case, what would be the best way to integrated from jenv as well.

**Comment by apzentral** [comment]
Seem like I would need to link 

`sudo ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk` 

in order to make it shows in VS Code.

Thank you.

**Comment by testforstephen** [comment]
We didn't discover JDKs from jenv yet, this could be a feature request against https://github.com/microsoft/vscode-java-pack/issues, which is the owner of "Configure Java Runtime" feature.

**Comment by testforstephen** [comment]
Looks like you have resolved the issue. I will close it. Feel free to reopen it if you have more concern.

**Comment by codebling** [comment]
For those using Codium or Code-OSS, you may need to [change your extensions marketplace/gallery](https://stackoverflow.com/questions/65188958/trying-to-download-import-cost-extension-on-codeoss) before you're able to install `vscode-java-pack`, which provides the **"Java: Configure Java Runtime"** page

[Visual Studio Marketplace link to `vscode-java-pack`](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack)
[Theoretical Open VSX Registry link to `vscode-java-pack`](https://open-vsx.org/extension/vscjava/vscode-java-pack) (if this link works, you should be able to install `vscode-java-pack` without changing your marketplace/gallery
