### ISSUE TITLE
Run button runs old file, not in directory anymore

### ISSUE THREAD

**Issue by tawatts1** [microsoft/vscode-java-debug#965]
Pressing the play button to run a java program runs an old file that isn't in the directory anymore. 
As you can see I have only one file in this directory, the file that is open, and it should simply print "test"
![java_run_issue](https://user-images.githubusercontent.com/38234567/111088071-97d92d80-84e2-11eb-9a92-70eccac0d6cc.png)

##### Environment
- Operating System: Ubuntu 20.04
- JDK version: 11.0.10
- Visual Studio Code version: 1.54.2
- Java extension version: 0.13.0
- Java Debugger extension version: 0.32.0

**Comment by testforstephen** [comment]
> Pressing the play button to run a java program runs an old file that isn't in the directory anymore.

What do you mean "not in the directory anymore"?

Also please share your user setting.

**Comment by tawatts1** [comment]
I placed every other file in a separate directory except the one I wanted to run. It still runs the old file somehow. 

Which user setting?

**Comment by testforstephen** [comment]
> I placed every other file in a separate directory except the one I wanted to run. It still runs the old file somehow.

Could you please share the elaborate steps how to reproduce it?

> Which user setting?

All your settings.json. If you don't know how to get settings.json, see https://code.visualstudio.com/docs/getstarted/settings

**Comment by tawatts1** [comment]
Here is my settings.json and launch.json in case that helps. 
![settingsjson](https://user-images.githubusercontent.com/38234567/111250175-1e1c6f00-85ca-11eb-82c2-57f94720c64d.png)

There are no special steps to reproduce it. The run button just does not run the proper file, in fact it runs a file that isn't even in the directory anymore! How is that possible? Is there a cache it is using somewhere? 

It runs the command : 
`cd /home/ted/games/chess ; /usr/bin/env /usr/lib/jvm/java-11-openjdk-amd64/bin/java -Dfile.encoding=UTF-8 -cp /home/ted/.config/Code/User/workspaceStorage/df8ce7c08bf67b769e86b15598fbdcdd/redhat.java/jdt_ws/chess_9c6cc7b5/bin complex_scoring ` 
But it does not run the file complex_scoring

I can still run the file from the terminal but it is convenient to use the run button. 

I have tried uninstalling and reinstalling to no avail.

**Comment by testforstephen** [comment]
`/home/ted/.config/Code/User/workspaceStorage/df8ce7c08bf67b769e86b15598fbdcdd/redhat.java/jdt_ws/chess_9c6cc7b5/bin` is a tmp directory used to store the compiled classes, that's by design.

However, you could run command "**F1 -> Java: Clean Java Language Server Workspace**" to clean the cache.

**Comment by tawatts1** [comment]
Thank you. It is now working as expected.
