### ISSUE TITLE
Failed to run command 

### ISSUE THREAD

**Issue by tomereli** [microsoft/vscode-java-debug#969]
When trying to organize imports in vscode with the Java extension, I get the following error:

> Running the contributed command: '_vscode_delegate_cmd_kmj6g88a' failed.

##### Environment
- Operating System: Windows
- JDK version: java-1.8.0-openjdk-1.8.0.275.b01-1.el8_3.x86_64
- Visual Studio Code version: 1.54.3
- Java extension version: 0.13.0
- Java Debugger extension version: 0.32.0

##### Steps To Reproduce
1. Install latest vscode + java extension pack
2. Open a java 1.8 project on remote-ssh server (I have centos8)
3. Update settings accordingly to support running with Java8 runtime (update installation path according to your system):
```
"java.configuration.runtimes": [
        {
          "name": "JavaSE-1.8",
          "path": "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-1.el8_3.x86_64/",
          "default": true
        },
      ],
```
3. Try to organize imports

##### Current Result
> Running the contributed command: '_vscode_delegate_cmd_kmj6g88a' failed.

##### Expected Result
Should succeed

**Comment by testforstephen** [comment]
i'm curious how did you trigger "organize imports" feature?

**Comment by tomereli** [comment]
> i'm curious how did you trigger "organize imports" feature?

ALT+SHIFT+O
Or using the light bulb icon on top of one of the import lines

**Comment by shrinidhi111** [comment]
```
Running the contributed command: '_vscode_delegate_cmd_ksyh6wbh' failed.
```

Same issue faced by me but in a different context. I have codelens active and this error comes when I click on references for exactly one particular function. The other functions gives me references with no issues

**Comment by shrinidhi111** [comment]
Okay, it went off once I reloaded the Window 😆

**Comment by testforstephen** [comment]
This duplicates with https://github.com/redhat-developer/vscode-java/issues/1840. And the upstream VS Code has fixed it.
