### ISSUE TITLE
Spring Boot Dashboard couldn't list project

### ISSUE THREAD

**Issue by naveenroy001** [microsoft/vscode-java-debug#972]
Spring Boot Dashboard Extention cannot list spring project it continues finding project but couldn't resolve project and couldn't generate launch.json 

##### Environment
- Operating System: Windows 10
- JDK version: 11 and 8
- Visual Studio Code version: 1.54.3
- Java extension version:  0.2.0
- Java Debugger extension version: 0.32.1

##### Steps To Reproduce
1. Add Existing Spring Boot Project
2. Goto Spring Dashboard Extension

##### Project Details
Just Goto Spring Initializer and create a new spring boot project in java 8 

##### Current Result
Continues Finding project and couldn't creating launch.json

##### Expected Result
Find Project and create lanuch.json
![Screenshot 2021-03-12 123851](https://user-images.githubusercontent.com/25478188/112439173-ccfd3f80-8d6e-11eb-86d0-dc810512f9fb.png)
![Screenshot 2021-03-25 133354](https://user-images.githubusercontent.com/25478188/112439177-ce2e6c80-8d6e-11eb-9b15-2bae6bc081a3.png)

**Comment by testforstephen** [comment]
To use these features, you have to wait for the Java tooling to be fully started. There is a thumbs up icon at the status bar when it's ready.

![image](https://user-images.githubusercontent.com/14052197/112603674-4b7dde00-8e50-11eb-91d7-7e3bb05595c6.png)

**Comment by naveenroy001** [comment]
![springDashboard](https://user-images.githubusercontent.com/25478188/112605788-afe37200-8e3d-11eb-99a6-b173cca53095.png)

it's already in thumbs up but spring boot couldn't resolved.

**Comment by testforstephen** [comment]
SpringBoot Dashboard is not contributed by the debugger extension. Could you please open a bug to SpringBoot Dashboard extension?

**Comment by naveenroy001** [comment]
Ok

**Comment by naveenroy001** [comment]
Ok
