### ISSUE TITLE
Debug options are duplicated when open a multiple project workspace for the second time in WSL 2

### ISSUE THREAD

**Issue by Fubuchi** [microsoft/vscode-java-debug#976]
When I open a workspace that contains more than one project using vscode WSL remote, the debug options are duplicated.
![image](https://user-images.githubusercontent.com/42483897/114090004-0ee6c380-98e1-11eb-9043-cc82966c3edf.png)

##### Environment
- Operating System: Void Linux in WSL 2 (work fine on windows)
- JDK version:
```
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
```
- Visual Studio Code version:
```
Version: 1.55.1 (user setup)
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T15:06:02.360Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```
- Java extension version: 0.76.0
- Java Debugger extension version:  0.32.1

##### Steps To Reproduce
~~1. Open a work space that contain 2 java maven projects~~
1. Open a work space that contain 2 java maven projects in WSL2
2. Create a launch,json with 2 options, one for each project
3. Close and open the work space again

[zh-service.zip](https://github.com/microsoft/vscode-java-debug/files/6281200/zh-service.zip)

[verbose.log](https://github.com/microsoft/vscode-java-debug/files/6281223/verbose.log)

##### Current result
- One debug option is duplicated
- If I delete the launch,json and then select "show all automatic configuration", the duplicated one is displayed here:
![image](https://user-images.githubusercontent.com/42483897/114091295-b31d3a00-98e2-11eb-8afb-ca4593e2e7c8.png)

##### Expected Result
- No duplicate options in debug tab

##### Additional Informations
- If I delete the workspace data folder in windows' side (C:\Users\<name>\AppData\Roaming\Code\User\workspaceStorage), then the duplicated option is removed, but it appear again when close and re-open vscode.

**Comment by testforstephen** [comment]
I tried the same project in VS Code 1.55.1 of macOS, but didn't observe duplicated debug options.

![image](https://user-images.githubusercontent.com/14052197/114330994-9e0c0980-9b75-11eb-8ffa-9599c338d1a7.png)

Also when i clicked "Show all automatic debug configurations", i didn't see the duplicated one there.

![image](https://user-images.githubusercontent.com/14052197/114331089-d6abe300-9b75-11eb-8aa2-225892cd63d7.png)

Could you disable other extensions but just keep "Language Support for Java" and "Debugger for Java" extensions?

**Comment by Fubuchi** [comment]
I update the title and my post to add more context.

This issue only happen if you open the project using WSL remote in a WSL 2 distro.

I tested again with openSUSE Tumbleweed WSL2 and got the same issue with this project (the zh service example use lombok so I can't disable all unreleated extensions)

[test.zip](https://github.com/microsoft/vscode-java-debug/files/6293682/test.zip)

Enabled extensions:

![image](https://user-images.githubusercontent.com/42483897/114336624-951d3700-9b79-11eb-9660-3a3c9cf023e1.png)

![image](https://user-images.githubusercontent.com/42483897/114336752-d3b2f180-9b79-11eb-8365-31dd19e56d0d.png)

**Comment by Fubuchi** [comment]
Look like VS Code team made some change in their side and broke all language servers while they worked in WSL mode. I had the same issue with Scala metals and Rust analyzer.

**Comment by Fubuchi** [comment]
Closed, the issue is on vscode's side microsoft/vscode#121148
