### ISSUE TITLE
Run in terminal twice and it failed with "not recognized name of cmdlet, function, script, program"

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-debug#979]
See https://github.com/redhat-developer/vscode-java/issues/1873#issue-856272854 for more details.

https://user-images.githubusercontent.com/82240394/114447784-718ad880-9bdb-11eb-8e0e-c7f128989585.mp4

**Comment by testforstephen** [comment]
@DumbestThan, I cannot reproduce it with VS Code 1.55.1 and PowerShell as terminal. Can you try other terminals such as cmd?

![image](https://user-images.githubusercontent.com/14052197/114516265-ced06980-9c6f-11eb-98d5-922125c00d50.png)

**Comment by ereamer** [comment]
I was getting the same error. When I drilled into the directory c:\Users\username\.vscode\extensions\vscjava.vscode-java-debug-0.32.0\scripts\launcher.bat I found that the launcher.bat file was missing. I created a new launcher.bat file using the code available on Github, saved it to the directory and now it works fine.  Not sure what caused the file to go missing in the first place.
