### ISSUE TITLE
Allow for "adding" to a java launch classpath configuration via launch.json rather than replace it completely

### ISSUE THREAD

**Issue by stefanrybacki** [microsoft/vscode-java-debug#980]
Sometimes there is a need to add additional classpaths to a launch configuration. However, right now this is only possible by providing ALL classpaths (which are usually automatically set when using java projects, gradle or maven) and then add the additional ones.

It would be nice to have the option to add to the automatically determined classpath. Either by
- an additional option in the launch configuration
- or maybe introduce a generated classpath variable that can be reused in the classpaths property (e.g. similar to how the PATH variable works in the OS: PATH=$PATH;...)

##### Current Result
- adding manual classpaths only works if the ENTIRE classpath (gradle/maven) is provided manually 

##### Expected Result
- an option to ADD to the existing generated classpath, rather than only a replace option

##### Additional Informations
Feature Request

**Comment by testforstephen** [comment]
The debugger 0.34.0 supports the following predefined variables in classPaths/modulePaths configs of launch.json.
- $Auto - Automatically resolve the classpaths of current project
- $Runtime - The classpaths within 'runtime' scope of current project
- $Test - The classpaths within 'test' scope of current project
- !\<path\> - Exclude the specified path from classpaths.

You can see the sample below to add extra classpath to launch.json.

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Launch Foo",
            "request": "launch",
            "mainClass": "foo.bar.Foo",
            "classPaths": [
                "$Auto",
                "<extra class path>"
            ]
        }
    ]
}

```
