### ISSUE TITLE
Cannot resolve the modulepaths/classpaths automatically, please specify the value in the launch.json.

### ISSUE THREAD

**Issue by OOOHA** [microsoft/vscode-java-debug#981]
Issue Type: <b>Bug</b>

I can run my code just after I launch VSCode and it'll be no error after the first run.
If I didn't press Run and Debug then I'll not be able to run the code.
And I'll get this " #file name#  is not on the classpath of project Program_9299c099, only syntax errors are reported."
my foder name is called java_code.
Here is another fun thing.
Because I use Mac and Windows and I found if I got a launch.json then it'll have a lots of error.
Since I never have created a launch.jason file in my  Workspace and it still work great.

Or did I do anything wrong?
Please help me fix this, I can't find a similar problem on the net.

Extension version: 0.32.1
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.35GB free)|
|Process Argv|--crash-reporter-id 6e0a0302-b09c-4c20-8e81-5fa91decd80f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
openwsldoc:30282072
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820cf:30276953
vscorecescf:30285484
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by testforstephen** [comment]
Could you please share a sample project to reproduce the issue?

**Comment by OOOHA** [comment]
https://user-images.githubusercontent.com/45551120/115235634-fc745180-a14c-11eb-89d5-fddcda83b4a6.mp4


Maybe this screen record can show you what I mean.

**Comment by testforstephen** [comment]
> " #file name# is not on the classpath of project Program_9299c099, only syntax errors are reported."

Regarding this warning, you could leverage workspace setting `"java.project.sourcePaths"` to add the source root containing source files to the classpath.

> Cannot resolve the modulepaths/classpaths automatically, please specify the value in the launch.json.

Could you share the logs? 
**F1 -> Java: Open Java Language Server Log File**

**Comment by OOOHA** [comment]
[.log](https://github.com/microsoft/vscode-java-debug/files/6336213/default.log)

**Comment by OOOHA** [comment]
Can you be more detailed of 

> leverage workspace setting "java.project.sourcePaths" to add the source root containing source files to the classpath.

**Comment by testforstephen** [comment]
When you opened an unmanaged folder (without build tool such as maven or gradle) in VS Code, Java tooling actually cannot recognize those folders containing Java files well. The workspace setting `"java.project.sourcePaths"` is a new way to explicitly tell the tooling which folders contain Java files.

In your case, "java_code" folder is a java package name, so the source root should be "Program" folder itself. Considering `"java.project.sourcePaths"` only supports relative path, so adding `"java.project.sourcePaths": ["."]` to the workspace setting should be OK. Notice change it in user setting won't work.

**Comment by OOOHA** [comment]
OK.
I'll try it and learn more.
Thanks.

**Comment by OOOHA** [comment]
It's totally dead now on my MackBook Pro 2017

**Comment by OOOHA** [comment]
<img width="1440" alt="Screen Shot 2021-04-30 at 6 23 30 PM" src="https://user-images.githubusercontent.com/45551120/116682757-3f51e700-a9e1-11eb-8341-f6a0e24c55a4.png">

**Comment by OOOHA** [comment]
It's OK on the Mac but it's still having a trouble on the Windows 10.

**Comment by OOOHA** [comment]
I did Clean Java Language Server Workspace again and it's fixed!

**Comment by OOOHA** [comment]
Clean Java Language Server Workspace isn't working on my other device.
<img width="1440" alt="Screen Shot 2021-05-03 at 1 48 48 PM" src="https://user-images.githubusercontent.com/45551120/116844711-73621d80-ac16-11eb-801d-ab30e77829e7.png">

**Comment by herocodess** [comment]
I still have the same error on Ubuntu 20.04. I have tried and followed all steps I've seen on StackOverflow and Github Issues, yet no avail.

![Screenshot from 2021-10-12 06-24-28](https://user-images.githubusercontent.com/42640073/136896509-854c23e4-3af2-4fca-8993-392a995ffd08.png)

**Comment by renzailvtuplus** [comment]
I still have the same error on Windows. I have tried and followed all steps I've seen on StackOverflow and Github Issues, yet no avail.
![Uploading image.png…]()

>

**Comment by OOOHA** [comment]
> 

Still can't see your image.
<img width="893" alt="Screenshot 2022-04-21 225814" src="https://user-images.githubusercontent.com/45551120/164486743-fa181e3d-8c00-41ea-b902-0d4bb5705af9.png">

**Comment by mickotec** [comment]
I just cut and pasted the folders outside the workspace and then I created another folder and pasted the files into the newly created folder in the workspace.
