### ISSUE TITLE
Integrate decompiler extension with debugger

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-debug#992]
Currently there is a Java decompiler in marketplace https://marketplace.visualstudio.com/items?itemName=dgileadi.java-decompiler, but the debugger cannot recognize the breakpoint in the decompiled source yet. Need extra work in debugger side to address the gap between the decompiler and debugger.

**Comment by xiaods** [comment]
eclipse and jetbrain ide already support this feature.

**Comment by mozhuanzuojing** [comment]
> eclipse and jetbrain ide already support this feature.

You can try https://marketplace.visualstudio.com/items?itemName=guxgn.java-decompiler

this is I create it by learn eclipse ecd plugin

**Comment by mozhuanzuojing** [comment]
> eclipse and jetbrain ide already support this feature.


Eclipse is also support thrid plugin and not eclipse debug component

**Comment by xiaods** [comment]
> > eclipse and jetbrain ide already support this feature.
> 
> Eclipse decompiler support is also by thrid ecd plugin and not eclipse debug component

thanks for your reminder

**Comment by testforstephen** [comment]
this has been supported. redhat java extension has integrated a built-in fernflower decompiler, and the debugger will auto adjust the line mappings when it detects a decompiler is invoked during debugging.
