### ISSUE TITLE
I can't read utf-8 content using Scanner

### ISSUE THREAD

**Issue by lucasmoura-dev** [microsoft/vscode-java-debug#994]
I'm trying to type a text containing accents using Scanner (System.in), after reading, I print on the terminal but is not the same.

Thanks.

##### Environment
- Operating System: Windows 10
- JDK version: jdk1.8.0_281
- Visual Studio Code version: 1.55.2
- Java extension version:  ??
- Java Debugger extension version: v0.33.0

##### Steps To Reproduce
I have this simple code:
```
Scanner in = new Scanner(System.in);
String output = in.next();
System.out.println("Your text is " + output);
```

Example:
Input: "Coração"
Desired output: "Your text is Coração"
Output from the integrated terminal: "Your text is Corao"

##### Current Result
"Your text is Corao"

##### Expected Result
"Your text is Coração"

##### Additional Informations
Is it a bug? How can I fix it?

**Comment by testforstephen** [comment]
In debugger 0.37.0, we have fixed the encoding issues on Windows. Could you pls retry with the latest debugger version?
