### ISSUE TITLE
Breakpoints run to a wrong code line

### ISSUE THREAD

**Issue by Zhouchuanwen** [microsoft/vscode-java-debug#998]
Breakpoints run to a wrong code line
the breakpoints run to a place with wrong code lines. (breakpoints not keep the same position with source code )

##### Environment
- Operating System:  Darwin arm64 20.3.0
- JDK version:  zulu-8.jdk
- Visual Studio Code version:  Visual Studio Code - Insiders  (1.57.0-insider)

- Java extension version:  Java Extension Pack(v0.14.0)
- Java Debugger extension version: Debugger for Java(v0.33.1)

##### Steps To Reproduce
1. [step 1] mvn clean package -DskipTests
2. [step 2] Launch my SpringBoot WebApplication with Debug mode.
3. [step 3] set my breakpoints and start to debug code
4. [step 4] the breakpoints run to a place with wrong code lines. (breakpoints not keep the same position with source code )

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
breakpoints in a wrong code lines:
![image](https://user-images.githubusercontent.com/7982753/117266516-eb834a00-ae87-11eb-82ae-5cd3ec5a9c7f.png)

debug class code file position:
![image](https://user-images.githubusercontent.com/7982753/117266641-0ce43600-ae88-11eb-96b6-912edd7ab7ae.png)

**Comment by testforstephen** [comment]
Could you please share a sample project to help us reproduce the issue?

Also you could try **F1 -> Java: Clean Java Language Server Workspace**.

**Comment by ole1986** [comment]
Is still an issue. Even after clean up
